[Student][MBL-14795] Remember collapsed modules
instructure/canvas-android pull request #1033
Opened 2020-10-08 08:55 UTC by hermannakos

2020-10-08 16:47 UTC, joehoag commented on apps/student/src/main/java/com/instructure/student/util/CollapsedModulesStore.kt
> +package com.instructure.student.util
You should include our copyright notice at the top of new code modules.  You can just copy it from another file.

2020-10-12 13:49 UTC, joehoag commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt
> +    @Stub
Did you create a Jira ticket for me to get this test working again, as we discussed?

2020-10-12 14:00 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt
> +    @Stub
Not yet, wanted to do that once the changes were accepted.

2020-10-12 20:55 UTC, joehoag requested changes
So, from some testing, the new behavior seems to be:
(1) Modules default to open
(2) Modules' open/close state will be saved across app restarts

Is that the intended behavior?

I was able to verify that the ModulesE2ETest still passes.

My one complaint (applies to the test that is failing) is that empty modules should not show the expand/collapse icons.  Because you can't expand or collapse them.  I guess you could ask UX or Product (both Nate for now) what the proper behavior should be in that case.

2020-10-12 21:12 UTC, joehoag commented
OK, I locally altered the failing test to include an assignment inside the locked module, and in that case the expand/collapse support made sense and did the right thing.  We should just remove expand/contract support for empty modules.

2020-10-13 14:42 UTC, joehoag approved these changes
Sounds like this is acceptable as is -- we'll address empty-module logic in a separate ticket.

2020-10-14 08:02 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt
> +    @Stub
I created the ticket, MBL-14842

2020-10-14 08:03 UTC, merged