[Teacher] Empty state added for modules with no items
instructure/canvas-android pull request #1066
Opened 2020-10-19 13:47 UTC by hermannakos

refs: MBL-14829
affects: Teacher
release note: Empty state added for modules with no items.

test plan:

2020-10-19 18:17 UTC, JordanMarshall requested changes
Just one issue with multiple empty modules, but otherwise it looks good.

2020-10-20 08:16 UTC, tamaskozmer commented on apps/teacher/src/main/res/layout/adapter_module_empty_item.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Do we need a `ConstraintLayout` for this? I'm sure it doesn't have too much performance overhead, if it has any, but I would use a `FrameLayout` in cases like this. It's not an action item, just adding my 2 cents.

2020-10-20 08:20 UTC, tamaskozmer commented on apps/teacher/src/main/res/layout/adapter_module_empty_item.xml
> +        android:text="@string/noItemsToDisplayShort"
I see that you are reusing this string resource here, and just checked that it is already reused in many places. It is a common practice on the project @JordanMarshall ?

2020-10-20 08:22 UTC, tamaskozmer commented
I have added two comments, but neither of them requires action, the PR looks good.

2020-10-20 08:59 UTC, hermannakos commented on apps/teacher/src/main/res/layout/adapter_module_empty_item.xml
> +        android:text="@string/noItemsToDisplayShort"
We already use this for the same thing in Student, that's why I use it here.

2020-10-20 09:28 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListEmptyItemBinder.kt
> +class ModuleListEmptyItemBinder : ListItemBinder<ModuleListItemData.EmptyItem, ModuleListCallback>() {
Thanks, it's fixed now.

2020-10-20 13:41 UTC, JordanMarshall commented on apps/teacher/src/main/res/layout/adapter_module_empty_item.xml
> +        android:text="@string/noItemsToDisplayShort"
👍  It's not uncommon for us to reuse generic empty/error messages, especially if there isn't specific product/design direction.

2020-10-20 13:41 UTC, JordanMarshall approved these changes

2020-10-20 14:01 UTC, merged