[Teacher][MBL-14813] View Syllabus
instructure/canvas-android pull request #1083
Opened 2020-11-05 10:00 UTC by tamaskozmer

Testing: Testing can be done by comparing with the student app. The syllabus should look the same as in the student app, with one difference. In the teacher app there aren't locked items in the syllabus events. Also clicking on a syllabus event, which is not an assignment is not working yet, will be implmented in a follow up ticket.

refs: MBL-14813
affects: Teacher
release note: Implemented option to view the course syllabus

2020-11-09 21:33 UTC, Blackchai commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/renderTests/SyllabusRenderTest.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
Not a big deal, but copyright should be 2020

2020-11-09 21:33 UTC, Blackchai commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SyllabusPage.kt
> +/*
copyright 2020

2020-11-09 21:33 UTC, Blackchai commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SyllabusPageTest.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:33 UTC, Blackchai commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/renderTests/pages/SyllabusRenderPage.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020, I'm guessing either the file settings or copy pasta issues :)

2020-11-09 21:34 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusEffectHandler.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
copyright

2020-11-09 21:37 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusPresenter.kt
> +package com.instructure.teacher.features.syllabus
Missing license

2020-11-09 21:37 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusModels.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:38 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusUpdate.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:39 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusEventsAdapter.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020 :)

2020-11-09 21:40 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusFragment.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020, just marking all of these so we can check that they get changed, really no big deal

2020-11-09 21:40 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusTabAdapter.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:41 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusView.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:43 UTC, Blackchai commented on apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusViewState.kt
> + *
2020

2020-11-09 21:45 UTC, Blackchai commented on apps/teacher/src/main/res/layout/fragment_syllabus.xml
> +  ~ Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:45 UTC, Blackchai commented on apps/teacher/src/main/res/layout/fragment_syllabus_events.xml
> +  ~ Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:45 UTC, Blackchai commented on apps/teacher/src/main/res/layout/fragment_syllabus_webview.xml
> +  ~ Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:45 UTC, Blackchai commented on apps/teacher/src/main/res/layout/viewholder_syllabus_item.xml
> +  ~ Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:45 UTC, Blackchai commented on apps/teacher/src/test/java/com/instructure/teacher/features/syllabus/SyllabusEffectHandlerTest.kt
> +package com.instructure.teacher.features.syllabus
missing license

2020-11-09 21:46 UTC, Blackchai commented on apps/teacher/src/test/java/com/instructure/teacher/features/syllabus/SyllabusPresenterTest.kt
> +package com.instructure.teacher.features.syllabus
license

2020-11-09 21:47 UTC, Blackchai commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/DateExtensions.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
2020

2020-11-09 21:55 UTC, Blackchai requested changes
This is looking great. I'm going to do testing now, the only changes I'm requesting are the super minor licensing ones.

2020-11-10 07:07 UTC, tamaskozmer commented
I don't know why some classes does not have the license, because I set it up as an automatic header. Maybe if I create a Kotlin file instead of a Kotlin class it doesn't add the licence, I will look into it. I just copied one licence header from a class, and added it to Android Studio, but haven't checked the date on it.

2020-11-10 15:18 UTC, Blackchai commented
Something I just noticed this morning, I don't see a remote config param for this feature on firebase. Do you need help creating one?

2020-11-10 17:02 UTC, Blackchai approved these changes
LGTM!

2020-11-11 07:35 UTC, merged