[MBL-14875][Student] Assignment Sorting
instructure/canvas-android pull request #1204
Opened 2021-02-08 15:32 UTC by tamaskozmer

Test plan: Acceptance criteria is in the ticket.

refs: MBL-14875
affects: Student
release note: Added an option to sort the assignments by type.

2021-02-09 14:53 UTC, hermannakos requested changes
QA+1. Awesome, it works great. I requested a few changes, let's talk about them if you have any questions.

2021-02-09 14:53 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentListInteractionTest.kt
> +        assignmentListPage.assertSortByButtonShowsSortByType()
I think we should also check for labels here like we do in the sort by time case.

2021-02-09 14:53 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/adapter/assignment/AssignmentListByDateRecyclerAdapter.kt
> + * Copyright (C) 2016 - present Instructure, Inc.
I think the date needs to be updated

2021-02-09 14:53 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt
> +private const val SORT_BY_TYPE = "type"
These could be moved to an enum.

2021-02-09 14:53 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt
> +        sortByButton.importantForAccessibility
We do nothing with this.

2021-02-09 14:53 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt
> +    private fun sortByTimeSelected() {
If we move the consts to an enum we can merge these methods.

2021-02-09 14:53 UTC, hermannakos commented on apps/student/src/main/res/values/arrays.xml
> +  ~ Copyright (C)  - present Instructure, Inc.
Date is missing.

2021-02-09 14:53 UTC, hermannakos commented on libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt
> +    const val ASSIGNMENT_LIST_SORT_BY_TYPE_SELECTED = "assignment_list_sort_by_type_selected"
This should be alphabetised.

2021-02-09 14:53 UTC, hermannakos commented on libs/pandares/src/main/res/values/strings.xml
> +    <string name="sortByTime">Sort by Time</string>
We use this for content description as well as titles. It would be nice to separate these. The content description ones should follow the naming scheme with the a11y_ prefix. Also TalkBack only announces the title, it should be clear that it's a button.

2021-02-09 14:53 UTC, hermannakos commented on libs/pandares/src/main/res/drawable/ic_chevron_down.xml
> +<vector android:height="24dp" android:tint="#008EE2"
I don't think we should set the tint and color in the same svg.

2021-02-09 16:00 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentListInteractionTest.kt
> +        assignmentListPage.assertSortByButtonShowsSortByType()
I wanted to do that, but assignments groups in the mock canvas doesn't have names, so the label is empty. I can take a look, but it might take long.

2021-02-09 16:00 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt
> +        sortByButton.importantForAccessibility
Thanks, forgot to remove this.

2021-02-09 16:02 UTC, tamaskozmer commented on libs/pandares/src/main/res/drawable/ic_chevron_down.xml
> +<vector android:height="24dp" android:tint="#008EE2"
This is how Android studio generates the vector asset, I don't think we should modify this.

2021-02-09 16:21 UTC, tamaskozmer commented on libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt
> +    const val ASSIGNMENT_LIST_SORT_BY_TYPE_SELECTED = "assignment_list_sort_by_type_selected"
On a second look I don't think this list is in an alphabetised order, and don't think it really matters, but I can move it to the top near the values starting with "assignment".

2021-02-10 09:31 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt
> +            sortByButton.contentDescription = getString(selectedSortOrder.contentDescriptionRes)
I think we should announce the sorting change for accessibility

2021-02-10 10:51 UTC, hermannakos approved these changes

2021-02-10 11:11 UTC, merged