[MBL-15342][Student] Change layout if FeatureFlag is on
instructure/canvas-android pull request #1267
Opened 2021-04-23 10:41 UTC by tamaskozmer

Test plan: 

Verify all the scenarios that can possible happen in the login flow:
- Completely new login
- Starting the app with logged in user
- Logging in with QR code
- Logging in with a previously saved user (online/offline)
- Logging in with a QR link. (By using an external QR reader to scan the login QR code)

Verify the scenarios when switching on/off the remote config flag in Firebase.

In each case a K5 user should see the new navigation and any user who is not in a K5 account should see the current navigation.

refs: MBL-15342
affects: Student
release note: none

2021-04-23 13:20 UTC, hermannakos requested changes
Great job. Only some minor things.

2021-04-23 13:34 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/activity/InterwebsToApplication.kt
> +                    val canvasForElementary = featureFlagProvider.getCanvasForElementaryFlag()
It seems like, but actually can't. This performs a network request on the user, so to perform this first we need to perform the login (the line above this `performSSOLogin`). The other occurrences are in other conditional branches, where we are already signed in. There are many conditions in this method, but this method will be called only once either way.

2021-04-23 13:37 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/activity/LoginActivity.kt
> +@AndroidEntryPoint
Since we inject the viewModel in the parent Activity we need this to be an EntryPoint as well.

2021-04-23 13:37 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/activity/LoginLandingPageActivity.kt
> +@AndroidEntryPoint
Since we inject the viewModel in the parent Activity we need this to be an EntryPoint as well.

2021-04-23 13:41 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
> +    private fun setupNavDrawerItems() {
We could, but I found this much more elegant than creating the navigation drawer from code.

2021-04-23 13:47 UTC, tamaskozmer commented on libs/login-api-2/src/main/java/com/instructure/loginapi/login/model/SignedInUser.kt
> +        var canvasForElementary: Boolean = false
I thought about this, but we only use this when the user clicks some of the previous users on the landing page, so wouldn't be that much help. Also if we want to use this by default we would need to implement some caching mechanism, what invalidates the value of this field if it changes on backend. This seems unlikely, but these can happen when we switch the feature flag to true and it already has false cached.

2021-04-23 13:49 UTC, tamaskozmer commented on libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
> +    private suspend fun updateUser() {
Right. First I wanted to check the feature flag here, but than refactored and forgot this.

2021-04-26 12:04 UTC, hermannakos approved these changes

2021-04-26 13:25 UTC, merged