[MBL-15422][Student] K5 Schedule content
instructure/canvas-android pull request #1329
Opened 2021-07-19 14:49 UTC by hermannakos

refs: MBL-15422
affects: Student
release note: none

2021-07-21 14:59 UTC, tamaskozmer requested changes

2021-07-21 14:59 UTC, tamaskozmer commented on libs/pandautils/src/main/res/layout-large/item_schedule_course.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
Are you using the `layout-large` qualifier for the tablet design, or is there some other requirement that requires this? If it's the first, please use the `sw720dp` qualifier to remain consistent with the other parts of the Homeroom screens.

2021-07-21 14:59 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt
> +    fun jumpToToday() {
This function should be private.

2021-07-21 14:59 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt
> +    private fun getData() {
I think we should have a force network parameter here, we probably don't want to load from network every time we open the page.

2021-07-21 14:59 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt
> +                assignmentMap = plannerItems
Do we need to fetch the assignments here for each planner item? I see that we only get these to determine the chips to show, but most of those states can be found under the `planner_item/submission` object. The only thing I not found is how to get the `replies` chip, what only applies to discussions. Maybe there is a way to determine that as well. It would worth a try asking the web team about this, since they didn't mention in the API document that we have to request each individual assignment. 

If this is not possible we can still eliminate a lot of unnecessary network requests by requesting only the discussions instead of all the assignments. We can know from the `PlannableType`, which items are discussions.

2021-07-21 14:59 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt
> +                    if (htmlUrl.startsWith('/')) htmlUrl = ApiPrefs.fullDomain + htmlUrl
It would be better to inject the `ApiPrefs` through the `ViewModel` constructor.

2021-07-22 09:08 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt
> +fun addBorderToContainer(view: View, borderColor: Int?, borderWidth: Int?, backgroundColor: Int?, borderCornerRadius: Int?) {
It would be easier but reusability would be an issue then. We would do the same thing as we do here only with drawables in that case.

2021-07-22 12:10 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt
> +fun addBorderToContainer(view: View, borderColor: Int?, borderWidth: Int?, backgroundColor: Int?, borderCornerRadius: Int?) {
This might be a bit more reusable, but generally the responsibility of Data Binding and Binding Adapters is to bind some kind of data to the view, and not to set the style of the view. I think setting a color can be considered Data Binding since color is dynamic and we receive it from the API, but adding a background is part of the design. I think this is not a big issue, so you can leave it like this, if this would require big effort to change.

2021-07-26 06:40 UTC, tamaskozmer approved these changes

2021-07-27 07:58 UTC, merged