[MBL-15155][Student] K5 Grades
instructure/canvas-android pull request #1331
Opened 2021-07-21 09:33 UTC by tamaskozmer

Test Plan:
- Verify if K5 Grades page shows the correct data (compare with web)
- Verify if the layouts are correct on Phone and Tablet (check designs)
- Verify changing grading periods shows data for correct grading period
- Enable TalkBack and check if the feature is accessible

refs: MBL-15155
affects: Student
release note: Added Grades page for K5 Homeroom

2021-07-21 14:38 UTC, hermannakos requested changes
Nice! Everything works great! Just a few really nit-picky stuff

2021-07-21 14:38 UTC, hermannakos commented on libs/pandautils/src/main/res/layout/fragment_grades.xml
> +            android:id="@+id/emptyView"
I had issues with tests finding this id multiple times within the ViewPager. We should rename this to gradesEmptyView or something like that.

2021-07-22 06:26 UTC, tamaskozmer commented on libs/pandautils/src/main/res/layout/fragment_grades.xml
> +            android:id="@+id/emptyView"
Good idea, we have a lots of conflicting ids in the project (toolbar, emptyView), I support that we distinguish these by which screen are they on.

2021-07-22 06:35 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/grades/itemviewmodels/GradingPeriodSelectorItemViewModel.kt
> +        events.postValue(Event(GradesAction.OpenGradingPeriodsDialog(gradingPeriods, index)))
I wanted to keep this logic here, so it seemed logical this way, but I see your point. We never pass the events LiveData to the items, so it might make sense to keep it that way, but I can see that this might change, when we have some conditional logic happen in the items when users interact with them. In the end, it's almost the same if we use lambdas, because in that case we have a reference to the `viewModel` in the items.

2021-07-22 06:39 UTC, tamaskozmer commented on libs/pandautils/src/main/res/layout/item_grading_period_selector.xml
> +        android:importantForAccessibility="no">
I wanted to achieve that the talkback announces the selected grading period and the description of the click action together, because it's more descriptive. I will try if I can do this with your suggestion, but I think in this case we would need to add the click action to the layout instead of the TextView.

2021-07-22 09:30 UTC, hermannakos approved these changes

2021-07-22 10:26 UTC, merged