Mbl 15716 implement homeroom e2e test
instructure/canvas-android pull request #1404
Opened 2021-11-12 15:19 UTC by kdeakinstructure

refs: MBL-15716
affects: Student
release note: none

Homeroom E2E test implementation.

2021-11-12 15:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F99909769%2Fp%2Fbc5333a0c98bb176575c547246847226&size=150x150">

2021-11-15 10:44 UTC, hermannakos requested changes

2021-11-15 10:44 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/HomeroomE2ETest.kt
> +        announcementListPage.assertAnnouncementTitleVisible(homeroomAnnouncement.title!!)
The non-null assertion is unnecessary, there are a few others as well.

2021-11-15 10:44 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/HomeroomE2ETest.kt
> +                    data.announcementsList[noHomeroomCourseTitleIndex++].title
You can use i+1

2021-11-15 10:44 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/HomeroomE2ETest.kt
> +        for (i in 0 until 2) {
This should be `i in 0 until nonHomeroomCourses.size - 1`

2021-11-15 12:09 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/HomeroomE2ETest.kt
> +        for (i in 0 until 2) {
Nice catch, thx

2021-11-15 14:09 UTC, kdeakinstructure commented
E2E test run: https://app.bitrise.io/build/5a99c8cd-bac3-445c-b699-6f2b957f7486#?tab=log

2021-11-15 14:31 UTC, hermannakos approved these changes

2021-11-16 10:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100285393%2Fp%2Fce459d0f79c86b870470fc4ad19be66e&size=150x150">

2021-11-16 11:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100293311%2Fp%2F7f50f9847d6444198c8abb79d4fc5c75&size=150x150">

2021-11-16 13:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100328089%2Fp%2Ff737495bf3118a71fa7c375b4badc6ec&size=150x150">

2021-11-16 14:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100334970%2Fp%2Fa5cc14c62c0d5d38169e08c29d6181cf&size=150x150">

2021-11-16 15:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100345485%2Fp%2Ffcbfe062c5a59973429842cfc6036f6b&size=150x150">

2021-11-16 15:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100351586%2Fp%2F0cda5cd7c5e25d402124d4d16411fc72&size=150x150">

2021-11-16 17:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100371127%2Fp%2F41afc08781f7321bafc71ddbe6b8f5fa&size=150x150">

2021-11-16 20:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100403024%2Fp%2Ff6771ef5e40faa630dc0b26aca968f8d&size=150x150">

2021-11-16 21:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100406107%2Fp%2Fa850d81fc1acfb48ff94a4290234b3e5&size=150x150">

2021-11-17 12:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100517113%2Fp%2F29ce4e36d9a1e397273821d827c98e5b&size=150x150">

2021-11-17 13:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100527870%2Fp%2F44e0db99b57ed92f3e88693d1cb4c294&size=150x150">

2021-11-17 14:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100547957%2Fp%2F164ea387ea2670014c42991e464fe20c&size=150x150">

2021-11-17 16:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100570869%2Fp%2Fe7eac14e2f3070e2fe8515b85956783a&size=150x150">

2021-11-17 22:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100631045%2Fp%2Ffd3a05ae343c2ece97aa13f148eedf5b&size=150x150">

2021-11-18 08:53 UTC, merged