[MBL-15503][Student][Parent] Update Flutter SDK and dependencies
instructure/canvas-android pull request #1411
Opened 2021-11-18 13:21 UTC by tamaskozmer

Updated the Flutter SDK to the latest version and updated all the dependencies to their null safety versions. Project codebase will be migrated to null safety in a follow-up ticket.

Test plan: 

- Since almost everything changed we will need a thorough smoke testing.

- There are some failing tests that were skipped for now, and will be fixed later. The functionality they test should be tested manually. Here are the list of files, where we have failing tests:

```
- test/network/fetch_test.dart
- test/utils/veneer/android_intent_veneer_test.dart
- test/utils/widgets/view_attachments/viewers/audio_video_attachment_viewer_test.dart
- test/utils/widgets/empty_panda_widget_test.dart
- test/utils/widgets/full_screen_scroll_container_test.dart
- test/screens/masquerade/masquerade_screen_test.dart 
- test/screens/calendar/calendar_day_planner_test.dart
- test/screens/inbox/conversation_list/conversation_list_screen_test.dart
- test/screens/inbox/conversation_details/message_widget_test.dart
- test/screens/alerts/alerts_screen_test.dart
- test/screens/courses/course_grades_screen_test.dart
- test/screens/login/login_landing_screen_test.dart
```

- Some use cases that are tested by failing tests:

```
- Masquarading animation
- Video attachmanet
- SVG attachment
- Pull to refresh on FullScreenScrollContainer screens
- Clicking links in messages
- Login Flow
- Android Intent
- Permissions
- Calendar pull to refresh
```

refs: MBL-15503
affects: Student, Parent
release note: none

2021-11-18 13:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100756577%2Fp%2F9b84872024f1139c4495506db089f841&size=150x150>

2021-11-18 13:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100762485%2Fp%2F1ee9ef41383f4be94d38f416a75cf421&size=150x150>

2021-11-18 14:24 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F100769926%2Fp%2F89793fd7a176c976b3459b4411deac0a&size=150x150">

2021-11-25 10:24 UTC, hermannakos requested changes
Wow, that's a lot of changes.

2021-11-30 12:04 UTC, tamaskozmer commented on apps/flutter_parent/test/utils/veneer/android_intent_veneer_test.dart
> +import 'package:flutter_test/src/deprecated.dart';
The `setMockMethodCallHandler` is in that package. Maybe we will rewrite these tests in a later ticket, because currently they are skipped, but until then I will leave this to not break the test build.

2021-11-30 12:05 UTC, tamaskozmer commented on apps/flutter_parent/test/utils/url_launcher_test.dart
> +import 'package:flutter_test/src/deprecated.dart';
The `setMockMethodCallHandler` is in that package.

2021-11-30 12:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102447699%2Fp%2Fb937349ee10523543efb2481c2d625a5&size=150x150>

2021-11-30 12:05 UTC, tamaskozmer commented on apps/flutter_parent/test/utils/test_app.dart
> +import 'package:flutter_test/src/deprecated.dart';
The `setMockMethodCallHandler` is in that package.

2021-11-30 12:06 UTC, tamaskozmer commented on apps/flutter_parent/test/utils/old_app_migrations_test.dart
> +import 'package:flutter_test/src/deprecated.dart';
The `setMockMethodCallHandler` is in that package.

2021-11-30 12:08 UTC, tamaskozmer commented on apps/flutter_parent/test/utils/notification_util_test.dart
> -  test('initializes', () async {
I don't think this test makes much sense. I would only skip tests that we plan to fix in the future.

2021-11-30 12:08 UTC, tamaskozmer commented on apps/flutter_parent/test/utils/db/db_utils_test.dart
> -  test('init throws FlutterError in unit test', () async {
I don't think this test makes much sense. I would only skip tests that we plan to fix in the future.

2021-11-30 12:17 UTC, tamaskozmer commented on apps/flutter_parent/android/build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
We use different Kotlin version for the Parent app, but we can update it as well.

2021-11-30 12:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102456723%2Fp%2F1fae8883456ec5626946070e3ed5a2d9&size=150x150>

2021-11-30 13:58 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102473610%2Fp%2F16cbc526cac82ca3a27730414efa5a63&size=150x150">

2021-12-01 11:47 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102654430%2Fp%2F13b348b0eb37fca9e44481560f73a4ef&size=150x150">

2021-12-01 11:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102654849%2Fp%2Fd772b7f059b2886dccb6815b0b526b16&size=150x150>

2021-12-01 11:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102655527%2Fp%2F238a756050b127d7b90abd5a4789bbb9&size=150x150">

2021-12-01 13:08 UTC, hermannakos approved these changes

2021-12-02 10:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102858871%2Fp%2Fd0e301f6db71bde53a7a15df1750856f&size=150x150>

2021-12-02 10:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102859599%2Fp%2F6d08c3fca0a200fb4b47591083ab20f3&size=150x150">

2021-12-02 12:28 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102875614%2Fp%2F12046a04e282bce5993492c58565c015&size=150x150">

2021-12-02 12:28 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102875674%2Fp%2F001a7272dd34cd5707d672e6d3b51bf9&size=150x150>

2021-12-02 12:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F102876330%2Fp%2Feb1552e7225ac35d56e758fc86a51ba3&size=150x150">

2021-12-02 14:06 UTC, kdeakinstructure commented
QA 👍

2021-12-02 14:06 UTC, kdeakinstructure approved these changes

2021-12-02 14:14 UTC, merged