[MBL-15742] [Student] - Implement schedule e2e test case
instructure/canvas-android pull request #1415
Opened 2021-11-22 23:40 UTC by kdeakinstructure

refs: MBL-15742
affects: Student
release note: none

implement schedule e2e test.

2021-11-22 23:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F101320046%2Fp%2F2698d01645a96540f69fa8feec07b6a6&size=150x150">

2021-11-23 14:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F101435759%2Fp%2F8b94724f57eb6af7a1aae632477b5318&size=150x150">

2021-11-23 15:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F101458137%2Fp%2F4b39919b4f65dd7f13546c708e45afc8&size=150x150">

2021-11-25 12:57 UTC, tamaskozmer requested changes

2021-11-25 12:57 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ScheduleE2ETest.kt
> +    fun getCurrentDateCalendar(timeZone: String): Calendar {
The timezone parameter is always the same for all of these functions, it can be removed and harcoded here. Also these utility functions can be private.

2021-11-25 12:57 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ScheduleE2ETest.kt
> +    fun getMonthString(calendar: Calendar): String {
You can replace this and the function below with functions from the Calendar API. For example: `calendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.US)`

2021-11-25 12:57 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ScheduleE2ETest.kt
> +        return if(dayOfMonthIntValue < 10) getMonthString(calendar) + " 0" + calendar.get(Calendar.DAY_OF_MONTH).toString()
You can use `SimpleDateFormat` here instead if adding a zero in some cases. You can even substitute the `getMonthString` with a correct date format passed to `SimpleDateFormat`.

2021-11-25 12:57 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/SchedulePage.kt
> +    fun assertDayHeaderShownScrollToByItemName(dateText: String, dayText: String, itemName: String, ) {
The name of this function is confusing for me. It seems like this asserts that we have a specific day header wherever on the screen. I think `assertDayHeaderShown` would be fine, because that's what it does. Also `itemName` seems redundant for me, it is always the same as `dayText`.

2021-11-25 12:57 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ScheduleE2ETest.kt
> +        if(currentDateCalendar.get(Calendar.DAY_OF_WEEK) != 1)
Please don't use conditional statements without `{}` if it's multiline, it makes the code hard to read.

2021-11-25 12:57 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ScheduleE2ETest.kt
> +    fun scheduleE2ETest() {
I think these are really good test cases, and they cover a lot's of important cases, nice job. One thing I would improve is the structure. There are lots of assertions here, and lot's of different cases tested in one test. Maybe it would be good to structure it in a more readable way, like each scenario/step would be a private method with a descriptive name.

2021-11-25 13:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F101870100%2Fp%2Fd45f146c08c4f261c04e33cbdc771656&size=150x150">

2021-11-25 14:09 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/SchedulePage.kt
> +    fun assertDayHeaderShownScrollToByItemName(dateText: String, dayText: String, itemName: String, ) {
There is an existing function with the name you wrote (aka. assertDayHeaderShown) which is used in the interaction tests. It is scrolling to the item based on it's position. I gave this name because i wanted that the difference between these two similar functions could be recognized easily by their method names

2021-11-25 15:13 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ScheduleE2ETest.kt
> +    fun scheduleE2ETest() {
Good idea. I will refactor and extract some frequently used part.

2021-11-25 15:14 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ScheduleE2ETest.kt
> +        return if(dayOfMonthIntValue < 10) getMonthString(calendar) + " 0" + calendar.get(Calendar.DAY_OF_MONTH).toString()
I would leave it as it is (I've refactored getMonthString with the getDisplayName method u suggested above, I think it is ok that way)

2021-11-25 15:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F101898569%2Fp%2F04e0bcf8e11aa4c08a12de888c80d36d&size=150x150">

2021-11-25 15:48 UTC, tamaskozmer approved these changes

2021-11-25 16:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F101902683%2Fp%2F6a28b42ff9176f091213089a6b3849fc&size=150x150">

2021-11-25 16:43 UTC, merged