[MBL-15762] - Implement k5 grades e2e test
instructure/canvas-android pull request #1427
Opened 2021-12-03 13:22 UTC by kdeakinstructure

Implement k5 GradesE2E test case + add some api methods + refactor seed api createCourse logics

refs: MBL-15762
affects: Student
release note: none

2021-12-03 13:24 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/ElementaryDashboardPage.kt
> +    fun selectTab(elementaryTabType: ElementaryTabType) {
Note: I'm planning a bigger refactor to use this generic method in every other test case. That will be in a separate pull request after this one is merged.

2021-12-03 13:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F103078902%2Fp%2Fbf782b12992fe6fb0aeceb22e873caf8&size=150x150">

2021-12-15 14:43 UTC, tamaskozmer requested changes

2021-12-15 14:43 UTC, tamaskozmer commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SeedApi.kt
> +                  val courseWithTerm = CoursesApi.createCourseInSubAccount(accountId = accountId, homeroomCourse = isHomeroomCourse, enrollmentTermId = enrollmentTerm.id, publish = publishCourses)
There is a lot of duplication here. You can easily eliminate it by only checking the `subAccountCours` condition where you create a course. You can also use `accountId` instead of an additional boolean flag. Something like this:

```
private fun createCourse(gradingPeriods: Boolean = false, publishCourses: Boolean = true, isHomeroomCourse: Boolean = false, accountId: Long? = null) : CourseApiModel {
          return if(gradingPeriods) {
              val enrollmentTerm = EnrollmentTermsApi.createEnrollmentTerm()
              val gradingPeriodSetWrapper = GradingPeriodsApi.createGradingPeriodSet(enrollmentTerm.id)
              val gradingPeriodSet = GradingPeriodsApi.createGradingPeriod(gradingPeriodSetWrapper.gradingPeriodSet.id)
              val courseWithTerm = createCourse(publishCourses, isHomeroomCourse, accountId, enrollmentTerm.id)
              courseWithTerm
        } else {
              val course = createCourse(publishCourses, isHomeroomCourse, accountId)
              course
        }
    }
    
    private fun createCourse(publishCourses: Boolean = true, isHomeroomCourse: Boolean = false, accountId: Long? = null, enrollmentTermId: Long? = null): CourseApiModel {
        return if (accountId != null) {
            CoursesApi.createCourseInSubAccount(accountId = accountId, homeroomCourse = isHomeroomCourse, enrollmentTermId = enrollmentTermId, publish = publishCourses)
        } else {
            CoursesApi.createCourse(enrollmentTermId, publishCourses)
        }
    }
```

2021-12-20 09:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F105344328%2Fp%2Fcab15acaa6488f51b42485ebefdb74a3&size=150x150">

2021-12-20 10:51 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/ElementaryDashboardPage.kt
> +    fun selectTab(elementaryTabType: ElementaryTabType) {
Nice catch, thx! ;)

2021-12-20 11:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F105362646%2Fp%2F78acf89904d0d7d8bcdf141f8582af29&size=150x150>

2021-12-20 11:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F105363303%2Fp%2F5193059a81e2211313dee1e3ae9b0d03&size=150x150">

2021-12-20 12:24 UTC, tamaskozmer approved these changes

2021-12-20 22:20 UTC, merged