[MBL-15695][Student] Dashboard announcements for K5
instructure/canvas-android pull request #1430
Opened 2021-12-09 13:25 UTC by hermannakos

refs: MBL-15695
affects: Student
release note: Notifications are now visible on the elementary dashboard.

test plan: Check both the K5 and non-K5 Dashboard, both have been changed.

Create a course and invite the student, the notification card should be visible. Check accepting and declining the invitation.
Create a conference for a course, the notification card should be visible after starting the conference. Dismissing the conference once should keep the notification from popping up until the app data is cleared. Clicking the card should navigate to the conference in a custom tab.
Create a global announcement. All the announcement types should be visible with the correct color and icon. Clicking the announcement should take to the announcement details. Clearing the announcement should keep it from popping up EVER.

2021-12-09 13:40 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F103954904%2Fp%2Ffdb31555e608c5750c7eb88afa52b6f0&size=150x150">

2021-12-21 10:52 UTC, tamaskozmer requested changes

2021-12-21 10:52 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModel.kt
> +            val courses = courseManager.getCoursesAsync(forceNetwork).await().dataOrNull
Just a long shot idea for the future: We should create a repository layer below the ViewModels, which could be reactive, and in that case we would avoid making the same requests multiple times. I assume these exact same requests are triggered on the dashboard as well, and since they are both started at the same time, there won't be enough time for one to complete and use the cache.

2021-12-21 11:21 UTC, kdeakinstructure commented
QA findings:

Course invitation:

1. When a user has been invited to a k5 course, it will automatically appears on the “My Subject” list within the app (but this has been worked like this before, so it might be expected), and there will be a pop-up (green-white) box at the top of the page in which we can accept or decline the invitation. But the problem is that the user even can open the course without accepting this invitation, but that would not have been a problem as well, because opening a course means “automatically accept” the invitation. The problem is after the user stepping back from the course page to the dashboard, the green-white box will still be there and if the user clicks on the “Decline” button, there will be an Unexpected error message. (If the user clicks on the “Accept” button, nothing actually happens, because by opening the course he/she already accepted the invitation).  Note: After stepping back to the dashboard, if we do a “manual refresh”, the invitation pop-up will disappear, but I think it should be disappear even without manual refresh, as the user already accepted the course invitation by opening it.

2. For non-k5 user, opening the course does not mean automatically acceptation for the invite, and this is a problem because it isn’t consistent with k5 process. I think we should handle this on the same way, so that means that if the user opens a non-k5 course which he/she has not accepted the pop-up invitation yet, it should mean an “automatically accept” as well as in the K5 case.

3. After accepting a k5 course invitation for a k5 user, and put the app on the background, and then open it again, the k5 dashboard will change to non-k5.

4. Is it expected that we can invite k5 user for non-k5 course and fica-versa. If the user accepts such invite, it can cause anomalies like k5 dashboard appearing on non-k5 user’s screen and vica-versa. But this probably the “expected” behaviour, it’s just might be weird and could cause issues in the future.

--------------------------------------------------------------------
Conference:

5. As for NON-K5 conference, there should be a button like “Join” or something like that to make it clear that the user can join by one click into an ongoing conference.

6. Practically we do not have an appearing pop-up window while we are logging in with a K5 user. It may be expected, but this should be discussed, because as I have seen there is no chance for a K5 user to join a conference from mobile app, since if we are opening the K5 course, we cannot see a “BigBlueButton” like while opening a NON-k5 course.

--------------------------------------------------------------------
Global Announcements: It is working as it’s expected according to the test plan.

2022-01-03 11:43 UTC, hermannakos commented on apps/student/src/main/res/layout/panda_recycler_refresh_layout.xml
> +    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
Oops, missed that, fixed now.

2022-01-05 11:27 UTC, hermannakos commented
> Conference:
> 
> 6. As for NON-K5 conference, there should be a button like “Join” or something like that to make it clear that the user can join by one click into an ongoing conference.
> 7. Practically we do not have an appearing pop-up window while we are logging in with a K5 user. It may be expected, but this should be discussed, because as I have seen there is no chance for a K5 user to join a conference from mobile app, since if we are opening the K5 course, we cannot see a “BigBlueButton” like while opening a NON-k5 course.

If you click on the notification the app joins the conference for K5 and non-K5 as well.

2022-01-06 12:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F107177814%2Fp%2Fbf874af793e070a237260968a455cbba&size=150x150>

2022-01-06 12:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F107178768%2Fp%2F80b4aa982f4aa348107511379bee78fe&size=150x150">

2022-01-06 13:01 UTC, tamaskozmer approved these changes

2022-01-06 13:56 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F107187735%2Fp%2F1b510ce6dbba7787d9d2c69f8032d132&size=150x150>

2022-01-06 14:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F107188459%2Fp%2Fbc34b13ef84e130356cfb98a1be3b33a&size=150x150">

2022-01-07 10:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F107323606%2Fp%2F76494c094c9c9438f748176b7000ddfc&size=150x150>

2022-01-07 10:27 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F107324467%2Fp%2F79f9f7c0e00cb2610688b416957fa564&size=150x150">

2022-01-07 10:43 UTC, merged