[MBL-15816][Student] Important dates
instructure/canvas-android pull request #1459
Opened 2022-01-20 15:08 UTC by hermannakos

refs: MBL-15816
affects: Student
release note: Added Important Dates to the Elementary Dashboard.

test plan:
- On mobile the important dates tab should be visible.
- On tablet in portrait the important dates should be in the side bar. The Schedule tab should load the mobile design.
- On tablet in landscape the important dates should be in the side bar. The Schedule tab should load the old tablet design.
- Both assignments and events should be visible.
- Clicking an item should take to the details screen.
- See specs for more info.

2022-01-20 15:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109349142%2Fp%2F9478c2d7a4953561056cdd8f35a1ad37&size=150x150>

2022-01-20 15:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109351005%2Fp%2Fe93c50bb601f86028ced5f68a8f9e6df&size=150x150">

2022-01-21 14:53 UTC, tamaskozmer requested changes

2022-01-21 14:53 UTC, tamaskozmer commented on libs/pandautils/src/main/res/layout-sw720dp-port/item_schedule_course.xml
> +<?xml version="1.0" encoding="utf-8"?><!--
Are these layouts exactly the same as the default layouts what we also use on phone? If yes, we can delete these and in that case the `sw720dp-port` config will use the default one, because the other `sw720dp` res is only applied to landscape.

2022-01-21 14:53 UTC, tamaskozmer commented on libs/pandautils/src/main/res/values/strings.xml
> +    <string name="important_dates">Important Dates</string>
We should move these strings to `pandares` as well to remain consistent.

2022-01-21 14:53 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/importantdates/ImportantDatesFragment.kt
> +        viewModel.loadData()
Do we need to explicitly call this here, or can we move it to the `init` of the ViewModel?

2022-01-21 15:05 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/importantdates/itemviewmodels/ImportantDatesHeaderItemViewModel.kt
> +) : GroupItemViewModel(false, false, itemViewModels) {
It's just to keep items for the same day together and a bit easier to test.

2022-01-21 15:42 UTC, kdeakinstructure commented
QA 👍

2022-01-21 16:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109563359%2Fp%2F6c23dd22c0d09290f736ad35a57584ec&size=150x150>

2022-01-21 16:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109564694%2Fp%2Fb28e4bc0198346767612943c80524a8c&size=150x150">

2022-01-24 08:44 UTC, tamaskozmer approved these changes

2022-01-25 08:49 UTC, merged