[MBL-15819][Teacher] Comment Library
instructure/canvas-android pull request #1461
Opened 2022-01-21 10:33 UTC by tamaskozmer

refs: MBL-15819
affects: Teacher
release note: Added comment library to Speed Grader.

Test plan:
- Most of the use cases are covered in the specification linked in the ticket.
- Also verify that sending a comment or adding an attachment when the comment library is open closes the comment library.

2022-01-21 11:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109504015%2Fp%2F2d60e66823d3c0e052dde84be6ef2aa1&size=150x150>

2022-01-21 11:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109505305%2Fp%2Fc1f78da62a2b59f85027d9d2f8aeb62c&size=150x150">

2022-01-25 08:51 UTC, kdeakinstructure commented
QA 👍

2022-01-25 10:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109922320%2Fp%2Fccd3a0ed6de8b93f8101a735a0564655&size=150x150>

2022-01-25 10:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109924273%2Fp%2F20c946b5e19f80050b2feddba44d0af0&size=150x150">

2022-01-25 14:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109978387%2Fp%2Faa92db8826cdb007c86a929c3ec617f9&size=150x150>

2022-01-25 14:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109980292%2Fp%2Ff5f4a95e2db38abea5545d740e1178fa&size=150x150">

2022-01-25 14:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F109987405%2Fp%2Fe05e8ae1108b74cf42b5eb2fed327e8f&size=150x150>

2022-01-25 14:45 UTC, hermannakos requested changes
LGTM! My only real RC is about the filtering.

2022-01-25 14:45 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/features/speedgrader/commentlibrary/CommentLibraryViewModel.kt
> +                // No-op Silently fail if we don't have info about the comment library, and just don't show anything.
Just for debugging purposes we may want to log the exception

2022-01-25 14:45 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/features/speedgrader/commentlibrary/Highlighter.kt
> +    fun createHighlightedText(data: HighlightedSuggestionViewData): Spannable {
We could use this highlighter somewhere else as well. Could we just pass the required params to it so it's not restricted to the `HighlightedSuggestionViewData`

2022-01-25 14:45 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/features/speedgrader/commentlibrary/CommentLibraryViewModel.kt
> +            .filter { it.contains(query, ignoreCase = true) }
We should also ignore accented characters as well.

2022-01-26 08:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F110116624%2Fp%2F40eecb9f7afb27ac2c05fab7a0a63f71&size=150x150>

2022-01-26 08:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F110117737%2Fp%2F1e2722353c6d15c4d625cf1780b8fb2e&size=150x150">

2022-01-26 08:58 UTC, hermannakos approved these changes

2022-01-26 09:15 UTC, merged