[MBL-15817][Student] Important dates interaction tests
instructure/canvas-android pull request #1471
Opened 2022-02-02 16:46 UTC by hermannakos

refs: MBL-15817
affects: Student
release note: none

test plan:

2022-02-02 17:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111373284%2Fp%2F5a8643e581d2b2a71c9842129572f5e5&size=150x150>

2022-02-02 17:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111374423%2Fp%2Fe06398cc7487a4a63031513561b20e86&size=150x150">

2022-02-02 22:45 UTC, kdeakinstructure requested changes

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    @Test
A comment would be nice in which we explain why we don't run these on tablet (I know, because it's design is different than from the mobile, but we might forgot this in the future)

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        goToImportantDatesTab(data)
Please use our general tab navigating method, you can see it within the ElementaryDashboardPage class (selectTab method)

![image](https://user-images.githubusercontent.com/92309696/152246987-d044e59d-8709-4f4b-91e5-cf17962c8c41.png)

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    @TestMetaData(Priority.P0, FeatureCategory.K5_DASHBOARD, TestCategory.INTERACTION)
I'd take this refresh test case to P1 priority as we marked in the other classes. (also, the name could be simply testRefresh(), we used this name in the other classes)

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    private fun goToImportantDatesTab(data: MockCanvas) {
If u use our general tab navigating method which I mentioned above, this won't be needed here, so it can be removed

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    fun testOpenCalendarEvent() {
I'm seeing two ways here:

1. To merge this method with the testShowCalendarEvents method, and leave it on P0 priority.

2. They remain separate methods because testShowCalendarEvents is happening directly on the Important Dates page, so that's mandatory to check in these tests, so that would remain on P0, but this testOpenCalendarEvent case should be on P1, since it's just and "indirect", "secondary link" function of the Important Dates function.

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    fun testOpenAssignment() {
Same as with the CalendarEvent tests

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/ImportantDatesPage.kt
> +import com.instructure.espresso.page.*
Hint: You can increase the threshold of the imports to 1000 (or some big enough number) so it won't replace the direct imports automatically with *. (It would be clearer to see the classes which are really used). But that's just a personal preference from my side...:)

2022-02-02 22:45 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/ImportantDatesPage.kt
> +    fun clickItem(title: String) {
I'd name this as "clickOnCalendarItem", would be a bit more accurate when we read the code

2022-02-02 22:45 UTC, kdeakinstructure commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/StubTabletAnnotation.kt
> +annotation class StubTablet
Cool! :)

2022-02-02 22:45 UTC, kdeakinstructure commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
> +    return newScheduleItem
I'd consider to return with the whole calendarEventList here, so we could get the any element from it on the caller side.

2022-02-02 22:45 UTC, kdeakinstructure commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
> +fun MockCanvas.addAssignmentCalendarEvent(courseId: Long, date: String, title: String, description: String, isImportantDate: Boolean = false, assignment: Assignment): ScheduleItem {
Can we have a short conversation about handling assignments and scheduleItems? Just to make sure we are on the same page and we think them the same.

2022-02-02 22:45 UTC, kdeakinstructure commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
> +fun MockCanvas.addAssignmentCalendarEvent(courseId: Long, date: String, title: String, description: String, isImportantDate: Boolean = false, assignment: Assignment): ScheduleItem {
If we can discuss and agree in how we handle them, my above comment might won't be interesting any more.

2022-02-03 08:56 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        goToImportantDatesTab(data)
That's the one we use.

2022-02-03 09:03 UTC, hermannakos commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
> +    return newScheduleItem
We can get the whole list from the MockData, with this method we only care about the one that we just created.

2022-02-03 09:27 UTC, kdeakinstructure approved these changes

2022-02-03 09:36 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    @Test
An even better solution would be to add a string parameter to the `StubTablet` annotations.

2022-02-03 09:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111489353%2Fp%2F4e1b2e47420e741f84eef5038d4eaf9b&size=150x150>

2022-02-03 09:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111491374%2Fp%2F133b91725cc9030c989d1a354f690b81&size=150x150">

2022-02-03 09:50 UTC, tamaskozmer approved these changes

2022-02-03 09:50 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    fun testOpenCalendarEvent() {
I would vote for the 2nd option. We don't need to merge tests that test different things. The first thing tests if the items are showing, and this tests if it opens correctly. I think it's better to separate test cases, so if one fails we know where the problem is exactly.

2022-02-03 09:50 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        importantDatesPage.assertItemDisplayed(event.title!!)
I see that there is no assertions that the date is visible. Using the `DateTimeProvider` in the ViewModel instead of hardcoding a Calendar instance could solve this, because in that case you can mock the time in tests. I don't think this is high prio right now, but maybe @kdeakinstructure you can take a look when you work on the test refinements.

2022-02-03 10:03 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        importantDatesPage.assertItemDisplayed(event.title!!)
Good idea!

2022-02-03 10:04 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    @Test
Yeah, exactly. I didn't know if there is an opportunity to define attributes/parameters to custom annotations in Kotlin, but that's really nice.

2022-02-03 10:07 UTC, merged

2022-02-03 10:09 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    fun testOpenCalendarEvent() {
What you are saying is basically right generally, but in these particular cases, the situation is that one case is actually the subset of the other, so we test the same thing twice.

I'd advice that if we go with the 2nd way (to remain in separate test methods) to remove the assertion which has already done in the simple "show" case, thus we would really test another function (actually opening). Right now, if the assertItemDisplayed will fail (whether it was because a real bug, or just flakyness), the "opening" method will fail as well, so we won't know if the opening works well or not because the test method does not get there.