[MBL-15878] extend k5 important dates interaction tests
instructure/canvas-android pull request #1474
Opened 2022-02-03 14:42 UTC by kdeakinstructure

2022-02-03 15:09 UTC, hermannakos requested changes

2022-02-03 15:09 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        return if(dayOfMonthIntValue < 10) weekDayString + ", " + calendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.US) + " 0" + calendar.get(Calendar.DAY_OF_MONTH).toString()
You should use SimpleDateFormat or some other formatter for generating the Date string. That way you wouldn't need to use Calendar either.

2022-02-03 15:09 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        importantDatesPage.assertRecyclerViewItemCount(2) // We count both day texts and calendar events here, since both types are part of the recyclerView.
This should assert that 3 items are visible now since before it was only 2.

2022-02-03 15:09 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        importantDatesPage.assertDayTextIsDisplayed(concatDayString(twoDaysFromNowCalendar))
You should move this up to with the other importantDatesPage test

2022-02-03 15:09 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        importantDatesPage.assertDayTextIsDisplayed(concatDayString(twoDaysFromNowCalendar))
Same as above

2022-02-03 15:09 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        val twoDaysFromNowCalendar = getCustomDateCalendar(2)
That's not really readable, but should not matter if you change the logic behind it.

2022-02-03 15:09 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +    private fun getCustomDateCalendar(dayDiffFromToday: Int): Calendar {
You can use {Int}.days.fromNow instead of this one

2022-02-03 15:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111561539%2Fp%2F594ed2407a31cf21b5c18d29fcc31194&size=150x150>

2022-02-03 15:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111562794%2Fp%2Fcb61dc324d7ed6fef1d9619dfdd027f3&size=150x150">

2022-02-03 16:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111584888%2Fp%2F9bffc1bd1bbc88d1c644472df98b9a6e&size=150x150>

2022-02-03 16:48 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111585875%2Fp%2F99413c552a3bb3ee4f9ed009261ca995&size=150x150">

2022-02-04 10:01 UTC, tamaskozmer approved these changes

2022-02-04 10:52 UTC, hermannakos approved these changes

2022-02-04 10:52 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
> +        importantDatesPage.assertDayTextIsDisplayed(generateDayString(2.days.fromNow.iso8601.toDate()))
You can use the same Date object here that is used for the schedule item creation.

2022-02-04 12:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111725106%2Fp%2F3dc4050a36d7045c2d18183f3cbbb4db&size=150x150>

2022-02-04 12:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F111725823%2Fp%2Fc705d4a665b7af39379777bd964e0637&size=150x150">

2022-02-04 12:33 UTC, merged