[MBL-15836][Student] - Important dates E2E test for C4E
instructure/canvas-android pull request #1512
Opened 2022-03-01 15:40 UTC by kdeakinstructure

Implement important dates E2E test for Canvas For Elementary courses and extend AssignmentsAPI to handle important dates.

refs: MBL-15836
affects: Student
release note: none

2022-03-01 16:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F115421226%2Fp%2Fda8860bab30f070c135ef969a32e8f8f&size=150x150">

2022-03-02 09:43 UTC, tamaskozmer requested changes

2022-03-02 10:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F115546253%2Fp%2Fefa30560cc23ba0881bcc4155d5358cc&size=150x150">

2022-03-02 12:01 UTC, tamaskozmer approved these changes

2022-03-02 12:24 UTC, merged