Document scanning
instructure/canvas-android pull request #1515
Opened 2022-03-03 13:06 UTC by hermannakos

2022-03-03 13:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F115799746%2Fp%2F528fe9eab44351a48a61951d5235bccc&size=150x150">

2022-03-07 10:15 UTC, hermannakos commented on apps/DocumentScanner/src/main/java/com/zynksoftware/documentscanner/ui/imagecrop/ImageCropFragment.kt
> +    private fun onConfirmButtonClicked() {
Here instread of going to the ImageProcessingFragment return the cropped image and handle image processing in our code.

2022-03-07 11:37 UTC, tamaskozmer requested changes

2022-03-07 11:37 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/util/AppManager.kt
> +import com.zynksoftware.documentscanner.ui.DocumentScanner
This import is unused.

2022-03-07 11:37 UTC, tamaskozmer commented on apps/teacher/build.gradle
> +    api project(path: ':DocumentScanner')
Do we need this in the teacher app?

2022-03-07 16:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116258998%2Fp%2Ffb867dbcfbfcbf450ef0749fe989be31&size=150x150>

2022-03-08 09:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116377044%2Fp%2F7eee23e384c5b60e1042f4c92409478b&size=150x150>

2022-03-08 09:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116377512%2Fp%2F5183e914a2e10b28c6be3f1270dd8ae3&size=150x150">

2022-03-08 10:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116384117%2Fp%2F4863a97acfcf34e089ee09f7d19b5058&size=150x150>

2022-03-08 10:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116387995%2Fp%2F15f73983d03a3478a6116683599f6047&size=150x150">

2022-03-08 10:45 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116393422%2Fp%2F2e537244b5dad9bab1d56af75037ad10&size=150x150>

2022-03-08 10:52 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116394747%2Fp%2F43bab2c2ec54d18f4b75edef63ccbfcb&size=150x150">

2022-03-08 15:31 UTC, kdeakinstructure approved these changes
QA 👍

2022-03-09 11:54 UTC, tamaskozmer approved these changes

2022-03-09 12:58 UTC, merged