[MBL-15353][Student][Teacher] Add Push notification settings
instructure/canvas-android pull request #1521
Opened 2022-03-10 13:44 UTC by hermannakos

refs: MBL-15353
affects: Teacher
release note: Push notification settings can be changed from the app.

test plan: For both apps test the Settings > Push notifications screen. Check the api response

2022-03-10 14:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116856037%2Fp%2Fc974d9db0596130b0e686eb702d8f736&size=150x150>

2022-03-10 14:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F116858284%2Fp%2F678de2c6a97041448e8957259ae9b85e&size=150x150">

2022-03-11 10:28 UTC, tamaskozmer requested changes

2022-03-11 10:28 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/notification/preferences/NotificationPreferencesViewModelTest.kt
> +        mockkStatic("kotlinx.coroutines.AwaitKt")
We only need this, when we use the `awaitAll` call in the ViewModel.

2022-03-11 11:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F117037329%2Fp%2F712a61f4cde1056227115680a49a5d3a&size=150x150>

2022-03-11 11:17 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F117038537%2Fp%2F43ccf0f6d05d9b654a84f50299e15f7b&size=150x150">

2022-03-11 11:17 UTC, tamaskozmer approved these changes

2022-03-16 12:36 UTC, kdeakinstructure approved these changes
QA 👍

2022-03-16 12:48 UTC, merged