[MBL-15913][Student][Teacher] Discussion Redesign, anonymous replies don't load
instructure/canvas-android pull request #1526
Opened 2022-03-17 08:54 UTC by tamaskozmer

Test plan: 
- Create an anonymous discussion with the discussions redesign (one is included in the ticket)
- Open the anonymous discussion
- You should see a text that the discussion is not supported on mobile and a link to open the discussion in a WebView.
- Verify that the discussion opens
- Also smoke test regular discussions

refs: MBL-15913
affects: Teacher, Student
release note: none

2022-03-17 09:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F117873222%2Fp%2Ff923281abbf34cdecd6ecdc11afdd303&size=150x150>

2022-03-17 09:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F117874630%2Fp%2Fc311b49b15da3c98814574509b992bc6&size=150x150">

2022-03-17 09:28 UTC, hermannakos requested changes

2022-03-17 09:28 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt
> +            }
Maybe we should hide the button if for some reason the url is not available or have some error handling.

2022-03-21 08:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F118278167%2Fp%2F807af84cb579742237ff829bf1042b8d&size=150x150>

2022-03-21 08:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fartifact%2F118279018%2Fp%2F7081e579f5b09a47e1e5ef8b819f8303&size=150x150">

2022-03-21 10:10 UTC, kdeakinstructure approved these changes
QA 👍

2022-03-21 10:31 UTC, merged