[MBL-15595][Ops] Code coverage
instructure/canvas-android pull request #1535
Opened 2022-03-30 15:45 UTC by hermannakos

refs: MBL-15595
affects: All
release note: none

test plan: Check the coverage reports on inseng. Check the Bitrise workflow.

2022-03-30 16:00 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F3bbb442eee902883%2Fbuild%2F94cf652d-15b8-4c20-8e6f-b718ecc670e5%2Fartifact%2F5de4c818d00ecfe0%2Fp%2F47cf841df13275f74984b03217d92f63&size=150x150">

2022-03-31 09:00 UTC, kdeakinstructure approved these changes

2022-03-31 11:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0caa0443-4ef3-4225-915a-ceff56075a6a%2Fartifact%2Fa31ca0800e2b8809%2Fp%2Fc7c980631574cc3d084586b4783c6e63&size=150x150>

2022-03-31 11:41 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3b1d0617-4075-4099-9fc2-19651cff5ce2%2Fartifact%2Fc469b278e744ac5a%2Fp%2F4d738aea0e6062b6928dc278b0bf5a36&size=150x150">

2022-03-31 14:31 UTC, tamaskozmer requested changes

2022-03-31 14:31 UTC, tamaskozmer commented on apps/student/build.gradle
> +                           '**/*Reveiver*.*',
I think this is a typo that actually matters because Receiver classes won't be excluded.

2022-03-31 14:31 UTC, tamaskozmer commented on apps/teacher/build.gradle
> +                           '**/*Reveiver*.*',
Same here

2022-03-31 14:34 UTC, tamaskozmer approved these changes

2022-03-31 14:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F450ac7a3-cbde-406c-a119-0ef130a14a01%2Fartifact%2F94046530b3221947%2Fp%2Ffa149a0750516953462307c6961e69e0&size=150x150>

2022-03-31 14:50 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F3bbb442eee902883%2Fbuild%2F5afe908e-5255-4568-910e-9746560dd07e%2Fartifact%2Fa1354bd2fe592cef%2Fp%2F4d3d919153ba0e7b3bbf10e246a4e9f0&size=150x150">

2022-03-31 14:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa884fa27-2e45-41df-bf64-db6e45369b88%2Fartifact%2F3304d7d1aa3ed7dc%2Fp%2F4fbf6d79057ec3ec8de0c4a644978a9c&size=150x150">

2022-04-01 08:05 UTC, merged