[MBL-15977][Student][Teacher] Discussion redesign
instructure/canvas-android pull request #1588
Opened 2022-05-26 11:11 UTC by hermannakos

refs: MBL-15977
affects: Student, Teacher
release note: none

test plan: Enable the discussion redesign feature flag for your sandbox (you can enable/disable it by course as well). Smoke test around the Discussion, Announcements and Group Discussions.

2022-05-26 11:58 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb36d911e-0272-4683-b405-0e6070fce593%2Fartifact%2F1c8e16ced48e3532%2Fp%2Fc3a722cd5e1bc74fed61eb81beeb92e5&size=150x150>

2022-05-26 12:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd3f6aadd-315d-4059-832f-423646e0dfeb%2Fartifact%2F3c3e92a0d615cc4b%2Fp%2Ff078f79834fda4655e5b78c45467ad59&size=150x150">

2022-05-26 12:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F73c426dc-e3e6-461d-8075-e0f74bdba288%2Fartifact%2F3af9e7ffa301db7f%2Fp%2F8dd81fc9b83852d13dfe7989511ba8ee&size=150x150>

2022-05-26 12:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa547858d-d62f-421b-bc6f-2b85803429d8%2Fartifact%2Ff1886b82091de267%2Fp%2F42f5f94859b8d424c0acf5c1e7666ad1&size=150x150">

2022-05-30 10:42 UTC, kdeakinstructure approved these changes
QA 👍

2022-05-30 13:13 UTC, tamaskozmer requested changes

2022-05-30 13:13 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/details/DiscussionDetailsWebViewViewModel.kt
> +                val authenticatedUrl = "${oauthManager.getAuthenticatedSessionAsync(url).await().dataOrThrow.sessionUrl}&embed=true&session_locale=$locale&session_timezone=$timezone"
It looks a bit weird to embed an async call into a string.

2022-05-30 13:13 UTC, tamaskozmer commented on libs/pandautils/src/main/res/layout/fragment_discussion_details_web_view.xml
> +    <FrameLayout
Do we need this FrameLayout? I think the `EmptyView` can be in the `ConstraintLayout` as well.

2022-05-31 08:45 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F10e42641-0a5f-425f-a224-153fe76c0d26%2Fartifact%2Fbc845c51145b2a1c%2Fp%2F2c5a75c10a3041c1d5d99fc8339de981&size=150x150>

2022-05-31 08:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb8536833-c125-4dfd-b545-804db19613a9%2Fartifact%2F1b22c6dc52981acc%2Fp%2Fa439d4ce1c24bea45c2ae015ac5b1d02&size=150x150">

2022-05-31 09:52 UTC, hermannakos commented
refs: MBL-15977
affects: Student, Teacher
release note: none

test plan: Enable the discussion redesign feature flag for your sandbox (you can enable/disable it by course as well). Smoke test around the Discussion, Announcements and Group Discussions.

2022-05-31 09:52 UTC, merged