[MBL-16055] [Teacher] - Merge Modules E2E tests into one test case
instructure/canvas-android pull request #1599
Opened 2022-06-08 13:41 UTC by kdeakinstructure

Merge ModulesE2ETest cases into one case in Teacher.

refs: MBL-16055
affects: Teacher
release note: none

2022-06-08 13:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2ae60647-868f-420a-a878-869b7ca9f2f4%2Fartifact%2F0e7fa8c9f6d68f16%2Fp%2Fa635abfbf0489ca3bfa4da934898334a&size=150x150>

2022-06-09 09:13 UTC, hermannakos requested changes

2022-06-09 09:13 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
> +        Log.d(STEP_TAG, "Login with user: ${teacher.name}, login id: ${teacher.loginId} , password: ${teacher.password}")
I don't think we should log all of these information even if it's just a test user.

2022-06-09 14:25 UTC, hermannakos approved these changes

2022-06-09 14:29 UTC, merged