[MBL-16040] [Student] - Refactor announcement interaction tests
instructure/canvas-android pull request #1625
Opened 2022-06-24 15:03 UTC by kdeakinstructure

Implement group announcement creation with student user.
Implement new API endpoint for MockCanvas.
+Some refactor

refs: MBL-16040
affects: Student
release note: none

2022-06-24 15:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1e8532b0-5ee5-44ce-98a7-fb83160d8535%2Fartifact%2F14ef189655ab843b%2Fp%2F950a790c4c5566054763081049012561&size=150x150>

2022-06-27 10:30 UTC, hermannakos requested changes

2022-06-27 10:30 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AnnouncementInteractionTest.kt
> +        discussionListPage.createAnnouncement("Student created Group Announcement", "Cool group announcement", true)
I know it's been like this for a while now, but shouldn't we separate the creation and verification?

2022-06-27 10:37 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AnnouncementInteractionTest.kt
> +import com.instructure.canvas.espresso.mockCanvas.addFileToFolder
Damn, somehow my studio disabled the "Optimize imports" checkbox after update. Good catch, thx!

2022-06-27 10:42 UTC, kdeakinstructure commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
> +fun MockCanvas.addDiscussionTopicToCourse(
It's actually not a duplicate, because one method is calling the other with the corresponding parameters. It's just a simple overload to be able to call this even with a Course object or with a simple ID.

Lots of usages of the old one (with the Course object parameter), however, I think it is even unnecessary to pass the whole Course object to this method because it is only using it's id. 

The old usages might could be refactored in the future to use the id instead of the whole object, but in my case, my course is coming from actually a group, and i could only reach it from my "group" object somehow like this:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/92309696/175923610-54740890-3bbe-4920-89a5-91dd5bef7e90.png">

I just thought that it would be a bit overhead in this case so that's why I decided to refactor (aka. overload) the future so that I could passed the id itself easily by calling group!!.courseId.

2022-06-27 11:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb7d8d799-2a06-4eb3-935b-de318341ed22%2Fartifact%2F2e0fdf08ae7496d9%2Fp%2Fe6665874ca3689c047c6e48226fe0072&size=150x150>

2022-06-27 11:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9c2a3f54-377e-46a7-89a8-59b3c71217fe%2Fartifact%2F8b0b9d9ed092408c%2Fp%2F11a6f30314b75ffabeaaf615834a4860&size=150x150">

2022-06-27 12:13 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5bd2723c-ba03-472f-8892-d1ab7da05a5c%2Fartifact%2Fefdb42b8ad87b11d%2Fp%2F2927468db93f19036b502d2ad5edd58d&size=150x150>

2022-06-27 12:15 UTC, hermannakos approved these changes

2022-06-27 12:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8499bdec-26ec-47d6-af2f-765180a3fdde%2Fartifact%2F00ecd23bdda28773%2Fp%2F31a61a7ae1e17e31524fe047fea1a391&size=150x150>

2022-06-27 12:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc405f073-d378-470d-bb93-b431160e2550%2Fartifact%2Fd2489ef0e42beddf%2Fp%2Fbf83194c0c690523f6757b00582b8325&size=150x150">

2022-06-27 13:06 UTC, merged