[MBL-15990] [Student][Teacher] - Implement Dark mode tests in both apps
instructure/canvas-android pull request #1631
Opened 2022-06-28 14:13 UTC by kdeakinstructure

Implement Teacher Dark Mode settings test case.
Extend some pages in Teacher app with color asserting methods.
Extend Teacher SettingsPage with AppTheme related elements and methods.
Rename 'launch'-leading method name conventions to 'open'.
+Some refactor

Implement Student Dark Mode settings test case.
Extend some pages with color asserting methods.
Extend SettingsPage with AppTheme related elements and methods.
Rename 'launch'-leading method name conventions to 'open'.
+Some little refactor.

refs: MBL-15990
affects: Student, Teacher
release note: none

2022-06-28 14:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3498aecc-43df-4bdc-82cb-576af1724148%2Fartifact%2F0a2b5f97bdded8db%2Fp%2F4a51b87f1056c1418bfa0a0c1e39d4c9&size=150x150>

2022-06-28 14:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F28c0c2ef-f650-42b3-87d9-25691ad583ae%2Fartifact%2F91792414f07a041a%2Fp%2F3a660568d11491b94ea597fea85f6a7e&size=150x150">

2022-06-29 13:04 UTC, tamaskozmer requested changes

2022-06-29 13:04 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt
> +        when (appTheme) {
This could be much cleaner if you would just pass the string resource as a parameter. In that case you wouldn't need the condition.

2022-06-29 13:04 UTC, tamaskozmer commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SettingsPage.kt
> +    fun selectAppTheme(appTheme: AppTheme)
Same here

2022-06-29 13:04 UTC, tamaskozmer commented on automation/espresso/src/main/kotlin/com/instructure/espresso/CustomViewAssertions.kt
> +class TextViewColorAssertion(private val colorHexCode: String) : ViewAssertion {
Nice 👍

2022-06-29 15:21 UTC, tamaskozmer approved these changes

2022-06-29 15:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fcb63d3d1-6c0b-4a84-a5b8-b709c5097e74%2Fartifact%2F63f6e481a5dda79f%2Fp%2Fa86dd987c487b167c19354e3e16d2101&size=150x150>

2022-06-29 15:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8b89151d-4bb9-4d44-99bc-cf2d4208a5d6%2Fartifact%2F0e173e8b9109dab1%2Fp%2F1b2e70acf817ff1902d5266a8c7f2636&size=150x150">

2022-06-30 08:02 UTC, merged