[MBL-14127][Student] - Rewrite conferences e2e from webview to native
instructure/canvas-android pull request #1648
Opened 2022-07-13 23:00 UTC by kdeakinstructure

Major refactor (aka. re-write) on Student Conferences E2E test.
Adding new pages and filling up skeleton classes
Add id to a layout in fragment_conference_details.xml
Create Conferences API (there is no documentation for it)
Update android vault 

refs: MBL-14127
affects: Student
release note: none

2022-07-13 23:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1a8d7c1b-5fe5-4457-a2c8-ac8d48de9244%2Fartifact%2Fb4c038b39d3a84bc%2Fp%2F47c3b9936373a1e848664c1461b3a954&size=150x150">

2022-07-20 12:38 UTC, hermannakos requested changes
Could you check the models in general. It seems that they can be cleaned up a bit.

2022-07-20 12:38 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/ConferencesApi.kt
> +    fun createCourseConference(token: String, title: String, description: String, conferenceType: String, longRunning: Boolean?, duration: Int?, userIds: List<Long>?, courseId: Long): ConferencesResp
Why is this boolean nullable? Could you set a default value instead?

2022-07-20 12:38 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesRequestApiModel.kt
> +// Copyright (C) 2018-present Instructure, Inc.
Please check the copyright template to use the current year.

2022-07-20 12:38 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesRequestApiModel.kt
> +        val longRunning: Boolean? = false,
It has a default value, why is this nullable?

2022-07-20 12:38 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesRequestApiModel.kt
> +        val duration: Int? = null,
Can a duration ever be null?

2022-07-20 12:38 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesResponseApiModel.kt
> +        val longRunning: Int? = null,
Why is it an Int here instead of boolean like everywhere else?

2022-07-20 12:38 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesResponseApiModel.kt
> +        val duration: Double? = null,
It's double here but other places it's an integer

2022-07-20 12:59 UTC, kdeakinstructure commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesResponseApiModel.kt
> +        val longRunning: Int? = null,
This is how this API works, in the request, long_running is a boolean parameter but it gives back an integer (0 or 1) within the response

2022-07-21 12:30 UTC, tamaskozmer requested changes

2022-07-21 12:30 UTC, tamaskozmer commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/ConferencesApi.kt
> +    fun getCourseConferences(token: String, courseId: Long): List<ConferencesResponseApiModel> {
This function is unused.

2022-07-21 12:30 UTC, tamaskozmer commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/ConferencesApi.kt
> +        fun getCourseConferences(@Path("courseId") userId: Long): Call<List<ConferencesResponseApiModel>>
This is unused as well.

2022-07-22 10:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe6e39a86-2ec7-4d70-ba4b-1ec1d5b49eea%2Fartifact%2Fad6ac4a69e2ab587%2Fp%2Fb8a9392fb4a63f17e2ca4a09bac8f312&size=150x150">

2022-07-22 11:23 UTC, kdeakinstructure commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesRequestApiModel.kt
> +// Copyright (C) 2018-present Instructure, Inc.
thx

2022-07-22 11:26 UTC, kdeakinstructure commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ConferencesResponseApiModel.kt
> +        val duration: Double? = null,
thx, first i thought it can be double but later realized it can't.

2022-07-22 11:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6b97f99f-e3d0-4edc-9877-fa346150f5a3%2Fartifact%2Fc26a77d276e55b6e%2Fp%2F1f375d34d3e69da5ff06c67ced8204a9&size=150x150">

2022-07-22 15:52 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc9e707c2-01a8-47f1-a721-4ca68994e99a%2Fartifact%2Ffe1d4e41ddaf58d3%2Fp%2Fc1586043f1f9ea1256c1d5b03b95e085&size=150x150">

2022-07-25 09:05 UTC, kdeakinstructure commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/ConferencesApi.kt
> +    fun getCourseConferences(token: String, courseId: Long): List<ConferencesResponseApiModel> {
I've deleted them

2022-07-25 09:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1892763d-0ae6-4f96-a1b3-49a51ddbbe96%2Fartifact%2Fa3bbdf80fe19d40f%2Fp%2F41a614caa578f41c72190cf1eab5aa6f&size=150x150">

2022-07-25 10:51 UTC, tamaskozmer approved these changes

2022-07-25 11:36 UTC, hermannakos approved these changes

2022-07-25 11:36 UTC, merged