[MBL-16101][Teacher] - Implement Login E2E test cases to Teacher app
instructure/canvas-android pull request #1652
Opened 2022-07-20 09:41 UTC by kdeakinstructure

Implement Login E2E test cases to Teacher app
Add some page object methods and members to classes
Some refactor

refs: MBL-16101
affects: Teacher
release note:

test plan:

2022-07-20 10:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F06d062af-30d6-4b88-a4b4-513a8def40b0%2Fartifact%2F0ad87105f1d7c2f1%2Fp%2F685b4631fe3ba1d2dc35ceb2e8ed5d75&size=150x150>

2022-07-20 10:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff2c28124-8d83-4eff-a1dc-c477a1297c69%2Fartifact%2F2bca58aa026587e9%2Fp%2F384a1650986ed296ca95eab5e7731285&size=150x150">

2022-07-20 12:46 UTC, hermannakos requested changes

2022-07-20 12:46 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
Please setup a copyright template or change the year if you copy it from somewhere else

2022-07-20 12:46 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
> +        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
Don't leave a todo here, if you don't use this function make it return Unit.

2022-07-20 12:46 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
> +        Log.d(STEP_TAG,"Login with user: ${teacher1.name}, login id: ${teacher1.loginId} , password: ${teacher1.password}")
I still don't like that we're logging the password to a production environment.

2022-07-20 12:46 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt
> +        waitForMatcherWithSleeps(ViewMatchers.withId(R.id.canvasLogo), 20000).check(matches(isDisplayed()))
Do we really need a 20 second delay here?

2022-07-22 12:04 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
> +        Log.d(STEP_TAG,"Login with user: ${teacher1.name}, login id: ${teacher1.loginId} , password: ${teacher1.password}")
I'll figure out how to handle this in the near future.

2022-07-22 12:18 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt
> +        waitForMatcherWithSleeps(ViewMatchers.withId(R.id.canvasLogo), 20000).check(matches(isDisplayed()))
20 secs is just a maximum period of time here, this waitForMatchetWithSleeps is actually kind of a Selenium FluentWait, so it works with poll-intervalls. The method has a default poll interval in milliseconds, so it just keep re-checking and once it finds the logo, it won't wait any more.

Anyways, I've decreased the delay to 10 seconds, and we will see how it will work on Bitrise. (If it gets flaky, I might must to increase back to 20 sec, but let's give it a try with 10).

2022-07-22 12:28 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0fb3703f-8f69-4087-94ce-196877ce505f%2Fartifact%2F294e72735a35f505%2Fp%2F0bbfd24ce05d3609dc409cb8f450af16&size=150x150>

2022-07-22 12:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2d3bd087-ceb6-4ba0-b95e-37f51f54dd05%2Fartifact%2F15f9e7406c2d032e%2Fp%2F58afdf543536986f4d54683de62c21b9&size=150x150">

2022-07-25 10:34 UTC, hermannakos approved these changes

2022-07-25 11:16 UTC, merged