[MBL-16138][Student][Teacher] Share Extension basic UI + File Upload
instructure/canvas-android pull request #1661
Opened 2022-07-25 13:48 UTC by hermannakos

refs: MBL-16138
affects: Student, Teacher
release note: none

test plan: 

1. Check the Share Extension functionality when sharing into the app.
2. Smoke test the File Upload dialog

- User files in both apps
- Discussion reply in both apps
- Create discussion in both apps
- Messages in both apps
- Create/Edit announcement in the Teacher app

2022-07-25 13:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe93b5227-b069-4601-a88d-b557f1d89c1e%2Fartifact%2Faffa85b581d90d29%2Fp%2F90f35a0fa444bfbd491b7787c9593d12&size=150x150>

2022-07-28 12:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd37f3e7c-aba3-47b3-9a42-b8f6b130d932%2Fartifact%2F86914a41ae8e7654%2Fp%2Ff3b745436f876d110b30b00d26f23349&size=150x150>

2022-07-29 10:16 UTC, tamaskozmer requested changes

2022-07-29 10:16 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/target/ShareExtensionTargetViewModel.kt
> +    fun getValidatedData(): FileUploadTargetData? {
This function seems a bit out of the MVVM concept. It seems strange that we request data from the ViewModel, but the function also contains some side effects which is not reflected in the name of the function. I think it would be more readable if the function would be just `validateData` and it would send a `ShowUploadDialog` event if the data is valid.

2022-07-29 11:09 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/target/ShareExtensionTargetFragment.kt
> +                        }, 600)
This is from the legacy code, I'll check if we still need this.

2022-07-29 11:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F08fb35d2-f25b-439f-a72b-aafb019d2955%2Fartifact%2F31e1e736ed3e20bc%2Fp%2F687a8879d80351393f8b2c29d3ee46bb&size=150x150>

2022-07-29 12:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff5a63f08-3b08-453d-ae88-84961c285f67%2Fartifact%2Fde19d45d4e8f2b66%2Fp%2F8f1f66ad98b566ae28d1432e868dc00e&size=150x150>

2022-07-29 13:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd19891c0-95af-4a71-b5dd-54df3d9071ec%2Fartifact%2Fa2dc2c348bb1f1e2%2Fp%2Fcb91c8450ac049e2fc68e8eff31f662b&size=150x150>

2022-07-29 13:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F81614c80-cc2b-4c80-bb1e-765677ba2442%2Fartifact%2Fb2e9e610fde16c94%2Fp%2F2e0329be5441e9859d0139c045d42970&size=150x150>

2022-08-01 13:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F39dea639-07f6-49ce-b9f0-de9bb0010484%2Fartifact%2Fca2d938ab2d6d8e7%2Fp%2Fb78656045092427d263c6a40cc57aeb8&size=150x150>

2022-08-03 09:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb9a3f0b5-0f20-44cf-b6c5-09a54b325ea7%2Fartifact%2F857e723fbea0d527%2Fp%2F8cceeb55885569bea4ef2f849f5bd884&size=150x150>

2022-08-03 09:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fefe8d5e9-4490-4cd3-9a88-1698028b4235%2Fartifact%2Ff3a1dfef47ffa895%2Fp%2F97f62fe5b18019f315c6f8f338d7ec7d&size=150x150">

2022-08-08 09:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F017a7fd0-72a3-4da8-80ce-60458c3d2d95%2Fartifact%2F5050d3ba33db24da%2Fp%2Fe77f88eb75b808a30c5a412834cca550&size=150x150>

2022-08-08 09:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb35b721e-cede-4de6-b70e-a92972ae1c23%2Fartifact%2Fb3ce6e3432c9306d%2Fp%2Fdc38305051e2a6db0f06e6a8aba1621a&size=150x150">

2022-08-08 11:14 UTC, kdeakinstructure approved these changes
QA 👍

2022-08-08 14:14 UTC, merged