[MBL-16140][Student][Teacher] File Upload with WorkManager
instructure/canvas-android pull request #1687
Opened 2022-08-25 12:48 UTC by hermannakos

refs: MBL-16140
affects: Student, Teacher
release note: none

test plan: Smoke test both of the apps. Compare with the production version, the functionality should be the same.

- User files in both apps (with notifications)
- Discussion reply in both apps
- Create discussion in both apps
- Messages in both apps (with notifications)
- Create/Edit announcement in the Teacher app
- ShareExtension in the Student app (with notifications)

2022-08-25 13:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F084ace54-7400-42ae-860a-2b7e092ffc2d%2Fartifact%2F96a48096f466de0d%2Fp%2Feaa1ea2731dbc91228c4f523d9268d90&size=150x150>

2022-08-25 13:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa5079e78-6437-4967-ba3c-1cf35eccefd3%2Fartifact%2F1f8436b1c37b2085%2Fp%2F5409542bba2c4dd64a093dbf5d71177e&size=150x150">

2022-08-26 08:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F932e39d8-bc81-4c36-bd53-4c7558c8b265%2Fartifact%2F9073cfbb47986962%2Fp%2F776cbbc7c6958856bc0791ac4a16f4ca&size=150x150>

2022-08-26 08:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa33ee431-97e9-4c21-9d39-8389c584a5a5%2Fartifact%2Ff8510a55893dde3f%2Fp%2F8cce03baaaba5645c4230e9f7d2d7d31&size=150x150">

2022-08-26 12:21 UTC, tamaskozmer requested changes

2022-08-26 12:21 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/worker/FileUploadWorker.kt
> +            } ?: return Result.failure()
We should only add the worker id after this line so it won't stay there if we return with an early failure.

2022-08-26 12:27 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/worker/FileUploadWorker.kt
> +        if (fileSubmitObjects.contains(null)) throw IllegalArgumentException("Could not parse file.")
With the filtering we are really just converting from `List<T?>` to `List<T>`

2022-08-26 12:27 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogViewModel.kt
> +        uris.removeAt(index)
Sure, I'll do the second option.

2022-08-26 12:28 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/AddMessageFragment.kt
> +                        ?.map { it.fromJson<Attachment>() } ?: TODO("Handle error")
Nope, just forgot, thanks for catching it.

2022-08-26 12:29 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/worker/FileUploadWorker.kt
> +            } ?: return Result.failure()
I'll just throw an exception instead of the result, so it's more in line with the other error handling.

2022-08-26 13:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff511d3ed-4f9e-49c2-9ae2-eebfeba60420%2Fartifact%2F21993355f70892ed%2Fp%2Fe6534c92b7294b6ad9c57fddef40fcd7&size=150x150>

2022-08-26 13:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6917a6b5-5dfe-48aa-b95c-87d07874d042%2Fartifact%2Fc43a17768ad7ffa2%2Fp%2F5406405bd08fff8bb9d30364c07d4a1f&size=150x150">

2022-08-26 14:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F52c83e1c-6698-4761-9aae-d008ca2c9d03%2Fartifact%2F694e6b1825dc6f2e%2Fp%2F99f3d71893ce009c936bd4ed0d268776&size=150x150>

2022-08-26 14:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fde810b2a-387d-4aa1-8945-3a755160f956%2Fartifact%2Fb5a7f8cb1d74b77c%2Fp%2Fdd9f75b5532c1c386cd73611076f05f4&size=150x150">

2022-08-26 14:35 UTC, tamaskozmer approved these changes

2022-08-26 14:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1317d736-aab6-4dbe-b308-5c07785eed79%2Fartifact%2Fb24276228b4836e1%2Fp%2Fd8ba0c34bb992aeaf203df9db057f6fb&size=150x150>

2022-08-26 14:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7feb64b7-d451-467e-ae89-323683235820%2Fartifact%2F60cb7ebd223e4dbd%2Fp%2Ff766e85b09840b5a8664ae47590f2d20&size=150x150">

2022-08-29 08:17 UTC, kdeakinstructure approved these changes
QA 👍

2022-08-29 08:46 UTC, merged