[MBL-16141][Student] Share extension | Dashboard notification
instructure/canvas-android pull request #1690
Opened 2022-08-30 14:59 UTC by kristofnemere

refs: MBL-16141
affects: Student
release note: none

Test plan: smoke test the student app, the upload notification on dashboard should appear when
- sharing files to the app
- uploading files in the app by the new file upload dialog

2022-08-30 15:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe0dc77e2-53fd-41fc-bead-7889cde893b1%2Fartifact%2F519c9c5633c01a04%2Fp%2F3692dd91582af143d78deb7cd5ed995c&size=150x150>

2022-08-30 15:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc51770ba-c9d5-4cf8-a68b-071589445dc5%2Fartifact%2Fb498c1b12ec56b34%2Fp%2Fbfbfb989a0dc6f55e6c9c9d1b145bbfa&size=150x150">

2022-08-31 12:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc8eec443-24e3-4b0b-9f0c-176b62a12df5%2Fartifact%2F58df7812da27d38f%2Fp%2F782973e5188e43dacf8891f6e6755256&size=150x150>

2022-08-31 12:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb0ecb2e2-3e12-48fb-abf0-95f3386da524%2Fartifact%2F52b02ed0a56f69d2%2Fp%2Ff44789ff3cf35842cab13da68411332f&size=150x150">

2022-09-01 11:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F462e6d5d-e984-4415-a409-db1e7366eadf%2Fartifact%2Fd8109cb829229ef4%2Fp%2Fd35a9bde249677d26fb4c117e765c1e6&size=150x150>

2022-09-01 11:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F13b57148-ac16-4c88-bd51-751d8aa9f73e%2Fartifact%2F000b26ffc89bce9c%2Fp%2F64a288f49fb54816ad81b16f601fe961&size=150x150">

2022-09-01 13:17 UTC, kdeakinstructure approved these changes
QA 👍

2022-09-02 10:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc6e002a8-ebde-404c-bddb-66e5dd6fd900%2Fartifact%2Ffb5fa887bca7dddb%2Fp%2F7b2d773a82aaa8651a18f24b7360d852&size=150x150>

2022-09-02 10:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb7e5677c-9ba6-4e75-b892-9f8552203656%2Fartifact%2Ffc19f9e19bb1a0c2%2Fp%2F7b449dbc3ca1534a4e883f2f4e5aa235&size=150x150">

2022-09-02 11:17 UTC, hermannakos requested changes

2022-09-02 11:17 UTC, hermannakos commented on libs/pandautils/src/main/res/layout/item_dashboard_upload.xml
> +                android:layout_height="3dp"
this should be `wrap_content`

2022-09-02 11:17 UTC, hermannakos commented on libs/pandautils/src/main/res/layout/item_dashboard_upload.xml
> +                app:layout_constraintTop_toBottomOf="@id/uploadSubtitle" />
you can set the progress tint to `@color/backgroundInfo`

2022-09-02 11:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F28ead023-2a94-40e9-8166-149bb63ca3a3%2Fartifact%2Fdcfc8202ce06310e%2Fp%2F996d7e62c05ad93b21e71ef661c7da49&size=150x150>

2022-09-02 11:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F95559ed6-5bc3-4e05-88ca-473fbcd1ce3b%2Fartifact%2F91222d04760ac354%2Fp%2Ff3f34af3228b35f4ad7cf7d3df601f5e&size=150x150">

2022-09-02 11:31 UTC, hermannakos requested changes

2022-09-02 11:31 UTC, hermannakos commented on libs/pandautils/src/main/res/values/strings.xml
> +    <string name="dashboardNotificationUploadingSubmissionTitle">Uploading Submission</string>
These should be moved to pandares.

2022-09-02 11:31 UTC, hermannakos commented on libs/pandautils/src/main/res/layout/item_dashboard_upload.xml
> +                style="@android:style/Widget.ProgressBar.Horizontal"
set it to `style="?android:attr/progressBarStyleHorizontal"`

2022-09-02 11:57 UTC, hermannakos approved these changes

2022-09-02 11:58 UTC, kristofnemere commented on libs/pandautils/src/main/res/layout/item_dashboard_upload.xml
> +                app:layout_constraintTop_toBottomOf="@id/uploadSubtitle" />
Fixed, thanks.

2022-09-02 11:58 UTC, kristofnemere commented on libs/pandautils/src/main/res/values/strings.xml
> +    <string name="dashboardNotificationUploadingSubmissionTitle">Uploading Submission</string>
Fixed, thanks.

2022-09-02 11:58 UTC, kristofnemere commented on libs/pandautils/src/main/res/layout/item_dashboard_upload.xml
> +                style="@android:style/Widget.ProgressBar.Horizontal"
Fixed, thanks.

2022-09-02 12:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0645455a-d32b-4295-a6bc-73bc32ec163b%2Fartifact%2Fb93b51650e009feb%2Fp%2Fb667657cd83345af264bf14dc4a12d43&size=150x150>

2022-09-02 12:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0d80e57a-8b92-4c77-8c5b-8246846094e3%2Fartifact%2Fdce9e2448b2bf3f6%2Fp%2F639abd1361501697320d330cd16cd535&size=150x150">

2022-09-02 12:16 UTC, merged