[MBL-16139][Student] Share Extension progress
instructure/canvas-android pull request #1699
Opened 2022-09-08 10:33 UTC by hermannakos

refs: MBL-16139
affects: Student
release note: Updated the Share Extension workflow.

test plan: Smoke test the whole Share Extension workflow.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-09-08 10:45 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F22212aee-b773-4c71-b12e-80b88543354a%2Fartifact%2Fd85eeba414ea0732%2Fp%2F5d4ab6792a6c8bff96a34050b977eb5c&size=150x150>

2022-09-08 10:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2dd95b9f-e2c3-4755-8d85-971b1510b819%2Fartifact%2F997a68dbd3189f11%2Fp%2Fdee0f5a7ea87e63dd6853b4c3e03b835&size=150x150">

2022-09-08 12:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F21002fa7-2040-4511-90ca-37b47b6a1c27%2Fartifact%2F90f7eeb5a170538e%2Fp%2F17f7c0c7c9b9d805dc8d5c315ec2ed70&size=150x150>

2022-09-08 12:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa2d82386-ae41-4a8c-ad9b-323e29f1932b%2Fartifact%2F60850db7cd39a98a%2Fp%2F7af38276fe5645b21820c2a15969c988&size=150x150">

2022-09-08 12:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F72dcf681-d267-48a2-9112-fd2c4f9eb59d%2Fartifact%2F6e43932e5e60b303%2Fp%2F18d30b94939ae86f59302b255d124641&size=150x150>

2022-09-08 13:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd169e9da-b850-4801-83be-ca2186a15dc2%2Fartifact%2Fac65b61c055248df%2Fp%2F9d95daff04a9e4fc44e062035d98ed72&size=150x150">

2022-09-08 14:58 UTC, tamaskozmer requested changes

2022-09-08 14:58 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressDialogViewModel.kt
> +    private fun humanReadableByteCount(bytes: Long): String {
I have seen this already somewhere. Maybe we could make this an extension function.

2022-09-12 10:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa3a638e1-e393-4e0e-94f0-57eefcfc016b%2Fartifact%2F44cb586642ba95f2%2Fp%2F1a632e44e3e70025186c03265b04a526&size=150x150>

2022-09-12 10:58 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F19e28fee-cc56-4b50-9d46-7bced2767f59%2Fartifact%2F55af3905a65350eb%2Fp%2F5cdb49ae16a2de839fb49907cdd00b91&size=150x150">

2022-09-12 12:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F7163a58f-1bcc-44fd-af69-0645fa949f4b%2Fartifact%2F085c7e1901b414f9%2Fp%2F9a5f2991406581aa05cc72168407e0e0&size=150x150>

2022-09-12 12:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5a173b9c-4a18-4162-be40-b1fb4820857c%2Fartifact%2F9ae5167f63bd1650%2Fp%2F4dba7eb0075457034af7ff93d6365c39&size=150x150">

2022-09-12 12:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F49f70ef4-756b-4586-8c6c-01c915ac30fe%2Fartifact%2F25fa547ffe5804ce%2Fp%2Fb5d264589b9bb7a372a447ce892678f1&size=150x150>

2022-09-12 12:59 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2727593f-ceda-4c49-ba4d-53b50babdde5%2Fartifact%2F722eb86182e00087%2Fp%2F0c777af7fb1d5d6b67ead42934a3426e&size=150x150">

2022-09-13 12:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4b60c7c0-96f1-43f8-b934-d0a37a303b4f%2Fartifact%2F92dc6d7a33867a82%2Fp%2Fbb31be698719ca4ba41578a7f315372b&size=150x150>

2022-09-13 14:51 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F39bde927-8b3e-49b6-89fe-f95e28df405b%2Fartifact%2F97842cad70211b78%2Fp%2Fdb975c2c0ed1cc1dcf3acbf2a5f719eb&size=150x150>

2022-09-13 14:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F18bad41e-e11a-45c1-b1c2-78de9fff98d7%2Fartifact%2Fa68d3750a1c0059d%2Fp%2Fd5f30b46087904623be3eb45db733116&size=150x150">

2022-09-14 08:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff10c5877-fcd3-45d8-81d9-e0071b0c37e1%2Fartifact%2F33d9420fa5a319e1%2Fp%2F4572072801120212af3a254ad26cc4d1&size=150x150>

2022-09-14 08:19 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbd3369ac-9e3f-4502-89a6-6219811f64a4%2Fartifact%2Fd6d310db575654c8%2Fp%2Fe6b3e470d1a6bc0685f852788d05be16&size=150x150">

2022-09-14 08:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd2f56e36-d159-47e0-92c8-d69639b4ffb2%2Fartifact%2Fc0ed65928d53a363%2Fp%2F0213b1b0969f9df7f374921f691829d9&size=150x150>

2022-09-14 08:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F074fe90a-6e7c-4777-84bb-ed0aec6812fb%2Fartifact%2F9dc9a3d81d1fba08%2Fp%2Fb4661193f5fb388531059ef0d62c54cc&size=150x150">

2022-09-14 09:16 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F33d64b56-73ea-4af8-bed0-de39eb7d2f1d%2Fartifact%2F7972e6a681c8427e%2Fp%2Fadb1772d9b57f70522d82cd6746086d0&size=150x150>

2022-09-14 09:19 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Faf08256e-5b9e-4cb7-8ecb-a8752dce1207%2Fartifact%2Fb49fa744142daea2%2Fp%2F1c08a0f445e295fd4ef4dcfae8aa09ae&size=150x150">

2022-09-14 09:23 UTC, tamaskozmer approved these changes

2022-09-14 09:35 UTC, merged