[MBL-16133][Teacher] Pick up "Add File" menu on comment attachments
instructure/canvas-android pull request #1702
Opened 2022-09-09 10:22 UTC by kristofnemere

refs: MBL-16133
affects: Teacher
release note: none

test plan: Smoke test the submission comments screen.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="
![Screenshot_20220909-121653_Canvas Teacher](https://user-images.githubusercontent.com/109959688/189328362-8fcc198a-8820-4065-b929-3f819b3c714d.jpg)
" maxHeight=500></td>
<td><img src="
![Screenshot_20220909-114707_Canvas Teacher](https://user-images.githubusercontent.com/109959688/189328397-c4dc8669-019c-4b55-8110-068dcc7fe990.jpg)
" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-09-09 10:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe88254f9-9e8b-4360-8738-4319b614373b%2Fartifact%2F7175afcfd96b5287%2Fp%2Fea1f1fbcd1fd2c2312d93c2ecad73ad1&size=150x150>

2022-09-09 10:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb38f9b5a-0aac-4dd2-966e-afd74cc1507c%2Fartifact%2F1ad2cb3245e8a23c%2Fp%2Fd156a5819830e0613c382ca2dcec0eee&size=150x150">

2022-09-13 06:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3ff4beea-3f1c-49e9-9879-89c38ee2b620%2Fartifact%2F57697a0d896ad45b%2Fp%2F7177752d4e20fa3973d0e0ba7d9f1354&size=150x150>

2022-09-13 06:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff9d73cab-a1e1-42a0-9eb0-6eb7b8d2f9a7%2Fartifact%2Fe385d994db0c73ff%2Fp%2Fa5d29fd3ce2822f61d0e6686b260f63b&size=150x150">

2022-09-13 08:49 UTC, tamaskozmer requested changes

2022-09-13 08:49 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderCommentsPresenter.kt
> +            onError = {
This should be called `onRetry` instead, this is a bit confusing because it implies that we automatically restart after an error.

2022-09-14 11:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2266e784-7017-4af5-9333-61ffa1963dce%2Fartifact%2F3eb896951e03c3d7%2Fp%2F2b3625c9514dbcba4a96ade8bcc1246b&size=150x150>

2022-09-15 10:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fda5ace95-397d-4676-a723-fd16aa10df3b%2Fartifact%2F3138f1a53572bbff%2Fp%2F56b47a8b6f52d5eb5e10729ebc38a5f3&size=150x150>

2022-09-15 10:51 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderCommentsPresenter.kt
> +    fun removePendingFileUpload() {
I would rename this to `removeFailedFileUploads`. If I understand correctly this only removes the failed ones and not the ones that are pending upload.

2022-09-15 10:56 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ffe5edbd3-0c27-46c1-98ea-87851b702903%2Fartifact%2Fb5b8174ae9792377%2Fp%2Fd600404420718a8c3c54b1f1af0f5092&size=150x150>

2022-09-15 10:58 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderCommentsPresenter.kt
> +    fun removePendingFileUpload() {
Good point, fixed, thanks.

2022-09-15 11:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1e2c3138-369c-41cc-a4df-23380b5cfdd4%2Fartifact%2F90d3ba60323e0a7b%2Fp%2F0122b3b01873db257a8ffbb8d42996ff&size=150x150>

2022-09-15 11:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F075ffb05-65ac-467c-ae88-0c73d689c677%2Fartifact%2F3178f88a9af6ccec%2Fp%2F9515a978ecf64d7bdf7cccf2a9656a34&size=150x150">

2022-09-15 11:17 UTC, tamaskozmer approved these changes

2022-09-15 11:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F614e875c-aeb8-4c5c-a20c-7af0fdd4889a%2Fartifact%2F967e6e03bf707264%2Fp%2F02509598e69d2ce8be3c1f31fb1c7a24&size=150x150>

2022-09-15 11:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbd1e8c83-4478-433f-ad95-f6f2a9692f39%2Fartifact%2Fa0ad9a6dd17128f2%2Fp%2F661567068eed8b7423df9a81a3975202&size=150x150">

2022-09-15 12:50 UTC, hermannakos approved these changes

2022-09-15 12:59 UTC, merged