Draft: [MBL-15647][Student][Teacher] Image loading library dependency update
instructure/canvas-android pull request #1707
Opened 2022-09-14 15:19 UTC by kristofnemere

refs: MBL-15647
affects: Student, Teacher
release note: Added the option to select multiple files from the file browser for uploading.

test plan: Smoke test both apps.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-09-14 15:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc73f27e1-cdc5-4c9a-a49a-c8dd96bea10b%2Fartifact%2Fb7a9357a2d7105d5%2Fp%2Fe6122299062da1a33d399b65c856033c&size=150x150">

2022-09-15 13:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F7573034e-807d-4a0f-99f3-be5d23455fe3%2Fartifact%2F1ff3462e0466b298%2Fp%2Fc1d226b7e76bb9264e8d428fe8d293be&size=150x150>

2022-09-15 13:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd9d793b8-3673-4ebb-b4ad-fe7ea8d52e9b%2Fartifact%2F4238f904b09222f3%2Fp%2F8fef0ccc6c7715dbddaa39b3bfc523c1&size=150x150">

2022-09-20 10:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe5aeeeb2-3923-4def-84ad-0ad27758095b%2Fartifact%2Fcaf150ce85993003%2Fp%2Fd14bf94b6e6d44668915511f3ae395ba&size=150x150>

2022-09-20 10:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd5010251-4d42-4bff-8282-d126022d1e46%2Fartifact%2F929c4078aec6559f%2Fp%2F94da7cc75c71c2798b4b780e37ba9153&size=150x150">

2022-09-22 08:48 UTC, tamaskozmer requested changes

2022-09-22 08:48 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewExtensions.kt
> +                                createBitmapWithBorder(borderSize, borderColor)
This might cause problems in RecyclerViews with lots of content, because every time we scroll and bind data again we create a new bitmap. We should do some further investigation on where we call this with border and could it cause problems.

2022-09-22 08:48 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/holders/RecipientViewHolder.kt
> +                avatar.setBackgroundColor(selectionColor)
I think this causes a bug, because if the avatar is selected it should have a fill color with a white check mark, but in this case we just set a background and if it already has an avatar image this won't be displayed.

2022-09-22 08:48 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/holders/RecipientViewHolder.kt
> +                avatar.setBackgroundColor(selectionColor)
I think this causes a bug, because if the avatar is selected it should have a fill color with a white check mark, but in this case we just set a background and if it already has an avatar image this won't be displayed.

2022-09-22 11:39 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5c678f10-04e4-479b-9180-261f321bde2d%2Fartifact%2Fc4c390b069150db1%2Fp%2F7eeb7c3e67953ce463154bd68c4a09c6&size=150x150>

2022-09-22 11:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5a5d2398-450d-421e-aaaf-df512ad4c726%2Fartifact%2Fbe3863d53b940fa7%2Fp%2Fe49c37077b3a6358f859a9d2a035fad6&size=150x150">

2022-09-22 12:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F24e37e6c-b813-4bb4-89f8-e4898ef1b73e%2Fartifact%2Fae44dd3088f7064d%2Fp%2Fad88bb57bcd8633c7c4c7f7b81d676ed&size=150x150>

2022-09-22 12:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8332e5e4-bfa4-4fc8-969a-c801d5bf9ba6%2Fartifact%2F2d83fa1f4a79c64b%2Fp%2F6fd434d2e1dcda8e3d6b5c48cd976bd3&size=150x150">

2022-09-22 13:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F17d2a3b5-1776-4f99-9b6d-5758c4dd0f84%2Fartifact%2Fcae851456028ffcb%2Fp%2Fc6f55a9394cf852901989953d13aa394&size=150x150>

2022-09-22 13:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9affecb4-00a8-4760-aa19-456640f7ecf4%2Fartifact%2Fd9c1863a182c04a9%2Fp%2F8513c9fd06fc324ce9a6fa8dc31e5cec&size=150x150">

2022-09-22 13:57 UTC, tamaskozmer approved these changes

2022-09-22 14:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F05edd43f-3758-4fbc-9dfb-65a29552bb61%2Fartifact%2Ff20154f3baf0129f%2Fp%2F7ee35a5d0c9040ee03e37ab1c5bad66c&size=150x150>

2022-09-22 14:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0f015be3-0be1-402f-9a7f-3816af43c7ba%2Fartifact%2Fd72e6cc39172609a%2Fp%2F161f6b5a1162cae44f1e2b63a18946af&size=150x150">

2022-09-23 08:53 UTC, kdeakinstructure approved these changes
QA 👍

2022-09-23 09:58 UTC, merged