[Hackweek][Student] AssignmentList filters
instructure/canvas-android pull request #1724
Opened 2022-09-23 12:54 UTC by hermannakos

refs:
affects: Student
release note: Added the option to filter assignments.

test plan: Navigate to the assignment list. You can find the new filter button on the toolbar. Smoke test the assignment list screen.

2022-09-23 13:10 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff5227744-211e-4327-8152-24a2df208cb6%2Fartifact%2Fd3944fbd7bf432a8%2Fp%2Febdea2c83340cb1d90fcd49f711e3e50&size=150x150">

2022-09-27 10:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F69252908-e1b5-4c79-8e36-8476ed5ba1dd%2Fartifact%2F4da20ed5cbd28572%2Fp%2F9ca58e5b4bdd5ac6545c6a76b6375126&size=150x150>

2022-09-27 10:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0a5c8311-e909-4625-af73-cec71e789dc1%2Fartifact%2F42ce1b5f30426a34%2Fp%2F2f387ecc204bd626f3d342ed84d58b88&size=150x150">

2022-09-27 12:23 UTC, kdeakinstructure approved these changes
QA 👍

2022-09-27 15:43 UTC, kristofnemere requested changes

2022-09-27 15:43 UTC, kristofnemere commented on apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt
> +                    .setTitle(R.string.sortByDialogTitle)
I think because of the AS update your formatting settings changed, there are some unnecessary formatting changes in this PR.

2022-09-29 08:25 UTC, kristofnemere approved these changes

2022-09-29 09:11 UTC, tamaskozmer approved these changes

2022-09-29 09:16 UTC, merged