[MBL-15693][Student] Course announcement notifications
instructure/canvas-android pull request #1726
Opened 2022-09-27 13:37 UTC by kristofnemere

refs: MBL-15693
affects: Student
release note: Added notification count badge.

test plan: Smoke test all kind of notification.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Approve from product or not needed

2022-09-27 13:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F92b40de9-dbb2-4823-b6ff-2b5c91af8d35%2Fartifact%2Fe29cbde3ef0a7116%2Fp%2Fe24be223550f1ec9effd22e105a80d8b&size=150x150>

2022-09-27 13:52 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F588fdfae-c262-4777-b139-3d172229345a%2Fartifact%2F7b203cb244ba1be1%2Fp%2F3070bad5a89ea1d8b2cb296a5fe1cacc&size=150x150">

2022-09-27 15:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0d304fad-322c-4e44-a36b-53a707e4ef88%2Fartifact%2F0309e98fa54d831d%2Fp%2Ff683bde74c381dfefe6e5df92013495b&size=150x150>

2022-09-27 15:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3e3e087c-5490-428b-b837-0e3d602d60d4%2Fartifact%2F7cf298c69cb46a0a%2Fp%2F8414950fc33761103f9a08453215fdc3&size=150x150">

2022-09-28 14:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8e6cda73-55b9-45ee-8396-bdd3a87bd632%2Fartifact%2Fc42be4eab1b99456%2Fp%2F1dde39c12bd0792d13aa72bd4b5dbb47&size=150x150">

2022-09-30 07:57 UTC, kdeakinstructure requested changes
The notifications only marked as read after manual update. They shouldn't be bold after the user view them and navigates back to the notification list. (Also, the badge is only decreasing after manual refresh). We could investigate this together, because sometimes it is working, sometimes not, so it's not really consistent yet.

2022-09-30 13:36 UTC, tamaskozmer requested changes

2022-09-30 13:36 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/fragment/NotificationListFragment.kt
> +                    markSubmissionAsRead(streamItem)
I would move this into the submission screen or at least perform a network check here. It is possible that the user clicks the item, but it fails to load and we still mark it as read.

2022-09-30 13:36 UTC, tamaskozmer commented on libs/pandares/src/main/res/values/strings.xml
> +        <item quantity="other">%s unread notification</item>
This should be `%s unread notifications`.

2022-10-03 11:00 UTC, kdeakinstructure approved these changes
QA 👍

2022-10-03 12:21 UTC, kristofnemere commented on libs/pandares/src/main/res/values/strings.xml
> +        <item quantity="other">%s unread notification</item>
Fixed, thank you.

2022-10-03 12:21 UTC, kristofnemere commented on apps/student/src/main/java/com/instructure/student/fragment/NotificationListFragment.kt
> +                    markSubmissionAsRead(streamItem)
Fixed, thank you.

2022-10-03 12:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1e0372cc-d8d4-40d4-adbf-f0614eb9c0d5%2Fartifact%2Fe69f63efa59bb4cb%2Fp%2Fa1f351d18e049c25882858efc88055a5&size=150x150>

2022-10-03 12:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5d932148-89d0-4cbf-a310-5b9278fcf289%2Fartifact%2F1ac4c20a1e2edc50%2Fp%2F6c82eae777b7c5055df7bd8b53785d6e&size=150x150">

2022-10-03 15:18 UTC, tamaskozmer approved these changes

2022-10-03 15:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fcd13fb13-ad83-410e-8ddf-5954c14cb2d8%2Fartifact%2F41b5da29c149017a%2Fp%2Fe4cfec6c16b4fca063acf0b510fdd594&size=150x150>

2022-10-03 15:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8cdbc1ce-5681-4f53-804b-1475d0bb5138%2Fartifact%2F7a0c910ffda6e935%2Fp%2Fec707cf46df59cd96b3729069cbc693d&size=150x150">

2022-10-04 09:33 UTC, merged