[MBL-16286][Student][Teacher] - Add timestamp to dev build apks in Student/Teacher apps.
instructure/canvas-android pull request #1732
Opened 2022-10-03 10:53 UTC by kdeakinstructure

Add timestamp to qa and debug build apks in Student/Teacher apps.

refs: MBL-16286
affects: Student, Teacher
release note: none

2022-10-03 11:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F45fd8ea4-35f6-4d75-9250-faac0e46d959%2Fartifact%2F59c9ccfd91c5b98d%2Fp%2F2b3b1193e83400d4571305d76fdf6d1c&size=150x150>

2022-10-03 11:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4c776b8f-4c3e-4f47-9d51-bed96c6471fb%2Fartifact%2F0a9e8301072fb5e3%2Fp%2Fe083821a37d84266072cf7d4f645fd31&size=150x150">

2022-10-04 06:46 UTC, kristofnemere approved these changes

2022-10-04 06:47 UTC, kristofnemere approved these changes

2022-10-04 09:20 UTC, hermannakos requested changes

2022-10-04 09:20 UTC, hermannakos commented on apps/student/build.gradle
> +        applicationVariants.all {
flank won't be able to find the apk this way and break all the tests, you should look into that as well.

2022-10-04 09:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F776823a9-4079-4401-8cbc-bc37829cec8f%2Fartifact%2F78ea8369208fa3c6%2Fp%2F5ac6b29c52cc4ad19164855ac7fa7281&size=150x150>

2022-10-04 09:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fff3e2274-ebc9-463b-96c5-e35e6b0158dd%2Fartifact%2F4438db83668ae9d9%2Fp%2F6a9d1a7ebffe1ee5549d7577311174cf&size=150x150">

2022-10-04 10:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa660ec94-bf7e-447b-85ac-a1c6d893405f%2Fartifact%2F3170b30db61abbc2%2Fp%2F70fe0fa4132e012f6dd97f1311522483&size=150x150">

2022-10-04 10:39 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5eeaad6b-77d2-4bd7-8a60-45d19c07493e%2Fartifact%2Fb3552da79815ee2e%2Fp%2F0feca503469e397d4cb94419da809561&size=150x150>

2022-10-04 14:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffe434142-7063-4cd5-ba83-92c8f4e1ad02%2Fartifact%2F9debce09bbc15777%2Fp%2F1135595e7be8d94fec19250812ff73de&size=150x150">

2022-10-06 08:15 UTC, closed without merging