[MBL-16162][Student][Teacher] RCE insert image improvements
instructure/canvas-android pull request #1734
Opened 2022-10-04 12:37 UTC by kristofnemere

refs: MBL-16162
affects: Student, Teacher
release note: none

test plan: need to test the following places without permissions and with permissions in Student and Teacher app
> - CreateAnnouncementFragment
> - CreateDiscussionFragment 
> - DiscussionsReplyFragment
> - EditPageDetailsFragment
> - EditSyllabusFragment
> - CreateOrEditAnnouncementFragment
> - CreateOrEditPageDetailsFragment
> - DiscussionsUpdateFragment
> - EditAssignmentFragment
> - EditQuizDetailsFragment
> - EditProfileFragment

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-10-04 12:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9ae07098-8d0a-4a19-90d7-49a682143a26%2Fartifact%2F8982532f45439eba%2Fp%2Fcf3c99f61cfe76c528190f8ff1de3d09&size=150x150>

2022-10-04 12:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0b53fd89-aee9-43f9-9fcd-d886e57a91ef%2Fartifact%2F0f46fca26d5cf165%2Fp%2F354a4e821a5ab7f1520ea04069512b8e&size=150x150">

2022-10-05 06:33 UTC, tamaskozmer requested changes

2022-10-05 06:33 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/activities/FullscreenActivity.kt
> +class FullscreenActivity : BaseAppCompatActivity(), FullScreenInteractions,
We might need to do this on the `MasterDetailActivity` as well since in split view that hosts all the fragments.

2022-10-05 07:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F42361a89-fa49-4295-a2ca-b229bb043fab%2Fartifact%2Fa79ffbf865655d00%2Fp%2F20e46034ec4b90b145b6637932c24a7d&size=150x150>

2022-10-05 07:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fab3707e8-0d24-4239-a596-fdc6029df804%2Fartifact%2F37608124191baee1%2Fp%2Fd2b5da3c710bf29b12610fc2911b3402&size=150x150">

2022-10-05 09:01 UTC, tamaskozmer approved these changes

2022-10-05 11:17 UTC, kdeakinstructure approved these changes
QA 👍

2022-10-05 11:39 UTC, merged