[MBL-15325][Student][Teacher] Users should be able to open embedded google slides in the browser
instructure/canvas-android pull request #1737
Opened 2022-10-05 16:28 UTC by kristofnemere

refs: MBL-15325
affects: Student, Teacher
release note: Added option to open embedded google docs in the browser.

test plan: in the ticket

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-10-05 16:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F558c5063-43d1-4748-8fa8-6676dde07d60%2Fartifact%2F690205a2cd6fd6ff%2Fp%2F771b8c7d9d8d9723c2d030b473cf52a9&size=150x150>

2022-10-05 16:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Feb666e9b-f7e8-4f02-aa34-fbb7b1d9a90d%2Fartifact%2Fa640d60f4a1745e2%2Fp%2Fb2563ac5db5e7dcad6241d55b82b0ffd&size=150x150">

2022-10-06 08:25 UTC, hermannakos requested changes

2022-10-06 08:25 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
> +fun String.isGoogleDocsUrl() = this.contains("docs.google.com")
It feels a bit weird to make it an extension since it is not really associated with the String class itself. We could probably use a simple utility function instead of an extension. You can even duplicate the logic in each app since it is only used once.

2022-10-06 08:28 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
> +                val iframe = iframeMatcher.group(0).orEmpty()
Without that we have 'Unsafe use of a nullable receiver of type String?' warnings, that's why I changed that, but I can change it back of course.

2022-10-06 08:30 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
> +                val iframe = iframeMatcher.group(0).orEmpty()
You can leave it as is, I just prefer to have null if we have nothing and handle it rather than having an empty string.

2022-10-06 08:34 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
> +fun String.isGoogleDocsUrl() = this.contains("docs.google.com")
Or at least make it private, in that case you can use it here, but won't bloat the whole project scope with it for String autocomplete.

2022-10-06 08:36 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
> +fun String.isGoogleDocsUrl() = this.contains("docs.google.com")
Thanks, I created an utility function from it, but I left it in WebViewExtensions since I need it in 3 places.

2022-10-06 08:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9a16d109-4942-4d35-bdf8-de43dafdfe33%2Fartifact%2Fbeaddb506c8644da%2Fp%2F0588ffa90712f64231f755cdca843039&size=150x150>

2022-10-06 08:58 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9e308388-7e9c-48a4-be25-3d911f14ab01%2Fartifact%2Fb30c427e605667d5%2Fp%2F9f3f34d01a8e8cae52552de0f75623c9&size=150x150">

2022-10-06 12:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2d722b75-94ef-432a-bd1e-3f50814c1927%2Fartifact%2F9bdf12878c008a35%2Fp%2F2401a23587dbb27b75abb8f76e365489&size=150x150>

2022-10-06 12:36 UTC, PatelMilan commented
Running "flutter pub get" in flutter_parent...                  
    Because no versions of dio_http_cache match >0.3.0 <0.4.0 and dio_http_cache 0.3.0 depends on json_serializable ^4.1.4, dio_http_cache ^0.3.0 requires json_serializable ^4.1.4.
(1) So, because no versions of json_serializable match >4.1.4 <5.0.0 and json_serializable 4.1.4 depends on analyzer >=0.41.2 <2.0.0, dio_http_cache ^0.3.0 requires analyzer >=0.41.2 <2.0.0.

    Because no versions of test match >1.17.10 <1.17.11 and test >=1.17.11 <1.18.0 depends on test_api 0.4.3, test >1.17.10 <1.18.0 requires test_api 0.4.3.
    And because test >=1.18.0 <1.18.1 depends on test_api 0.4.4, test >1.17.10 <1.18.1 requires test_api 0.4.3 or 0.4.4.
    And because test >=1.18.1 <1.19.0 depends on test_api 0.4.5 and test >=1.19.0 <1.19.3 depends on test_api 0.4.6, test >1.17.10 <1.19.3 requires test_api 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6.
    And because test >=1.19.3 <1.19.4 depends on test_api 0.4.7 and test >=1.19.4 <1.20.0 depends on test_api 0.4.8, test >1.17.10 <1.20.0 requires test_api 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6 or 0.4.7 or 0.4.8.
    And because test >=1.20.0 <1.21.2 depends on test_api 0.4.9 and test >=1.21.0 <1.21.6 depends on analyzer >=2.0.0 <5.0.0, test >1.17.10 <1.21.6 requires analyzer >=2.0.0 <5.0.0 or test_api 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6 or 0.4.7 or 0.4.8 or 0.4.9.
    And because dio_http_cache ^0.3.0 requires analyzer >=0.41.2 <2.0.0 (1), if dio_http_cache ^0.3.0 and test >1.17.10 <1.21.6 then test_api 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6 or 0.4.7 or 0.4.8 or 0.4.9.
    And because test >=1.21.6 depends on test_api 0.4.14 and test 1.17.10 depends on test_api 0.4.2, if dio_http_cache ^0.3.0 and test >=1.17.10 then test_api 0.4.2 or 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6 or 0.4.7 or 0.4.8 or 0.4.9 or 0.4.14.
    And because every version of flutter_test from sdk depends on test_api 0.4.12 and flutter_parent depends on dio_http_cache ^0.3.0, test >=1.17.10 is incompatible with flutter_test from sdk.
    So, because flutter_parent depends on both flutter_test from sdk and test ^1.17.10, version solving failed.
pub get failed (1;     So, because flutter_parent depends on both flutter_test from sdk and test ^1.17.10, version solving failed.)

2022-10-07 08:50 UTC, hermannakos approved these changes

2022-10-07 09:14 UTC, kdeakinstructure approved these changes
QA 👍

2022-10-07 13:26 UTC, tamaskozmer approved these changes

2022-10-10 09:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F367e9cd9-a383-4a3c-b11b-0bef1fe2d4c0%2Fartifact%2F4eea50a6eb3019aa%2Fp%2F30d4db7dde749cf31ed2e4fa82dd50a0&size=150x150>

2022-10-10 09:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F363a539d-84fc-4af7-9ffd-adea7a6532ca%2Fartifact%2F87dd95ae23a1d73c%2Fp%2F3907e7b80aca6f1a9a200e21fc113aca&size=150x150">

2022-10-11 07:26 UTC, merged