[MBL-16182][Student][Teacher] Small UI improvements
instructure/canvas-android pull request #1743
Opened 2022-10-07 14:47 UTC by kristofnemere

refs: MBL-16182
affects: Student, Teacher
release note: UI improvements.

test plan: in the ticket

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-10-07 15:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F16fca8b2-6545-42c2-a932-19e8d8a2f0b6%2Fartifact%2F213e0ebf5eef73cf%2Fp%2Fca1a1132aacd6febb8b3704e460c767b&size=150x150>

2022-10-07 15:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9d5b7c62-41b5-470c-b337-8828a3a61afc%2Fartifact%2F16498f46a1d6849c%2Fp%2F8e087bb9787b7e0ad9e89e95c113d326&size=150x150">

2022-10-11 11:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F041cf9d3-dc42-436f-8300-65f9b6681473%2Fartifact%2F79ddecd451fc7e0e%2Fp%2F53d42a908d7e3e97bb5ac08c3804ba2a&size=150x150>

2022-10-11 12:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff0966c06-7d7c-4284-9668-ab204b7b5047%2Fartifact%2F6e94ccb1e5a51290%2Fp%2Fdf748a9c096df727b366fa05cb421da5&size=150x150">

2022-10-11 13:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F891ca24f-ae25-4825-be03-07a90c3600fc%2Fartifact%2F92ca911c1cd7611a%2Fp%2Fb965642d8cc424483936a115a4851bd0&size=150x150>

2022-10-11 13:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F563f647a-9cd5-46b2-808b-bcc3497043e2%2Fartifact%2F2e609f39a503a687%2Fp%2F4f4b85546a19dba817081f1ce31c20cf&size=150x150">

2022-10-12 08:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9231446f-3ebb-49f7-a207-d99d089f02ed%2Fartifact%2F3d4be50dafa499be%2Fp%2F33a545ea16ab17096912112304e1eb7d&size=150x150>

2022-10-12 08:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F66a2d8ae-fb03-4425-a741-00d385c37b58%2Fartifact%2F03c8891ad43b6d25%2Fp%2Fc190891a84ad172d902e8e7c2c4cc68a&size=150x150">

2022-10-12 08:42 UTC, tamaskozmer requested changes

2022-10-12 09:04 UTC, kdeakinstructure approved these changes
QA 👍

2022-10-12 09:07 UTC, kristofnemere commented on apps/student/src/main/java/com/instructure/student/util/StudentToolbarSetup.kt
> +class StudentToolbarSetup : ToolbarSetup {
Thanks, fixed it.

2022-10-12 09:07 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/di/ToolbarSetupModule.kt
> +    fun provideToolbarSetup(): ToolbarSetup {
Thanks, fixed it.

2022-10-12 09:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc75b0e26-104c-4927-8e8f-276bf133d103%2Fartifact%2F64585f15f43af5d9%2Fp%2Ff3de10d3a9a7bcde0319b4e345f7b86e&size=150x150>

2022-10-12 09:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F841ed32a-59d0-42ac-8878-26937aa8c4e1%2Fartifact%2Ffdf17e6f78a7a4f8%2Fp%2Fa2db8ae8036e4265ce34eb7b0271b6ea&size=150x150">

2022-10-12 09:36 UTC, tamaskozmer approved these changes

2022-10-12 09:48 UTC, merged