[MBL-15428][Teacher] Teacher edit dashboard
instructure/canvas-android pull request #1758
Opened 2022-10-21 17:18 UTC by kristofnemere

refs: MBL-15428
affects: Teacher
release note: Implemented edit dashboard functionality.

test plan: in the ticket.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-10-21 17:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb0653d73-bf16-4084-858f-d28206ac2f56%2Fartifact%2F8749f4c97659b531%2Fp%2Feb25f9dab2ba10fc3a0ecc61b0195ec9&size=150x150">

2022-10-24 12:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1455071b-b983-4956-97f2-3311d2632d5d%2Fartifact%2F4767b8d2013fa961%2Fp%2F705089e72e0b6bcd8696f015a4a00230&size=150x150>

2022-10-24 12:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff901dbee-b4a1-4e6b-8182-feae053a0f6e%2Fartifact%2Fda5c9639ddacce4a%2Fp%2F8b2b86a4c9ada04deb797342119fb798&size=150x150">

2022-10-24 12:59 UTC, tamaskozmer requested changes

2022-10-24 12:59 UTC, tamaskozmer commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditDashboardPageTest.kt
> +    fun favourCourse() {
I think this is a little bit strange wording, I never heard this in a context like this.

2022-10-24 12:59 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/DashboardFragment.kt
> +@AndroidEntryPoint
I don't think this needs to be an `@AndroidEntryPoint`.

2022-10-24 12:59 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/DashboardFragment.kt
> +    lateinit var editDashboardRouter: EditDashboardRouter
This is not used here.

2022-10-24 12:59 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/DashboardFragment.kt
> +        editDashboardTextView.setOnClickListener { mCourseListCallback?.onEditDashboard() }
I don't think this callback is necessary anymore. There is no point propagating this call to the Activty, we can just call `RouteMatcher.route(requireActivity, EditDashboardFragment.makeRoute())` instead and get rid of this callback completely.

2022-10-24 12:59 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/edit/EditDashboardViewModel.kt
> +package com.instructure.pandautils.features.dashboard.edit
I think there we should add some different behaviors for this class whether we are in the student app or in the teacher. Let's discuss this on Slack.

2022-10-24 13:34 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/AllCoursesFragment.kt
> -        presenter.loadData(false)
Please also remove the Presenter and the PresenterFactory.

2022-10-24 13:34 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/EditFavoritesFragment.kt
> -        presenter.loadData(true)
Please remove the Presenter and the PresenterFactory as well.

2022-10-24 13:45 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditDashboardPageTest.kt
> +    fun favourCourse() {
We thought that as well but the Android Studio suggested this change and it does not underlines it this way...

2022-10-24 15:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3b8756ef-79a9-408f-8ec4-23e1efc4a8b8%2Fartifact%2Fd3340d8d996ae71b%2Fp%2F1d63f9cc6385b9be364b6d8652055823&size=150x150>

2022-10-24 15:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe227b7eb-e930-4a05-a1d0-21bfba0ef053%2Fartifact%2F635126965edc27d8%2Fp%2F2e2708ebbc6c72c5722416905d79ff57&size=150x150">

2022-10-24 17:10 UTC, stephaniegilbert944 approved these changes

2022-10-25 12:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F361ab86e-c74a-40ba-80fd-a5fce48d5f88%2Fartifact%2F1c422b332bb47516%2Fp%2F8eec67402890caa5b8bc19b34585d356&size=150x150>

2022-10-25 13:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F20e22b6f-407a-41a6-9744-33d4fd4af38c%2Fartifact%2F3ad014c9b8f21c34%2Fp%2Fd187573d3b2bf92a92701f27e3a84f4b&size=150x150>

2022-10-27 12:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1e02ccd6-895a-433b-9a27-fe5f8593c2af%2Fartifact%2F46a174a71377c871%2Fp%2Fb010714a5e6de1672a11f3fbc238bd84&size=150x150">

2022-10-27 14:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff60b64d6-310d-4eb8-bb6c-7c3d5c8f1568%2Fartifact%2F6d70f0f224138933%2Fp%2F55d0f1f58cae7cb8d06b0291213cdad9&size=150x150>

2022-10-27 14:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F65c06527-53d6-4091-9449-d15d5a0b26e0%2Fartifact%2Fbce1dd0a663a4358%2Fp%2F74e429dfdd2c6fc3dfeb97d517d002c5&size=150x150">

2022-10-28 08:55 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/presenters/CoursesPresenter.kt
>          apiAsync<List<DashboardCard>> { CourseManager.getDashboardCourses(forceNetwork, it) }.await()
You might as well rename this class if the Fragment was also renamed to Dashboard.

2022-10-28 08:55 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/edit/EditDashboardViewModel.kt
> +        val coursesToFavorite = (currentCoursesViewData + pastCoursesViewData + futureCoursesViewData).filter { !it.isFavorite && it.favoriteable }
What is the reason for this change?

2022-10-28 08:55 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/edit/EditDashboardViewModelTest.kt
>      fun `Deleted courses cannot be opened`() {
I think this test and the test above is the same, one of them should be removed and the other maybe renamed.

2022-10-28 09:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0dcdd1e7-e4d9-473b-aff7-da886662c166%2Fartifact%2F5cd38a3be3c2ddae%2Fp%2Ffdaed02766fb48cfc115afa37c861f16&size=150x150>

2022-10-28 09:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff3b958d8-7829-4c75-a07b-7db387ed0f00%2Fartifact%2F1c3a91b1f32be5be%2Fp%2F1fd081f3cc9bc5d38ad444dd624bcddd&size=150x150">

2022-10-28 10:05 UTC, kdeakinstructure approved these changes
QA 👍

2022-10-28 10:16 UTC, tamaskozmer approved these changes

2022-10-28 12:08 UTC, merged