[MBL-16314][Teacher] Publish/Unpublish assignments
instructure/canvas-android pull request #1768
Opened 2022-11-08 10:46 UTC by kristofnemere

refs: MBL-16314
affects: Teacher
release note: none

Test plan: In the ticket

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-11-08 11:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdc7c6aa3-8d32-4858-9c16-2b1a3c7d54c6%2Fartifact%2Fe2c01ad3e9a413a6%2Fp%2Fb5e6066141ef118f23556e5945cad833&size=150x150">

2022-11-08 15:08 UTC, hermannakos requested changes

2022-11-08 15:17 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt
> +        publishSwitch.isEnabled = mAssignment.unpublishable
Fixed it, thanks! :)

2022-11-08 15:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F85fc60c9-42a0-40e5-9503-e67da9e2000f%2Fartifact%2Ffba4fb83e8624c0d%2Fp%2F72fa457264009497ba3e02be7b76d77d&size=150x150>

2022-11-08 15:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fafee7424-1e52-4793-a318-30626f3fd5a7%2Fartifact%2F089fdc84b1beadf9%2Fp%2Ff2e147a5e255beb46f216b73df106689&size=150x150">

2022-11-10 09:28 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F45b5c724-f59c-406a-bd0b-e17b3a85584c%2Fartifact%2F952c36e7d6844e23%2Fp%2F67d8af17d353860dc977570621b90f44&size=150x150">

2022-11-10 10:19 UTC, kdeakinstructure approved these changes
QA 👍

2022-11-10 11:16 UTC, hermannakos approved these changes

2022-11-10 11:22 UTC, merged