[MBL-16390][Student] -  Subscribe calendar added to SettingsE2E tests
instructure/canvas-android pull request #1784
Opened 2022-11-22 17:39 UTC by kdeakinstructure

Implement test for Subscribe to Calendar function.

refs: MBL-16390
affects: Student
release note: none

2022-11-23 09:44 UTC, tamaskozmer requested changes

2022-11-23 09:44 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
> +        intended(toPackage("org.chromium.webview_shell"))
I think instead of checking for the target package we should check the intents action and data, because different devices can have different packages to handle the intent. Also we don't explicitly want to open this package, but instead send an action.

2022-11-23 09:44 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
> +  //  val intentsTestRule = IntentsTestRule(SettingsActivity::class.java)
This can be removed.

2022-11-24 08:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff3a01356-0702-42b0-a9b3-fe79acc8a52c%2Fartifact%2Fe41cb5c00dfba22b%2Fp%2F77374cb2a488687d727d9b77d73d9fbf&size=150x150">

2022-11-24 12:03 UTC, tamaskozmer requested changes

2022-11-24 12:03 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
> +        intended(object: IntentActionMatcher(Intent.ACTION_VIEW, calendarDataMatcherString) {})
You don't need to create a new object here, just instantiate your class.

2022-11-24 12:03 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/utils/Matchers.kt
> +open class IntentActionMatcher(private val intentType: String, private val dataMatcher: String) : TypeSafeMatcher<Intent>() {
This doesn't need to be open.

2022-11-24 13:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F34e130ee-1227-4001-b5e6-0756a7944f39%2Fartifact%2Fc6487ac34aa63de6%2Fp%2Fa74afe5ffc58eea496cd52e179fc6cef&size=150x150">

2022-11-24 14:34 UTC, kristofnemere approved these changes

2022-11-24 15:38 UTC, tamaskozmer approved these changes

2022-11-24 15:42 UTC, merged