[MBL-16433] Submission comments saved to DB
instructure/canvas-android pull request #1805
Opened 2022-12-12 10:43 UTC by hermannakos

refs: MBL-16433
affects: Teacher
release note: none

test plan: Test everything relating to submission comments

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

2022-12-12 11:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F44872a5c-bf6b-48d3-938c-5836b544216a%2Fartifact%2F69df36637db75d5f%2Fp%2F5ed4508007df4c3e6aea47e807771a90&size=150x150>

2022-12-12 11:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5399ff79-09b5-4a08-9587-17d015c1ed75%2Fartifact%2Fa43bb0001f375981%2Fp%2F428b085e8ea3b60d9704780746b15aab&size=150x150">

2022-12-13 12:05 UTC, kristofnemere approved these changes

2022-12-13 12:12 UTC, tamaskozmer requested changes

2022-12-13 12:12 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderCommentsPresenter.kt
> +                    pendingSubmissionCommentDao.findById(pendingComment.id)?.let {
Shouldn't we use a query here that checks the file paths? In the shared prefs implementation we check that instead of the id.

2022-12-13 13:50 UTC, tamaskozmer approved these changes

2022-12-13 14:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fcda7e7df-ea57-4a7a-b268-4e233dca1bce%2Fartifact%2Fcdac38fdff12044e%2Fp%2F44f1d870cc9be2efb36031e517f31fd9&size=150x150>

2022-12-14 10:47 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6b7a16e7-4a87-4f9c-bbef-08b5e5717ffc%2Fartifact%2F50258c44e68f3e07%2Fp%2Fd950a220e5c10a0231a48ce33e5a9a1d&size=150x150">

2022-12-14 13:50 UTC, kdeakinstructure approved these changes
QA 👍

2022-12-15 09:09 UTC, merged