[Student][MBL-16380] Assignment Details enhancement
instructure/canvas-android pull request #1823
Opened 2023-01-04 11:07 UTC by kristofnemere

Test plan: Smoke test assignment details, compare it with the old version.

refs: MBL-16380
affects: Student
release note: Assignment details enhancement

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product or not needed

2023-01-04 11:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8fe32b77-18fc-45dc-8923-0b9b4d3fac3f%2Fartifact%2Fc3b43eec877d59dd%2Fp%2F22d6870897add63084792b62a5c2245d&size=150x150>

2023-01-06 14:10 UTC, hermannakos requested changes

2023-01-06 14:10 UTC, hermannakos commented on libs/pandares/src/main/res/values/strings.xml
> +    <string name="attempt">%d. attempt</string>
I know it's more of a design thing, in english it's`Attempt %d`.

2023-01-06 16:10 UTC, tamaskozmer requested changes

2023-01-06 16:10 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/assignmentdetails/AssignmentDetailFragment.kt
> +        floatingRecordingView.setContentType(RecordingMediaType.Audio)
We should use View Binding instead of Kotlin synthetics to access the view.

2023-01-06 16:10 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/assignmentdetails/AssignmentDetailFragment.kt
> +    private fun showSubmitDialogView(assignment: Assignment) {
Can we use View Binding for the dialogs as well instead of synthetics? In that case we could eliminate that completely.

2023-01-06 16:13 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/assignmentdetails/AssignmentDetailViewModel.kt
> +                }.await().dataOrThrow as Assignment
That would actually cause a crash (that we will catch in the catch block and the error would be hidden from us), because we can't cast it.

2023-01-10 17:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9d8257f7-9b87-4199-973a-105f2cc19a31%2Fartifact%2Fc58bc0c154406607%2Fp%2F2abae8b5ba318f5b0fe20e4a0167112b&size=150x150>

2023-01-11 15:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F994c8636-41b8-4105-924c-b4b23abc0b45%2Fartifact%2F6fa50acd6b82f13e%2Fp%2Ffec1b0809af04c590dda78fb332322ba&size=150x150>

2023-01-12 10:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe8ded3d0-322e-47c6-8036-918df0daa0ff%2Fartifact%2F1ac17dc5a778e5b3%2Fp%2Fd628c00402729f866b45e4ebe5ca17e9&size=150x150>

2023-01-13 16:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1574463e-df6e-4e8c-97d1-3ff65ca6bdea%2Fartifact%2F22eb3bd275b11c65%2Fp%2Fdca7da1eaa2be36c114df727b63ba227&size=150x150>

2023-01-18 07:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F92178144-c1fb-4fac-9af3-521df2dfd695%2Fartifact%2Fe3d3e8c956feb32d%2Fp%2F2010321c721da7e65ce5b1de894579ba&size=150x150>

2023-01-19 14:35 UTC, kdeakinstructure approved these changes
QA 👍

2023-01-20 07:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Feb98fdb7-d691-4ee2-b9f1-851c860dba61%2Fartifact%2Fb13a8c99fb2280ed%2Fp%2F73c21c1785b85675ba61bdac6c49d086&size=150x150>

2023-01-20 14:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8798ba3d-3641-467d-bc97-d0a768e6430f%2Fartifact%2Fbef2b9df8e3c604a%2Fp%2F9dddfb4348c899f0945f72f49eff851d&size=150x150>

2023-01-24 09:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ffed2e38e-7eca-4302-a949-57200d6f3a50%2Fartifact%2Fac44501c8566454b%2Fp%2F6c9b65ccce3c7d0d6cdf9d15856be24b&size=150x150>

2023-01-24 15:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F45de9ece-c54f-4116-a55a-72efb1fd7b93%2Fartifact%2F9bfd92dc3079e3bc%2Fp%2F96f4be031762e3e74e8be6533305faed&size=150x150>

2023-01-24 16:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F33f8d399-4b55-472e-a4bd-1d833c4767cb%2Fartifact%2F910820ccf300dd12%2Fp%2Fc79fb402c17512bd908b89d785c9e11f&size=150x150>

2023-01-25 13:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff6da496f-138c-4304-8bf6-5d025c81be35%2Fartifact%2Fb7070a3d5c9b3b90%2Fp%2Fbc2c3d324a04731de8f8b3d310b18c99&size=150x150>

2023-01-25 14:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc8f163fd-29eb-407b-8089-285837b194b5%2Fartifact%2F1f590fdd896c1bb6%2Fp%2F80f6f310b405b1b0e3974219bad67ff0&size=150x150>

2023-01-25 14:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fade050e9-d7c5-4aa9-a94c-0e39249d7934%2Fartifact%2F88ede02c39700c5b%2Fp%2Fa595c48048d3e5c7e2e6df8b9357bbad&size=150x150">

2023-01-25 15:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb149d833-dd08-4d96-8481-f78159483017%2Fartifact%2Fa392915f0de9f65f%2Fp%2F9374d5272b07d97a00fb22f2ea959d95&size=150x150>

2023-01-25 15:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6e9530f0-7c6c-447d-a4a0-070f1a5bad0d%2Fartifact%2F3d9451c300ad9300%2Fp%2Faf314158c2a3d81c2a126d406e4af7ba&size=150x150">

2023-02-01 09:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F7910725a-1f1a-4630-8ee7-b499e766dfea%2Fartifact%2Fd7ffff4370736683%2Fp%2F1012bb6df470ee6130b7f612a6cc88a6&size=150x150>

2023-02-01 09:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff13a6060-d862-4775-965e-002439c6ff21%2Fartifact%2F9814b9cb2d667445%2Fp%2F960f2378648f22ba1d8ad1bd844f3f0e&size=150x150">

2023-02-01 14:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc635c9cc-1ec7-4e3c-87dc-f3fde69572f4%2Fartifact%2F3f87b4c6c9a9b857%2Fp%2F844fe71c02017f6255300fae077d165f&size=150x150>

2023-02-01 15:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1143cd9f-79f6-4d7e-9ed7-844af13301e1%2Fartifact%2F4ba513fb7e85dccf%2Fp%2F1fa85ce5998f5670b0045796ac446403&size=150x150>

2023-02-01 15:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F25d37891-091e-4ea6-96ab-31b8b6fc9a6e%2Fartifact%2Fd88367a0809b8374%2Fp%2F546b9e9915416e33d16cdaa44938e03d&size=150x150">

2023-02-02 09:09 UTC, tamaskozmer approved these changes

2023-02-02 10:24 UTC, hermannakos approved these changes

2023-02-02 10:35 UTC, merged