Mbl 16359 custom heap events
instructure/canvas-android pull request #1825
Opened 2023-01-04 14:31 UTC by hermannakos

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product or not needed

2023-01-04 14:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F08ef8c35-64ae-41c1-b17f-082abf1538cb%2Fartifact%2F6d2d57b35d5cec75%2Fp%2F3c6b5c60a4d6bc911494890f44987819&size=150x150>

2023-01-05 11:11 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F3bbb442eee902883%2Fbuild%2F04075a3e-4bf4-4736-a654-69f62da8674d%2Fartifact%2F013b28bb0901ccfb%2Fp%2F6f25eafe769cb11049f42d5378a8984b&size=150x150">

2023-01-05 11:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F89f8956d-2129-4852-83e2-bc92ddf6f7a8%2Fartifact%2Fb2a30f4dcda911f5%2Fp%2Fb0a09ccd69c30919fce11003dad8c856&size=150x150>

2023-01-05 11:23 UTC, tamaskozmer requested changes

2023-01-05 11:23 UTC, tamaskozmer commented on apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
>      locator<Analytics>()
This event will never be logged because we remove the feature flag previously. It should be called before logout if we want to log this. And we might need to await it's result to make sure it's logged before logout.

2023-01-05 12:37 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F3bbb442eee902883%2Fbuild%2Fef95a87a-4c41-462b-8728-31752416d00e%2Fartifact%2Ff0094f3101ef1f50%2Fp%2F968aab34b2abace0c899a32576ec6d56&size=150x150">

2023-01-05 12:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fbd66f18b-1428-4598-b36b-42da1cc188d2%2Fartifact%2F558aa375bf6fb11b%2Fp%2F78c6c767bd30cd7b67a1a92ae6773d1c&size=150x150>

2023-01-05 12:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa030f019-017b-4e2e-9ac4-ac0f79839639%2Fartifact%2F576b1b52a72d6c30%2Fp%2F99554f95aacc5ec502d725794bd68067&size=150x150">

2023-01-05 13:53 UTC, tamaskozmer approved these changes

2023-01-05 13:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2632893a-b046-4e26-a465-6596cbbf92bb%2Fartifact%2Faef27d5f1e99fe8f%2Fp%2Fa9cccbaa72c88c3d124384f932fa4c79&size=150x150>

2023-01-06 14:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F22895e1f-7acb-44f5-b3a1-6733ac8e6a72%2Fartifact%2F587a9fbbef50d75b%2Fp%2F267d0ea71ad6be7ff6a2891c5a11f7bb&size=150x150>

2023-01-06 14:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffcf8cc7f-ea40-4c72-8877-9a5699f2eaa2%2Fartifact%2F440fbde0b7ad49f9%2Fp%2Fd701bb23d1acfa39fb7d3e0eca2b6461&size=150x150">

2023-01-06 14:55 UTC, merged