[MBL-16410][Student] - Separate left side menu from dashboard
instructure/canvas-android pull request #1836
Opened 2023-01-23 21:17 UTC by kdeakinstructure

Separate LeftSideNavigationDrawerPage from Dashboard
Refactor some methods and replace all usages.

refs: MBL-16410
affects: Student
release note: none

2023-01-23 21:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8b96b905-11be-4a2b-9c7b-047e99ce0ecb%2Fartifact%2F54ef66dd60ef7b28%2Fp%2F89ce263e87ebf59f7dfebe47597b16b7&size=150x150>

2023-01-23 22:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9555ce68-7d45-4bb3-b8ea-278599b98850%2Fartifact%2F70a6204b6cdff943%2Fp%2Ff11645044378784e4d9cc8e9c0cc9733&size=150x150>

2023-01-23 22:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2ef9a4fc-3ca2-4518-8abe-a3d4f9921e6e%2Fartifact%2F66be6e6234867573%2Fp%2F628d476d473ca856910cc3b2986230ce&size=150x150">

2023-01-23 23:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F98417be9-4508-4b32-b3ff-be76b0ecc157%2Fartifact%2F1392aa47ed78f710%2Fp%2F8718006f56399e202821da781274d82c&size=150x150>

2023-01-23 23:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe0b4dc38-0260-42f1-9987-a4be151b9f85%2Fartifact%2F3190b85a56886ea8%2Fp%2F55c3b29a35ebf1395777ddeb0a0b6b03&size=150x150">

2023-01-23 23:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4bd1a4b3-abd6-4b0d-bc1d-81c0b2e9a2cc%2Fartifact%2F5efc6d27b255f573%2Fp%2F89a286ef1362c2cb7a37eb3abb07429f&size=150x150>

2023-01-23 23:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0de6eafc-0df0-4afc-8aa5-c872a30fa261%2Fartifact%2F8c811dcdad41bc2c%2Fp%2Ff245f6ea796a3cc5be7fc8cb99a3b723&size=150x150">

2023-01-24 10:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdf7f6540-19f1-48e7-be2a-2e5fc115d79a%2Fartifact%2Fe7a2f37119004dd0%2Fp%2F9d0aaf2c0ea79800db9a1f9ece1744e4&size=150x150>

2023-01-24 10:17 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff90e475b-cad4-439e-8a5f-a78f8257924b%2Fartifact%2F245117d674cf6158%2Fp%2Feea877d29521516d7b94d25d784c7acd&size=150x150">

2023-01-25 09:31 UTC, tamaskozmer requested changes

2023-01-25 09:31 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
> +        Thread.sleep(3000) //Sometimes the remove button is not clickable and we have to wait for it.
Wouldn't it be better to use the `WaitForView` matcher instead of a fixed time waiting?

2023-01-25 09:39 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
> +        Thread.sleep(3000) //Sometimes the remove button is not clickable and we have to wait for it.
I think it won't be a good solution here because waitForView only checks if the view is VISIBLE, but that's not a guarantee that it's clickable as well.

2023-01-25 13:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff98877a4-89b8-4b88-bbb9-68879d801542%2Fartifact%2Fcc780b771d20e35b%2Fp%2F5ada07eaa30c8e37b3b67bb15a7f7a20&size=150x150>

2023-01-25 13:35 UTC, merged