[Student][MBL-16386] Inbox list redesign
instructure/canvas-android pull request #1843
Opened 2023-02-02 09:44 UTC by tamaskozmer

refs: MBL-16386
affects: Student
release note: Added bulk actions to Inbox

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product or not needed

2023-02-02 10:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc25e7532-aa47-4352-bc2d-f89bfec38223%2Fartifact%2F2a75a5bae1fd32ef%2Fp%2F7e30a4d87cefc27c9ee9c60640aefae2&size=150x150>

2023-02-02 12:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa0fcb980-ef2c-473b-8fbb-63e6b5c6ff91%2Fartifact%2Fa84928215bd2c06b%2Fp%2F764b62e0f4a08af48d6cecdf65d5b33a&size=150x150>

2023-02-02 12:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fbbab2fce-f4ed-4726-a3bc-9362821576ff%2Fartifact%2F32b8340cae750675%2Fp%2F36ec5953ca951d34d84f271a3e97424e&size=150x150>

2023-02-02 12:40 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9ed1ae0e-4148-4cf3-b4df-7a1924026d36%2Fartifact%2Fb32b8e821002766c%2Fp%2F7d939931a0bd463b038b48105b6887ca&size=150x150">

2023-02-02 16:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8e05dbd7-1b96-4266-87c7-1374b3ac4e82%2Fartifact%2Fb38ab017e1468d78%2Fp%2F16ee5de2beee851cf6d950e182b1f318&size=150x150>

2023-02-02 16:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe63219f4-4bdb-4f80-b1a7-e827dd448348%2Fartifact%2F33429145fdb09d02%2Fp%2F6a2088ab00cc44f4424621fa6b6feb2d&size=150x150">

2023-02-06 12:13 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxRepository.kt
> +        val groups = groupsResult.dataOrNull ?: emptyList()
We're hiding this error, shouldn't this be dataOrThrow instead?

2023-02-06 12:15 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
> +        return inboxEntryItemCreator.createInboxEntryItem(conversation, { starred ->
The function params are a bit confusing, can we use named params here to make it more clear?

2023-02-06 12:24 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
> +                inboxRepository.getCanvasContexts().dataOrNull?.let {
Do we need to fetch the contexts here again instead of passing the ones we already have? It could have side effects if the call fails.

2023-02-06 12:25 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/filter/ContextFilterFragment.kt
> +    private fun setFullScreen() {
Nice!

2023-02-06 12:26 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/filter/ContextFilterItemViewModel.kt
> +    override val viewType: Int
I think we could move these view types into an enum to be a bit more readable, like we usually do it.

2023-02-06 12:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F08c8947f-9073-4c92-af3c-d3cefa271c3d%2Fartifact%2Fa393df36a6a185d1%2Fp%2Fbcc31318e9d8584411dd7bf44b3e887c&size=150x150>

2023-02-06 12:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc65f094c-a45f-4ad0-91e6-3877ef1d041f%2Fartifact%2F48df06dd27a0c106%2Fp%2F3b9c97b3f62e744dad4bfd3c6109a2fb&size=150x150">

2023-02-06 13:25 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxRepository.kt
> +        val groups = groupsResult.dataOrNull ?: emptyList()
It's an edge case but we don't want to throw an error when we already got the courses but somehow failed to get the groups.

2023-02-06 13:28 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
> +                inboxRepository.getCanvasContexts().dataOrNull?.let {
We only fetch those if it's null or empty. In most of the cases we don't need to do that, this is just an edge case.

2023-02-06 14:01 UTC, kristofnemere requested changes

2023-02-06 14:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fccfe14e0-28cd-463c-88be-1cb7018507e2%2Fartifact%2Fdbf0cd47e3950cf8%2Fp%2F98089527ea1bc0453b3dad1571f1b9fe&size=150x150>

2023-02-06 14:15 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxFragment.kt
> +        if (itemBinding == null) return
It's just personal preference. I find it a bit confusing to have a condition that is used to assign a value but on the other branch it returns early from the method.

2023-02-06 14:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ffd58affd-6d02-451e-9e69-777d24d1551a%2Fartifact%2Fa4fb341b3734adc4%2Fp%2F647163571d7979f61083b6bf64e86943&size=150x150>

2023-02-06 14:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F94f64163-df69-43a9-8ed0-99ed24732dcb%2Fartifact%2F235fd3d5c79cd8b0%2Fp%2F87778e2fad4d2919f7404321dc9095e1&size=150x150">

2023-02-06 14:27 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
> +    @ApplicationContext private val context: Context,
I think Studio will always give a leak warning for context, but the annotation guarantees it's only application context.

2023-02-06 14:29 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
> +    @ApplicationContext private val context: Context,
We could resolve it by passing Application object instead of Context

2023-02-06 15:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0b3f502b-a146-447c-bda0-784bc07e4fc6%2Fartifact%2F3a3e31071a502390%2Fp%2F14af3a01cce2e3b0c7ecc93beebbb705&size=150x150">

2023-02-06 18:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa0e204c7-927a-4c79-98e3-7bbbb3c68b49%2Fartifact%2F6033e47b174c20ae%2Fp%2Fac3503b4fb4a0eb9515e2cdbaf82f2fc&size=150x150>

2023-02-06 18:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5e21714a-370f-4529-9e47-85ad6b337250%2Fartifact%2F35490208299e67e7%2Fp%2F76e232bb19e199b97ca04828558b3bec&size=150x150">

2023-02-07 08:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0d5c0b16-7431-44a3-b71b-6c15fa01ee9c%2Fartifact%2F7e7f1e6f0d48de00%2Fp%2F9c028d5eddcc4fffbd655ea9bae6fb8f&size=150x150>

2023-02-07 08:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcbfbb160-963c-4e5f-857a-571da5b304ca%2Fartifact%2F372992ce06908548%2Fp%2F9079326d909f866d74e2834103e4db8b&size=150x150">

2023-02-07 09:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4dd937dd-1379-47b3-9ff4-5f1b174899dd%2Fartifact%2F9436c4607eb06521%2Fp%2Fca35559be7e53f5a2e77baf18b982c1e&size=150x150>

2023-02-07 09:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fee46df34-4ea4-4fa1-a56d-0553d4486c2c%2Fartifact%2F3ee14cce8d328c42%2Fp%2F59506c99d20acbe5000a96265f66b4de&size=150x150">

2023-02-07 12:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdc5e0524-64ae-4fe6-8946-160da561ccaf%2Fartifact%2Ff6394fd1a977245b%2Fp%2Fc38cb5e448b409315d2af5cb5d936682&size=150x150>

2023-02-07 12:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb31313af-b4b6-436a-8399-43c347445a12%2Fartifact%2F7b8685af8311e075%2Fp%2Fc44b4152442bd127eb732c6e22434309&size=150x150">

2023-02-07 14:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5f789054-7114-4b0f-bd97-a043936e5fbc%2Fartifact%2Fdce3148f9f260c2d%2Fp%2F2879636ec574855e2ec2135e9ba32641&size=150x150>

2023-02-07 14:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2e48c23f-300b-4fe1-9068-6cb331f2a8ca%2Fartifact%2Ff36983fc99bef237%2Fp%2Fadca048b83405667e557bbc252faee12&size=150x150">

2023-02-07 15:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fce9d4e3c-c664-4e66-b462-c469b1577556%2Fartifact%2Fe13d0c1c52e46743%2Fp%2F192d3e280d7052716ad7cc4104ddc96b&size=150x150>

2023-02-07 15:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4481d2c4-bfd6-41dd-a772-d82959c934d8%2Fartifact%2F47f8521a519547c4%2Fp%2Fde7b255e21109e4c378d45600724781e&size=150x150">

2023-02-07 16:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc5492bcc-1b67-40ef-bdb2-bd706dd542d9%2Fartifact%2F2c24508ba47ab9fc%2Fp%2Fa173e805603e4d642c01cc2d0f4a97b2&size=150x150>

2023-02-07 16:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4e7ed882-5ba7-44db-80cb-1b8b6ba25210%2Fartifact%2F0f3bd145f14c4d7b%2Fp%2Fc4bf66ed48a0dfda50ca329b7ff21092&size=150x150">

2023-02-07 16:38 UTC, kristofnemere approved these changes

2023-02-08 10:22 UTC, hermannakos approved these changes

2023-02-08 10:31 UTC, merged