[MBL-16385][Student] - Refactor and create new Assignment E2E tests
instructure/canvas-android pull request #1851
Opened 2023-02-07 22:57 UTC by kdeakinstructure

- Extend some Assignment E2E test case (because of new assignment list page, and missing some assertions)

- Refactor an Assignment E2E test case to do the submission flow on the UI (at least in one test case, because we did not have a single test case which tested the submission flow on the UI....it was generated everywhere by the API, but it's a very important feature so it's essential to check it at least in one test case. I did not implemented the UI flow in all test cases because if one case checks it, it's enough to check the feature's basic flow, and the rest of the cases could remain with API because it's much more faster of course.)

- Implement a brand new test case which is focused on the multiple attempt selection on the Assignment List Page (which was the new feature of the assignment enhancement implemented yet)

refs: MBL-16385
affects: Student
release note: none

2023-02-07 23:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe6a2b6de-0cc4-42d1-839e-1a7ead1f9b04%2Fartifact%2F296ada4a944999f5%2Fp%2F8f61218bcae709b9d2c18d77a6f2eaa4&size=150x150">

2023-02-08 09:53 UTC, kristofnemere approved these changes

2023-02-09 10:02 UTC, tamaskozmer requested changes

2023-02-09 10:02 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
> +        Log.d(STEP_TAG, "Assert that when only there is one attempt, the spinner is displayed and the last/newest attempt is selected.")
I think this log step was the victim of copy paste :)

2023-02-09 10:02 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
> +        onView(allOf(withId(R.id.submissionAndRubricLabel), withText(R.string.submissionAndRubric)))
Do we need the `withText` matcher?

2023-02-09 11:19 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
> +        onView(allOf(withId(R.id.submissionAndRubricLabel), withText(R.string.submissionAndRubric)))
We do not, for the selector I guess (althought I think it just makes it more accurate), but there is really a problem with this that i forgot to put 'assertDisplayed()' at the end.

2023-02-09 11:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F63d7a96d-99c3-4d3f-8ed1-21d0ea80a282%2Fartifact%2Fabd9a5f64af16acc%2Fp%2F7a1eed1d56a1d800f3ff0051c8151a5c&size=150x150">

2023-02-09 12:13 UTC, tamaskozmer approved these changes

2023-02-09 12:34 UTC, merged