[MBL-16519][Student][Teacher] Inbox interaction tests
instructure/canvas-android pull request #1879
Opened 2023-02-28 12:12 UTC by tamaskozmer

refs: MBL-16519
affects: Student, Teacher
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product or not needed

2023-02-28 12:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F024b71cd-7c8f-4dc8-89c8-b872877ae4e0%2Fartifact%2F5b1b248f396112a0%2Fp%2Fc8eb932a98cb34eb8cf0387abdbe27c2&size=150x150>

2023-02-28 12:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F437b6bd2-f62f-492f-99bb-d3b8a6f167f9%2Fartifact%2Fbecfe9806781117a%2Fp%2F84f12d79ab7b81213e0726182c68b0ab&size=150x150">

2023-03-06 13:44 UTC, kdeakinstructure requested changes

2023-03-06 13:44 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt
> +        onView(ViewMatchers.withText("Delete"))
string resource should be used here

2023-03-06 13:44 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt
> +        openActionBarOverflowOrOptionsMenu(InstrumentationRegistry.getInstrumentation().getTargetContext())
You can use property access syntax instead of get

2023-03-06 13:44 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
> +        inboxPage.assertEditToolbarDisplayed()
We could check the buttons here besides the edit toolbar itself.

2023-03-06 13:44 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
> +        inboxPage.assertConversationNotDisplayed(conversation1.subject ?: "")
There is a static member in CanvasTest called EMPTY_STRING, please use it. (and in all further occasions)

2023-03-06 15:09 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
> +        inboxPage.assertConversationNotDisplayed(conversation1.subject ?: "")
But why do we need that `EMPTY_STRING` constant in the first place?

2023-03-06 15:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F558f6a31-d51a-46cd-8c1e-c3963728d9e6%2Fartifact%2F7c29df052cdb6bb3%2Fp%2F694fd5f084921b7fc2a0ff7312097f1b&size=150x150>

2023-03-06 15:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F475854ae-d1da-4be8-b1de-26f5f464b4bf%2Fartifact%2F94aa8abd566c3f38%2Fp%2F7ec22f7368e56cf50a600bdb20345c20&size=150x150">

2023-03-06 15:37 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
> +        inboxPage.assertConversationNotDisplayed(conversation1.subject ?: "")
Because it's increasing the readability.

2023-03-06 15:50 UTC, kdeakinstructure approved these changes

2023-03-06 15:55 UTC, merged