[MBL-16609][Student] Dashboard notifications are displayed with different users
instructure/canvas-android pull request #1915
Opened 2023-03-27 15:37 UTC by kristofnemere

Test plan: in the ticket. I just updated the migration since we didn't released this version yet, it won't work as an update, you need the delete the app before install.

refs: MBL-16609
affects: Student
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

2023-03-27 15:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4606864f-0a76-4c51-91ca-670b23d611ad%2Fartifact%2F24471f836e2d139b%2Fp%2Fe9b8aa9642afc3003a3ac23a3b12cfe1&size=150x150>

2023-03-27 15:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F21171e38-990a-48b8-88dc-2f68995f29aa%2Fartifact%2F1af3eea617d4dea1%2Fp%2F7ae95d9c051da0764f2a6a942c50a6bd&size=150x150">

2023-03-28 09:34 UTC, tamaskozmer requested changes

2023-03-28 09:34 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModel.kt
> -    private val fileUploads = dashboardFileUploadDao.getAll()
`apiPrefs` is already injected in the ViewModel. Please use that instead of the object reference. In this case you will also make the unit tests easier/cleaner.

2023-03-28 09:34 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/worker/FileUploadWorker.kt
> +        val userId = ApiPrefs.user?.id ?: return
We can inject `ApiPrefs` here as well.

2023-03-28 10:19 UTC, kdeakinstructure approved these changes
QA 👍

2023-03-28 12:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F90f92e27-f7b1-4893-a714-e9fae61fb5d9%2Fartifact%2F714ff5df64ff11c3%2Fp%2F3000a067e0848b068d7b3b50e34e71f9&size=150x150>

2023-03-28 12:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe0777656-f7c7-420b-a5e4-b05c6cca8eaa%2Fartifact%2F5e34f74ac8cc0c82%2Fp%2Fe234a7316d16ce5ff03d1fd9d2f5a9f0&size=150x150">

2023-03-28 13:44 UTC, tamaskozmer approved these changes

2023-03-28 14:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff07d4b1d-44e9-4ced-aee8-09fdff5e993d%2Fartifact%2F7b8b99299177ce95%2Fp%2Fcf4b12996e322d2ba5fc5d352ea7795f&size=150x150>

2023-03-28 14:27 UTC, merged