[MBL-16264][Student] Share Extension | Retry upload from progress screen
instructure/canvas-android pull request #1923
Opened 2023-04-03 17:24 UTC by kristofnemere

Test plan: smoke test share extension uploads, and other file uploads using the file upload dialog

refs: MBL-16264
affects: Student
release note: Added proper failed screen and retry logic for share extension.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product or not needed

2023-04-03 17:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5fba2397-9ca9-4be7-805e-6de1d377b381%2Fartifact%2F683aa55e784f0c74%2Fp%2F3053cd2413b6b0a80329951fa195520f&size=150x150>

2023-04-03 17:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3f4f647b-8758-4c02-b040-c9b2d820a32e%2Fartifact%2Fb27ee538a3e7634e%2Fp%2F5ec6dad2b5f4836c93088341c13142f9&size=150x150">

2023-04-04 07:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb7336487-b5bc-4c40-b983-72bd54bea603%2Fartifact%2Fe888f1beefd56409%2Fp%2F6fb72a94fb91d96cc83f647de2b7033e&size=150x150>

2023-04-04 07:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F94885932-b80b-44e5-9fdc-11822b3094c0%2Fartifact%2F8b137e4916dc3e74%2Fp%2F27f76cf4ac6f1fa89df32c2fd0aeda4b&size=150x150>

2023-04-04 07:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0cb1da75-6284-4a2a-8dcd-a9195aaa3914%2Fartifact%2F482b6a3f4bcf0f50%2Fp%2F2a94a6a9c27c5cdffc9f786f23bc017b&size=150x150">

2023-04-04 08:28 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2b66a077-a7d9-4909-ab35-c325762c65c4%2Fartifact%2Fd18c5c62142782b7%2Fp%2F224a94edf725b569106bb74506048b7b&size=150x150">

2023-04-04 12:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F867bc840-a8ad-4648-b69e-d23f261145e9%2Fartifact%2F1024ac332ec159f4%2Fp%2F836daebfcd7cb5cf579b78a6e077b99a&size=150x150>

2023-04-04 13:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F897867d6-a4ea-40a0-8387-c2b9f96ce9e1%2Fartifact%2F0579e7a7b85603a8%2Fp%2F09ef2ea265ed652d8845f23042d1a85b&size=150x150>

2023-04-05 09:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fec008fc3-2ecf-4a70-925b-747496dc0090%2Fartifact%2F2a593c0afef32672%2Fp%2F2cdd685c6e2d00e67d90d953e076f330&size=150x150>

2023-04-05 09:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3658d47a-a640-413f-a57a-9365a92234bb%2Fartifact%2Fb945c05465b3def4%2Fp%2F85ef2005db53b92c4f14560efbbfb179&size=150x150">

2023-04-05 11:48 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F67a2e0d4-87f7-4c07-a110-e66b72d9c331%2Fartifact%2Fa6683429a8ccc03c%2Fp%2Ff9c96145c24373d00f9253d0649e9ef5&size=150x150">

2023-04-05 11:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdb668ef4-e50a-459a-b5fc-a4f1b9c5ecc5%2Fartifact%2Fc4b7dfb49298c5aa%2Fp%2F3a356492257ad917f1a7adc8b48326f0&size=150x150>

2023-04-05 11:50 UTC, tamaskozmer approved these changes
QA + 1

2023-04-05 11:51 UTC, hermannakos requested changes

2023-04-05 11:51 UTC, hermannakos commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressViewModelTest.kt
> +        every { resources.getString(R.string.fileUploadFailedSubtitle) } returns "Error"
This should be in the `setupString()` with the other string resources.

2023-04-05 11:51 UTC, hermannakos commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressViewModelTest.kt
> +        every { resources.getString(R.string.fileUploadFailedSubtitle) } returns "Error"
This should be in the `setupString()` with the other string resources.

2023-04-05 11:51 UTC, hermannakos commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressViewModelTest.kt
> +        every { resources.getString(R.string.fileUploadFailedSubtitle) } returns "Error"
This should be in the `setupString()` with the other string resources.

2023-04-05 13:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd2fcf851-fc36-4a4c-93a0-807a4cbe8b07%2Fartifact%2Fc1bb915ccd23d17d%2Fp%2F0a08bbb42acec09a42e0ff7fc75a393d&size=150x150">

2023-04-05 13:28 UTC, hermannakos approved these changes

2023-04-05 14:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe50a1c80-330a-4da2-9fd1-1912583b82df%2Fartifact%2F62eaa743d465b27e%2Fp%2F642d49c7e21617789c9f986822dea0f9&size=150x150">

2023-04-05 14:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9b730e0b-c50b-4a52-a7e9-3eb65d697327%2Fartifact%2F71052a65e367b476%2Fp%2Fac21ae58fbad731ac05a514883e75f8b&size=150x150">

2023-04-05 14:58 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd74b96cb-be0b-4bc2-a69a-fbb450c4c2a5%2Fartifact%2F39f9e75664277bfb%2Fp%2Fbcdb8faa253eed58d6096b09857a4018&size=150x150>

2023-04-06 07:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fae4b9cb5-7f2f-4db7-87de-49173e401c88%2Fartifact%2F9c5ff04226ed72e2%2Fp%2F44e112887190dbcadd2ceaeaa66d3d53&size=150x150">

2023-04-06 09:10 UTC, kdeakinstructure approved these changes
QA 👍

2023-04-06 09:12 UTC, merged