[MBL-16719][Student] Offline content screen modifications
instructure/canvas-android pull request #2014
Opened 2023-06-05 13:03 UTC by hermannakos

Test plan: Check the functionality of the tri state checkbox. Check if the file selection is saved to the db correctly.

refs: MBL-16719
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] A11y checked

2023-06-05 13:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc5767db4-cc5b-4fcc-bf8d-3b9f2d40d131%2Fartifact%2Fc9591dd2b693ac49%2Fp%2Fccd85c00a6c9ca09f204cecfe1909182&size=150x150>

2023-06-05 14:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4bb65382-57bc-4cb0-aa3f-ffa1eba19014%2Fartifact%2Fd432ec4c5d6ad8e2%2Fp%2Fc9b739c021ec06f7492dcc514a408061&size=150x150">

2023-06-07 11:13 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fefae0f8a-1514-453a-850c-864e851a6c70%2Fartifact%2F235471636fbb0bbc%2Fp%2F25c51ea745db06da15dd0edf65ce869d&size=150x150">

2023-06-07 21:41 UTC, kdeakinstructure approved these changes
QA 👍

2023-06-08 08:11 UTC, kristofnemere requested changes

2023-06-08 08:11 UTC, kristofnemere commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/CourseSyncSettingsDaoTest.kt
The copyright text is missing here.

2023-06-08 08:11 UTC, kristofnemere commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/CourseSyncSettingsDaoTest.kt
> +package com.instructure.pandautils.room.offline.daos
The copyright text is missing here.

2023-06-08 08:11 UTC, kristofnemere commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/FileSyncSettingsDaoTest.kt
> +package com.instructure.pandautils.room.offline.daos
The copyright text is missing here.

2023-06-08 08:11 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewData.kt
> +package com.instructure.pandautils.features.offline.offlinecontent
The copyright text is missing here.

2023-06-08 08:11 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/FileSyncSettingsEntity.kt
> +package com.instructure.pandautils.room.offline.entities
The copyright text is missing here.

2023-06-08 08:11 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/model/CourseSyncSettingsWithFiles.kt
> +package com.instructure.pandautils.room.offline.model
The copyright text is missing here.

2023-06-12 13:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F69768de7-266d-4bfb-a1e5-3ee8a9c6508f%2Fartifact%2F97cfba53bf60b070%2Fp%2F20ddb0c64a890627ede3adc01d1d4f35&size=150x150>

2023-06-12 13:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3e7c533d-fb1a-48a3-9fd2-20e481404423%2Fartifact%2Fa520002356440e43%2Fp%2Fd71a282dbebccb49dc5c39582a8243a5&size=150x150">

2023-06-13 14:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F53e7566b-1e04-4b1d-8f4d-86dc28fd0f36%2Fartifact%2F9e37a6e6b46cf1e0%2Fp%2Fd5d7b7a2f34705e02644e04268e9c428&size=150x150">

2023-06-15 09:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F94844133-df47-4680-b0e4-e246a064197e%2Fartifact%2F087fd7da58d761fb%2Fp%2F1543b1113f28a48dcfd9011941a1bdac&size=150x150>

2023-06-15 09:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F74a25a0f-47f6-4106-b839-0d471909636a%2Fartifact%2F656ad95716c381d5%2Fp%2F6a1a61c8b2f520a36fd7514008a79a1a&size=150x150>

2023-06-15 09:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F54bc3c44-33fe-4b7b-abb4-28f4de9f2947%2Fartifact%2F465e2604976a8c72%2Fp%2F3a93c861257710091eeba76ee937b73b&size=150x150">

2023-06-15 10:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F975a7792-6da8-4111-937b-1cf779d645bb%2Fartifact%2F05bca249b9cd4341%2Fp%2F317d1b03da6a39e1be6aea1baf0037e2&size=150x150>

2023-06-15 10:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2e01abde-8585-4272-8773-b5129724a3b8%2Fartifact%2F27e353b707a00002%2Fp%2F1e88c07347cb29ae02849b39d5b49127&size=150x150">

2023-06-15 10:51 UTC, kristofnemere approved these changes
QA+1

2023-06-15 11:00 UTC, merged