[MBL-16775][Student] Offline Assignment List
instructure/canvas-android pull request #2016
Opened 2023-06-05 16:31 UTC by kristofnemere

Test plan: in the ticket.

refs: MBL-16775
affects: Student
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode

2023-06-05 16:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1ae9165b-8b85-4c2c-bda4-cf4b6f50d17e%2Fartifact%2F449bd285e6b93051%2Fp%2F78e1dd3dfc4a7d4fcb1f0916b7725660&size=150x150>

2023-06-05 16:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F30307548-6b72-4a05-bccd-b62ac95467aa%2Fartifact%2F53868fb8ece49f6c%2Fp%2F55ba71cd5705403901e7df29455dbf86&size=150x150">

2023-06-05 17:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb155b8c9-f7db-49d7-a04a-4bf773bd240c%2Fartifact%2F886809642f56be67%2Fp%2F1cc934afb9ce3b6c8928e9ffc2b7238e&size=150x150>

2023-06-05 17:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffdcde080-f8d4-4e75-8c4e-9b5ceca4e49e%2Fartifact%2F7ff6f0f6d0695d76%2Fp%2F870548b9ff1ec5de5d5cc5c8023a2722&size=150x150">

2023-06-07 08:56 UTC, hermannakos requested changes
Great job, only a minor request for the tests

2023-06-07 08:56 UTC, hermannakos commented on apps/student/src/test/java/com/instructure/student/features/assignmentlist/AssignmentListRepositoryTest.kt
> +        coVerify { networkDataSource.getAssignmentGroupsWithAssignmentsForGradingPeriod(any(), any(), any(), any()) }
Instead of using any() you can verify the parameters as well, to make sure it's called with the right ones.

2023-06-07 10:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F341a39cf-3b46-48c2-a261-ccded44d117a%2Fartifact%2Fdcec2a61d9456ac7%2Fp%2F1d67ccf026e64744a5432eeabdc41dcf&size=150x150">

2023-06-07 13:37 UTC, kdeakinstructure approved these changes
QA 👍

2023-06-07 13:50 UTC, merged