[MBL-16777][Student] Offline Grades
instructure/canvas-android pull request #2023
Opened 2023-06-13 09:36 UTC by kristofnemere

Test plan: test grades list screen online and offline.

refs: MBL-16777
affects: Student
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode

2023-06-13 09:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F64b8299c-8903-481a-8b42-8dd7d268f3a6%2Fartifact%2F4503bad2bfdd04cd%2Fp%2Ffd2c0d6a78fa319142041e7df11a1c86&size=150x150>

2023-06-13 10:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fab2b8c5e-d58a-49ca-9632-2d116f0201eb%2Fartifact%2F181577ffaf6d48f7%2Fp%2Ff08c4c9e50d38266b7f1165a36df7e1a&size=150x150>

2023-06-14 09:12 UTC, tamaskozmer approved these changes

2023-06-14 09:24 UTC, hermannakos requested changes

2023-06-14 09:24 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/di/feature/GradesListModule.kt
> +    fun provideAssignmentListNetworkDataSource(
This is the grades list

2023-06-14 09:24 UTC, hermannakos commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/EnrollmentDaoTest.kt
> +class EnrollmentDaoTest {
You could write tests to check the foreign keys.

2023-06-14 09:24 UTC, hermannakos commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/SubmissionDaoTest.kt
> +class SubmissionDaoTest {
You could write tests to check the foreign keys.

2023-06-14 09:24 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/CourseGradingPeriodDao.kt
>  interface CourseGradingPeriodDao {
You could write tests for this dao

2023-06-14 09:24 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/GradingPeriodDao.kt
> +    @Insert(onConflict = OnConflictStrategy.IGNORE)
It could lead to problems to ignore the updates. We should handle the conflict manually if it causes problems elsewhere.

2023-06-14 09:24 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/GradingPeriodDao.kt
>  interface GradingPeriodDao {
You could write tests for this dao

2023-06-14 09:24 UTC, hermannakos commented on apps/student/src/test/java/com/instructure/student/test/adapter/GradesListRecyclerAdapterTest.kt
>      private var mAdapter: GradesListRecyclerAdapter? = null
You could refactor the hungarian notation here.

2023-06-14 09:24 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/grades/datasource/GradesListLocalDataSource.kt
> +        return enrollmentFacade.getAllEnrollments()
It throws an error in the network data source. Should we add error handling here? Or the network error throwing is unnecessary?

2023-06-14 09:24 UTC, hermannakos commented on libs/pandautils/src/test/java/com/instructure/pandautils/room/offline/facade/SubmissionFacadeTest.kt
> +        coEvery { groupDao.findById(any()) } returns GroupEntity(group)
You could set the params here or verify later that the daos were called with the correct params.

2023-06-14 09:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6db1bfa8-e088-4cd5-93ff-17644b09f1ab%2Fartifact%2F2ac97fcd4c7e3632%2Fp%2Fb55c8afe8ff41143319cee76567cfcf1&size=150x150>

2023-06-14 09:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F487de4b0-3673-4914-b557-78c6b6c77aeb%2Fartifact%2F02d439ab1be0982f%2Fp%2F747e378c01fe5e8fe447fff75844753f&size=150x150">

2023-06-14 12:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F877c4c59-004e-4ca6-a366-574e87237314%2Fartifact%2F0edc8bd656488202%2Fp%2F80c2213f375e76b110826916681a752b&size=150x150>

2023-06-14 12:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F43579660-676d-4d5c-bc11-52f7f9fdb91c%2Fartifact%2F84dec645d39c045a%2Fp%2F2a81325f3bef987caf44efc1c64d1ba4&size=150x150">

2023-06-14 14:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F92802cc9-35e7-438c-a58b-1aa5c5ddb57d%2Fartifact%2F24af19a33e81edc9%2Fp%2Fb5e01b69347f24eab32795602351df92&size=150x150>

2023-06-15 07:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe9cb008d-75d9-4c06-a4ae-2dea15104c6d%2Fartifact%2Fc6fad9cc13fd9235%2Fp%2F51a75f98ded1fb1a7e8cfbd5a721e34f&size=150x150>

2023-06-15 07:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F94a151f6-c919-4d0a-b6f0-222a7df5be4e%2Fartifact%2Fa0b309d31d9d61c3%2Fp%2Fb76d6a390ab676447cd55e0acd92ba80&size=150x150">

2023-06-15 08:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F7aae5423-3423-48db-913b-bf9bf06731be%2Fartifact%2Fb030503518f9679a%2Fp%2F4304b29217a76e1a9deae3a0211675b3&size=150x150>

2023-06-15 08:27 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5e40cc85-4e63-47c1-9cae-ccdd315a5318%2Fartifact%2Fdd676c3b1113ce0a%2Fp%2F5254d26e1857c8d4cd82efcb9ccecc34&size=150x150">

2023-06-15 08:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0e399152-81da-4044-859b-dc23423b95ff%2Fartifact%2F8b7b60594273a027%2Fp%2Fbc28039e83a267a84131499b814cf622&size=150x150>

2023-06-15 08:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd5e50797-4421-4e45-9c74-a5a4181e2cf0%2Fartifact%2Fc33c96a5cf836956%2Fp%2F6b3f4d1cb5fecea307b342f6d29a3ee1&size=150x150">

2023-06-15 09:10 UTC, hermannakos approved these changes

2023-06-15 09:12 UTC, merged