[MBL-16792][Student] Offline Conference list
instructure/canvas-android pull request #2029
Opened 2023-06-16 11:49 UTC by kristofnemere

Test plan: test BigBlueButton tab online and offline.

refs: MBL-16792]
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode

2023-06-16 12:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa35b7179-a7da-4703-bf16-208f8a9018b9%2Fartifact%2Ffe0387ef8899c086%2Fp%2Ffa07b8a4374f220a6a53f18b278d6275&size=150x150>

2023-06-16 13:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc6b0d2fb-96b1-41bc-8409-9a0588229435%2Fartifact%2F93953335c7caeb3f%2Fp%2F15e5415d27f1925725ba3288d4eae4a5&size=150x150>

2023-06-16 13:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F84c1a9f9-f96f-44fe-b5e6-7acecad576b2%2Fartifact%2F43572b6d54816bf2%2Fp%2Fc7358dc71375381cb9df8443b9091b4f&size=150x150">

2023-06-19 10:57 UTC, hermannakos requested changes

2023-06-19 10:57 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/ConferenceEntity.kt
> +    val courseId: Long,
This should be a foreign key.

2023-06-19 10:57 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/ConferenceRecordingEntity.kt
> +    val conferenceId: Long,
This should be a foreign key.

2023-06-19 10:57 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/ConferenceSyncHelper.kt
> +    private suspend fun DataResult<ConferenceList>.depaginate(
Move it out to global scope. Maybe we should look into if we have more apis like this and make it generic.

2023-06-19 10:57 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/ConferenceFacade.kt
> +                conferenceRecodingDao.insert(ConferenceRecordingEntity(recording, conference.id))
You could create an insertAll function, so all the entities are inserted in one transaction.

2023-06-19 11:12 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_list/datasource/ConferenceListLocalDataSource.kt
> +        throw IllegalStateException("This should never be called")
I know that, but it would be helpful to include that in the the exception as well.

2023-06-19 11:12 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/ConferenceEntity.kt
> +    val courseId: Long,
I'm trying to avoid using them, we gonna remove and store everything when we sync the data again.

2023-06-19 11:12 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/ConferenceRecordingEntity.kt
> +    val conferenceId: Long,
I'm trying to avoid using them, we gonna remove and store everything when we sync the data again.

2023-06-19 11:47 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_list/ui/ConferenceListView.kt
> +                if (APIHelper.hasNetworkConnection()) {
We have `context` here, we could just check if it's a FragmentActivity and we can use the extension for `FragmentActivity`.

2023-06-19 12:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa6cd3a5b-84af-4b73-9f06-c6f3be9eb7a9%2Fartifact%2F882c3becf54b9b6e%2Fp%2F11bba4bb07d9b07f8ef0a0696078b26d&size=150x150">

2023-06-19 13:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7ce42dd8-8f8f-4377-8158-093bfde6ed88%2Fartifact%2Fe89b92f5f8155177%2Fp%2Fae32fa46c671ca7bf15045ca3097a26d&size=150x150">

2023-06-19 13:56 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F65b48820-5acf-4aa4-b54a-cc8f827304b4%2Fartifact%2F2d09d4f8a7458ef4%2Fp%2Faa8f51c47aebea3e5144c6363e2aa4d7&size=150x150>

2023-06-19 15:39 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F516db210-9968-4aa7-8bf7-9171a75a871b%2Fartifact%2F8e18763f520a5b0d%2Fp%2F48b6a224a8995377f5d23f6c9837bf1a&size=150x150>

2023-06-19 15:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F27c8b86e-0367-4890-b76c-f88dc1401af3%2Fartifact%2F7724deae702925af%2Fp%2F473f655492e8a27004a044dfcb6c2c66&size=150x150">

2023-06-20 12:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F609e1547-def1-47ff-98c5-95f98ab32734%2Fartifact%2F3f2b5cfda10423ea%2Fp%2F5a074b1b0f41b5f47466bc1decb75bc6&size=150x150>

2023-06-20 12:33 UTC, hermannakos approved these changes
QA + 1

2023-06-20 12:34 UTC, merged