[MBL-16849][Student] - Handle API flakiness of Notifications and Todo E2E test cases
instructure/canvas-android pull request #2035
Opened 2023-06-21 17:15 UTC by kdeakinstructure

Workaround to handle API flakiness in ToDoE2E and NotificationsE2E tests.

refs: MBL-16849
affects: Student
release note: none

2023-06-21 17:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4527b1b9-8798-40f9-bddc-222ee0b1f21a%2Fartifact%2F93a23f52c788e82b%2Fp%2Fa3a4e703824b881400c7a3798f62e140&size=150x150">

2023-06-22 10:22 UTC, hermannakos requested changes

2023-06-22 10:22 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt
> +        while (remainingRetryAttempt > 0) {
You can use `repeat` for this.

2023-06-22 12:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff66bc395-0009-44ba-aaa0-d79ae895f32b%2Fartifact%2F473aebc87310d62d%2Fp%2Fe7777d0f7fcccc9dd45ea689834082f7&size=150x150">

2023-06-22 12:50 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt
> +        while (remainingRetryAttempt > 0) {
Thanks

2023-06-22 13:06 UTC, hermannakos approved these changes

2023-06-22 15:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0de5eb25-4a55-4872-92db-2435df684f46%2Fartifact%2Fd752325b10100ff4%2Fp%2Fac0cda31d4c6a145d1c322079e6a01a6&size=150x150">

2023-06-22 20:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2819d814-ffb5-4119-8b00-eae4a9b071ff%2Fartifact%2Fcffc3110cc14b6db%2Fp%2F187c9dfb1aeb1b76a7d32f8a02c905fe&size=150x150">

2023-06-22 21:26 UTC, merged