[MBL-16784][Student] Offline Announcements/Discussions list
instructure/canvas-android pull request #2037
Opened 2023-06-22 14:46 UTC by tamaskozmer

Test plan:

refs: MBL-16784
affects: Student
release note: none

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-06-22 14:47 UTC, tamaskozmer commented
E2E test run: https://app.bitrise.io/build/621357fb-b1d8-4e04-b66d-2f5f9ec93a4d

2023-06-22 15:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9cc3465c-af60-410a-bde7-4c54acfa9567%2Fartifact%2F818405e56d4af693%2Fp%2F9542c5f4a58f31d7ca3358ff40cfbbd5&size=150x150>

2023-06-22 15:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F15a0f52e-637a-4e5a-98f1-69e36d09f730%2Fartifact%2Ffd431c3053d15be9%2Fp%2F8fbe10b269a4d7a9d077a4584114d52f&size=150x150">

2023-06-23 08:45 UTC, hermannakos requested changes
Great job, some minor requests, otherwise QA + 1

2023-06-23 08:45 UTC, hermannakos commented on apps/student/src/test/java/com/instructure/student/features/discussion/list/DiscussionListRepositoryTest.kt
> +    fun `Get announcement creation permission from local data source for course when device is online`() = runTest {
typo 'when the device is offline'

2023-06-23 08:45 UTC, hermannakos commented on apps/student/src/test/java/com/instructure/student/features/discussion/list/DiscussionListRepositoryTest.kt
> +    fun `Get discussion creation permission from local data source for course when device is online`() = runTest {
typo 'when the device is offline'

2023-06-23 08:45 UTC, hermannakos commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/DiscussionTopicHeaderDaoTest.kt
> +class DiscussionTopicHeaderDaoTest {
You can add foreign key tests for this entity.

2023-06-23 08:51 UTC, tamaskozmer commented on apps/student/src/test/java/com/instructure/student/features/discussion/list/DiscussionListRepositoryTest.kt
> +    fun `Get announcement creation permission from local data source for course when device is online`() = runTest {
More like bad copypasta 😄

2023-06-23 13:48 UTC, hermannakos approved these changes
QA + 1

2023-06-23 14:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd35a06ac-b57c-4961-bdc5-d74ea16421dd%2Fartifact%2Fc00c03e54c4e6889%2Fp%2F41adac7931dc508c6ce10358ec8f39da&size=150x150>

2023-06-23 14:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F05b239d9-4221-46ad-9297-d3642a8007c8%2Fartifact%2Ff70fa63557ecda81%2Fp%2F6227382e95767dce399248e6915bbaeb&size=150x150">

2023-06-23 14:37 UTC, kristofnemere approved these changes
QA+1

2023-06-23 14:37 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseSyncSettingsEntity.kt
> +        get() = tabs.values.all { it == true } && fullFileSync
== true is not necessary

2023-06-23 14:37 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseSyncSettingsEntity.kt
> +        get() = fullContentSync || fullFileSync || tabs.values.any() { it == true }
== true is not necessary

2023-06-23 14:37 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/DiscussionTopicHeaderFacade.kt
> +            .map { it.author }
could be mapNotNull

2023-06-23 14:54 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseSyncSettingsEntity.kt
> +        get() = tabs.values.all { it == true } && fullFileSync
I know, this was intentional for better readability, because we can't see the type of the `tabs.values` here.

2023-06-23 14:55 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseSyncSettingsEntity.kt
> +        get() = fullContentSync || fullFileSync || tabs.values.any() { it == true }
I know, this was intentional for better readability, because we can't see the type of the `tabs.values` here.

2023-06-26 06:31 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseSyncSettingsEntity.kt
> +        get() = tabs.values.all { it == true } && fullFileSync
We know how .all { } works, but okay, fine by me :)

2023-06-26 09:12 UTC, kdeakinstructure approved these changes
QA 👍

2023-06-26 09:34 UTC, merged