[MBL-16846][Student] Navigate to hidden tabs
instructure/canvas-android pull request #2040
Opened 2023-06-27 08:49 UTC by hermannakos

refs: MBL-16846
affects: Student
release note: none

test plan: See ticket.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/38b3b282-0662-4f58-964f-d4fc829f6c02" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/c84e16d1-a2de-47a4-a08d-64fcc06272ed" maxHeight=500></td>
</tr>
</table>

2023-06-27 09:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8ababa84-83f7-4411-bfa3-ab2fb3eb2f44%2Fartifact%2F8e0d7a30d9db0ca1%2Fp%2F3fa2b0e0da796136b167e9cda500632b&size=150x150">

2023-06-27 11:47 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F918c256f-33c0-4a55-baa3-fab49e3f6e8b%2Fartifact%2F54136b1367808189%2Fp%2F79385078f1443e7506af164c31e59a3d&size=150x150">

2023-06-28 11:52 UTC, kdeakinstructure approved these changes
QA 👍

2023-06-28 12:15 UTC, tamaskozmer requested changes

2023-06-28 12:15 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModel.kt
> +                    _state.postValue(ViewState.Success)
It would be nice to cover these changes with unit tests.

2023-06-28 12:55 UTC, tamaskozmer approved these changes

2023-06-28 14:55 UTC, merged