[MBL-16788][Student] Offline People List
instructure/canvas-android pull request #2044
Opened 2023-07-03 11:08 UTC by domonkosadam

Test plan:

refs: MBL-16788
affects: Student
release note: none

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-07-03 11:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fbe8dde7c-360a-4552-8036-a8aa0a183aae%2Fartifact%2Fadad03653c32bb35%2Fp%2F8279c0ccad4063e03c28a5f0bde37e5c&size=150x150>

2023-07-03 11:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd8209820-133b-4a0e-b410-f42c154cf771%2Fartifact%2Fd6c14aeffca0fcd1%2Fp%2F4f1054356e343bc612b17ba433f31d61&size=150x150">

2023-07-04 14:28 UTC, tamaskozmer requested changes

2023-07-04 14:28 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/PeopleFacade.kt
> +class PeopleFacade(
Please write unit tests for this class as well.

2023-07-04 14:28 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/PeopleFacade.kt
> +class PeopleFacade(
I think the name of this facade classes represents the underlying data and not the user facing screen, so `UserFacade` would be more fitting.

2023-07-04 14:33 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
> +        val users = userApi.getFirstPagePeopleList(courseId, CanvasContext.Type.COURSE.apiString, restParams).dataOrNull
Also I think we need to add the `usePerPageQueryParam` to the `restParams` to add the `perPage=100` parameter to the request, because the default paging is 10 on the API. I will look into this later, because we might need to add this to other requests here as well.

2023-07-06 11:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F138ca36a-6123-48f5-8b0a-4b212b5e6003%2Fartifact%2Fbea096283f192b8a%2Fp%2F4670882e08d9dd67354ef363337735d1&size=150x150>

2023-07-06 11:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F23e4a6ce-2912-4bbf-9184-5ad7617fbad4%2Fartifact%2F0977deaf92631cc1%2Fp%2F14ec201f2f115c46f1ed6bf5da22693b&size=150x150">

2023-07-06 14:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9b22b56a-6575-435f-8c1f-7c656d570d9c%2Fartifact%2F96777709ef4bf37a%2Fp%2F68be2783640551384dfa620a90efc2dd&size=150x150>

2023-07-06 14:44 UTC, tamaskozmer requested changes

2023-07-06 14:44 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRecyclerAdapter.kt
> +                withContext(Dispatchers.Main) {
I don't think we need this. This is the default context for the `lifecycleScope`.

2023-07-06 14:44 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRecyclerAdapter.kt
> +                withContext(Dispatchers.Main) {
Same here.

2023-07-06 14:44 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRecyclerAdapter.kt
> +        lifecycleScope.launch {
You can use `lifecycleScope.tryLaunch` if the whole coroutine block is included in a try-catch.

2023-07-06 14:44 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRecyclerAdapter.kt
> +        lifecycleScope.cancel()
You can just delete this override, the `lifecycleScope` is tied to the Fragment's lifecycle so it will be automatically cancelled.

2023-07-06 14:44 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/UserFacade.kt
> +        val users = enrollments.groupBy { it.userId }.keys.mapNotNull { userId ->
You can refactor this duplicated code by extracting it to a private function.

2023-07-06 14:44 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRecyclerAdapter.kt
> +            } catch (e: CancellationException) {
`CancellationException` should not be caught.

2023-07-06 15:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F098fc292-06c4-436b-a661-8b0b96880fba%2Fartifact%2F138f16a033ed7fb3%2Fp%2Fca2606094e5ccba9cc1ebad005fc58a4&size=150x150>

2023-07-07 07:43 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRecyclerAdapter.kt
> +            withContext(Dispatchers.Main) {
This is not needed as well.

2023-07-07 10:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8ed6c7da-d119-4aa4-b882-c888b672e8c7%2Fartifact%2Fe168fcd97ca0e1cd%2Fp%2F3e0e2d416120ce5393f5b2f1ed4760a1&size=150x150>

2023-07-07 11:23 UTC, tamaskozmer approved these changes
Great work

2023-07-07 15:24 UTC, kristofnemere approved these changes

2023-07-10 08:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F16164e74-fd29-4b1f-ae92-ea54abc320e5%2Fartifact%2F26cf181d874a96cc%2Fp%2F62ebd801b1de06f874a5882d41283d13&size=150x150">

2023-07-10 08:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F48dbd8fa-7428-4d4e-a18e-fafa63e9f1e0%2Fartifact%2Fa6ece57793031a0e%2Fp%2Fa0671e00006212f91628fb9089e8d756&size=150x150">

2023-07-10 11:45 UTC, merged