[MBL-16782][Student] Offline submission details
instructure/canvas-android pull request #2047
Opened 2023-07-04 16:17 UTC by kristofnemere

Test plan: test submission details online and offline. The submission content part is out of scope, we can do that after files sync.

refs: MBL-16782
affects: Student
release note: none.

## Checklist

- [ ] Tested in dark mode

2023-07-04 16:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7087be0b-c711-44bc-915c-266aff04e7ab%2Fartifact%2F9607f20b9754e5cf%2Fp%2Fdc4dea9db398a9d881a6e7e51062cdfc&size=150x150">

2023-07-04 17:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5e8a9269-6182-4273-afc4-fb21933dfbb7%2Fartifact%2F968018432ddd9321%2Fp%2F19869fc547a10f7b99077722ab1e3ddb&size=150x150>

2023-07-04 17:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcf1cf3c0-c3b1-49cc-9ed8-517b1d6186e4%2Fartifact%2F446be7c2156f3ac9%2Fp%2Fb2bfc16bc1609a80a9b3fe2234d3c81f&size=150x150">

2023-07-05 12:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6b531a9f-aea6-4368-b670-6c2a28cad22f%2Fartifact%2Fb47f9c2a798a8672%2Fp%2Ff4bd660f39a4b3c058cd838195c18438&size=150x150>

2023-07-06 07:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa58fc940-296e-4abf-8dd2-383568eefdcc%2Fartifact%2Fe086329d2c4ad4ef%2Fp%2Fc37e9fbd2b0b636eedc976b58b0a7163&size=150x150>

2023-07-06 09:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fff2eb450-7415-48da-810c-68d933ac0662%2Fartifact%2Fd268e533017dec06%2Fp%2Faadd4f64dddb2dd8e7bdb121a9bc8999&size=150x150>

2023-07-06 09:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F08c8a779-24c6-404e-abd7-5005d09e670e%2Fartifact%2F451063ec4dfc971b%2Fp%2F39c018074168a008e6b8b746a21142bd&size=150x150">

2023-07-07 15:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2d00c131-3026-44a1-9fa6-4165f7d7e1ce%2Fartifact%2Fe09b06a8f8619615%2Fp%2F16457d9d50c34c0839bd39d610e20363&size=150x150>

2023-07-10 15:39 UTC, tamaskozmer requested changes

2023-07-10 15:39 UTC, tamaskozmer commented on libs/pandautils/schemas/com.instructure.pandautils.room.appdatabase.AppDatabase/6.json
> +    "identityHash": "fb05592c38126b79cd49f3ffb5768382",
I think this file shouldn't have been changed. If this file changes it means we the DB was changed so in that case we need to increase the version and create a new migration. As I see you handled the migration so the only thing you need to do is to revert the changes in this class.

2023-07-10 15:39 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseFeaturesEntity.kt
> +    val courseId: Long,
I think we agreed previously that the primary key should always be called `id` even though it will get the same `id` as the entity it's associated with.

2023-07-10 15:39 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/AssignmentFacade.kt
> +            this.submission = submission?.copy(assignment = this.copy(submission = null))
I know we talked about this, but it might be worth it to indicate why is this happening here with a comment.

2023-07-11 06:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Faf29a085-e963-4fcd-8d52-027827831ace%2Fartifact%2Fb90585bfae4650e0%2Fp%2F503a761064eb14c06554fc2fa65de6cd&size=150x150>

2023-07-11 06:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F556b0a10-b7f9-4843-b18e-bbcdc8a808f5%2Fartifact%2Fb7bf5cb49494743c%2Fp%2Fcf6a114dc8d6460b13c8e400cd0265fd&size=150x150">

2023-07-11 09:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa14f42eb-046f-4e8b-a1bd-f5a49d53352e%2Fartifact%2F777e9841f8c87a1a%2Fp%2F5e316dc5a7b42f728c9cf106f2054adb&size=150x150>

2023-07-11 09:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fec777768-b622-48d0-8ef4-cbc06c44d22d%2Fartifact%2Fccccba81599f5571%2Fp%2Fb970b466c39ee427d96984a1f65cd155&size=150x150">

2023-07-11 11:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F32a6dc0d-301e-4a78-9543-041bb8f10e23%2Fartifact%2F8c49db6911bb0807%2Fp%2Ff418aeb2bc5bdede65f04a042b8f18ad&size=150x150">

2023-07-11 14:28 UTC, kdeakinstructure approved these changes
QA 👍

2023-07-11 17:16 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1920bc39-d159-4ad5-bfff-6c4367dca439%2Fartifact%2Fc257fd9a252dfebb%2Fp%2Ff821c82a92b79cb016ef18f1768948c9&size=150x150>

2023-07-11 17:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2d78b5db-7c8e-4eea-9b86-db8e7c14e9d6%2Fartifact%2Fa5f74195c888b6cc%2Fp%2F8548a072231889d3406089436b875ad5&size=150x150">

2023-07-12 09:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5530d1b0-dd7e-4a1a-9177-f36fad07c35f%2Fartifact%2Fc37e76109130ef8e%2Fp%2Faef2a8f2a1a2e76af5ca9540a6dafe0d&size=150x150>

2023-07-12 09:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd34ac915-ef52-461c-a35e-0906abe134e5%2Fartifact%2F1b1f223f8706a342%2Fp%2F6d31ccbaac96a9a30b199195a5f6c3b6&size=150x150">

2023-07-12 11:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F10b79adc-5ae0-49b7-853d-1b49e387f787%2Fartifact%2F1b0122b2e3c251a1%2Fp%2Fcd8e73a91b8acb6d3fde55440c8f601d&size=150x150>

2023-07-12 11:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe35a6526-488c-4541-ac71-bb0b5f9ba501%2Fartifact%2F6ea2d9a1e5de3d40%2Fp%2F3d3e0f0b272e5e0102023dc1cd28609e&size=150x150">

2023-07-12 12:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F942c53d5-c8c5-423e-b5c0-cd8a04d4ad54%2Fartifact%2Fc3fd9a7a408c2e63%2Fp%2F95799ba4a692d2ba3f1b9448e3449284&size=150x150>

2023-07-12 12:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc157ed1b-0055-4b04-ac35-5fe75234327e%2Fartifact%2Fc094100c68781cc0%2Fp%2Fc9d6b48e580ee0551daf876a92a9e730&size=150x150">

2023-07-12 13:09 UTC, merged