[MBL-16881][Student] Offline People Details
instructure/canvas-android pull request #2055
Opened 2023-07-11 12:29 UTC by domonkosadam

Test plan:

refs: MBL-16881
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2023-07-11 12:45 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3267cdda-0ef9-42f1-9b07-dcd027b2d016%2Fartifact%2F5d91a7ed982e487d%2Fp%2F7d24e5cde432bc88c5817dbf6708e168&size=150x150>

2023-07-11 12:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6b74dc71-a173-4a83-8e62-733b2d95b11d%2Fartifact%2Fd9f264cc059df3e6%2Fp%2Fd887977e32df29815caafad5e131cbf3&size=150x150">

2023-07-12 09:17 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsDataSource.kt
> +    suspend fun loadUser(canvasContext: CanvasContext, userId: Long, forceNetwork: Boolean = false): DataResult<User>
You could return the `User` object here

2023-07-12 09:20 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsFragment.kt
You should move the permission api call to the repository as well.

2023-07-12 12:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F18642050-4d66-4d3f-8745-c1f129a0a9b0%2Fartifact%2Fe2df8921ed8a9539%2Fp%2Fa936c0a8de705e899473e705473a910c&size=150x150>

2023-07-12 13:17 UTC, tamaskozmer requested changes

2023-07-12 13:17 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsNetworkDataSource.kt
> +            canvasContext.isGroup -> GroupManager.getPermissionsAsync(id).awaitOrThrow().send_messages
We are not meant to use these legacy manager classes in the new architecture. Please change it to the API instances and inject them in the constructor.

2023-07-12 13:17 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsFragment.kt
> +            canvasContext.isCourse -> fetchUser()
I think this was okay the way it was before. If we come from a group and already have a user we don't need to fetch it again.

2023-07-12 13:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4e8e6a79-6ca6-4a9c-a429-edf62bbea6ba%2Fartifact%2F1056593ccb35edbb%2Fp%2Fd4cb449253497b5b755f0301f09d13d3&size=150x150>

2023-07-12 13:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F26115801-f0f5-449f-b36e-9e5e3f3ddb35%2Fartifact%2F1437a55102dc730a%2Fp%2F0fd9b7afb540aad393ae6f7f6724ed2a&size=150x150>

2023-07-12 15:13 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb277609c-9b4f-445f-923e-93d12224da54%2Fartifact%2F5cd4467578aa5064%2Fp%2F8abe2645c1b3a38d7099370715a3684d&size=150x150>

2023-07-12 15:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F460d1b9b-a588-494a-ac65-d92b0efe129e%2Fartifact%2F967b4736fa4a4d07%2Fp%2Fbb3b1dfe18879436e739355a745c1756&size=150x150">

2023-07-13 07:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1c274d7d-9d80-4069-9d4a-736ca5c63c15%2Fartifact%2Fdcc9aa345752bcf9%2Fp%2F4ee35c9a6e5b7d14002839fda48b8a6a&size=150x150">

2023-07-13 09:04 UTC, tamaskozmer approved these changes

2023-07-13 10:14 UTC, tamaskozmer commented
QA + 1

2023-07-13 11:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1e73dd30-34e0-4f6a-9606-f4036468cfd2%2Fartifact%2Fc49f42d93ad77722%2Fp%2F0db19da8799a5f31d5b9dbec9910004e&size=150x150>

2023-07-13 13:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F886920e4-ee54-4f05-a4e4-02226fccfe03%2Fartifact%2F0f31f315ac50f2e9%2Fp%2F0dd42272f9eb9523a68cb6b5c17ae42f&size=150x150>

2023-07-13 13:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6ae44367-7f49-4594-829b-8ccbc2edbaaf%2Fartifact%2Fa8ee906869f31301%2Fp%2F18a21cee5173f530f8a76a48509d488b&size=150x150">

2023-07-13 14:28 UTC, merged