[MBL-16856][Student] Offline feature flag
instructure/canvas-android pull request #2067
Opened 2023-07-18 12:55 UTC by hermannakos

Test plan: Test the app with the feature flag on and off. You might want to disable the network caching.

If the flag is off:

Always use the network data source
Remove the kebab menu on the dashboard and only show the column/grid option.
Do not indicate the synced courses.
Remove the Sync Settings menu item from the Application Settings screen.
Sync no longer runs.
The synced data remains in the db.

refs: MBL-16856
affects: Student
release note: none

2023-07-18 13:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0b43bd9f-b175-4424-a750-028dc8a5d41c%2Fartifact%2Fc4eb1ad3e1356881%2Fp%2Fc6163b9d5e5f9cbffb09d55f78ed10bf&size=150x150>

2023-07-18 13:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcf07f11e-ba73-45e1-8e08-36603e9e41d8%2Fartifact%2Fa040b83b3d197fe4%2Fp%2Fdadc21e00dc6c251ed66f4a3d53667d6&size=150x150">

2023-07-19 07:51 UTC, tamaskozmer requested changes

2023-07-19 07:51 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
> +import com.instructure.canvasapi2.utils.weave.tryLaunch
This seems unused.

2023-07-19 07:51 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
> +            if (!featureFlagProvider.checkEnvironmentFeatureFlag(FEATURE_FLAG_OFFLINE)) {
I think it would be better to run only this block in the coroutine.

2023-07-19 07:51 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/FeatureFlagProvider.kt
> +import com.instructure.canvasapi2.utils.weave.tryWeave
I think this is also unused.

2023-07-19 08:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F357f8762-f835-40ba-bda2-01578ce6db20%2Fartifact%2Fff28120259e5b19d%2Fp%2Fde12fd5964f90f0f9772ac65be45914e&size=150x150>

2023-07-19 08:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9d781b53-5658-458a-8290-37bd3b2291cf%2Fartifact%2F34c73ebd9fdff54c%2Fp%2F2795592a245338cdeeb9a8d4e8851349&size=150x150">

2023-07-19 11:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F77ef12fe-c533-4d41-af56-cb1bccddbbc5%2Fartifact%2F9dd63beabd22a371%2Fp%2F8688d5cecf6f62ec3d473bf5dc417700&size=150x150>

2023-07-19 13:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F42bcf602-571b-4cbf-b199-3272b7b359e7%2Fartifact%2F3cea0f01f5c8e652%2Fp%2F403320f416d024d9a08a31edcb02a0bb&size=150x150>

2023-07-20 08:43 UTC, kristofnemere approved these changes

2023-07-20 09:12 UTC, kdeakinstructure approved these changes
QA 👍

2023-07-20 10:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F87c561a9-3d8e-4bd9-91a2-fbbd95341814%2Fartifact%2F3a9483be0fa0ac7e%2Fp%2Fbdc9d4834eaeb8f7a80c996acd5e7bdc&size=150x150>

2023-07-20 10:28 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4f70244b-8569-474a-999e-ebeb142915e6%2Fartifact%2F57b8d5f63d8c3763%2Fp%2Fe9ab50d27393c459699f0da0204a4dd3&size=150x150>

2023-07-20 10:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff6a82205-93f4-41df-8a76-062d6eb63241%2Fartifact%2Fe2c97f92db512a90%2Fp%2F558bb8d24d6f16ff6655b4730e340dad&size=150x150">

2023-07-20 11:52 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9fafd831-1a37-4244-b37e-22c3dd87d359%2Fartifact%2F6a7df3cbcfdd349b%2Fp%2Fecaa1c14a574739f1fe8b25c78d226a6&size=150x150">

2023-07-20 12:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd0f2dcb4-8e41-4ea5-83b5-24e5226714a0%2Fartifact%2F0bc941f2fdeca503%2Fp%2F09583e49d9eaa6820b40c2a8c55451ca&size=150x150>

2023-07-20 12:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1f9066ed-4a5d-4c62-848f-4ae84ce68ed8%2Fartifact%2Fa859abe03ab23ec4%2Fp%2F74cbe8aed50bfbe1be0fd380af9f430a&size=150x150">

2023-07-20 13:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F710c4650-9f1c-4f32-a3b0-9127a7d373e6%2Fartifact%2F7a7ed34b888cafd3%2Fp%2F71918318f24dea9fba0018b324adb51a&size=150x150">

2023-07-20 14:15 UTC, merged