[MBL-16942][Teacher] - Fix PeopleListFragment accepts few letters as search query
instructure/canvas-android pull request #2075
Opened 2023-07-28 09:34 UTC by kdeakinstructure

Fix PeopleListFragment accepts few letters (1, 2) as search query.

refs: MBL-16942
affects: Teacher
release note: none

Test plan: Test 

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="" maxHeight=500>![Screenshot_20230728_113213_Canvas Teacher](https://github.com/instructure/canvas-android/assets/92309696/55ecc61d-a901-4106-b952-3acbf2d28b18)</td>
<td><img src="" maxHeight=500>
![image](https://github.com/instructure/canvas-android/assets/92309696/1dc4cfd2-5e07-40ef-857d-73689bcfea54)
</td>
</tr>
</table>

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-07-28 09:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdfee7e78-4ccc-49bd-8515-0d9bd1d7256e%2Fartifact%2F49980ab6dd8d5108%2Fp%2Fad0a8a8c1c5ce4a8478db84f7de35fca&size=150x150>

2023-07-28 12:48 UTC, tamaskozmer requested changes

2023-07-28 12:48 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/PeopleListFragment.kt
> +        val searchQuery = newText.trim().takeIf { it.length > 2 }.orEmpty()
This logic should be in the Presenter instead of the Fragment. Also there is a much easier way to check the length of the string. You can do this:
```
if(newText.length > 2) {
            presenter.searchPeopleList("")
}
```

2023-07-31 09:33 UTC, closed without merging

2023-07-31 09:33 UTC, kdeakinstructure commented
Won't do because product agreed that the original way is the expected behaviour.