[MBL-16890][Student] - Test folder control flow in user groups
instructure/canvas-android pull request #2077
Opened 2023-07-28 12:34 UTC by kdeakinstructure

Implement user group folder control flow (create folder, upload file, create subfolder, open folder).
Add some UserGroup related classes.
Add some page object methods.
Initial commit (will be continued with the exact test case)

refs: MBL-16890
affects: Student
release note: none

2023-07-28 12:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2b851fb9-7c4e-4d32-a301-4efa747732e6%2Fartifact%2F14a4b66975c6192a%2Fp%2F996957e93fc6590fe6b93edd4488f350&size=150x150">

2023-07-31 07:52 UTC, kristofnemere requested changes

2023-07-31 07:52 UTC, kristofnemere commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt
> +    fun assertTitleCorrect(group: GroupApiModel) {
This method should be in GroupBrowserPage

2023-07-31 07:52 UTC, kristofnemere commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/usergroups/UserGroupFilesE2ETest.kt
> +    private fun setupFileOnDevice(fileName: String): Uri {
We have this method already somewhere else, I would put that in a util class and use it from all the other places

2023-07-31 09:35 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt
> +    fun assertTitleCorrect(group: GroupApiModel) {
Sure, and so the other Group related methods. Nice catch, thanks.

2023-07-31 10:16 UTC, tamaskozmer approved these changes

2023-07-31 11:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe25c1b4b-0053-4cd1-8081-a11e671860d1%2Fartifact%2Fd514237716c2b045%2Fp%2F1a60d52cdc7440fbcc27013aa6269799&size=150x150">

2023-07-31 11:43 UTC, kristofnemere approved these changes

2023-07-31 12:47 UTC, merged