[MBL-16915][Student] Quizzes screen letter grade only
instructure/canvas-android pull request #2085
Opened 2023-08-02 13:29 UTC by kristofnemere

Test plan: quiz points should be hidden if letter grade only.

refs: MBL-16915
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

2023-08-02 13:33 UTC, kdeakinstructure approved these changes

2023-08-02 13:37 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff469f699-e106-49fb-95b2-ac3cb71e0b5f%2Fartifact%2Fcde1b2f89c160123%2Fp%2F32d35b2e454a6f4dcd22309c849610ec&size=150x150>

2023-08-02 13:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F923343fe-fd94-4bda-bb8e-bc362cb4f882%2Fartifact%2F2e103a4d7a90878c%2Fp%2F6d3bb6a2eca434b17e0a8f7c4e8812af&size=150x150>

2023-08-02 13:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc82ff5ca-2c53-4350-9260-421930a99083%2Fartifact%2F8dc9c2935746c663%2Fp%2Fbedb55ae136b045bbc16dacc5bef16eb&size=150x150">

2023-08-02 14:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F76b0c8cc-404b-43bb-8606-573803ce1e70%2Fartifact%2Fbba4b4d60914019d%2Fp%2Fdae3b66054928269ceeca39d2df01b38&size=150x150>

2023-08-02 14:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F25ada1be-76f7-49ab-a5e6-965d1324ea1d%2Fartifact%2Fa8e46b483f533428%2Fp%2F1f59351517652cbc6151302eb0afcb6c&size=150x150">

2023-08-02 14:58 UTC, kdeakinstructure commented
QA 👍

2023-08-03 11:10 UTC, tamaskozmer requested changes

2023-08-03 11:10 UTC, tamaskozmer commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt
> +                request.successResponse(quizzesForCourse.orEmpty())
What's the reason for this change?

2023-08-04 09:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcdcb1184-66c5-4f14-bd55-a2e2c3b88a68%2Fartifact%2Fae2d6c6c819ac6ed%2Fp%2F6310039dcdbd689f6e7cdec86738dcc0&size=150x150">

2023-08-04 09:47 UTC, tamaskozmer approved these changes

2023-08-04 10:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9e5ca51d-f650-4339-95cd-3009bc3c9173%2Fartifact%2F1e449f2cd36fbb47%2Fp%2Fe855cddcd1817c71c3cb4f1f16d79a84&size=150x150>

2023-08-04 10:33 UTC, merged