[MBL-16941][Student][Teacher] - Introduce SearchablePage interface
instructure/canvas-android pull request #2090
Opened 2023-08-04 12:01 UTC by kdeakinstructure

Introduce SearchablePage interface in Teacher and Student
Refactor existing tests.

refs: MBL-16941
affects: Teacher, Student
release note: none

2023-08-04 12:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4f62136c-1c02-4345-8815-0755b14d095b%2Fartifact%2F63aaa0490fdf6bdd%2Fp%2F26d2608c77b78a872644b80ed6898cdc&size=150x150>

2023-08-04 12:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3c841f06-72ac-47fa-9f82-29597aa86e38%2Fartifact%2F098653f7629f472e%2Fp%2F7f19a75be4bf6a93f1b3f0b13c1c32dc&size=150x150">

2023-08-04 13:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe69936a9-ab9b-4890-8f7e-62f4fb94ac9c%2Fartifact%2Fbc35959279569da9%2Fp%2Fa2a46394b92a6123bc687f4ec3ac5985&size=150x150>

2023-08-04 13:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F344b9533-bb00-4c30-9a1b-b724c46f0af6%2Fartifact%2F398fc3337d3e01a0%2Fp%2F03b61d221084b8192926da5aedb9670b&size=150x150">

2023-08-04 13:47 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/interfaces/SearchablePage.kt
> +interface SearchablePage {
Why do we need this interface? As far as I can see we still call the classes directly and not via the interface. If it's only to have the functions be named the same in every class I suggest only renaming the functions and not adding a layer for it.

2023-08-04 13:47 UTC, tamaskozmer requested changes

2023-08-04 13:47 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/interfaces/SearchablePage.kt
> +interface SearchablePage {
You can include this in the Espresso module to avoid duplciation.

2023-08-04 13:47 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt
> -class QuizzesE2ETest: StudentTest() {
Why is this implemented here?

2023-08-04 14:56 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/interfaces/SearchablePage.kt
> +interface SearchablePage {
Good catch, thanks!

2023-08-04 14:58 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt
> -class QuizzesE2ETest: StudentTest() {
There is a separate small ticket  (MBL-16953) in which I will implement the search for this page as well, when we will figure out why the quizzes E2E test is not working on our emulators.

2023-08-15 10:28 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1f69f1e8-3f68-4d5f-b283-a5a82ec16d51%2Fartifact%2F09d5e6e96ccf6e9f%2Fp%2F9ed208353a1b5c59ba0e34ea29705748&size=150x150>

2023-08-15 11:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F98b88ec0-54a1-47c0-831c-d0a435aa8b81%2Fartifact%2F07db85bed7232adf%2Fp%2F9bb67679ff6c5051177b6d09bff4351c&size=150x150>

2023-08-15 11:13 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9b3bb460-48aa-4b27-a048-ce9daaea6cc7%2Fartifact%2Fbdfbbedd54508773%2Fp%2F6e1947b833d9a6e6f6f6bf45862742d2&size=150x150">

2023-08-15 11:20 UTC, hermannakos requested changes

2023-08-15 11:20 UTC, hermannakos commented on automation/espresso/src/main/kotlin/com/instructure/espresso/Searchable.kt
> +        onView(withId(searchButtonId!!)).click()
You should use let here, so it doesn't crash.

2023-08-15 11:24 UTC, tamaskozmer approved these changes

2023-08-15 11:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F423eb95f-c747-43b5-b888-c712e4d04928%2Fartifact%2F1c6843fb66cfc087%2Fp%2F8c217a9c2697548e43db195e98d8daf3&size=150x150>

2023-08-15 11:41 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdc30459d-aa9b-4872-9bae-38dbbb15c66c%2Fartifact%2F8a42f3330ea632fe%2Fp%2F9d19f0ea146358a3f88a8a355a415da8&size=150x150">

2023-08-15 12:36 UTC, hermannakos approved these changes

2023-08-15 12:46 UTC, merged