[MBL-16879][Student] Sync course files
instructure/canvas-android pull request #2106
Opened 2023-08-16 11:30 UTC by hermannakos

Test plan: Sync course files. 
- The file structure should always be visible, but only synced items are enabled.
- Only selected files should be synced.
- If full file sync is enabled newly added files should be synced as well.
- Removed files should be deleted from the device as well.

refs: MBL-16879
affects: Student
release note: none

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode

2023-08-16 11:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1476b0dd-88e1-4467-bdd4-c40e2b640aec%2Fartifact%2Fb236d2493d3413a9%2Fp%2F574010f47c0d569cc18c78e79607119e&size=150x150>

2023-08-16 11:52 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff8a000b5-ed28-4a81-b443-44e9f68f4730%2Fartifact%2F5804c0116177eb90%2Fp%2Fce9b6f45801e3b86cee1ab85fc2bc73c&size=150x150">

2023-08-17 11:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fbcaeb675-a127-44dd-84f3-d26ba7b44f4b%2Fartifact%2F5fc67235d0e63d2a%2Fp%2Fcbdf7337302a830d25785103d9d65ab1&size=150x150>

2023-08-17 12:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffabbf7e1-4532-491f-930d-ebd6e5dbc390%2Fartifact%2Fe98cdbe90e8c9ab4%2Fp%2Fc1192b30edb80df68188c55ee6edaa66&size=150x150">

2023-08-18 13:39 UTC, tamaskozmer requested changes

2023-08-18 13:39 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/CourseFileSharedRepositoryTest.kt
> +class CourseFileSharedRepositoryTest {
It would be nice to add tests for the other public method in this class `getCourseFoldersAndFiles`.

2023-08-21 07:20 UTC, kristofnemere requested changes
Good job, I found a few thins while testing:

- Unexpected error occurred when there’s no file
- Deleted files not getting removed from device
- com.instructure.student.tasks.StudentLogoutTask#removeOfflineData we need to remove files also on logout

2023-08-21 10:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F981d78cf-e4b9-4d21-8403-3665a8aa4c92%2Fartifact%2F073ea58348e230cd%2Fp%2F53735622f2d558142c175c55c156694a&size=150x150>

2023-08-21 10:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8135b310-f9b7-4792-8c09-1205e375b804%2Fartifact%2Fc26a1980c736165b%2Fp%2Fc2474960509abbc332ed267a30325055&size=150x150">

2023-08-21 14:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fad38c050-a9a8-47dc-8e57-a02bf27850c1%2Fartifact%2Ffebfa4de8bda57be%2Fp%2Ff5c1d23dc3b99ecfbb9dae282120cda9&size=150x150>

2023-08-21 14:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8336fec7-9aa8-49f2-ad5e-d4f2be5d2012%2Fartifact%2Fbc79b756d8440879%2Fp%2F611924aa1a4b245e34c97cbe51e69932&size=150x150">

2023-08-22 08:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F09713d2d-3e4d-49d0-bbcd-d157198754f4%2Fartifact%2F71249e59ec485ce0%2Fp%2F8f08c4f8404caf26edf21c29739deaad&size=150x150>

2023-08-22 08:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F206fd8d7-d5a6-4db2-a1d1-44f4f80f5695%2Fartifact%2F15a92ee97baba140%2Fp%2F42a1513a84c969a6f2dd2762dfd58e5b&size=150x150">

2023-08-22 12:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc5986a42-c389-479f-a4b5-2465519cae99%2Fartifact%2F99bb33b2b6a73bb5%2Fp%2F02b7f5a0c84e4990875d42aa14634a47&size=150x150>

2023-08-22 13:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F505d4fab-3855-41ae-b197-5335ccf2f2dc%2Fartifact%2F3eb89d2b97fd672e%2Fp%2Feb1e98fa151ae3574343ce65956bd0ad&size=150x150>

2023-08-22 13:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa546c6f3-ccba-44e0-be3f-ececdbb70225%2Fartifact%2F01221cc365467a34%2Fp%2Fbd7e3e0beaa82d086970287ee7dab3ac&size=150x150">

2023-08-22 14:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F77eaca04-feb0-4d04-a4b7-e0b3ca49bf3f%2Fartifact%2F62abcaf3d0be5413%2Fp%2F695e392ec8230673fee48a943a467c65&size=150x150>

2023-08-22 14:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5208ce75-14f5-4dca-a14f-90de345f73d1%2Fartifact%2Fe972c8a780240884%2Fp%2Fb47fe3a5ba27f8b331fd0f4fe5399d7a&size=150x150">

2023-08-22 15:18 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe3c03946-2f1a-4db5-83c6-5e4b072d2615%2Fartifact%2Fcc38272a4a6da4d9%2Fp%2F67172dd9d67f3004013c6a239a53d24f&size=150x150>

2023-08-22 15:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff7d85542-971c-4a40-b6c9-58f360c3de99%2Fartifact%2F4f10ae8f20a3bf8c%2Fp%2F5502da547d05724abef40a0b47c93105&size=150x150">

2023-08-23 09:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F17697dd2-4625-458b-ba1b-1aa9beed24ce%2Fartifact%2Fad15c0c63d1b2985%2Fp%2F91a4ed95e289b9c32b38289e52b0055a&size=150x150>

2023-08-23 12:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F490b5ba2-f035-42db-83f0-9442899c85c6%2Fartifact%2F91d5720f0274b041%2Fp%2F7ea7ef2f7d455b046fe6b3523faa6149&size=150x150>

2023-08-23 12:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F71414bb3-2c99-4004-9301-0d47931fe66c%2Fartifact%2Fd553f8e77ed6a6d9%2Fp%2Fb3d92d8b06c86353cc0b9994d9a06689&size=150x150">

2023-08-23 13:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2d6076d8-a561-486f-8518-a3712fac3631%2Fartifact%2F446858e8f8455510%2Fp%2F94092bc8458e09571ed15bcfc47d66a4&size=150x150>

2023-08-23 13:47 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5ab95110-db1b-4429-8362-c224b0f38081%2Fartifact%2Fc1c92873d8bedf64%2Fp%2F0d954d989185b70c7e5d71ba60d49778&size=150x150">

2023-08-24 07:12 UTC, tamaskozmer approved these changes

2023-08-24 08:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F026d0c8d-7118-45ee-9199-adf9530f353c%2Fartifact%2Faad8caaf2d0bf78c%2Fp%2Fbfb73cd18da5dec8ae89873cbe163714&size=150x150>

2023-08-24 08:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff52295d1-50e2-491d-a675-ea6cf9f030a9%2Fartifact%2F70dff5d4a4d81e3a%2Fp%2F0ea8de9dc264b675eaf82efd0953635d&size=150x150>

2023-08-24 08:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F21f5dc74-6dc3-45a7-9954-9d2381451973%2Fartifact%2Fd17a074f94b8f2b7%2Fp%2F3d32a73d16ab831656326f78786a3a92&size=150x150">

2023-08-24 10:56 UTC, kdeakinstructure approved these changes
QA 👍  Great job!!!

2023-08-24 10:58 UTC, merged