[MBL-16965][Student] - Separate announcement list page from discussion list page
instructure/canvas-android pull request #2125
Opened 2023-08-29 12:24 UTC by kdeakinstructure

Inherit AnnouncementListPage from DiscussionListPage to make code readable.
Rename editAnnouncementPage to AnnouncementDetailsPage, since it's the detailer page.
Some other minor refactors.

refs: MBL-16965
affects: Student, Teacher
release note: none

2023-08-29 12:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F419f76f2-f020-4990-9327-e436baf6d231%2Fartifact%2Fe5a8ea73db9ce3f6%2Fp%2F84568bc645f9f2027d9c5b12fc569b5e&size=150x150">

2023-08-30 08:43 UTC, tamaskozmer requested changes

2023-08-30 08:43 UTC, tamaskozmer commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AnnouncementDetailsPage.kt
> +class AnnouncementDetailsPage : BasePage() {
This is not necessarily correct. As you can see most of the actions on this page are indeed on the edit announcement screen. The only one which is not is the `openEdit`. It's a bit strange but I can live with that, since it navigates to the edit screen. However the better option would be to leave this as is, remove this one function and use the `DiscussionDetailsPage` (which is the same as an announcement) and use the `openEdit` function from there.

2023-08-30 10:13 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AnnouncementDetailsPage.kt
> +class AnnouncementDetailsPage : BasePage() {
We have discussed this via Slack.

2023-08-30 10:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb8957cb9-1716-46cf-b6e4-c9cdd25538ca%2Fartifact%2F21ad27f264d1010e%2Fp%2F8caba9560c158084ab5114a9c0e34815&size=150x150>

2023-08-30 10:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6b8e6d09-0da2-441e-8097-fb2f92022ef0%2Fartifact%2F7e5d8681f42b5aa8%2Fp%2Fb585b2098db484eff8e226a66c97a978&size=150x150>

2023-08-30 10:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc1410c3d-3920-4d8b-a6a8-321c8655ec93%2Fartifact%2Fc4969789e5f512e8%2Fp%2F3b60ce074526e035a1aa3e866e3fd6fe&size=150x150">

2023-08-30 11:41 UTC, tamaskozmer approved these changes

2023-08-30 11:54 UTC, merged