[MBL-16948][Student] Sync progress
instructure/canvas-android pull request #2142
Opened 2023-09-07 14:16 UTC by hermannakos

Test plan: See ticket and design. 

refs: MBL-16948
affects: Student
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product

2023-09-07 14:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4c40e0be-dbad-4cd9-9207-f2cca8391606%2Fartifact%2F8e1e32e368ccb0af%2Fp%2F905ef9f093479530251018eb11787669&size=150x150>

2023-09-11 10:37 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0315927c-ed63-4a32-a289-6f15300bd396%2Fartifact%2F1cb3219c469ed1cf%2Fp%2F42045e93f2b7f77d5324d48a7e9bf023&size=150x150>

2023-09-11 11:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe6fac3f0-8fb7-489b-bd43-303472553e73%2Fartifact%2F4fcb3498f1894a09%2Fp%2Fc73ade7fd2ecb536ac43ad514eb69c1e&size=150x150>

2023-09-12 09:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff9d7e91d-2b7a-4ada-857b-8cf56dc3c070%2Fartifact%2Ffd3d5ff36ec94f37%2Fp%2F375093323424636295fdedac1411732e&size=150x150>

2023-09-12 09:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F224f0b3d-c5b5-449f-b2b8-d1735e279ff5%2Fartifact%2Fa51bbc3a6b110f94%2Fp%2Ff247c0449b9f2423e9f64d69b34023a4&size=150x150">

2023-09-12 09:57 UTC, tamaskozmer requested changes

2023-09-12 09:57 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +                _events.postValue(Event(SyncProgressAction.Back))
Do we need to go back when clicking retry?

2023-09-12 09:57 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +                ?.fromJson<CourseProgress>()?.fileSyncData != null
Why do we need this check? What if we don't sync any files?

2023-09-12 09:57 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +                val tabSize = courseProgress.tabs.count() * 100 * 1000
It's a bit strange that we use 1000 instead of 1024 here. I guess the reason is that we use the same for file sizes in `NumberHelper.readableFileSize` to match the web behavior. We might as well add a comment here, to make it clear.

2023-09-12 10:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb3173ac7-2752-4ea4-a2df-96844b0c271b%2Fartifact%2F7f8aa9befda0ba39%2Fp%2F5168cf4002d40f141774dec03b012049&size=150x150>

2023-09-12 10:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fadbdfc46-7131-4444-b83b-c47c8069c322%2Fartifact%2Fec68186dd1e85107%2Fp%2F8e855e8d433156b22711f3ca695bb134&size=150x150">

2023-09-12 10:10 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +                ?.fromJson<CourseProgress>()?.fileSyncData != null
Until the files are started the fileSyncData is null. If we don't sync any files the fileSyncData is going to be an emptyList().

2023-09-12 10:10 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +                _events.postValue(Event(SyncProgressAction.Back))
It is based on the design.

2023-09-12 10:11 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +@SuppressLint("StaticFieldLeak")
For the ApplicationContext. Studio is worrying about leaks.

2023-09-12 10:13 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +                val tabSize = courseProgress.tabs.count() * 100 * 1000
We are using kB instead of KiB, but sure, I add a comment.

2023-09-12 11:09 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
> +@SuppressLint("StaticFieldLeak")
Strange, I don't get these warnings, even when running code inspection on the class.

2023-09-12 14:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F224a563a-24b5-471a-b826-98127e945625%2Fartifact%2Ff829a2ea6ebd6e2b%2Fp%2F8d701feefb92d729ea01ebca3ceae912&size=150x150>

2023-09-13 10:07 UTC, tamaskozmer approved these changes

2023-09-13 10:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc6d611fb-5b82-4f99-ac8f-77dc2ea67b41%2Fartifact%2F45de48e94483a584%2Fp%2F2bbd64987a5f33d636ae17eeacaaadc3&size=150x150>

2023-09-13 10:11 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F3bbb442eee902883%2Fbuild%2F163fd2f5-2238-4256-a223-a2cd4a9ec4bf%2Fartifact%2Fcec5f036e5ae9269%2Fp%2Fcdfb1603c6a73a17974eb898f9cd1771&size=150x150">

2023-09-13 10:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb5710442-c9f4-48eb-997d-ea88a2b640fa%2Fartifact%2F9f9b0ffda5b4b17d%2Fp%2F746c75b7d3c6c2f3a80856c00e1851f6&size=150x150>

2023-09-13 10:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F87ec5e6e-8b56-448b-995f-50bb918e0099%2Fartifact%2F85c195fca94a5d63%2Fp%2F1e6cccd10fae7e9c33d9540d9b0a01ec&size=150x150">

2023-09-13 11:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4ab6659b-b172-4dc7-ae6a-971ff927d034%2Fartifact%2F15945e5055204787%2Fp%2F5c65104cf451a1a368f85a2f447574a6&size=150x150>

2023-09-13 12:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F17f27ae2-a3dc-459a-a8d3-cd2c340fb08e%2Fartifact%2F856dbea22e46c968%2Fp%2F0f3c3a3b8cc105abaaa55549b0a717be&size=150x150">

2023-09-13 12:44 UTC, kdeakinstructure approved these changes
QA 👍

2023-09-13 13:50 UTC, merged