[MBL-16905][Student] Offline File Details
instructure/canvas-android pull request #2148
Opened 2023-09-11 14:18 UTC by domonkosadam

Test plan: Steps are in the ticket

refs: MBL-16905
affects: Student
release note: none

## Checklist

- [x] Tested in light mode

2023-09-11 15:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F92243eff-7f33-4bbf-a794-9af60c082c70%2Fartifact%2F9413b87abcb9b109%2Fp%2F9bf43e847bba86806e9feca0e2419675&size=150x150>

2023-09-12 09:31 UTC, hermannakos requested changes
Great job! Just some minor things to make it cleaner.

2023-09-12 09:31 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/files/details/FileDetailsFragment.kt
> +        return networkStateProvider.isOnline().not()
You don't have to inject the NetworkStateProvider for this. you can use the repository here to check if we're online.

2023-09-12 09:31 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/files/details/FileDetailsFragment.kt
> +            binding.downloadButton.visibility = View.GONE
You can use the View::setVisible extension here.

2023-09-12 09:31 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/files/details/FileDetailsLocalDataSource.kt
> +    override suspend fun markAsRead(canvasContext: CanvasContext, moduleId: Long, itemId: Long, forceNetwork: Boolean): ResponseBody? {
You're always calling the networkDataSource for this call, so you this localDataSource doesn't need to have it at all to keep it clean. You could just remove it from the interface and just add it to the networkDataSource.

2023-09-12 12:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Faa78d7fd-48e2-4e64-808e-abbc1185a103%2Fartifact%2Fe97e82e11cb88597%2Fp%2Faaf1af1c1297ab3db9fd0d3e1fb65d50&size=150x150>

2023-09-13 08:39 UTC, hermannakos requested changes

2023-09-13 08:39 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/files/details/FileDetailsFragment.kt
> +            binding.downloadButton.setVisible(false)
You could pass the condition to the setVisible instead. `binding.downloadButton.setVisible(!isOffline())` or even better, making not inverting the repository isOnline and using that instead like `binding.downloadButton.setVisible(repository.isOnline())`

2023-09-14 09:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F27a25e76-fa58-4d19-88cd-bab4441ee182%2Fartifact%2F7c864d45e78e4d9c%2Fp%2F620a6dbca6cbaa443834cc799cd91ea1&size=150x150>

2023-09-14 09:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F675540ca-caca-4e22-a1e5-b9642c7c65cc%2Fartifact%2F2e4631cbc2be1b97%2Fp%2F6c5147036c4559730a7c9edcaa36d5c9&size=150x150">

2023-09-14 12:00 UTC, hermannakos approved these changes

2023-09-14 14:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4cd95400-b29d-41f4-81cc-dd3666e681d9%2Fartifact%2Fed1b1a44ba888d00%2Fp%2Fde958bd54a01f67e65f5e62c507636cc&size=150x150">

2023-09-18 21:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F106b7294-5c91-4bc0-9ecc-329390330bbb%2Fartifact%2Fc7444afee5006534%2Fp%2Ffdcf7e6e2fb34144406ffdaea4b7529e&size=150x150">

2023-09-19 15:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff57d3263-81bd-4310-958c-ea54cfdb9cf4%2Fartifact%2Ff0a51e08edf940d4%2Fp%2F9805c7e0bd9de9ae943f2d63cde693dd&size=150x150">

2023-09-20 13:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F55485ff1-cff1-45b6-9256-cdfd1391d21f%2Fartifact%2Fdbeb97c0a6ab1b8a%2Fp%2Fb3d04ac45727e84c85c6649074afd287&size=150x150>

2023-09-20 14:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff9aaed0c-e192-4600-bfa1-afe4f4333488%2Fartifact%2Fe3d455da28e91491%2Fp%2Fbfc01ffa83bbd5c62ff6837858042bd2&size=150x150>

2023-09-20 14:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc515d9f5-fd6e-46cd-bb89-580e2f6b4d15%2Fartifact%2F2f222c4d7d4d92e4%2Fp%2Fb7a610fda1c49a1a5db784159a7693d5&size=150x150">

2023-09-21 07:24 UTC, tamaskozmer requested changes

2023-09-21 07:24 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/modules/progression/ModuleProgressionRepository.kt
> +    suspend fun getSyncedFileIds(courseId: Long): List<Long> {
You should write tests for this.

2023-09-21 07:24 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/modules/util/ModuleUtility.kt
> +    ): Fragment? {
I think you can move the whole logic into this function. We only call this in one instance so the creation block  is always the same.

2023-09-21 07:24 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/modules/util/ModuleUtility.kt
> +            createFileDetailsFragmentWithOfflineCheck(isOnline, course, item, syncedFileIds, context) {
You can also add a test for this logic like for the other screens.

2023-09-22 07:46 UTC, kdeakinstructure approved these changes
QA 👍  (with the conclusion of our meeting on Wednesday that we leave it as it is now, so the user have to select the exact module items, for example files as well, if the module item is a file) to be able to see it offline within the module.)

2023-09-22 07:58 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb0c9efdb-c953-4529-a62c-351f532705cc%2Fartifact%2F02563160fed4e3dc%2Fp%2F9f642eb308ae2ac105282c5187e7526b&size=150x150>

2023-09-22 08:35 UTC, tamaskozmer approved these changes

2023-09-22 09:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6c87cbe8-594b-4c1f-98c7-1b0b2355a6d4%2Fartifact%2Fac87a4c953a610c9%2Fp%2F326a6659c436994ae709c81db8397b73&size=150x150>

2023-09-22 09:51 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Faefe7fa0-8773-4d72-9a8c-dc5c8d20c999%2Fartifact%2F4a5e6986e025cc83%2Fp%2F36dba05a25d538fbb1008ed2a3e06edf&size=150x150>

2023-09-22 10:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F857d41ca-c08a-4295-9565-d736e4b1df4a%2Fartifact%2Fba20391ece8896b1%2Fp%2Fd17fc78a6d53e0eca9c0b6d12a233b02&size=150x150>

2023-09-22 10:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4b37d4c2-9d51-4c22-8315-34f751936889%2Fartifact%2Fd2a20635358ed578%2Fp%2F8a6f5ed6d7db2839e8174a164bfd6efe&size=150x150">

2023-09-22 10:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd7106d2f-5af4-4099-a685-86b6f7847853%2Fartifact%2F2fbe8f6bf6c55003%2Fp%2F43f66bacbf310995a4d4e901e9b5cbfc&size=150x150>

2023-09-22 11:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdf10b648-e51c-44bc-ae8c-5d2d1d98ca9f%2Fartifact%2F4660e0127db3bc9c%2Fp%2Fedd7296301f80c5a6bf60a1f49ee3465&size=150x150>

2023-09-22 11:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F37180b4f-72de-48e8-8002-36b6b935f1de%2Fartifact%2F6ee2175ee955c2c3%2Fp%2F7927bee318118474619c2fe996a5e408&size=150x150">

2023-09-26 12:29 UTC, merged