[MBL-17035][Student] - Remove unnecessary whitespace from course grade text in course cards
instructure/canvas-android pull request #2149
Opened 2023-09-11 14:48 UTC by kdeakinstructure

Fix minor dev maintenance issue by removing unnecessary course grade white space character from course card.

refs: MBL-17035
affects: Student
release note: none

2023-09-11 15:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F54f52926-ff6c-4996-a804-015442669dcb%2Fartifact%2F2935f9252ffb0fb9%2Fp%2Fe25065d1cd65571288f68310be7dd43e&size=150x150">

2023-09-12 08:19 UTC, hermannakos requested changes

2023-09-12 08:19 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/holders/CourseViewHolder.kt
> +                textView.text = "${if(courseGrade.hasCurrentGradeString()) courseGrade.currentGrade + " " else ""}$scoreString"
I'm not a fan of concatenating strings when we're already using patterns. It would be nicer if we moved the condition out of the pattern.

2023-09-12 09:58 UTC, hermannakos approved these changes

2023-09-12 10:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F357cb2c3-50c9-4444-92ab-2d6631b26477%2Fartifact%2F77ffc2c8ae5ea9e5%2Fp%2Faa3b99a3613f0847fea3ed70098bff08&size=150x150">

2023-09-12 11:36 UTC, merged