[MBL-17085] Offline Discussion Details
instructure/canvas-android pull request #2182
Opened 2023-10-06 12:39 UTC by domonkosadam

Test plan: Steps are in the ticket

refs: MBL-17085
affects: Student
release note: none

## Checklist

- [ ] Tested in light mode

2023-10-06 12:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff5bb6cf0-ea74-4ba3-8318-0b06197b61e6%2Fartifact%2Ffc22460bdcab4533%2Fp%2Feb7874464a594b3371d9b5c03d366d33&size=150x150>

2023-10-09 09:45 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F80eaa63e-1937-4ad4-9bb7-f048fe26909a%2Fartifact%2F67ad8e2a7dcae482%2Fp%2Fae04445b3f91b290959d750e23d5f430&size=150x150>

2023-10-09 11:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2d95c86d-d2db-45b0-92a8-b9c059c83062%2Fartifact%2Fd4d7a6e94afd4ed5%2Fp%2F83a19c4f9a9a78364894771ec584de34&size=150x150>

2023-10-09 12:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb049e159-0cbb-462d-ad12-d59512c4c614%2Fartifact%2F786448e6b5874adf%2Fp%2F541cf12ee0060387bc4c7f731d6e92f0&size=150x150>

2023-10-09 12:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbce7ba50-73f4-428b-8433-7e0c683b0ed0%2Fartifact%2Fa2d7440fced77296%2Fp%2Fe1a4d054e962a584847d9f34752fa0fc&size=150x150">

2023-10-09 12:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0b870d30-717e-487d-a3dd-2e668beedb3b%2Fartifact%2F3ba6e759e44bfbb6%2Fp%2Fbf7066947f655ffdadfc421a5d5268bc&size=150x150>

2023-10-09 13:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F71b0dcff-3c00-4de8-8c0c-87a2ea9dbf56%2Fartifact%2Fca3d247e5063ac7d%2Fp%2F4c2e53a2674337fb56287df4f661c537&size=150x150">

2023-10-09 14:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1143bbe5-7b56-459e-b80d-fdb55abdbe51%2Fartifact%2F9b53cad1b1aeca63%2Fp%2F55c1ea379b6c12965e75aa3cdab608e3&size=150x150>

2023-10-09 14:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F39ce5a99-8aea-422d-adba-d589d6e3f7e2%2Fartifact%2F8090106427186513%2Fp%2F936f30f95226320de38b2853a87f2668&size=150x150">

2023-10-09 15:02 UTC, tamaskozmer requested changes

2023-10-10 09:22 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
> +                val html = DiscussionUtils.createDiscussionTopicHtml(
I just checked and this might be the issue for the comment not loading correctly. Adding this block will have the same effect as the `inBackground` function:
```
async(context = Dispatchers.Default) {
                }.await()
```

2023-10-10 09:22 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
> +                discussionTopic?.views?.forEach { it.init(discussionTopic!!, it) }
I would revert this as well. See my other comment.

2023-10-11 08:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff20b8a9e-2072-49cb-b1a5-f670774f02a6%2Fartifact%2Fcee8914df47b3515%2Fp%2F8af3fb91298642d978dc6b2074b54ded&size=150x150>

2023-10-11 08:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3147b371-04ad-4cde-8374-baf30725ef13%2Fartifact%2Ffaaaa9edb4114bb2%2Fp%2F597c48ab211e9c25d517247a8b39d5c7&size=150x150">

2023-10-11 14:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F265a5ade-4ebc-4133-b0e2-acec244c40c1%2Fartifact%2Fe9c6ad6d2d90611f%2Fp%2F3107f0fe88cbac397a2b3be2d8f7da30&size=150x150>

2023-10-12 13:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F29735a91-527d-48c6-be4e-14500a9abaa9%2Fartifact%2F7161abb4feb56944%2Fp%2F4e6d04630d8ac06b3b1560624512b796&size=150x150>

2023-10-12 13:47 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdb53692d-714f-4c3b-9282-6afd31fc812d%2Fartifact%2F456985c0a16b72d7%2Fp%2Fddfa9c6459c526ccf2d0e26f4456013c&size=150x150">

2023-10-12 14:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd2677579-32c5-423a-8c65-efd35523b5d6%2Fartifact%2F411ad8ec0b4a99e3%2Fp%2F293787ffa75c5c55c810d6a5d8bace57&size=150x150>

2023-10-12 14:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd01ccfe3-9cd6-4665-847c-24f2c22b5650%2Fartifact%2Ff86387aad73ead84%2Fp%2Fa41c5c214afa7d1a8a2e962046134d3d&size=150x150">

2023-10-12 15:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6420cbce-edc8-4f0e-977b-2ecf267c20bb%2Fartifact%2F807b088631078e17%2Fp%2F0a8111ee500134b94ea9102306e7fb4d&size=150x150>

2023-10-12 15:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F60f9ec87-c177-490b-925d-c7c05bf6e969%2Fartifact%2F6b40089763c092b7%2Fp%2Ff487ab7a6bcb70ee29117d94ddc02dae&size=150x150>

2023-10-12 15:57 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F33008491-410f-424d-80da-74ec69aa38bc%2Fartifact%2Fe7002ad6ef7a087e%2Fp%2Fd56a7553e72f8593aecdf700bf1dd271&size=150x150>

2023-10-16 08:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2b59555d-85be-455e-9775-951a4c4f8daf%2Fartifact%2F0c1a5dd2ac8662ab%2Fp%2Faaac9395468d587db4116ca9bd6f321b&size=150x150>

2023-10-16 09:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdf2b27c0-518d-453b-bc31-230fe6bbcae6%2Fartifact%2F99e148ae13717cd0%2Fp%2F98e6ae28dcfb66b579baedee12b9ad35&size=150x150>

2023-10-16 10:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7ed0e0ce-9844-4a83-8145-40bcfff3971b%2Fartifact%2Ffdfd0b9005be6aff%2Fp%2F0f1e7b72b1e62f0928191dfd6b52609d&size=150x150">

2023-10-16 11:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F606bb2de-10f4-4f8e-b313-6f78350ca851%2Fartifact%2F75e461f92531399c%2Fp%2Ffa8761a40136057e01d6e8f5c468fcc8&size=150x150>

2023-10-16 12:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa2aa18bf-033f-402a-905c-2f5a07e70f1f%2Fartifact%2Fe9201bfae407d04e%2Fp%2F371a0fac898416bd4a8990a3ed28ec4f&size=150x150">

2023-10-16 12:31 UTC, tamaskozmer approved these changes

2023-10-17 09:15 UTC, kdeakinstructure approved these changes
QA 👍

2023-10-17 09:18 UTC, merged