[MBL-17074][Student] Offline: Manage Offline Content
instructure/canvas-android pull request #2196
Opened 2023-10-17 07:09 UTC by kristofnemere

Test plan: 
- test empty states
- test loading
- test dialogs
- test storage info

refs: MBL-17074
affects: Student
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2023-10-17 07:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2e33da11-657f-4eed-a021-978c88a89002%2Fartifact%2F4a157236c85a37c2%2Fp%2Ffa70d7a93cce8036c07a77b34db5aff9&size=150x150>

2023-10-17 07:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb266170a-f094-48de-a58f-2ce134c36190%2Fartifact%2Fe594c17ff88935d2%2Fp%2Fb0f9dd819f972cc41f2f217fc298c4fc&size=150x150">

2023-10-17 08:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9fbf94e5-7273-49cc-91e0-7c4498612d2a%2Fartifact%2F09b2d9daf5031b00%2Fp%2F781c0a755b9fbe3f24c75c26a6e65f20&size=150x150">

2023-10-18 13:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F42e737dc-c790-40bd-a0f7-877db468ac4f%2Fartifact%2F686ad20c7d2a9b79%2Fp%2F94a400fde4a3e2a68debf81c182a3319&size=150x150>

2023-10-18 13:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff9a29218-b548-4fa2-85cd-d3f3e9e2293e%2Fartifact%2Fcd54609202b8c11c%2Fp%2F5f1c14e62cac0fd2c90381e7c38446be&size=150x150">

2023-10-19 13:04 UTC, kdeakinstructure approved these changes
QA 👍

2023-10-19 14:36 UTC, tamaskozmer requested changes

2023-10-19 14:36 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentFragment.kt
> +        dialog.setOnShowListener {
You can remove this and use the `showThemed` extension instead of `show`.

2023-10-19 14:36 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentRepositoryTest.kt
> +        coVerify(exactly = 1) { syncSettingsFacade.getSyncSettings() }
I would extend these tests with asserting the return value. If you just call the dao in the code, but don't return the result these tests will still pass.

2023-10-19 14:36 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModelTest.kt
> +        assert(viewModel.events.value?.getContentIfNotHandled() is OfflineContentAction.Dialog)
I am not strictly against this type of assert, but at least be consistent in the same test class and use the JUnit one.

2023-10-19 14:36 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModelTest.kt
> +        assert(viewModel.events.value?.getContentIfNotHandled() is OfflineContentAction.Dialog)
Same here

2023-10-19 14:36 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModelTest.kt
>          assert(viewModel.events.value?.getContentIfNotHandled() is OfflineContentAction.Back)
Same here

2023-10-20 14:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F05df553d-40f1-4367-bc66-195c145d26c0%2Fartifact%2F36da727179df2cc4%2Fp%2Fceb3a99c62686309f01dc14be6fb84b9&size=150x150">

2023-10-24 09:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F99e04033-590c-45ac-b274-a0e220dc56d6%2Fartifact%2Ffb61f9b3315afe9d%2Fp%2F9e7da442728db16b8fda6b31322d5d4d&size=150x150>

2023-10-24 09:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F78240264-64e6-4573-aa3b-7341b041c8dd%2Fartifact%2F5bda21c980f2f62e%2Fp%2Fae8ebd1b60094f54e87f974ce9d6c77e&size=150x150">

2023-10-24 10:13 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3f4500a8-ad54-4dd8-8260-1f2d177c8f32%2Fartifact%2F07ec330345c75512%2Fp%2F2af3ef9b241e1e532ffd6b3e4e593c8e&size=150x150>

2023-10-24 10:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff25ca309-5bc7-4659-8640-c7200d785c6d%2Fartifact%2F3a85bfb4dd1688c4%2Fp%2F8db33c06b252009df5664c453d920202&size=150x150">

2023-10-24 10:56 UTC, tamaskozmer approved these changes

2023-10-25 07:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F937b4f28-3b29-4cbf-84a0-ab5e20e29d68%2Fartifact%2F30eee5d386893735%2Fp%2F9f9b0ed727af8de1eb8b682fbdf637eb&size=150x150>

2023-10-25 07:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6fd4ed32-304c-4dfa-b1f8-d0f2342423d1%2Fartifact%2F556ea960c6e78d17%2Fp%2Fca42c1a9ffb97990dce1583de6a15627&size=150x150">

2023-10-25 07:37 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F65583c81-f453-4ded-abf6-306407ef17e1%2Fartifact%2F6bc1a3cc48215e0e%2Fp%2Fe334a50f52ef874fb2bdf19a7c994307&size=150x150>

2023-10-25 07:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F40095c07-2588-4201-b527-a66a1e479a8d%2Fartifact%2F84e7bc5735b3e22b%2Fp%2F1d3b11b6e5dcccc24b25700cff9cf709&size=150x150">

2023-10-25 07:56 UTC, merged