[MBL-17144][Student] Sync fixes
instructure/canvas-android pull request #2218
Opened 2023-10-26 11:36 UTC by hermannakos

Test plan: See ticket.

refs: MBL-17144
affects: Student
release note: none

2023-10-26 11:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F34660d52-3dd0-421c-906d-51ab898b6276%2Fartifact%2Fa1296c2e42eeffbe%2Fp%2F3c02ec101afd965684efbc9c54aa00d5&size=150x150>

2023-10-26 11:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fda654fd5-eac8-45ef-b1f0-25a9b4475d69%2Fartifact%2F840869383b97872d%2Fp%2F804299aa04036b071597b023569f55e8&size=150x150">

2023-10-26 12:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd0fa51f7-9bf4-4247-9c8e-371dab6b9fe8%2Fartifact%2F8be77d2c8f234663%2Fp%2F1d7d2cef226ca6659f425b4eafc934f3&size=150x150>

2023-10-26 12:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3f0dc652-402f-4f37-be69-e1eeb992a9e6%2Fartifact%2F869c5e64da9566ab%2Fp%2F1fbb41cce8e6761acdd188649a538561&size=150x150">

2023-10-27 11:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdc2bd186-df9c-47d5-965e-481b2f7b83c1%2Fartifact%2Fea1141c06a84c492%2Fp%2F1a6dcc3ca09b2682c934e8e6dee1a955&size=150x150>

2023-10-27 12:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa50e7944-dd41-4f6a-b715-ac4e078d768d%2Fartifact%2Fa3a776c37d01d375%2Fp%2F8f204da5096ab6adf6e1bf60d9b3e6a1&size=150x150">

2023-10-30 11:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4daf108f-0c93-4dfa-bcb1-7ffce891431e%2Fartifact%2F474262e0709b3ad5%2Fp%2F6c25a6d8806a4ba51ef58a7fbdb57739&size=150x150>

2023-10-30 11:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5dd00815-18dc-4973-8e5e-42fa74ab831b%2Fartifact%2Fe73e559a7eee51f5%2Fp%2F89b18773db4125cade5ce0b7dbafa7f6&size=150x150">

2023-10-30 13:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6f5bc76d-acaf-40ba-91fa-02ad7e720f88%2Fartifact%2F58c430878ef269d6%2Fp%2Fda251c5a7f3b45b80a44c4eacde785bb&size=150x150>

2023-10-30 13:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcf355611-2d6f-4ab7-9ab8-44adbcae4d4e%2Fartifact%2Fc69cba9e35c5250c%2Fp%2F4a9623c1a2ed2e7c1fd0a5be16f135aa&size=150x150">

2023-10-30 13:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff6089b3c-ad08-4c51-9ac8-5b6ed34ae799%2Fartifact%2Facc9aaeb636afae2%2Fp%2Fe68077741d7018c8809245751374893d&size=150x150>

2023-10-30 14:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F73a9053b-8183-4b4b-b477-30282888c420%2Fartifact%2F33fca47208cf8d59%2Fp%2Fd760c5275f1122d3e00670a8fb9e5870&size=150x150">

2023-10-31 11:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2fc41e92-505b-4386-96f2-1b1cc62d7004%2Fartifact%2F0a8743aeed0d39b1%2Fp%2F44dfec1178fa5cb05b8c8b821ec9d80f&size=150x150>

2023-10-31 11:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F60c42468-39ed-4950-92c5-6beb3646257d%2Fartifact%2F95950342e9a699b7%2Fp%2Ff52c55184157a381f9f17b6229ec3aeb&size=150x150">

2023-10-31 13:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F46da4792-661f-4835-809c-2b60d762ce61%2Fartifact%2Fa16bbf51f99fde33%2Fp%2Ffb82c01df00cd1b2b71faf43f28dc324&size=150x150>

2023-10-31 13:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff422e604-6cd7-417b-8c48-280aba0be99d%2Fartifact%2F2fd14dda82719fca%2Fp%2F2e039949a41d80e4bd88c18e59d196ce&size=150x150">

2023-11-03 13:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F18c796fc-9099-40f9-a6c5-490244991eda%2Fartifact%2F8749cc41c984e129%2Fp%2F866d2810af15323865732f4822de338a&size=150x150>

2023-11-03 14:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Faabfbd2b-fdb8-4e46-8a0a-07136f216f7a%2Fartifact%2Faf83cfb1cd18af33%2Fp%2F8a0c136e76f759d69cc3f8569a3c5084&size=150x150">

2023-11-06 09:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1d89b0ab-b15f-462e-9513-671301f611fe%2Fartifact%2Ffa400fc963b174a9%2Fp%2F66c0736dd5b6d7a48cb1cbf651ad0184&size=150x150>

2023-11-06 12:16 UTC, tamaskozmer requested changes

2023-11-06 12:16 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/FileSyncProgressDao.kt
> +    suspend fun findByRowId(rowId: Long): FileSyncProgressEntity?
It would be good to write tests for these 2 new functions

2023-11-06 12:16 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
> +    private val fileSync = FileSync(
Is it possible to inject this instead?

2023-11-06 12:19 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
> +    private val fileSync = FileSync(
We can only inject singletons workers. I would rather not use the same object for all the courses.

2023-11-06 14:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5902c34d-bd99-43cf-9a0d-ec44c883d292%2Fartifact%2F22a84836187fdb9a%2Fp%2Fef8c53c030200266dd7ad00f581c0f26&size=150x150>

2023-11-06 14:45 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4f0cb6ce-495d-4608-97bd-15619a734183%2Fartifact%2F9ad2857f3c117a3b%2Fp%2F988da4552a3c130ea4dbe55604e19706&size=150x150>

2023-11-06 14:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9c7d1225-deaf-40b6-ab0f-75f364b03f7a%2Fartifact%2F4f55a013c9a7d9e1%2Fp%2F4d3bb66ebda302009c443eb735a5a22e&size=150x150">

2023-11-06 17:18 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4bb6edf4-ebd8-43fb-8f3a-25346589b78d%2Fartifact%2F5bf76f5a29701920%2Fp%2Fba7ad69514d9fceac7323f5bd79c9401&size=150x150>

2023-11-06 17:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd29e7ba3-edd8-44f8-96b9-62d27317c49a%2Fartifact%2F72f63e0fe1053958%2Fp%2F8cc871d38e129b90a9ab8d8fd8b11077&size=150x150">

2023-11-07 09:51 UTC, tamaskozmer approved these changes

2023-11-07 10:50 UTC, merged