[MBL-17146][Student] - Workaround to stabilize flaky Inbox E2E tests
instructure/canvas-android pull request #2252
Opened 2023-11-15 15:10 UTC by kdeakinstructure

Workaround for flaky inbox swipe tests

refs: MBL-17146
affects: Student
release note: none

2023-11-15 15:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fbb057371-0cca-459c-a330-ddd52de68eee%2Fartifact%2Fb7a56bffe18faefa%2Fp%2F1ded7f2cb4a173e7c9e13eaac898f47d&size=150x150>

2023-11-15 15:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fffddc5ba-af47-4c98-8ac9-10e04f228d35%2Fartifact%2F1586094b434a6d20%2Fp%2Fedcb97dd84d3e9091caf5c8c79a4b13b&size=150x150">

2023-11-20 09:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F81a5aadf-bdd3-498c-9254-771bf4d7f52d%2Fartifact%2F0214fc397dc8a1d0%2Fp%2Fb63877266ad1f8a79ac369a50202f499&size=150x150>

2023-11-20 09:27 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F538ac460-ab70-4ab9-86d6-158fefcc3526%2Fartifact%2F69cf3ef04f602d58%2Fp%2Fd8cfc2ca59e70e1f8f35f9b97148809c&size=150x150">

2023-11-21 10:00 UTC, tamaskozmer approved these changes

2023-11-22 11:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F13921a98-aca8-49ed-bb44-bafd018fe39b%2Fartifact%2Fb53145d7277b3a78%2Fp%2Fca79cf72d18597027ecc03239323a7db&size=150x150>

2023-11-22 11:48 UTC, hermannakos requested changes

2023-11-22 11:48 UTC, hermannakos commented on automation/espresso/src/main/kotlin/com/instructure/espresso/TestingUtils.kt
> +    block: () -> Unit
We talked about an incremental delay here, that would also be nice to be added.

2023-11-22 11:48 UTC, hermannakos commented on automation/espresso/src/main/kotlin/com/instructure/espresso/TestingUtils.kt
> +        Thread.sleep(3000)
this delay will always happen, and not just when an exception is thrown. Also this is baked in, so the delay param is not used.

2023-11-22 11:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd02b5139-b504-40d6-bf3c-ce6af4ce675f%2Fartifact%2F33ad1cfcb6eee16b%2Fp%2F1975495e5c03e47a0a66015917d33468&size=150x150">

2023-11-22 11:53 UTC, hermannakos submitted a review, later dismissed

2023-11-22 11:53 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
> +            inboxPage.selectConversations(listOf(seededConversation.subject))
I don't think we need to retry all of this, only the assertion. We make the needed change, and only after that start the retry for the assertion only. This way we could undo previous changes made in earlier attempts.

2023-11-22 12:02 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
> +            inboxPage.selectConversations(listOf(seededConversation.subject))
We don't need for sure if it's the API response which is slow, or maybe the automation click/swipe was too fast, that's why I put that there, but I will refactor and we will see on nightly.

2023-11-22 12:46 UTC, kdeakinstructure commented on automation/espresso/src/main/kotlin/com/instructure/espresso/TestingUtils.kt
> +        Thread.sleep(3000)
This won't always happen, because the return does not let it to happen when it's the 'happy path'. The delay variable thing is valid, thanks.

2023-11-22 12:48 UTC, kdeakinstructure commented on automation/espresso/src/main/kotlin/com/instructure/espresso/TestingUtils.kt
> +    block: () -> Unit
I have made another version of this function which will have an incremental delay. I'll put both versions to the tests and we can monitor which one is more stabile, because it cannot be tested locally, because the API response is non-deterministical and sometimes it fails locally but sometimes not (there are periods in which it is failing for sure, but mostly it is passing simply).

2023-11-22 13:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F7d03326f-edd5-4f08-8f62-d2af598c5094%2Fartifact%2F3e751a1938d23b4e%2Fp%2F028c6adafef3f2a747cbb7c52e2220c4&size=150x150>

2023-11-22 13:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5bb08c63-9bc8-4571-82e6-18712b011769%2Fartifact%2F897cef1aca231936%2Fp%2F89512f770da08f4a34fc9538a3c8c2e1&size=150x150">

2023-11-22 14:28 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fafcb9ec8-f641-4680-a922-72ca3280e92b%2Fartifact%2Fb6fdb13951a20373%2Fp%2F49bbf29b311d38dc79713f8684afc3b8&size=150x150>

2023-11-22 14:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2c6626f5-f570-4516-ae9e-fd352d3f18f0%2Fartifact%2F662ab647b3591ce3%2Fp%2F9e810e75f116fdf5c52b65f12fbd1d59&size=150x150">

2023-11-22 14:47 UTC, merged