[MBL-14485][Teacher] Module items have no previous or next buttons
instructure/canvas-android pull request #2269
Opened 2023-12-04 13:54 UTC by kristofnemere

Test plan: 
- test opened from module list
- test opened from links
- if the asset is not part of a module it should be redirected
- on tablet all items should have the expand detail button in toolbar
- also changed the chevrons in the Student app
- test module item edit, delete and publish

refs: MBL-14485
affects: Teacher
release note: Added previous and next buttons to module items.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/1ee8641f-258d-46d1-8b04-e698543b0e8e" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/14c38000-0de1-4669-8433-c91bee8be6df" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2023-12-04 15:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7276dd84-9aec-4bcc-b3ce-acababd910cd%2Fartifact%2F225b8d97efd88d36%2Fp%2F9eb9c4425fabbd617053ff3d81f3007a&size=150x150">

2023-12-05 15:58 UTC, hermannakos requested changes

2023-12-05 15:58 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/progression/ModuleProgressionViewData.kt
> +    val onPageChangeListener: OnPageChangeListener = object : SimpleOnPageChangeListener() {
I think this logic should be in the viewModel and not the data. It would also be nice to make the data immutable and let the viewModel handle the state changes if possible.

2023-12-05 15:58 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/progression/ModuleProgressionViewModel.kt
> +    val canvasContext = savedStateHandle.get<CanvasContext>(Const.CANVAS_CONTEXT)!!
I'm not a fan of these handles with the nullability not checked and all. I would move these to be params of the `loadData` function, which would be called from the fragment rather then from the init block.

2023-12-05 15:58 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/progression/ModuleProgressionViewModel.kt
> +        "Page" -> ModuleItemViewData.Page(item.pageUrl.orEmpty())
There's an enum for these, `ModuleItem.Type`

2023-12-05 15:58 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
> +        routes.add(Route(courseOrGroup("/:course_id/pages/:page_id/"), PageListFragment::class.java, ModuleProgressionFragment::class.java))
One of these routes are not needed. Also above there is another one for the same route.

2023-12-05 17:54 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
> +        routes.add(Route(courseOrGroup("/:course_id/pages/:page_id/"), PageListFragment::class.java, ModuleProgressionFragment::class.java))
It is needd, that's how the redirect works when opened from an url and the asset not part of any module - the secondary class is different.

2023-12-05 17:55 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/progression/ModuleProgressionViewModel.kt
> +    val canvasContext = savedStateHandle.get<CanvasContext>(Const.CANVAS_CONTEXT)!!
It is checked in the validRoute method

2023-12-05 17:57 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/progression/ModuleProgressionRepository.kt
> +            if (it.itemCount != it.items.size) {
See the comment above this method: com.instructure.teacher.features.modules.list.ModuleListEffectHandler#fetchPageData

It might be not valid anymore, in my case the secondary endpoint never got called

2023-12-05 17:59 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/progression/ModuleProgressionFragment.kt
> +            setupPager(it.moduleItems, it.initialPosition)
I had a version where I created binding adapters for that, but I had to change it:
https://github.com/instructure/canvas-android/pull/2269/commits/b69cfd762cd838f655f0f398ddb9b322c3d9b838

Let's have a chat about it tomorrow

2023-12-05 18:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc7d045dc-0002-47dc-a0a0-0a583783287a%2Fartifact%2Fdeb0756fa61aa987%2Fp%2F548a22036079c2a9e18d9ad772594eae&size=150x150">

2023-12-07 12:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc3af377e-2ec5-424e-94a3-0fdc760971f5%2Fartifact%2Fae30f26fbcb4cee6%2Fp%2Ffda0d7d1b42974505abb4d2c718e886d&size=150x150">

2023-12-07 13:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6f3c7bbe-11eb-451e-bd9e-63a722cbf52d%2Fartifact%2F6943d18d6d6d18b6%2Fp%2F1a8fed0674776991acb71e85b5f54ebf&size=150x150">

2023-12-07 14:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc0e1aacb-acfc-4872-95f1-19650446383c%2Fartifact%2F0c5dca5fb25fe527%2Fp%2F4509b96f1571a46a4cfd1da34cd6a3d4&size=150x150">

2023-12-07 15:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbd9dfe44-6ab7-4458-8b11-5557422897d2%2Fartifact%2Fb08fe50d8b7f21c7%2Fp%2F7ac86a1e714f18252a6ffd6d0db2f92c&size=150x150">

2023-12-07 15:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd887bdfe-5318-41ee-b590-5a8d38d5b53b%2Fartifact%2F5211be7746a84ac6%2Fp%2F8a069cf8b87962df7ae53821016767fb&size=150x150>

2023-12-07 15:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc4c225b4-0b12-4cb5-89ef-0b822b68517b%2Fartifact%2Fa6c44f41d3a314bb%2Fp%2F3f59a617c253cb0da11324a1f77d2743&size=150x150>

2023-12-07 19:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F79b7f02a-5eae-48cd-924f-9f5fcf6e1efe%2Fartifact%2F42f024166caa5f6d%2Fp%2F7676551c8cc5f084eb2bd38285d0010e&size=150x150">

2023-12-07 21:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F341e3282-1303-4469-b76f-6a5fc1f78f1f%2Fartifact%2F8d6a60ce6943d40b%2Fp%2F0a2ac600c49e573c902158fc555dd652&size=150x150>

2023-12-07 21:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F60abf84c-f3fc-4660-b7f2-797b49f75af3%2Fartifact%2F9db11332dd0294a2%2Fp%2F4f09d0d5cb7424ddecaa3547eb006d4f&size=150x150">

2023-12-08 08:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F7ca8d438-af78-48e3-b395-a85fd26ae958%2Fartifact%2F2a0c63ea35a22552%2Fp%2F80d1d3b07d8618978a9ac43d21ef407b&size=150x150>

2023-12-08 08:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F445c19be-938c-4da5-8467-06f0f1181f0f%2Fartifact%2Fc1633856e7094312%2Fp%2Fac19bee0df8ea90bd9bba8449d7705f2&size=150x150">

2023-12-08 11:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5939c7fd-d9a4-4e56-a0cc-c06f7bb2ff72%2Fartifact%2F2fb2b88cf8c22f5e%2Fp%2Fff6609e7ac99a359cbd278c74d2a22eb&size=150x150">

2023-12-08 11:22 UTC, hermannakos approved these changes
QA + 1

2023-12-08 11:24 UTC, kdeakinstructure commented
Successful E2E Test run: https://app.bitrise.io/build/10fddee9-4ac7-46dc-ad9a-94ac18501b81

2023-12-08 11:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fde0a95f7-e7a4-4fe7-99e6-c00351f5e848%2Fartifact%2Fbd298922f27b237a%2Fp%2F8b3e7c4f1155d535f48fbb650f4a7401&size=150x150>

2023-12-08 11:51 UTC, kdeakinstructure approved these changes
QA 👍

2023-12-08 11:57 UTC, merged