[MBL-17250][Student] - Add Selection to the EditTextDialog
instructure/canvas-android pull request #2297
Opened 2024-01-08 14:43 UTC by kdeakinstructure

Test plan: Smoke test file renaming and edit username dialogs.

Add Selection to EditTextDialog (it's used in profile settings as well).
Request focus to make the selection visible for users.
Handle that folder names (which does not contain '.' character) should be entirely selected.

refs: MBL-1725
affects: Student
release note: Add selection to file name within the file renaming dialog and profile settings edit username dialog

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-01-08 14:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F91e5f13b-f4c2-42a2-829d-5325d0efff05%2Fartifact%2F3e025f1cd5fc744f%2Fp%2Fca11f25191da66c968e473aaf684f025&size=150x150">

2024-01-11 10:35 UTC, hermannakos requested changes

2024-01-11 10:35 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/dialog/EditTextDialog.kt
> +        if(endIndex == -1) binding.textInput.selectAll()
The formatting is wrong here. See any other if-else anywhere in code and follow that.

2024-01-11 10:35 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/dialog/EditTextDialog.kt
> +        else binding.textInput.setSelection(0, endIndex)
You can use `selectAll()`

2024-01-11 10:35 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/files/list/FileListFragment.kt
> +        EditTextDialog.show(parentFragmentManager, title, item.displayName ?: item.name ?: "") {
Why do we need the `parentFragmentManager` here? We should use the fragment's fragmentManager.

2024-01-11 11:53 UTC, tamaskozmer approved these changes

2024-01-11 12:15 UTC, kdeakinstructure commented on apps/student/src/main/java/com/instructure/student/features/files/list/FileListFragment.kt
> +        EditTextDialog.show(parentFragmentManager, title, item.displayName ?: item.name ?: "") {
Because requireFragmentManager() was deprecated according to Android Studio

2024-01-11 12:19 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/features/files/list/FileListFragment.kt
> +        EditTextDialog.show(parentFragmentManager, title, item.displayName ?: item.name ?: "") {
Yes, so you should use `childFragmentManager`

2024-01-11 12:25 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/dialog/EditTextDialog.kt
> +        else binding.textInput.setSelection(0, endIndex)
Sorry, misunderstood it. We usually put the happy path inside the if statement and the error handling in the else branch, it is reversed here.

2024-01-11 13:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4241ac1e-f055-4fd3-b1b9-d9263737fe94%2Fartifact%2Fe75aae9f2d199cb5%2Fp%2F65130e0a2c48bdac40c2c1c3f861a4d2&size=150x150">

2024-01-11 14:35 UTC, hermannakos approved these changes

2024-01-11 14:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F46377a25-ff57-45a7-a27b-5c21de7f9d2a%2Fartifact%2F09f68317719206ea%2Fp%2F94b21596bfac882bd90bed3989f9bc0f&size=150x150">

2024-01-11 15:07 UTC, merged