[MBL-17041][Teacher] - Extend People E2E test with filter by (user) groups
instructure/canvas-android pull request #2299
Opened 2024-01-10 14:23 UTC by kdeakinstructure

Extend PeopleE2ETest with filter by (user) groups.
Seed user groups and assign student to them.
Add some page object methods.

refs: MBL-17041
affects: Teacher
release note: none

2024-01-10 14:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0f1f9781-2a1a-40c2-82cc-5c05f4b0e14b%2Fartifact%2F97367e018c5817de%2Fp%2F8056b35c4aa0a68906d94060b8f5dd4b&size=150x150>

2024-01-11 10:29 UTC, hermannakos requested changes

2024-01-11 10:29 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
> +        val groupCategory = GroupsApi.createCourseGroupCategory(data.coursesList[0].id, teacher.token)
I would move these to the `StudentTestExtensions.kt` with the other seed functions.

2024-01-11 11:48 UTC, tamaskozmer approved these changes

2024-01-11 11:56 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
> +        val groupCategory = GroupsApi.createCourseGroupCategory(data.coursesList[0].id, teacher.token)
There will be a major refactor in a separate ticket when the so called 'ApiManager' classes will be introduced soon.

2024-01-11 12:00 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
> +        val groupCategory = GroupsApi.createCourseGroupCategory(data.coursesList[0].id, teacher.token)
That's awesome, but until then we should still stick with the already used patterns. Otherwise things might get looked over during a major refactor.

2024-01-11 13:01 UTC, hermannakos commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
> +        val groupCategory = GroupsApi.createCourseGroupCategory(data.coursesList[0].id, teacher.token)
I'll drop the CR, but still think we should follow existing patterns.

2024-01-11 13:04 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
> +        val groupCategory = GroupsApi.createCourseGroupCategory(data.coursesList[0].id, teacher.token)
Thanks. I'll do my best to make that refactor asap.

2024-01-11 13:05 UTC, merged