[MBL-17312][Student] - Create Offline E2E test for People page
instructure/canvas-android pull request #2304
Opened 2024-01-15 15:22 UTC by kdeakinstructure

Implement Offline test for People page.
Stabilize existing ManageOfflineContentE2ETest.
Add some page object methods and test class.

refs: MBL-17312
affects: Student
release note: none

2024-01-15 15:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F527413e0-4f42-4e92-9a42-3f4ea6076daf%2Fartifact%2Fe1983f9e32b5f824%2Fp%2Fc040a6de5bad6443c52693eac1c14367&size=150x150">

2024-01-17 10:04 UTC, hermannakos requested changes

2024-01-17 10:04 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
> +        Thread.sleep(10000) //Need to wait a bit here because of a UI glitch that when network state change, the dashboard page 'pops' a bit and it can confuse the automation script.
Do we need all these sleeps and waits together? Are 10 secs really necessary? Could we make it so we only wait until the desired state is reached?

2024-01-17 10:04 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
> +        Thread.sleep(10000) //Need to wait a bit here because of a UI glitch that when network state change, the dashboard page 'pops' a bit and it can confuse the automation script.
Do we need all these sleeps and waits together? Are 10 secs really necessary? Could we make it so we only wait until the desired state is reached?

2024-01-17 11:30 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
> +        Thread.sleep(10000) //Need to wait a bit here because of a UI glitch that when network state change, the dashboard page 'pops' a bit and it can confuse the automation script.
I have tried to figure it out what is actually happening on the emulator after I turn off the connection, but it still does not clear for me. I have tried many solutions and this is the only way when it is not flaky. If you up to help me figure it out what could be a better solution here, I'm up to it, but currently this is best I could make and this is works for sure, because there are some other offline tests in which this solution has really stabilized the test. As soon as we don't have many offline test, I think we can cope with this, but for the long term, there could be a better (optimal) solution of course.

2024-01-17 11:31 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
> +        Thread.sleep(10000) //Need to wait a bit here because of a UI glitch that when network state change, the dashboard page 'pops' a bit and it can confuse the automation script.
See above.

2024-01-18 12:57 UTC, tamaskozmer approved these changes

2024-01-18 12:57 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
> +        turnOffConnectionViaADB()
You could extract this sequence of actions into utility function that can be reused in every offline test. It will be cleaner that way, you avoid a lot of duplications and we can easily change it later when we come up with a better solution for the delays.

2024-01-18 22:11 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
> +        turnOffConnectionViaADB()
Good idea. I have made a separate ticket for this extracting, since there are other tests in which these are used.
I'll get this done the soonest, thanks!

2024-01-19 15:02 UTC, merged