[MBL-16500][Student] - Refactor MockCanvas addAssignment method to handle multiple submission types (as a list)
instructure/canvas-android pull request #2311
Opened 2024-01-24 14:35 UTC by kdeakinstructure

Refactor MockCanvas addAssignment method to handle submissions as a list (so we will be able to generate multi-type submissions in the future).
Modify existing usages to get list as a parameter value.
Implement interaction test for multiple submission type assignment.

refs: MBL-16500
affects: Student, Teacher
release note: none

2024-01-24 14:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F48e9d453-cb95-4eb9-bc60-d68f070a0db5%2Fartifact%2F4415ab99b2a8ed47%2Fp%2Fd8c0337527dd5fef429d3a090f4f25a9&size=150x150">

2024-01-24 23:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F7e055042-df63-43a0-95c8-e61bb246129e%2Fartifact%2Fa7fb2fc76c773b60%2Fp%2F990ddf78fe3ad7fe49d6d61241e766c2&size=150x150>

2024-01-24 23:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F979b6008-0f17-4122-9789-d36122c6c5b1%2Fartifact%2Fa2b09fd6401436a7%2Fp%2F96673abc276dd9ac7bfa9f35b0e541ef&size=150x150">

2024-01-25 08:58 UTC, kristofnemere requested changes

2024-01-25 08:58 UTC, kristofnemere commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditAssignmentDetailsPageTest.kt
> +                submissionTypeList = (if(submissionTypes.isEmpty()) listOf(Assignment.SubmissionType.ONLINE_TEXT_ENTRY) else submissionTypes.first()) as List<Assignment.SubmissionType>
you cannot cast it like that.

submissionTypes.ifEmpty { listOf(Assignment.SubmissionType.ONLINE_TEXT_ENTRY) }

2024-01-25 08:58 UTC, kristofnemere commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderCommentsPageTest.kt
> +        val commentText = submission?.get(0)!!.submissionComments[0].comment!!
I think you shuold rename submission to submissions and use it like this:

val commentText = submissions!![0].submissionComments[0].comment!!

2024-01-25 09:02 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditAssignmentDetailsPageTest.kt
> +                submissionTypeList = (if(submissionTypes.isEmpty()) listOf(Assignment.SubmissionType.ONLINE_TEXT_ENTRY) else submissionTypes.first()) as List<Assignment.SubmissionType>
Yes, actually I've fixed it already in my last commit, because it caused ClassCastException in one class. So now you can see my new solution.

2024-01-25 09:02 UTC, kdeakinstructure commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderCommentsPageTest.kt
> +        val commentText = submission?.get(0)!!.submissionComments[0].comment!!
Nice catch. thank you! :)

2024-01-25 09:02 UTC, kristofnemere requested changes

2024-01-25 09:02 UTC, kristofnemere commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentDetailsPageTest.kt
> +                submissionTypeList = (if(submissionTypes.isEmpty()) listOf(ONLINE_TEXT_ENTRY) else listOf(submissionTypes.first())),
Its still not okay, if submissionTypes is empty then you should not use first() on it.

submissionTypes.ifEmpty { listOf(Assignment.SubmissionType.ONLINE_TEXT_ENTRY) }

2024-01-25 09:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F034d4823-370e-497a-ab87-da8f1c30a3f8%2Fartifact%2Fea964d22d1a62c90%2Fp%2Fa7111c4b890512d90e3d7c7ef55e4599&size=150x150>

2024-01-25 09:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F881da44c-d551-47d0-b0eb-5699ace53540%2Fartifact%2F30aad0fe639abd78%2Fp%2Fdc2e230e4917538d518c7f83ba642781&size=150x150>

2024-01-25 09:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1eb7f855-f79e-4b60-890e-e0a1a287b3fb%2Fartifact%2Fef8f4a0d604afea3%2Fp%2F7642e0082d3e4f9322471657f7420819&size=150x150">

2024-01-25 09:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F92e1a258-fd7d-4be2-b9fd-d7e9459f885c%2Fartifact%2F6b5de2e4d67ba78a%2Fp%2F4e4ff09380ec70eb057718f78e5149bc&size=150x150>

2024-01-25 09:35 UTC, kristofnemere approved these changes

2024-01-25 09:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0d9422b7-e09c-455e-8f47-094000b338bf%2Fartifact%2Fa8fcff8857f448ff%2Fp%2Fdec90e08805678f8892d7d29cca40aa8&size=150x150">

2024-01-25 09:58 UTC, merged