[MBL-17271][Student] Add reminder section
instructure/canvas-android pull request #2312
Opened 2024-01-25 11:33 UTC by kristofnemere

Test plan: the new reminder section should appear when there's a future due date. The adding part is not finished, will be covered in the next ticket, but you can add and remove dummy reminders.

refs: MBL-17271
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-01-25 11:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb597145f-fda8-4677-a140-d2c5d5605231%2Fartifact%2F143bef1e1a9132de%2Fp%2F632fd320559884aed44f6ed38b22d9b4&size=150x150>

2024-01-25 11:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3b5187e8-0ee0-4a42-93cd-c6b06e22d5f7%2Fartifact%2Fb4acd270f0249adb%2Fp%2Fabde4d9b97c16410736032faeb98bb90&size=150x150">

2024-01-25 12:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb9a71205-f5dd-4eb5-98e6-4e245e075dbe%2Fartifact%2F30be9b99999f71da%2Fp%2Fe6a6ee724d887861efc4359397fbc461&size=150x150>

2024-01-25 12:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe71de04a-b2de-4bbe-bd9b-22a295e62f71%2Fartifact%2F861955301e704ea1%2Fp%2F909f222b95eae68338b6d317dd0b6056&size=150x150">

2024-01-26 13:22 UTC, kdeakinstructure approved these changes
QA 👍

2024-01-29 10:37 UTC, tamaskozmer requested changes

2024-01-29 10:37 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsViewModel.kt
> +        observeForever {
I think we should clear this observer or use one that is lifecycle aware.

2024-01-29 11:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5fc892f6-9e09-4672-9287-c244f4de98ff%2Fartifact%2F6b391fae4e45b94d%2Fp%2F657cf508922f51ba4de78caf70c985fc&size=150x150>

2024-01-29 11:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F57dfcbad-e14a-479a-ac4f-d8cb7c9d2941%2Fartifact%2Fc424b51ffa9a448c%2Fp%2F6a0e086af7e58e160e1c88f127495feb&size=150x150">

2024-01-29 11:54 UTC, tamaskozmer approved these changes

2024-01-29 11:55 UTC, merged