[MBL-17356][Student] - Fix front page title bug when navigating to front page from CourseBrowser 'Home'
instructure/canvas-android pull request #2318
Opened 2024-01-30 22:24 UTC by kdeakinstructure

Test plan: Test with a front page as the 'Home' of a course. Smoke test some other 'Home' settings and the Pages tab itself.

Fix front page issue by passing homePageTitle as the parameter for the TabHelper.getRouteByTabId method (null safely).

refs: MBL-17356
affects: Student
release note: Front Page title fixed when navigating from Course Browser by 'Home'.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/92309696/8c268b44-4f68-4ddc-bee0-d9c2752cfec2" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/92309696/dba991c3-8824-4f05-a8e7-5c93b1bd54bd" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in light mode

2024-01-30 22:40 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7216f619-abc2-48ad-aadd-637c67fa2614%2Fartifact%2F4ce8fd36e78411b5%2Fp%2Faf3730e7c1e5ece19f9442657c339ea1&size=150x150">

2024-02-01 09:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F852e36db-9ab6-48db-acaf-91064d070e73%2Fartifact%2Fd21c52f01dcb9fbd%2Fp%2Fbc642b28831d46683a2317b03f9db6b7&size=150x150">

2024-02-01 10:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd6972d94-fc8d-4994-999a-ad0dbe83cbe9%2Fartifact%2F2f215027e46aea2f%2Fp%2Ff421b7c70f81953a62b25e8f3e525a48&size=150x150">

2024-02-01 14:15 UTC, tamaskozmer requested changes

2024-02-01 14:15 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/util/TabHelper.kt
> +    fun getRouteByTabId(tabb: Tab?, canvasContext: CanvasContext, homePageTitle: String? = null): Route? {
This parameter is unused

2024-02-01 15:44 UTC, kdeakinstructure commented on apps/student/src/main/java/com/instructure/student/util/TabHelper.kt
> +    fun getRouteByTabId(tabb: Tab?, canvasContext: CanvasContext, homePageTitle: String? = null): Route? {
Forgot to delete, thanks!

2024-02-01 15:58 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffa706f91-3ad8-4034-98f1-7c13e4775517%2Fartifact%2F9f6dea67c2662eaf%2Fp%2F96d19afc8dccd97a68409783c2b20d54&size=150x150">

2024-02-01 16:22 UTC, tamaskozmer approved these changes

2024-02-02 10:08 UTC, kristofnemere approved these changes
QA+1

2024-02-02 10:24 UTC, merged