[MBL-17332][Teacher] Edit file permissions
instructure/canvas-android pull request #2320
Opened 2024-02-01 15:19 UTC by hermannakos

Test plan: See ticket for design. Compare functionality with web.

refs: MBL-17332
affects: Teacher
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-02-01 15:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Feca65ab7-f22a-4cd8-9c13-32489c40bd55%2Fartifact%2Ffd04850de43cc281%2Fp%2Faa17652f505e6edd90c5229e755ae9ef&size=150x150">

2024-02-01 16:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9319529c-a3a0-4630-8b0c-c8599bd3411f%2Fartifact%2F538b1a2a1c83124d%2Fp%2F9b001d1f16eb8e63b947bd0884fc33de&size=150x150">

2024-02-02 09:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0a9adf19-e949-498f-b730-24ba73a2fabe%2Fartifact%2F46b02c8b23a6240c%2Fp%2Fe84e7d9b0ed8e50ba0fad5a1ff87f725&size=150x150">

2024-02-02 10:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe308c21e-fe1a-430a-88ca-602d5e2619fc%2Fartifact%2F3d27feb90201a44e%2Fp%2Fab9112397013d4d3f8d37f2644f89aaa&size=150x150>

2024-02-02 10:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6bd2868c-790f-4b50-994c-37a14d83a8f1%2Fartifact%2F2dde669df4905e14%2Fp%2Faee9c8152fff9e0f6dc0f013430bb07c&size=150x150">

2024-02-02 15:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc64ac101-9144-43f6-987d-0482b15b768a%2Fartifact%2F08959958eeeb4a96%2Fp%2F0c711af9ef10b0e829b8c9ac6ffa92b3&size=150x150>

2024-02-02 15:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffcc71284-c8b1-460e-a51e-b865c2daff22%2Fartifact%2Fe6528b30da807050%2Fp%2F133beea483399ceb576b84837bf93582&size=150x150">

2024-02-06 12:22 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListFragment.kt
> +import com.instructure.canvasapi2.apis.FileFolderAPI
I guess this is unused.

2024-02-06 12:23 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListRecyclerAdapter.kt
> +import java.util.Date
This might be unused as well.

2024-02-06 13:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc8b552e5-651b-4541-a3bc-1d54597ad310%2Fartifact%2F5045442df3d38960%2Fp%2F9c8f5b0cefa2e7000428f35d40351d37&size=150x150">

2024-02-06 13:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2a6abf0d-6061-4342-aec6-e974734f972f%2Fartifact%2F095497913f336cc8%2Fp%2Fb27a953afa355c78bf1bdd45daf87efd&size=150x150>

2024-02-06 13:39 UTC, tamaskozmer approved these changes

2024-02-06 13:48 UTC, kristofnemere requested changes

2024-02-06 13:48 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListPresenter.kt
> +            type = ModuleItem.Type.valueOf(item.type.orEmpty()),
this could crash, could you handle it?

2024-02-06 15:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F86efc4d6-2525-4537-a0da-16a1a3ca4548%2Fartifact%2Ffad48792841ddfe0%2Fp%2F8850f052200767ddddf400b2d97c3334&size=150x150">

2024-02-06 16:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa5c992ef-ab99-46f9-b04d-d3e4758c96d1%2Fartifact%2F587fbb05da4ab51a%2Fp%2Faa95bf5fa8c982a6c3e87640faa18f1c&size=150x150">

2024-02-06 16:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F27646ad4-38e7-4b6b-af9f-985c46bf2fb5%2Fartifact%2F9e7e4ded1998abfe%2Fp%2Ff8cc1f2de9765e9a8db4c020ac4e4493&size=150x150>

2024-02-06 16:08 UTC, kristofnemere approved these changes
QA+1

2024-02-07 08:45 UTC, merged