[MBL-16673][Student] -  Introduce ApiManager class and extract direct API calls from E2E test files
instructure/canvas-android pull request #2336
Opened 2024-02-11 21:14 UTC by kdeakinstructure

Introduce StudentApiManager class.
Extract all the direct API calls from the E2E test classes into StudentApiManager.
Remove lots of duplications.

refs: MBL-16673
affects: Student
release note: none

2024-02-11 21:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd9e7b587-c746-4eff-aced-ae258beee05d%2Fartifact%2F59b5871bea460e7a%2Fp%2Fb950fd2e5f72da14b40e6e124a5e62e6&size=150x150>

2024-02-11 21:23 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdcdfac83-5205-4805-b498-7786e432532e%2Fartifact%2F5e33ea8f9a6c1dfd%2Fp%2F2e2b41fa363999f3cb1625de7dd95d07&size=150x150">

2024-02-12 11:52 UTC, kdeakinstructure commented
E2E test run: https://app.bitrise.io/build/f1c36967-6508-4959-90d9-90b4f692378d
(Successful)

Offline E2E test run: https://app.bitrise.io/build/6f0da429-0ddd-4f5e-9ee8-a01efae4dd0f
(Successful)

2024-02-12 15:06 UTC, tamaskozmer requested changes

2024-02-12 15:06 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentApiManager.kt
> +class StudentApiManager {
This could be an Object instead of a Class, since everything here is in the companion object.

2024-02-12 15:06 UTC, tamaskozmer commented on apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentApiManager.kt
> +class StudentApiManager {
I wouldn't call this `StudentApiManager`. I guess the most of the API calls could be used in the teacher tests, since these calls are for creating data for the test users. Ideally the role wouldn't matter here and this object would be in the `dataseeding` module.

2024-02-14 14:57 UTC, kdeakinstructure commented on apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentApiManager.kt
> +class StudentApiManager {
Refactored

2024-02-14 15:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2fcf3114-e716-4cf8-8146-3d849850d841%2Fartifact%2Ffe9059635d7f0b49%2Fp%2F2129a70f57c8a2f1e904c139fc21f126&size=150x150>

2024-02-14 15:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F43620399-240b-45ff-a244-8f9e87ddc395%2Fartifact%2F4eac3418ffd5dd50%2Fp%2F1777aed3cc198bb6ef06c2ea86064f11&size=150x150">

2024-02-14 15:23 UTC, tamaskozmer approved these changes

2024-02-15 09:22 UTC, hermannakos requested changes

2024-02-15 09:22 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/ApiManager.kt
> +object ApiManager {
I feel like this object could grow bigger and bigger with no end. It would possible be beneficial to split it into different classes based on the api called. i.e `UserApiManager`, `CourseApiManager` etc. I would do this now rather than later, because it will always be overlooked.

2024-02-15 09:22 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/Extensions.kt
> +fun Date?.toApiString(timeZone: TimeZone? = null): String {
this is now duplicated. Since the calendar is not used other than fetching the date we could pass the date string instead.

2024-02-15 09:39 UTC, kdeakinstructure commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/Extensions.kt
> +fun Date?.toApiString(timeZone: TimeZone? = null): String {
I am using the calendars in some if conditions below.

2024-02-15 09:41 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/Extensions.kt
> +fun Date?.toApiString(timeZone: TimeZone? = null): String {
It is only used once, in `ApiManager.kt::107`

2024-02-15 09:45 UTC, kdeakinstructure commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/ApiManager.kt
> +object ApiManager {
Actually the goal was to extract all the api calls into one file/class, to reduce code duplication significantly. So this was intentional to be in one class. I don't really think this will endlessly grow in the future since the most API calls we are using in the tests are mostly already in it.  The current size of it is less than 400 lines, I don't feel this as big, there are some much more bigger classes already in our code base (e.g. MockCanvas with 2000+ lines).

2024-02-15 09:49 UTC, hermannakos commented on automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/ApiManager.kt
> +object ApiManager {
On second thought it might defeat the purpose of this `ApiManager`. I would look for a unified way of handling these seeding calls. If you have some logic in the `ApiManager` you don't want to handle in the tests then it might be beneficial to separate it into different managers. But if the `ApiManager` would only be a middle man and just pass calls to the api, it would make sense to call the api directly.

2024-02-16 10:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F443aadfd-748f-4201-b7a0-19d089277ab7%2Fartifact%2Fe6c2c7d11fa03795%2Fp%2Fb5b91946ecd58d43b03c142e2a212f26&size=150x150>

2024-02-16 10:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff56c27ff-c077-45fa-a2d0-fb6b6e0afbde%2Fartifact%2F8ac28ec8001555fa%2Fp%2F9ab1c9de1703b5674045a82680faf6a1&size=150x150">

2024-02-16 12:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa5afa9dc-6475-4eae-a156-6404099b848c%2Fartifact%2F09334821ffbb8093%2Fp%2F9deb2d0cca42616fafe12aa48e76ac65&size=150x150>

2024-02-16 12:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4daf3b74-88cc-4001-b22f-30c1721ae495%2Fartifact%2F4b1f0d84a83d8f36%2Fp%2Fdfa7b7d9e01b261cd99a6b530cb5a350&size=150x150>

2024-02-16 12:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F19fc7f16-a9a8-4635-86b9-16d2a3dfbf32%2Fartifact%2Faecf2676e55f234c%2Fp%2F091582b5b9ad26a2863f2602e87a39b4&size=150x150">

2024-02-16 13:13 UTC, kristofnemere approved these changes

2024-02-16 13:53 UTC, hermannakos approved these changes

2024-02-16 14:34 UTC, merged