[MBL-17262][Student] To Do details screen
instructure/canvas-android pull request #2339
Opened 2024-02-12 12:06 UTC by kristofnemere

Test plan:  
- same functionality as in the Flutter version 
- slightly different design (check Figma)
- Edit and delete will be implemented in another ticket

refs: MBL-17262
affects: Student
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-02-12 12:16 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5f1984cc-179d-41d5-9958-5b52706106ac%2Fartifact%2F1faeb77dc3ee50b6%2Fp%2F3b2f5d9c80a4a561a273fca28a9a544c&size=150x150>

2024-02-12 12:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F58a01967-8337-4dff-a9b0-26259b2e1704%2Fartifact%2Fa78881bf9fec3cd3%2Fp%2Fe2c2c9ed13f737eeef0d7832cda92c46&size=150x150>

2024-02-12 12:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3101e345-11bc-4b11-b199-5bac278294ac%2Fartifact%2Fbfcbe6c39c7395f3%2Fp%2Fabbbced74cda635b22a582559321c4c4&size=150x150>

2024-02-12 12:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2ae1c1f1-bb16-43be-bb0c-1f1e3771f658%2Fartifact%2Fa350b7b049bf8bbe%2Fp%2Fca0ec5637dd2dc87a354aab1b369e27d&size=150x150">

2024-02-12 12:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F69159b33-b6c8-422d-bfca-2e8b2c997870%2Fartifact%2F138ca92d286709d8%2Fp%2F61a709aedaeead2ce0d62062ebecda69&size=150x150>

2024-02-12 12:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd9cb8b71-6acb-4354-8ab2-14aa1bac2be1%2Fartifact%2F37ad4e31c31569bb%2Fp%2Fbf533872c7051d16cbcfbbc83312ed9a&size=150x150">

2024-02-13 10:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F17559ea7-cfcd-4af8-a540-8dd053e95365%2Fartifact%2F3b4f4b460284a7b1%2Fp%2F6d56d9d432d4e9e13ffb4e45aaf5aa12&size=150x150>

2024-02-13 10:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F311787aa-7b3c-4238-9f4e-f1a5fae46bf6%2Fartifact%2Fd97c5eb89a0d99a6%2Fp%2Fae9e7436fe5273f3525867c5ccaf622b&size=150x150">

2024-02-13 11:19 UTC, kdeakinstructure approved these changes
QA 👍

2024-02-13 11:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa479a7bb-88ca-4c2d-a8c1-c475a0a16a04%2Fartifact%2F2b2a01437815ec98%2Fp%2Fc4fba7b2aadf2ed6dc5bef6f6bc85063&size=150x150">

2024-02-13 12:00 UTC, tamaskozmer requested changes

2024-02-13 12:00 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/todo/details/composables/OverflowMenu.kt
> +fun OverflowMenu(content: @Composable () -> Unit) {
I would move this out to a common package where we will store our common Composables that can be reused by multiple screens. Also shouldn't this have a modifier parameter that is passed to the `DropdownMenu`?

2024-02-13 12:00 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/todo/details/composables/ToDoScreen.kt
> +fun CalendarPreview() {
I would rename this to ToDoPreview.

2024-02-13 12:24 UTC, tamaskozmer approved these changes

2024-02-13 12:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F31ac231d-553e-4f46-a200-5ac8f4488b9a%2Fartifact%2Fcbdc1e57304586ce%2Fp%2Fe85eadc7af53d80d995116bc327661c9&size=150x150">

2024-02-13 12:57 UTC, merged