[MBL-17277][Teacher] Progress screen
instructure/canvas-android pull request #2341
Opened 2024-02-12 17:11 UTC by hermannakos

Test plan: Test the bulk update progress screen. See ticket for design. All bulk module operations should show the progress screen **except** when only a single module header is updated.

refs: MBL-17277
affects: Teacher
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-02-12 17:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F195a2067-b17d-40ca-8f4e-b4b1ee342a0f%2Fartifact%2F0ae7f2691f3d5968%2Fp%2Fcd83ac19bb813406d59c9ed277cbb43a&size=150x150>

2024-02-12 17:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe39c6bb7-626f-41c9-9fc7-ac18cf16b845%2Fartifact%2F1c28cca56e96ff9f%2Fp%2F6a9c4c1afa272c7ddc35472a55ff104c&size=150x150">

2024-02-12 17:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F583917c6-277b-4033-b7de-aa4ed04fb7fc%2Fartifact%2Fb11a41c32bd61988%2Fp%2Fada525b05354ad71ba8c955bcd695c01&size=150x150>

2024-02-12 17:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F809f45b7-3734-4593-a040-555944cc2052%2Fartifact%2F5c588a01253cc1c1%2Fp%2F8eeb460b533f5ddabb6a0bc5becb5026&size=150x150">

2024-02-13 12:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F14469db4-57ff-4024-97ef-82dcd60bab2b%2Fartifact%2F252942137ab9f2a3%2Fp%2Fc4301a91c7d1674b01373ce96cf12344&size=150x150>

2024-02-13 12:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9494a868-2402-4083-8d81-d6df4a553923%2Fartifact%2Fa9eace17c35e99c3%2Fp%2F2ec293faabe8aff63d8edf05e906b71f&size=150x150">

2024-02-13 15:10 UTC, kristofnemere requested changes

2024-02-13 15:10 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/progress/composables/ProgressScreen.kt
> +fun Note(note: String) {
this could get a modifier as parameter, and set the padding from outside

2024-02-14 09:18 UTC, hermannakos commented on libs/pandautils/build.gradle
> +    implementation 'androidx.compose.ui:ui-android:1.6.0'
No, I needed to add this just forgot to move it to GlobalDependencies.

2024-02-14 10:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F49d71b4f-62d8-4369-9e11-2679573c4a32%2Fartifact%2F9eefbb665e9af95e%2Fp%2F18f146f4c08bcc5017be226e57840bb0&size=150x150>

2024-02-14 10:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2c575a93-8b77-468e-93d1-fdbb453438c3%2Fartifact%2F77b5d591f13eb0ed%2Fp%2F7ae79c7df447b1d20b0caab0dc5e52f8&size=150x150">

2024-02-14 10:07 UTC, tamaskozmer commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/progress/ProgressViewModelTests.kt
> +        Dispatchers.setMain(testDispatcher)
You also need to reset the Dispatchers in the `@After` function.

2024-02-14 10:37 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe3c6c6fa-d2bc-4494-b96b-9601d717cc9b%2Fartifact%2F70976898af782dcd%2Fp%2Fa7f54ccce6941563237120c22a34e9aa&size=150x150>

2024-02-14 10:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F07087320-25d9-4216-9658-cbf60a1d9c13%2Fartifact%2Fe26753f0d5e7f6b4%2Fp%2F47eba06dc64c4d9e007f7b2e76785918&size=150x150>

2024-02-14 10:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fadde812c-a700-425d-9dfc-62578bed5ee2%2Fartifact%2F3b19c2cf45d5a473%2Fp%2F32d56e1a33e7dde4aa00c359f3d900d0&size=150x150">

2024-02-14 12:02 UTC, kristofnemere approved these changes
QA+1

2024-02-14 14:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4c1e55e8-f277-42e3-8136-5f09f3b5163d%2Fartifact%2F61710e2f9bd6c289%2Fp%2F7ad07f1865838c5dc0ef899e7268eba2&size=150x150>

2024-02-14 15:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe5b58f22-f5be-448e-98d1-7bb1a03866c0%2Fartifact%2Ffd1f971d2734af39%2Fp%2F64294de4a0eb89db647e8780e631091f&size=150x150">

2024-02-14 15:19 UTC, tamaskozmer approved these changes

2024-02-15 09:58 UTC, merged