[MBL-17246][Teacher] - Extend modules e2e test with navigating by previous/next button and publishing on the UI
instructure/canvas-android pull request #2346
Opened 2024-02-19 16:27 UTC by kdeakinstructure

Extend ModulesE2ETest with steps of changing between module item details screens by clicking on the previous and next arrow buttons.
Extend the ModulesE2ETest with a publishing process on the UI.

refs: MBL-17246
affects: Student
release note: none

2024-02-19 16:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F190dc37d-54a5-4cff-b010-9fac0b4c0465%2Fartifact%2Ff1d0f56fe8825823%2Fp%2F1e8491772ceff53a3d1f28e5bf208a20&size=150x150>

2024-02-19 16:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe17974cc-1217-4f04-8224-0c8cad238724%2Fartifact%2Ffb83509f8496abfc%2Fp%2Fdb4a4eeafa31ace3b144f18c2fc1e813&size=150x150">

2024-02-20 14:13 UTC, tamaskozmer requested changes

2024-02-20 14:13 UTC, tamaskozmer commented on apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
> +    val editPageDetailsPage = EditPageDetailsPage(ModuleItem(R.id.moduleName, R.id.next, R.id.previous))
I see the point in extracting the module item assertions into a separate class, but I would name this differently. When I first saw it I thought it would be some kind of API modell or representation of a module item. Something like `ModuleItemAssertions` or `ModuleItemInteractions`.  Also I wouldn't extract the ids, since those will probably not change. If you really want to add the ids as parameters you could use default parameters and only pass it when it's different.

2024-02-20 14:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fcb6c58ba-60e0-44db-bacf-330f11b80e3a%2Fartifact%2F0c61c9f39794b7a5%2Fp%2Fcb7a958d38558c9c66cec5c912e51ec1&size=150x150>

2024-02-20 14:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5ca583b3-6c65-45be-9458-f04a5cb4498c%2Fartifact%2Fbe3bf15696c3c792%2Fp%2F4f6000d0ace52c1d20563edf4bf47e7f&size=150x150">

2024-02-20 15:01 UTC, tamaskozmer approved these changes

2024-02-20 18:53 UTC, merged