[MBL-17263][Student] Create, edit, delete To Do
instructure/canvas-android pull request #2349
Opened 2024-02-20 15:38 UTC by kristofnemere

Test plan: 
- same functionality as in the Flutter version
- slightly different design (check Figma)

refs: MBL-17263
affects: Student
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked

2024-02-20 15:42 UTC, kristofnemere commented
e2e: https://app.bitrise.io/build/34477769-450a-4ebc-94da-db90a37ef128

2024-02-20 15:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1261ecb5-f1de-4311-96d7-8ca0776ee07e%2Fartifact%2Fa74371d0d0a89340%2Fp%2F455b9134537a7b9a2845ae91b2330c02&size=150x150>

2024-02-20 15:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa1ccd43c-f722-47b1-839f-4624aa146d4f%2Fartifact%2Fd9e6a01e4f4c1e1e%2Fp%2F0dce72e949e28af97aa3ba8917979348&size=150x150">

2024-02-21 14:47 UTC, kdeakinstructure requested changes
I've written my findings to you via Slack

2024-02-22 10:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fca97b9b7-c58e-4bfe-8ed5-be65a9a023ce%2Fartifact%2F321af3d69711db0f%2Fp%2Fb03ccc96b24c55069615e8882d9f76fc&size=150x150>

2024-02-22 10:13 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe58d02b1-9556-42f9-93eb-8c6e254cab0f%2Fartifact%2F40b8bd0e041b841e%2Fp%2F7c5894cea03d94e933120ef90813ad0e&size=150x150">

2024-02-22 12:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9c6c9c02-bfbf-4fd8-990e-1ff4597810ef%2Fartifact%2F809d8e8dc4085bcd%2Fp%2Fda1294583aaa6e32e36243d519de37d3&size=150x150>

2024-02-22 12:55 UTC, kdeakinstructure approved these changes
QA 👍

2024-02-22 12:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2fe2f375-e8d9-41a4-a91b-cf9271ef1dc4%2Fartifact%2Fbc31549fbe2ba8c0%2Fp%2Fd8d9d51a683227fe9d6a65d4de05ce3b&size=150x150">

2024-02-22 14:02 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/todo/createupdate/CreateUpdateToDoViewModel.kt
> +    private val initialDate = savedStateHandle.get<String>(CreateUpdateToDoFragment.INITIAL_DATE).toSimpleDate()?.toLocalDate() ?: LocalDate.now()
You can pass a `clock` parameter to the `.now` function to make testing more felxible. (optional)

2024-02-22 14:13 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/todo/createupdate/composables/SelectCalendarScreen.kt
> +                                    fontWeight = FontWeight(600),
I think these font weighs are causing the design issues I mentioned in the QA findings. I know it's in Figma but seems like it's wrong.

2024-02-22 14:20 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/todo/createupdate/composables/CreateUpdateToDoScreen.kt
> +                    LocalTime.of(
You can use `toLocalTime` extension here.

2024-02-22 14:20 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/todo/createupdate/composables/CreateUpdateToDoScreen.kt
> +                    LocalDate.of(
You can use `toLocalDate` extension here.

2024-02-22 14:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F32c87e71-fb8b-4bdc-920d-ec455cecb64c%2Fartifact%2F88189d2df1c9c3a6%2Fp%2F862b8a822f5bd4aac7d8621ae198bb52&size=150x150>

2024-02-22 14:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd948e3a8-2771-4819-946e-69ddfca12488%2Fartifact%2F21f9c4a059f86eab%2Fp%2Faea73eef656d88eaeabcf35d1be10d84&size=150x150">

2024-02-22 14:49 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
> +                        .padding(padding)
I think that padding param from content should be passed everytime

2024-02-22 15:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F54293c81-0b4d-40df-b115-8104d6e2bfc5%2Fartifact%2F4494435c79bbdbe5%2Fp%2Fe869cc474ae35d03ea0a31fe1935ed1c&size=150x150>

2024-02-22 15:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F68c8f73e-e7d2-4d90-a646-450e9a10a8ae%2Fartifact%2F6159cebd6d38302f%2Fp%2F4aac7d256ce5aa57b474efbccf2091c9&size=150x150">

2024-02-23 12:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc448a9a8-1c2c-4ffe-a34b-bf3d85e8dd44%2Fartifact%2F865c04802994065d%2Fp%2Fe800a7233caf05c50e5b5dd41b9148da&size=150x150>

2024-02-23 12:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe66fc7b8-d5a0-49f1-8143-9822941a7f90%2Fartifact%2F24c4fb990dede39b%2Fp%2Faa7e3066bf8e17c3e3d1c11c7ca8a411&size=150x150">

2024-02-23 13:10 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe270cd4c-6559-46e9-a44e-267bda4bb7e7%2Fartifact%2Feab3b000b660d85a%2Fp%2Fcaf5d725112d82f8db2c5d0265350420&size=150x150">

2024-02-23 13:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F27a06200-212a-4eb4-af6c-86db69b0d6a3%2Fartifact%2Fe0d551c539b14154%2Fp%2F8d1bd36baa2ec406ffa0b0fdb68c7773&size=150x150>

2024-02-23 13:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F285eaebf-7ac8-471a-ac90-f0e5c603953b%2Fartifact%2F8776fb7f5b6a602e%2Fp%2F371858d76455d5b0b14b8141ce27812b&size=150x150">

2024-02-23 14:10 UTC, tamaskozmer requested changes

2024-02-23 14:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F22cc4036-014d-4411-ae9f-552facd20501%2Fartifact%2Fb2e34003efa0ae27%2Fp%2F9a2c5da95ea1661a295da533779eb698&size=150x150>

2024-02-23 14:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe8ffa753-befe-47af-9681-2acde623a371%2Fartifact%2F061bf0f74ce0853e%2Fp%2Fa71a4137816b827395e6993f20e3c0c4&size=150x150">

2024-02-23 14:49 UTC, kdeakinstructure approved these changes
QA 👍

2024-02-23 15:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffbff3170-5f7c-43e4-8bb4-9de9e2cd006c%2Fartifact%2F648b252499818a26%2Fp%2Faac290a63e37d4b84357aba8860d4e16&size=150x150">

2024-02-23 15:22 UTC, merged