[MBL-17282][Student] Redesign calendar event details screen
instructure/canvas-android pull request #2361
Opened 2024-02-29 20:23 UTC by kristofnemere

Test plan: 
- same functionality as before
- slightly different design (check Figma)
- Edit/Delete will handled in another ticket

refs: MBL-17282
affects: Student
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-02-29 20:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fce8a1001-d894-4a3c-ab63-4e04278f3cd2%2Fartifact%2F48b834d032968bb3%2Fp%2F8976e3d137fd9f18dd9f567aad6a7a8c&size=150x150>

2024-02-29 20:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff9d66d3e-f22f-48f3-9982-f59d0e5c6387%2Fartifact%2F1ff86cfa112de931%2Fp%2F9dacbc90b5e55533bc07b65c6e1c86ed&size=150x150">

2024-03-01 09:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F390292b8-c0c8-473b-ba95-b12676c28360%2Fartifact%2F87e6a1f3c163f0be%2Fp%2F843a6574425e6fe9b6c79d46d5a75bc9&size=150x150>

2024-03-01 10:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb449fe72-2637-4131-a2fc-3b0284e0d73e%2Fartifact%2F5db7233316c3b91b%2Fp%2F8ec1e09b6b33f6788023e133e7cea476&size=150x150>

2024-03-01 10:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe0113093-99bd-4051-92ac-6bbaec162389%2Fartifact%2Fc9812c7fa52c6954%2Fp%2F90041c4ae7e25afc11edc3410051a9a8&size=150x150">

2024-03-01 10:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa94ff8be-4f4f-46f1-ae43-1d0b78076ad2%2Fartifact%2Fdfa14b0c3125bedd%2Fp%2F7148a674e28b42fb72d54a81cc30b32f&size=150x150>

2024-03-01 10:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F13ab0a7a-b096-47b6-93c0-13e957da65c9%2Fartifact%2Fadce01837a98a452%2Fp%2F9f319807900ab9a5852d46ed57d21583&size=150x150">

2024-03-01 13:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3d9f5cf8-4c98-4c9f-b44a-223cee310718%2Fartifact%2F2e277ff0f875ebf6%2Fp%2F16894564b792aa02efa8e5a4df64edf7&size=150x150>

2024-03-01 13:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F64bb59ee-8b91-43d2-87e4-98701f009987%2Fartifact%2F811f74e45cf2d212%2Fp%2F181ac50ccbfd702d3cabb6ce859f62ff&size=150x150">

2024-03-04 09:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Faaf80c75-9077-4fd6-91b8-44e21bfce6ab%2Fartifact%2Fe3739cd8a6822a2f%2Fp%2F3889ed84ffc4d42f07719bbae3b96b8d&size=150x150>

2024-03-04 09:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1e6193b3-ba7d-4adb-900d-b0c766489c7a%2Fartifact%2F8e71e5988e6dd6ed%2Fp%2F252086e67699b83952003b8a05fe4f93&size=150x150">

2024-03-04 11:36 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/EventViewModel.kt
> +            is EventAction.DeleteEvent -> {}
Pretty much same here, I would try and complete this screen with the events as much as possible just to make it easier to integrate everything else.

2024-03-04 11:36 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/composables/EventScreen.kt
> +private fun TopAppBarContent(
It's not just the content only, bit misleading.

2024-03-04 11:55 UTC, hermannakos approved these changes
QA + 1

2024-03-04 13:15 UTC, tamaskozmer requested changes

2024-03-04 14:18 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/EventViewModel.kt
> +                modifyAllowed = scheduleItem.contextId == apiPrefs.user?.id,
I'll find this out when I can test it, probably in the next ticket - currently it's not working properly even on web

2024-03-04 15:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb841bb1d-59e7-488c-a4c8-8c81472c4fa7%2Fartifact%2F230fdcbd94e5ab3f%2Fp%2F6dfd0df3fca43e509cfc5a4271edcff9&size=150x150>

2024-03-04 15:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6cf5ce3d-60bc-4275-8a03-9e5b7aade4c6%2Fartifact%2F9e2eceb881d3955e%2Fp%2F950c7ba9e3a61b5bd6c5e1c7a2693e19&size=150x150">

2024-03-05 08:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6dbbc901-866f-4f47-8413-6e65f2fcbfe5%2Fartifact%2F9e52cc802bdd4803%2Fp%2F5fe26a17c00d179e4eb69dc1a7498009&size=150x150>

2024-03-05 08:48 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fca4a48be-0287-4af8-9006-b418706e7c89%2Fartifact%2F75580c68dad6d06b%2Fp%2F337537d82507dfcd9e3f7dd4992610b3&size=150x150">

2024-03-05 11:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5c2b19ab-ef2f-47e0-bd76-3892ebcc0c11%2Fartifact%2Fba1632d1ede23912%2Fp%2Fe8d836d26da1103e0563f99633955b21&size=150x150>

2024-03-05 11:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Feb403981-ae3d-494f-b020-7109cc55e50b%2Fartifact%2Fa04a40bded75c82b%2Fp%2Fa38956478a5029c90cfb7ba91e049ae8&size=150x150">

2024-03-05 11:47 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/composables/EventScreen.kt
>          contentColor = Color.White,
I would use `colorResource(R.color.white)` to be consistent.

2024-03-05 11:50 UTC, tamaskozmer approved these changes

2024-03-05 12:37 UTC, kdeakinstructure approved these changes
QA 👍

2024-03-05 12:39 UTC, merged