[MBL-17264][Student][Teacher] Calendar filters
instructure/canvas-android pull request #2362
Opened 2024-03-01 09:49 UTC by tamaskozmer

Test plan:
- Verify that the correct filters are shown in the calendar filters screen
- Verify that changing the filters changes the displayed events
- Verify that the users selected filters are kept if the user updates the app (for this you can install an app from a recent PR that targets master and update with this one). If user had all the filters selected in the Flutter version, groups should be selected as well, if some filters are not selected groups shouldn't be selected (currently we only show group events if there are no filtering).
- If no filter is selected all events should be displayed.

refs: MBL-17264
affects: Student, Teacher
release note: Added an option to filter groups in the Calendar

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-03-01 10:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8070432e-1822-4b31-9b49-ef77bd5c27fc%2Fartifact%2Fc8dccc03f4539f3f%2Fp%2F571cc8b8b5b2083f95a5095e6264986e&size=150x150>

2024-03-01 10:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8fb6d553-3dc7-4557-bdd9-dc03093600be%2Fartifact%2F41550426dff2d4be%2Fp%2F10899ce64c2a9486687742c52de26a80&size=150x150">

2024-03-04 09:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6cca64b3-9ee2-4131-b922-2cd56b48cea3%2Fartifact%2F337bd3254c5c51f7%2Fp%2Ff2e8c2d907cfb291a009191604915d7d&size=150x150>

2024-03-04 09:59 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F50dd980e-f51e-401b-b6d1-4dba72e62dce%2Fartifact%2Ff9186a12f1014ea3%2Fp%2Fb4501d09e30c6d7ef7f3209046a1055e&size=150x150">

2024-03-04 10:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa0f0a041-ce0c-4f1b-b1d0-5e4a74b0b12b%2Fartifact%2Fe1441631cdf0fb64%2Fp%2Fb4e0e6e79ae4760d85c211e7800ce7e5&size=150x150>

2024-03-04 10:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F748bce17-ef52-453d-8381-0bcf4093ad86%2Fartifact%2F290390239947a97e%2Fp%2F41dc77c77bf8be68175cf64e2c9cb28a&size=150x150">

2024-03-04 12:05 UTC, kristofnemere requested changes

2024-03-04 12:05 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/room/calendar/daos/CalendarFilterDao.kt
> +    suspend fun findByUserIdAndDomain(userId: Long, domain: String): List<CalendarFilterEntity>
This could be a single object instead of a list IMO

2024-03-04 13:21 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/composables/CalendarFilterScreen.kt
> +        item {
I don't like not scrolling things. :D On a serious note it looks bad, only way it would look good is with sticky header, but I think it's a bit of an overkill in this scenario, because we don't have actions on that part, it's not that the user would like to interact or even read that part when scrolling.

2024-03-04 14:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F090e8b5a-6ce9-4b96-a7e4-187f5b74502a%2Fartifact%2F5370e297436b2803%2Fp%2Fa772b14356df977c325bc5a5d3098799&size=150x150>

2024-03-04 14:10 UTC, kdeakinstructure approved these changes
QA 👍

2024-03-04 14:13 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8c656ac8-4096-4a94-9b21-e16fe09a1d72%2Fartifact%2Fd591ba87323686e8%2Fp%2Fe9c4a4862128d01744890a228499b6f8&size=150x150">

2024-03-04 14:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F49d3d7fd-d88d-44df-bf62-d93e77c59ed1%2Fartifact%2F07e80049415c7b57%2Fp%2Ff7865f073eb79786eeed5f4f188766e0&size=150x150>

2024-03-04 15:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5375964f-53b7-437e-a1b6-8e934cdac506%2Fartifact%2Ffceddec68c13119e%2Fp%2Ff56fe448ecc2302c9263807cc4a4b9ce&size=150x150>

2024-03-04 15:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa8a97838-5347-4b67-a9cf-64c1ec2747e9%2Fartifact%2Fff696c907f74a7ca%2Fp%2F0d2f8ed58ec167b9d0bd1d4899969411&size=150x150">

2024-03-04 15:31 UTC, hermannakos requested changes

2024-03-05 08:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fcc5ac398-f33b-4775-896f-87fe16461b78%2Fartifact%2F63856916e41cd3c6%2Fp%2F50dc1b146c17c60500b7899ad07535d2&size=150x150>

2024-03-05 08:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F61849ff6-c7ef-4708-a251-ae9b76cb316e%2Fartifact%2F381a60c17f14fdb0%2Fp%2Fbb3488fbb196114f4cc0d4ceb835c4dc&size=150x150">

2024-03-05 11:12 UTC, merged