[MBL-17455][Student] Compose RCE
instructure/canvas-android pull request #2404
Opened 2024-04-09 08:42 UTC by hermannakos

Test plan: Test the RCE in the create ToDo screen. Smoke test other RCEs, the image insertion has changed a bit.

refs: MBL-17455
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-04-09 08:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdc82b124-5130-4932-b622-4884a6671563%2Fartifact%2Ff6e87c110c378300%2Fp%2F18077097c08adbc9f6568c57986dc208&size=150x150>

2024-04-09 08:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb72cf79c-8f75-460d-bcab-60eac48fb415%2Fartifact%2F15a20ad1ad7c7af5%2Fp%2F87e4d4387fcd914e3a4818c5b574ee71&size=150x150">

2024-04-10 08:52 UTC, tamaskozmer requested changes

2024-04-10 08:52 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/RCEControls.kt
> +        item {
Shouldn't we use `items` when adding multiple items to a row?

2024-04-10 08:52 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/RCEControls.kt
> +        item {
Shouldn't we use `items` when adding multiple items to a row?

2024-04-10 08:52 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/RCEControls.kt
> +fun RCEControls(
By our conventions we should add a Modifier as the first optional parameter to all of the Composables in this file.

2024-04-10 08:52 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/ComposeRCE.kt
> +    onTextChangeListener: (String) -> Unit
I am not sure about this, but shouldn't mandatory parameters be before the optional ones?

2024-04-10 08:52 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/ComposeRCE.kt
> +                    rceTextEditor.insertImage(imageUrl, "")
Why don't we add alt text for the image picker images? We do this in other places where we use RCE.

2024-04-10 08:53 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/ComposeRCE.kt
> +    onTextChangeListener: (String) -> Unit
it's so we could use lambdas

2024-04-11 08:19 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe079bd90-b16e-4819-a879-e53a2f442e00%2Fartifact%2F4b35ed8ad90c78bb%2Fp%2F470135405ff07c39060e8d3f237e52f2&size=150x150">

2024-04-12 09:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa82332a0-a486-4ac2-ab2b-45d34f8381d9%2Fartifact%2F2fd7c8c1170059f6%2Fp%2F23860b6eaabfc96cf36698b4597750a0&size=150x150>

2024-04-12 09:28 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2454a570-5bfe-4158-9a2f-73e2a6ae3fa8%2Fartifact%2Fa0f27dbdf8ebad77%2Fp%2F28eed6f92967b1ff3fffe9c0b557be6c&size=150x150">

2024-04-12 10:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F86895705-a2e9-477f-8f99-257a2f53828d%2Fartifact%2Fc354eca4e47562de%2Fp%2F1b66d0099f161621948f618caee01512&size=150x150>

2024-04-12 11:28 UTC, kdeakinstructure approved these changes
QA 👍

2024-04-12 11:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2d476aae-f672-46cb-b0ae-cde640580671%2Fartifact%2F9a3b131865fd4044%2Fp%2F45080cd572d857901d76a95d6ac20ae3&size=150x150>

2024-04-12 11:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcacdee0c-1859-4920-a895-956557246eb8%2Fartifact%2Fe177af0e433c202a%2Fp%2F198180bd15e819e4afe5408ba97c9031&size=150x150">

2024-04-12 11:53 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/ComposeRCE.kt
> +        setEditorHeight(280.dp.value.toInt().toPx)
You can simplify this to `280.toPx`, we have an extension like this for Int.

2024-04-16 09:26 UTC, tamaskozmer approved these changes

2024-04-16 12:11 UTC, merged