[MBL-17497][Teacher] Load submissions in SpeedGrader
instructure/canvas-android pull request #2411
Opened 2024-04-12 10:34 UTC by hermannakos

Test plan: See ticket. SpeedGrader now loads the submissions itself and no longer passed in a bundle. Smoke test thoroughly.

refs: MBL-17497
affects: Teacher
release note: Fixed a bug where SpeedGrader would not load with large number of submissions.

## Checklist

- [x] Run E2E test suite

2024-04-12 10:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F48e1c055-1cb9-40c4-b1c7-ee723f793510%2Fartifact%2F4eb83442e16c1030%2Fp%2F5067ea859bf9bcbdedafc24ba6b1f9cb&size=150x150>

2024-04-12 10:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbc616c8a-ea49-420c-9683-df75f98b0197%2Fartifact%2F3f2a9b259fe6a0bf%2Fp%2Fefac4e1b1f350f2ed52f22fb18f31581&size=150x150">

2024-04-12 11:51 UTC, tamaskozmer requested changes

2024-04-12 11:51 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt
> +            selectedIdx: Int,
Is this "x" intentional?

2024-04-12 11:51 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/AssignmentSubmissionListModule.kt
> +@InstallIn(SingletonComponent::class)
What if we put this into the `ActivityComponent`? I think it can be injected into Activity and Fragment as well.

2024-04-12 11:51 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/AssignmentSubmissionRepository.kt
> +class AssignmentSubmissionRepository(
You should add some unit tests for this class.

2024-04-12 11:55 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt
> +            selectedIdx: Int,
Yes, index nem id

2024-04-16 08:13 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F04670512-f0bb-422f-84cf-9955a4d3fe03%2Fartifact%2F839a14462bf9efbd%2Fp%2F7af62caafc23f29e8c33e256dd2be551&size=150x150>

2024-04-16 08:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F460a9665-9c9e-4a86-b8a2-5e866b66e630%2Fartifact%2Fa9ce1847900f103a%2Fp%2F2984487d43d6ce027b12de0ace2cf9ab&size=150x150>

2024-04-16 08:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9f7b1559-9121-4296-8ca6-7356d7b172bb%2Fartifact%2Ff668c6dfb5f24127%2Fp%2Fbb5dd5d36ac4783cd7a30a6c2b32d92d&size=150x150">

2024-04-16 08:38 UTC, tamaskozmer approved these changes

2024-04-16 12:12 UTC, merged