[MBL-17517][Student][Teacher] Add RCE editor to Create Event
instructure/canvas-android pull request #2419
Opened 2024-04-18 12:16 UTC by tamaskozmer

Test plan: Check create event and create todo screens. Only the event should have RCE. Try creating both events and todos. Smoke test the RCE features.

refs: MBL-17517
affects: Student, Teacher
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-04-18 12:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F504d01a1-8ebc-4c06-8899-1d697e199360%2Fartifact%2F210f9312530b61c8%2Fp%2Fe6a09cb6630f8a13a33e6ad8f2ad8246&size=150x150>

2024-04-18 13:23 UTC, kristofnemere approved these changes

2024-04-18 13:27 UTC, hermannakos approved these changes

2024-04-18 13:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F42096382-40d2-4975-8bea-419e38073ee6%2Fartifact%2Fffde0ca0b922d14c%2Fp%2Fa449db3d9fcd43e485169cb348030ff0&size=150x150">

2024-04-19 08:32 UTC, kdeakinstructure commented
Cannot edit/delete event (todo is working).

https://github.com/instructure/canvas-android/assets/92309696/e8e28675-3a11-42c1-8ca0-52649a6f464f

2024-04-19 08:33 UTC, kdeakinstructure requested changes
Finding (and video) in comment.

2024-04-19 09:45 UTC, kdeakinstructure approved these changes

2024-04-19 09:45 UTC, merged