[MBL-17285][Student][Teacher] -  Implement Calendar Event Screen E2E test
instructure/canvas-android pull request #2429
Opened 2024-04-25 22:25 UTC by kdeakinstructure

Implement Student Calendar Event create/edit/delete test.
Implement Teacher Calendar Event create/edit/delete test.

Add new page objects (screen pages, event details pages).
Add lots of testTags on composables in order to make them more easy to select with matchers.
Import compose UI dependency in espresso build.gradle
Minor refactor, renaming on existing methods.
Add some utility functions.
Add new FeatureCategory.

Restructure compose UI pages and e2e tests into 'compose' packages.

refs: MBL-17285
affects: Student, Teacher
release note: none

2024-04-25 22:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F245003da-d84a-4d7c-895a-5aad2137ce81%2Fartifact%2Fada0215137818c18%2Fp%2F45eeea23442931217708a66d118068b1&size=150x150">

2024-04-25 22:39 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F79bdb304-0c05-4641-9b0c-cb116161bc6f%2Fartifact%2F9d2965965b42383c%2Fp%2F2c5be1351776102cc78d9b64e7d55e9e&size=150x150>

2024-04-26 13:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F618d2fbb-3fb9-4aff-bf26-704795629548%2Fartifact%2F9af1d481e44fe904%2Fp%2F3d19e14ec443873ccd2f9b7f57f4aa51&size=150x150">

2024-04-26 13:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F03dd69ad-3b88-4d45-83c5-9c5f7fc1869d%2Fartifact%2F8e95db3daffb6517%2Fp%2Fc8ae2546e41fcc61c412142be717dfcc&size=150x150>

2024-04-29 11:35 UTC, tamaskozmer requested changes

2024-04-29 11:35 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/composables/EventScreen.kt
> +                        modifier = Modifier.padding(horizontal = 6.dp).testTag("recurrence"),
Why did you change the padding here?

2024-04-29 22:16 UTC, kdeakinstructure commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/composables/EventScreen.kt
> +                        modifier = Modifier.padding(horizontal = 6.dp).testTag("recurrence"),
It was just experiment, I forgot to set it back, nice catch!

2024-04-29 22:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fce8c072b-4ef7-47ab-b7b9-52d40275d5bd%2Fartifact%2Fb9f785f93181fb16%2Fp%2F88cf31c309d91910fdbba9317196f99a&size=150x150>

2024-04-29 22:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6e5d095a-4247-4e57-af32-c59b324fcc5e%2Fartifact%2F58d753157204d472%2Fp%2F94586974920b8e5ac2e04a46156029b2&size=150x150>

2024-04-29 22:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa3a6e73b-a70b-4a5f-aa92-3d343f822dba%2Fartifact%2F5ed1c7244058002b%2Fp%2Fae6ed121d56626ff4ee14a663c5b3069&size=150x150">

2024-05-10 11:53 UTC, kristofnemere requested changes

2024-05-10 11:53 UTC, kristofnemere commented on automation/espresso/build.gradle
> +    implementation 'androidx.compose.ui:ui-test-android:1.6.6'
Would be better to use the constanst to make sure we use the same version at all places: implementation Libs.COMPOSE_UI_TEST

2024-05-13 22:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd47c6ff1-54dc-405b-b440-6ea0a146f580%2Fartifact%2F69471bb293a02318%2Fp%2F34b9d964c2e2bbd71a0fadaab5d9d6a3&size=150x150">

2024-05-13 22:10 UTC, kdeakinstructure commented on automation/espresso/build.gradle
> +    implementation 'androidx.compose.ui:ui-test-android:1.6.6'
Did it, thanks!

2024-05-14 07:09 UTC, kristofnemere approved these changes

2024-05-15 12:06 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F95ebb3fb-c460-49b7-baaa-748b4d63c265%2Fartifact%2F0f5375e668548dfe%2Fp%2Fd06494ec833d4f5fc2593c334cb79617&size=150x150>

2024-05-15 12:08 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F53c6a18d-62ff-491b-b9d9-b2d99d2ca9a7%2Fartifact%2F3e842a43f18ca49c%2Fp%2Feade7fe7d78d0b03c852374931243664&size=150x150">

2024-05-15 12:54 UTC, tamaskozmer approved these changes

2024-05-15 13:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fba0bc47a-1a5c-46b7-a1fe-7cf103b7ea3b%2Fartifact%2Fafb8ea3093bae8de%2Fp%2Ffdd4eed1d6abce64e0084eb596753db8&size=150x150">

2024-05-15 13:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6014f7bc-00fa-4c19-9398-d5f13633e5ed%2Fartifact%2F1f3b81c75d370c18%2Fp%2Fab6e92d676d2d38cb5e30fc5bbd924b7&size=150x150>

2024-05-15 13:22 UTC, merged