[MBL-17481][Parent] Project init
instructure/canvas-android pull request #2436
Opened 2024-04-30 13:37 UTC by kristofnemere

Test plan: in the ticket

refs: MBL-17481
affects: Parent
release note: none

2024-04-30 13:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdae41918-3f3f-4495-9cb8-1b71b469738d%2Fartifact%2F34cded5f80a607d8%2Fp%2F7ec6788ac44a0e732e9148a200ddb2eb&size=150x150>

2024-04-30 13:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Faf80e9f3-a2ed-48cf-8122-90b3059a2129%2Fartifact%2F054092e2e14bd810%2Fp%2F34265af9283b58aca88f1d80b9cef17c&size=150x150">

2024-05-13 13:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc9db5d28-2ffa-49b3-b070-3d71b0884700%2Fartifact%2F5133c07eaccd8b97%2Fp%2F55699ba42455011de6db6e20677ea1ce&size=150x150>

2024-05-13 13:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc6c0e9b6-24e4-415b-a749-8d7409e50b93%2Fartifact%2Fd902f0c10083ab43%2Fp%2F676543c2a1055f1d6432481e95d41480&size=150x150">

2024-05-21 13:13 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F59c171da-5f96-4bfe-a34c-289c22d75d75%2Fartifact%2F00b414f0794afe6b%2Fp%2F78bf168f64c4847273dcebd70dbbc5b1&size=150x150>

2024-05-21 13:13 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbf46f659-3776-4679-9c30-afb66ac50839%2Fartifact%2F2ede345d1ff5fc22%2Fp%2Fd0b3da035cb28edb2f972e9f81a6e494&size=150x150">

2024-05-22 13:02 UTC, tamaskozmer requested changes

2024-05-23 08:41 UTC, kristofnemere commented on apps/parent/build.gradle
> +        dataBinding true
I used viewBinding at some places, removed dataBinding

2024-05-23 08:42 UTC, kristofnemere commented on apps/parent/build.gradle
> +        versionName "3.10.0"
Yeah we'll find it out before release

2024-05-23 09:02 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/list/ParentInboxRepository.kt
> +        val coursesResult = coursesApi.getFirstPageCourses(params)
Will be done in this ticket: MBL-17609

2024-05-23 10:22 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/list/ParentInboxRepository.kt
> +class ParentInboxRepository(
Will be done in the ingegration ticket

2024-05-23 10:41 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/help/ParentHelpLinkFilter.kt
> +class ParentHelpLinkFilter : HelpLinkFilter {
Will be done here: MBL-17610

2024-05-23 10:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fae2db781-2082-44ea-bf1d-b133227db1f0%2Fartifact%2F40153c8bf8c4c853%2Fp%2Fd799d540fb031e45198a3fb7d16e8bc5&size=150x150>

2024-05-23 10:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe67ec1aa-9d6e-4614-9dd7-8c30cb08edd8%2Fartifact%2Fc97b3bb3d3c4b716%2Fp%2Fdc923e8ef2c531d32ce3348d28984185&size=150x150">

2024-05-23 12:21 UTC, hermannakos approved these changes

2024-05-23 13:48 UTC, merged