[MBL-17244][Student] Migrate SQLDelight into Room
instructure/canvas-android pull request #2463
Opened 2024-05-31 11:42 UTC by hermannakos

Test plan: Test migration with existing data from the production version (pending comments, failed/draft submissions etc). Test everything relating to submissions, all submissions types, comments, files.

refs: MBL-17244
affects: Student
release note: none

## Checklist

- [x] Run E2E test suite

2024-05-31 11:53 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fea872253-de6c-4ddb-9cdb-5fca76a63aac%2Fartifact%2F6c6b866ed77638b8%2Fp%2Fb828ae435274613897c0a7e86000e95e&size=150x150">

2024-05-31 11:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0f84da86-7df5-437b-b401-8b59353ac110%2Fartifact%2Ff0fa502dac19fa73%2Fp%2Fa4667178831a7f4bb0346b6a3a165248&size=150x150>

2024-05-31 11:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa3147acb-c721-4281-b66c-d8b98ef3fdb0%2Fartifact%2F08061ca5ae4d392c%2Fp%2F4a856523a366f5bc529a04eb724d0000&size=150x150">

2024-05-31 12:41 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Faef6855b-a335-4188-942b-c760008e90be%2Fartifact%2F8a6f72c250d0eac3%2Fp%2Ff8cad04d5b6b6cc7af38292387be4675&size=150x150">

2024-05-31 12:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff03ee10f-0608-4653-b823-494c74938030%2Fartifact%2F4674928454834b26%2Fp%2Fa8dcccd00b75b88ae81c48df9a2a987f&size=150x150>

2024-05-31 12:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff98086f6-fb48-44ae-a1e2-8426fbbd71ec%2Fartifact%2Fa59aa20dd3429230%2Fp%2Ffc5fc782903b7096a70968bd55d6db24&size=150x150>

2024-05-31 12:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7b0e9d4f-28e3-46c0-a4f4-16e9c6f91c04%2Fartifact%2Fd8ce6ca1a9a39883%2Fp%2Fad125c9895b24b6619ba446289a5410c&size=150x150">

2024-06-04 08:55 UTC, kristofnemere requested changes

2024-06-04 08:55 UTC, kristofnemere commented on apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/SubmissionCommentsPresenter.kt
> +        val pendingItems = runBlocking {
The db fetch would be better in the effectHandler, since it's gonna block UI, but as I see it would be a bigger change, and also it was like this originally

2024-06-04 08:55 UTC, kristofnemere commented on apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionHelper.kt
> +    fun saveDraft(
It would be better to make these suspend instead of runBlocking, and call from a coroutine scope, if it's called from an effect handler it could be in launch { }

2024-06-05 12:15 UTC, tamaskozmer approved these changes

2024-06-05 12:15 UTC, tamaskozmer commented on apps/student/src/test/java/com/instructure/student/test/SubmissionServiceTest.kt
> +//class SubmissionServiceTest : Assert() {
Please delete this class if these are not relevant anymore.

2024-06-05 13:53 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F88d5ff04-3938-4b5d-8a0f-ec369098ab82%2Fartifact%2F77afbe4985071d2b%2Fp%2F6ea8133f882dc0d71bf1d0f4680a273c&size=150x150">

2024-06-05 13:56 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff2292537-45ff-43dc-8ff4-3355500be3b9%2Fartifact%2Fc5363e753069a373%2Fp%2Faa628e12c7e1088a0dc0481b23480eb1&size=150x150>

2024-06-06 11:07 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Ffb1484d9-4737-4a63-aa5d-978415b6ba19%2Fartifact%2F8d3c301fb93e3621%2Fp%2F0d43b29c1523b1608f756a83713ed3a1&size=150x150">

2024-06-06 11:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fbd3a884f-fbca-4f68-9a50-9dfff220d4d0%2Fartifact%2Fdc2cce35ca3febf3%2Fp%2Fcc0afa0e26cef4183cf72353e0d0d594&size=150x150>

2024-06-06 11:10 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F48a715a2-84d6-427a-86f0-21988061c34c%2Fartifact%2Fce85678a3e753220%2Fp%2F19702abedd097cde4898bedb72adfec5&size=150x150">

2024-06-06 11:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe49fd386-5607-48d8-b921-8a57aab4beb9%2Fartifact%2Ff80e5d25337dc955%2Fp%2Fb7532da3006668db35f96ff7bd3bc8ce&size=150x150>

2024-06-06 11:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F22246074-ffcb-4bfc-81fb-3d69a57ecc94%2Fartifact%2Fe2719f1e3ced568e%2Fp%2Fe44b8c2462408d26dc73c201c0a835aa&size=150x150">

2024-06-06 12:06 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F428df327-11a2-4b70-9808-a8972fff2027%2Fartifact%2F829d741600e84e6e%2Fp%2Ffc8a466a92c281af2d1a104e710a525e&size=150x150">

2024-06-06 12:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb87fe40a-0e58-4ed0-8014-9757286ea7b1%2Fartifact%2Fd6e94e76d6684cb3%2Fp%2F3d1d1f6706816909b8bf17b805d79a66&size=150x150>

2024-06-06 12:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb8c3607c-ccac-4c8a-8a52-c040010abf62%2Fartifact%2F27a4cf5e785d3f1b%2Fp%2F6a5fc0835d89f6c9f3cae62ff7ffab1d&size=150x150">

2024-06-06 12:31 UTC, hermannakos commented on apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/ui/BaseUploadStatusSubmissionFragment.kt
> + * Copyright (C) 2019 - present Instructure, Inc.
The original class was renamed here, that's why it has the old date.

2024-06-06 13:00 UTC, tamaskozmer approved these changes

2024-06-06 13:01 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fcdb7451b-c383-494c-8953-3e7aaa8c48dd%2Fartifact%2F6e0a5355a0608406%2Fp%2F1b8b2fa7624f2cb18c107430f000fb48&size=150x150">

2024-06-06 13:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F330024da-2bff-480a-a082-b6bc3df54f74%2Fartifact%2F1e67711480066533%2Fp%2F03436f0edfd84be664646f516de5cc7f&size=150x150>

2024-06-06 13:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fecf2f3f2-6bd1-4f22-986e-674dfa2b42f7%2Fartifact%2F3cf4aa7d0ca57cf6%2Fp%2Fe89d2d7946d3c90baa246f5a6cf93832&size=150x150>

2024-06-06 13:29 UTC, tamaskozmer commented
QA + 1

2024-06-06 13:43 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fbb88c933-1b50-4508-ad69-9ff88e8d6540%2Fartifact%2F0f150b6a06c29ea9%2Fp%2F5abd2d09bc0022f66779599526849a27&size=150x150">

2024-06-06 13:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0992732a-45d5-4e5c-8ba1-f7430fe9a15e%2Fartifact%2Ff3b971c63dd3a34c%2Fp%2F6f4b72a178dcdbac9106a0d648be2862&size=150x150>

2024-06-06 13:45 UTC, kristofnemere approved these changes
QA+1

2024-06-06 13:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F51fbe3c3-2134-4420-9094-a9c7f5fb7319%2Fartifact%2Fd18f2a3fd12d5f89%2Fp%2F5bfa8a5085bc33105253673100da4a05&size=150x150">

2024-06-07 10:43 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fdeec6181-a60f-4b84-9037-4331434b2d5f%2Fartifact%2Ff6b35b5748af3dc5%2Fp%2F0d55a4c122b1f2a2ed70b7889c81e33c&size=150x150">

2024-06-07 10:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe66998b5-9acc-48f2-b730-b780c8ad8569%2Fartifact%2F7681a81ea050d244%2Fp%2Fe886d830870d81da1cb74f9025abf468&size=150x150">

2024-06-07 10:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F2637ccc2-6b06-4096-84be-cb7c9e76446f%2Fartifact%2Fbf79162d6e3504c2%2Fp%2F0459d82560da525f5c8980e6590a629e&size=150x150>

2024-06-11 09:49 UTC, kdeakinstructure approved these changes
QA 👍

2024-06-11 10:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ffced08eb-c49f-4220-98fe-abd9779f66a7%2Fartifact%2F2c0baf609be78cfa%2Fp%2Ffe04a7d6bb3f526921b92efa5836d2c7&size=150x150>

2024-06-11 10:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc2ff65bd-b0ae-4e4d-95c8-ae5117ea35ed%2Fartifact%2F3c68733971ab2743%2Fp%2Fd2eb5809b5b424cec41e40734f17e90a&size=150x150">

2024-06-11 11:31 UTC, merged