[MBL-17615][Parent] Student selector toolbar
instructure/canvas-android pull request #2472
Opened 2024-06-10 14:11 UTC by kristofnemere

Test plan: 
- compare the functionality with the flutter version
- prefs are not migrated yet

refs: MBL-17615
affects: Parent
release note: none

2024-06-10 14:22 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F1a61e9f9-0663-4221-8780-fbdb3c8c2231%2Fartifact%2F726c448e73ee141b%2Fp%2F166af0433f995bbc0c3e8e2a0b478cfd&size=150x150">

2024-06-10 14:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd59121a4-e5cf-44d8-9aae-7b89521c3307%2Fartifact%2Fcf79e957f51dd6bf%2Fp%2Fd38ac3a1efecf63f091cbe287107e85f&size=150x150">

2024-06-10 14:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5b024698-b64d-41b2-9ba3-5cdc76fd83a5%2Fartifact%2F598ec659a3bb31cd%2Fp%2F2817911aef1372c19bd3cc34ff36b980&size=150x150>

2024-06-11 08:16 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F8229cbca-faa0-4125-9b64-29f4b84f934d%2Fartifact%2F3b955433d1bd40e1%2Fp%2F7de73375d836f895a5b0e268e6827daa&size=150x150">

2024-06-11 08:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd453cfb8-00f4-47d9-9568-06e08d32aeda%2Fartifact%2F9dc69cb4c1bc9dbd%2Fp%2F3746c07aa09ac7f563141da1e6657339&size=150x150>

2024-06-11 08:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdf836583-6b67-4b6b-b7dd-8355b4a92582%2Fartifact%2Ff421b4ec737d5fa8%2Fp%2F72433109bc90987b94fd3ee71d6c5df9&size=150x150">

2024-06-12 10:28 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F98c9bbcd-be44-44d0-8025-5f2bd73b5180%2Fartifact%2F8f8a36cb8ea6f9bd%2Fp%2F9b3271da2e7cd5e5292385a833b16970&size=150x150">

2024-06-12 10:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fbec48b24-b429-4435-845a-0411fc91e828%2Fartifact%2F8a154900d672dea2%2Fp%2F753e9b85a599f5dbfafe1c29cb3aa151&size=150x150>

2024-06-12 10:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9b5a0ea7-545a-44c8-8210-42b6e1825cf6%2Fartifact%2Fbee0fefb00b98d78%2Fp%2F13cca7c9535ccfdc9e158cdde187c619&size=150x150">

2024-06-12 12:23 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F0fe37283-9cae-4746-af7b-ae7c46e1f682%2Fartifact%2F8feef00e2fba58ee%2Fp%2F4bc8bcf6d9e0e209fd06739744bb22d5&size=150x150">

2024-06-12 12:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb8182fe3-c05c-4723-8206-5bfa1402b937%2Fartifact%2Fda77b5b6a72d3d21%2Fp%2Ff69803505fe3f028efc7d7fa529a74eb&size=150x150>

2024-06-12 12:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1c025d4a-4163-4ae7-9f12-3bf720d0a30d%2Fartifact%2Fb0c3d8dab1f5da04%2Fp%2F7d69c7c72784351d8991b345da333911&size=150x150">

2024-06-13 08:33 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fb4d1fc0f-4047-45a4-b463-85e0daecfa51%2Fartifact%2F2affb9dcae6ff5c9%2Fp%2F00a527d6d8c4a198e5bd28d072de0710&size=150x150">

2024-06-13 08:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F04d6ff66-f594-4114-951d-ff9385c7be51%2Fartifact%2F9becf99f584f1c63%2Fp%2Fd5980431d06ccd7804067e929e2fa157&size=150x150>

2024-06-13 08:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6c785211-90a2-433f-bef6-86f71de303bf%2Fartifact%2Fa809a46bfb221540%2Fp%2Fccaaa1e93dd1e1502a14f55578b25ca0&size=150x150">

2024-06-13 10:56 UTC, kdeakinstructure approved these changes
QA 👍

2024-06-13 11:37 UTC, hermannakos requested changes

2024-06-13 11:37 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/di/MainModule.kt
> +class MainModule {
I'm not sure calling these `Main*` is the right call, since it does not describe the functionality. I would rather call it `StudentSelector*` or similar.

2024-06-13 11:37 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/main/StudentItemViewModel.kt
> +        onStudentSelected.invoke(studentItemViewData.studentId)
The invoke is not necessary.

2024-06-13 11:37 UTC, hermannakos commented on apps/parent/src/main/res/layout/view_student_item.xml
I would rename this to `item_student.xml` so it matches the other item layouts.

2024-06-13 11:37 UTC, hermannakos commented on apps/parent/src/main/res/layout/view_student_item.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
In the current version we indicate the selected student with elevation in the list.

2024-06-14 09:33 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F162da01f-528e-468e-b802-903e9d07e885%2Fartifact%2Fd933b581fdde6351%2Fp%2F78e40ec7cf566109bbf182d029c37156&size=150x150">

2024-06-14 09:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9bfb875d-54e9-4869-b024-5826724d0b4a%2Fartifact%2Fd5e04d23244acb02%2Fp%2Fe4c41d4e49cdbb5d9bb1ebda540ef520&size=150x150>

2024-06-14 09:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdf593248-48af-432f-b223-873902eacc44%2Fartifact%2F54f3cca00feada5b%2Fp%2F1c1f25e518da589b792c81cc91e77688&size=150x150">

2024-06-14 11:01 UTC, tamaskozmer approved these changes

2024-06-14 11:54 UTC, hermannakos approved these changes

2024-06-14 11:57 UTC, merged