[MBL-17267][Student][Teacher] - Implement Calendar Screen E2E tests
instructure/canvas-android pull request #2478
Opened 2024-06-18 10:24 UTC by kdeakinstructure

Implement Calendar Screen E2E test in both the Student and Teacher apps
Add page object methods.

refs: MBL-17267
affects: Teacher, Student
release note: none

2024-06-18 10:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F66cf6721-6b89-4322-ba67-d0858158cc2c%2Fartifact%2F3e587983be99693b%2Fp%2Fb6f5f6dea8f88969a171d4b9e65c724b&size=150x150>

2024-06-18 10:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbbb2d468-b780-496f-a288-0a341663cf3b%2Fartifact%2F97672a39d09cb5e6%2Fp%2F60d02b834e29334f18a2f65625654a93&size=150x150">

2024-06-18 10:37 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F84ca2929-8844-4d39-8ccb-d685b9655e66%2Fartifact%2Fc3593de4071b70e6%2Fp%2F02e5fa68f3ae40c02f10dff666e4314e&size=150x150">

2024-06-20 10:40 UTC, hermannakos requested changes

2024-06-20 10:40 UTC, hermannakos commented on apps/student/src/androidTest/java/com/instructure/student/ui/e2e/compose/CalendarE2ETest.kt
> +        //Calendar expand/collapse state remains sometimes from previous runs and this way we are handling whether if it's starting from a collapsed or expanded state.
We should clear the prefs before the test runs, so we don't have this problem.

2024-06-20 13:36 UTC, tamaskozmer approved these changes

2024-06-21 10:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F359c5cfd-8fca-465e-a1cc-537a87a48395%2Fartifact%2F70a811efb83d0e49%2Fp%2Fcf407d08f57c5ac46bcfe873eb4a0bb7&size=150x150>

2024-06-21 10:36 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fdd9b8589-1e0d-46c0-b68d-f3deff741c09%2Fartifact%2F460069b3909534d5%2Fp%2F2e8de69aa59a43427f338d91f0c2651e&size=150x150">

2024-06-21 10:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdd729577-064b-444d-b0aa-fef09387ecd9%2Fartifact%2F4839b9bf42ea4ec1%2Fp%2F88e3928ed901bc290e8af83056fc055e&size=150x150">

2024-06-21 10:45 UTC, hermannakos approved these changes

2024-06-21 11:09 UTC, merged