[MBL-17485][Parent] Course list screen
instructure/canvas-android pull request #2480
Opened 2024-06-18 15:15 UTC by kristofnemere

Test plan: compare with the flutter version

refs: MBL-17485
affects: Parent
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed

2024-06-18 15:26 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F5c9803dd-091d-43bb-8c77-b8082c8ab47e%2Fartifact%2F7db0aaea894a9e72%2Fp%2Ffdba7a677d8663a554c625a1a5022a99&size=150x150">

2024-06-18 15:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F50e80196-e57d-4973-bbdd-d2e2c9301f4d%2Fartifact%2F9b85d5da77f9e947%2Fp%2F83fe6a106e598131fa7e6445690ed7a4&size=150x150>

2024-06-18 15:28 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcbd0e3df-9803-4ef7-86f7-3d88927313db%2Fartifact%2F21348d239a26b19c%2Fp%2F284919c935ac76e4614c31ae47a653cd&size=150x150">

2024-06-20 08:58 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F5c99ffa1-ebe7-48a3-845e-077eb0ed901c%2Fartifact%2F914b2c5068e048ee%2Fp%2F537643a9b45f15ff4ae8f3c2e9749543&size=150x150">

2024-06-20 10:21 UTC, hermannakos requested changes

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesUiState.kt
> +    val loadError: Boolean = false,
I would not call this `loadError`, `isError` would be better. Also `loading` could be `isLoading` as well to be consistent.

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesScreen.kt
> +                } else if (uiState.courseListItems.isEmpty() && !uiState.loading) {
We could move this logic to the view model and add an `isEmpty` flag to the state. This way it could be more testable.

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesScreen.kt
> +            if (!uiState.loading) {
Do we need to hide the items on pull to refresh?

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesScreen.kt
> +                    CourseListItem(it, uiState.studentColor, Modifier.clickable {
I would set the clickable modifier in the composable and pass a lambda for the click handling.

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesUiState.kt
> +data class CourseItemUiState(
I would call this `CourseListItemUiState` to indicate that it's for this screen only.

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesUiState.kt
> +    val courseName: String = "",
These could be nullable, just like on the api.

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesViewModel.kt
> +    private fun getGradeText(course: Course): String {
The api returns the grade as nullable, if this function returns a nullable string the logic could be cleaned up a lot.

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesViewModel.kt
> +            val courses = repository.getCourses(selectedStudent!!.id, forceRefresh)
Please check for null. don't use `!!`

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesViewModel.kt
> +    fun studentChanged(student: User?) {
We should really look into making the student change reactive.

2024-06-20 10:21 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesViewModel.kt
> +                            "${apiPrefs.fullDomain}/courses/${action.courseId}"
We could add some destination system to the app, so this whole url creation could be simplified.

2024-06-20 10:21 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/EmptyContent.kt
> +    emptyTitle: String,
These could have default values.

2024-06-20 14:25 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F5696527c-cb5f-4ad9-876e-75a7dafc65ff%2Fartifact%2F8040f7694efd05ca%2Fp%2Fa2f00a00a5b6bf165c0afc584ae47f2d&size=150x150">

2024-06-20 14:43 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F45ade69a-b93d-40ed-916f-d4576c49ea8e%2Fartifact%2Fa545c4e338f8168d%2Fp%2F1ac2590e74da4fa60fda80220c607de5&size=150x150">

2024-06-20 14:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F22f9b413-5d67-4e38-9a64-47cf6fe3110f%2Fartifact%2F3f0ace2629ab09ce%2Fp%2F39c1361fadfe97158e306050451378f0&size=150x150>

2024-06-20 14:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7cdf27c4-01e5-4f82-bb85-49ba0046269f%2Fartifact%2F978974579608dc30%2Fp%2F39d911b106d6e4400dcf84bb6f6fd373&size=150x150">

2024-06-20 15:11 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Ff197a54f-cf23-433a-a0f7-e0614b462fcf%2Fartifact%2F8e86bc5ef331007d%2Fp%2F147d932c34219dae67028fec17754d38&size=150x150">

2024-06-20 15:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa1727ca8-669f-4bdc-9f53-58d8e447e32b%2Fartifact%2Ff99d7f05ca824248%2Fp%2F1bbb9c3238f0d1ba31b71e39fd5b11b8&size=150x150>

2024-06-20 15:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fddb44e11-ff91-4346-98a3-33e8172afe72%2Fartifact%2F15d236a54b8ed308%2Fp%2F4721c30349b61c9e1b8468707114cca9&size=150x150">

2024-06-21 11:54 UTC, tamaskozmer requested changes

2024-06-24 13:30 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-06-24 13:45 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fa05e2d40-3574-4d45-b436-4c3b1040f700%2Fartifact%2Fe24dec2a4ad28c94%2Fp%2Fd12cbdd94f9c5dfb44e6b854850ad908&size=150x150">

2024-06-24 13:45 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F45e46ad4-bfbd-435d-9d60-b0957ab1e2d7%2Fartifact%2F06d4851bca8fc883%2Fp%2Fd5070457abccc472ac12f4ebd7f80596&size=150x150>

2024-06-24 13:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa005d636-5319-4fb8-8862-9a380c8990d5%2Fartifact%2F89e4d539829f28f0%2Fp%2Fe18204b4a80437508be12999e7887524&size=150x150">

2024-06-24 14:26 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fc8fa4945-0a45-4f9a-a5f5-7ed0ff32ad2d%2Fartifact%2Fc72d4e0b9d98985c%2Fp%2F645b15918b3ddfd2098423d6a1fa3d8a&size=150x150">

2024-06-24 14:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdb9f4dbd-b07b-47fe-883a-a7a7ede6b7ab%2Fartifact%2F1726eaf7dc698d67%2Fp%2Ff69de4bc678797fafb1b80ec33d284c0&size=150x150>

2024-06-24 14:27 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2b74e09c-918c-477f-84fe-fdc1c535ce45%2Fartifact%2F4bf2b87f43287cda%2Fp%2Fa8dd93ae9057b5ffc14f5a6f2389d8f0&size=150x150">

2024-06-24 17:53 UTC, kdeakinstructure approved these changes
QA 👍

2024-06-25 10:38 UTC, hermannakos approved these changes

2024-06-25 11:58 UTC, tamaskozmer approved these changes

2024-06-25 12:17 UTC, merged