[MBL-17638][Student][Teacher] Calendar selection A11y
instructure/canvas-android pull request #2482
Opened 2024-06-20 12:33 UTC by hermannakos

Test plan: See ticket.

refs: MBL-17638
affects: Student, Teacher
release note: none

2024-06-20 12:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1bb08f27-b5c0-468a-acb4-c0d554299440%2Fartifact%2F601fbfb477b34ad3%2Fp%2F21029494fdec37f6d824ca732f4ddb9d&size=150x150">

2024-06-20 12:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ffda57f57-dc7b-4730-a9fd-957dc9177b1c%2Fartifact%2Fc2de0d5e846dd0de%2Fp%2F7db2aea292d6dcecdedbc5313385031c&size=150x150>

2024-06-20 13:40 UTC, tamaskozmer requested changes

2024-06-20 13:40 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SelectCalendarScreen.kt
> +                    "${canvasContext.name.orEmpty()} ${if (selected) context.getString(R.string.selected) else ""}"
I would extract this to a string with arguments. It might have different structure in some languages.

2024-06-20 14:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb6e89188-8a11-41f1-83c5-fd88c7b363f0%2Fartifact%2F9eb40f833108cf7d%2Fp%2F1c6f29f12a1828f2a3769a0eea2d7f1c&size=150x150>

2024-06-20 14:15 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F1a566d40-b091-482c-a6c1-113369e7bba2%2Fartifact%2F5cde527509a7c031%2Fp%2F8183fad1d914dbbd4525c98722145a30&size=150x150">

2024-06-20 14:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0d842eaa-838e-4b2f-936d-5820d647823d%2Fartifact%2F464ee11101da7207%2Fp%2F59c72a6462ec1979ad919059af38e001&size=150x150">

2024-06-21 08:39 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F970c06a0-1e69-46bc-84a9-2928425ecfca%2Fartifact%2F975e6744f9fcde50%2Fp%2F4f6cf995ac95d7e93d9954b9789fa2fd&size=150x150">

2024-06-21 08:39 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F5ec4dd0e-8ba0-4da0-9375-81852716f44f%2Fartifact%2Fb42097a569e94e6d%2Fp%2Fa2360546fdf342e6844fc1661c4f53c7&size=150x150>

2024-06-21 08:41 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9b08f7a1-792a-418c-8e9b-637e8e685500%2Fartifact%2Fbf50a679aec0f7ca%2Fp%2F59780413a74c46043653e82f161ce9da&size=150x150">

2024-06-21 10:30 UTC, kdeakinstructure approved these changes
QA 👍

2024-06-21 12:09 UTC, tamaskozmer approved these changes

2024-06-24 07:02 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F0318cb30-bf47-4362-bb6e-2fe812490b8c%2Fartifact%2Fdfbb16953b30bc4f%2Fp%2Fcb26c3cd5f6f94a251fa89681a6ec2e7&size=150x150">

2024-06-24 07:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe73ea1d6-d67e-4430-aebd-90b47c3b1411%2Fartifact%2Fb64f69872c59332c%2Fp%2F157c92df361d19f36e08fd52da456149&size=150x150>

2024-06-24 10:25 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fd32a233d-1c2d-493d-bb79-e9121072d4aa%2Fartifact%2Ff5950656506132ac%2Fp%2Fa758a36e983c0c6fb1d00c0b92b7014d&size=150x150">

2024-06-24 10:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa04e24db-b467-48a2-a3f1-403670eada3e%2Fartifact%2F677eb073c03f8597%2Fp%2F07e6ed4720d928910864cb6fd2e55a50&size=150x150>

2024-06-24 10:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7bdaf3d9-a75e-47ce-bd1b-da07e928f132%2Fartifact%2Fadbe508f5a791ba6%2Fp%2Fbb4c7a2d4e6d6c6a95d0db450075d97f&size=150x150">

2024-06-24 11:22 UTC, merged