[MBL-17610][Parent] Implement help dialog
instructure/canvas-android pull request #2496
Opened 2024-07-16 14:18 UTC by domonkosadam

Test plan:
- Select Help option from the Navigation Drawer.
- Try out all available options at the dialog.
- Compare the available options with the previous Parent app
- Both Student and Parent app should be tested because the Report a Problem dialog has been refactored

refs: MBL-17610
affects: Student, Parent
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-07-16 14:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdb0a9a28-a2ec-4523-a6bb-a37e11707334%2Fartifact%2F155417f51c032dbd%2Fp%2F9c0f1708e8fb21428b8db9306030a7db&size=150x150">

2024-07-16 14:30 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F8f933cb7-8b5b-40ce-b6ee-fe4eeb2b3520%2Fartifact%2Fa0ee5d4e5aa3c9d9%2Fp%2Fc6c92012131cb4186c469f66ce8cb1fb&size=150x150">

2024-07-16 14:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0bfe4fb5-052f-427f-8a64-dbe96077567c%2Fartifact%2F29b9f0775cca7454%2Fp%2F99f6d659cd0947045fa808bca5a8889e&size=150x150">

2024-07-16 14:54 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fcfb933b6-b12a-4ac9-b9a5-ddda675160d4%2Fartifact%2F8c911dd130ae4067%2Fp%2F1dfbdc44ebbff6e0aa2a3a4b26b19414&size=150x150">

2024-07-16 14:57 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F051d18de-6f4f-42a7-a387-12a3f7e26e52%2Fartifact%2F905c652ee72b894b%2Fp%2Fe15df3bc4055eb002b807d9abc007504&size=150x150>

2024-07-17 07:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F00b32085-f142-4321-8b77-076f5db11cb5%2Fartifact%2F50062767d412a021%2Fp%2F63615e86e4ed393293bc6ca69e05386f&size=150x150>

2024-07-17 07:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F582a20b1-ec67-4472-97f4-e9d4cb6137a4%2Fartifact%2F1c80368667556ab6%2Fp%2F3850ae2a23736bccf879f20d6fc7f288&size=150x150">

2024-07-17 07:30 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fec9c227e-5fd8-40ba-88c0-d329cd26dec9%2Fartifact%2F58cf530347fe77a0%2Fp%2F891dfd98ebf7e71bdf159cf96cd2db2a&size=150x150">

2024-07-17 08:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F164b8299-667b-4f14-ae61-36adb087c725%2Fartifact%2F9c26e669b5f03fe8%2Fp%2Fdbc4eb6c37fdb965b66262f7e29b884d&size=150x150>

2024-07-17 11:52 UTC, tamaskozmer requested changes

2024-07-17 11:52 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/help/ParentHelpDialogFragmentBehavior.kt
> +            arguments = ErrorReportDialog.createBundle(parentActivity.getString(R.string.appUserTypeStudent))
This should be `appUserTypeParent`.

2024-07-17 11:52 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/help/ParentHelpDialogFragmentBehavior.kt
> +        val intent = Intent(Intent.ACTION_VIEW, url.toUri())
I would put a TODO here just in case we don't forget to change this to route to a WebView, when we implement the Internal WebView for the Parent.

2024-07-17 12:02 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/help/ParentHelpDialogFragmentBehavior.kt
> +        val intent = Intent(Intent.ACTION_VIEW, url.toUri())
In the flutter version it opens the external browser as well, so we can keep it like this imo

2024-07-17 12:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa962d9fe-9f3d-4459-b200-7d9c0c92d9f9%2Fartifact%2F14de197e139555ef%2Fp%2F9074f377728168c5663fcbfee9bf0844&size=150x150>

2024-07-17 12:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7dc80b85-170f-41be-be4e-464db43aafb5%2Fartifact%2Ff68656509108c797%2Fp%2Faf34d8e036cc760c48ae5fc8b88aff32&size=150x150">

2024-07-17 12:27 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F5f07a691-69d1-4d43-a297-1e7ca290f100%2Fartifact%2Fd892b39d4d664919%2Fp%2F6e72c1add4756aad13e77f6366614e37&size=150x150">

2024-07-18 06:48 UTC, kristofnemere requested changes

2024-07-18 06:48 UTC, kristofnemere commented on apps/teacher/src/main/java/com/instructure/teacher/features/help/TeacherHelpDialogFragmentBehavior.kt
> +        Utils.goToAppStore(AppType.PARENT, parentActivity)
This should be TEACHER

2024-07-18 09:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc267e296-eae1-4d78-82cf-ad4edc10dd57%2Fartifact%2F11b06f329f3af85a%2Fp%2F19f982682c8995f13dc8f82d7c94de55&size=150x150>

2024-07-18 09:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fdcd7f35d-af9e-4ad1-93b0-6730ce23155e%2Fartifact%2F074e8249bc8693a1%2Fp%2F7f08aa93590dce68365bc1412fcf54dd&size=150x150>

2024-07-18 09:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5730fc57-9399-4078-b420-c4bf624bee8f%2Fartifact%2Fc5372b75cbdf5027%2Fp%2F25a004958d14553bfcb84c908bacfc65&size=150x150">

2024-07-18 09:58 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F447f0a33-12e0-4e55-b94a-7a92e2fec4f1%2Fartifact%2Ff78aae53ca0528c0%2Fp%2Ff88f56972374d62552f13e5e60ee60bc&size=150x150">

2024-07-22 10:42 UTC, kristofnemere approved these changes
QA+1

2024-07-22 11:34 UTC, tamaskozmer approved these changes

2024-07-22 14:18 UTC, kdeakinstructure approved these changes
QA 👍

2024-07-22 14:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa963db45-f290-4334-bb8e-a122cdc8fb22%2Fartifact%2Fba68c5c66932a6e0%2Fp%2F4a2d2271b80eaa107a8489a94179b80c&size=150x150>

2024-07-22 14:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F73844fb7-8fbf-410a-a65f-e2f7fa32d7ad%2Fartifact%2F507ccc43be0a47ef%2Fp%2F50a9892308f24e10ca89a5721d4cbea7&size=150x150">

2024-07-22 14:47 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F30057354-0059-4611-8ed0-144f21df3577%2Fartifact%2F00456531167d18e1%2Fp%2F6080b4b809eafa0390b405d27ea6782d&size=150x150">

2024-07-23 14:55 UTC, merged