[MBL-17486][Parent] Alerts list
instructure/canvas-android pull request #2497
Opened 2024-07-16 15:06 UTC by hermannakos

Test plan: Compare with the flutter version.

refs: MBL-17486
affects: Parent
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite
- [ ] Tested in dark mode

2024-07-16 15:14 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-07-16 15:19 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F3d2e85fa-831c-4376-8ec9-be58581a458c%2Fartifact%2Fa8e7d24bc44d242e%2Fp%2Fc120ed258919870f1f6f86c602e32f2e&size=150x150">

2024-07-16 15:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9f1cd07c-51e8-4b43-9c47-1f67493f983e%2Fartifact%2F9986150af30c3dc9%2Fp%2F16a6c54dae2fb6031fd9cf5b3857acf1&size=150x150>

2024-07-17 09:25 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-07-17 09:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa5a9f3d1-b66d-4146-b470-2a5856b2827c%2Fartifact%2F22e52d7951f74501%2Fp%2Fa6f056331fccf1a8515df1bbf7badb41&size=150x150>

2024-07-17 09:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F921c0602-d5ba-4ff9-a5d9-d5c481711994%2Fartifact%2F738fc1369931b8b4%2Fp%2Ffcc48125fe4ce778db0df2a69bdd6329&size=150x150">

2024-07-17 09:48 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-07-17 09:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0f6db5df-b9cb-4ed2-8031-aaa955b62bb8%2Fartifact%2F42f0d416e295b59d%2Fp%2F649ba0aa6dbb425d807e706843123587&size=150x150>

2024-07-17 09:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5b799604-194e-4037-88dd-eb9a2f28aad2%2Fartifact%2Fce654dcdbac01a24%2Fp%2Fd4ab27933ae7627442aa33e49c14c9c0&size=150x150">

2024-07-17 11:06 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fae14a08a-bea9-43e5-a326-8e6b3afa4a91%2Fartifact%2F905ea87aedfe8347%2Fp%2F678537196801bab20ccf6e74b819cd38&size=150x150>

2024-07-17 11:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0b3653d2-f7e0-49be-97b3-e196498256cc%2Fartifact%2Fea1fa449fb82ffa9%2Fp%2Fc705bac2685b9fc07b042d2b3e619e92&size=150x150">

2024-07-17 11:07 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F0b636436-a1b1-4415-a1b3-38699b328398%2Fartifact%2Ff6e6b539f8930c87%2Fp%2Fc4ae986a9cf9bd788044b88960bf28d7&size=150x150">

2024-07-18 12:49 UTC, kdeakinstructure requested changes
Issues sent via Slack message.

2024-07-22 10:54 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F074d1441-1565-418c-abfe-894d27f771d8%2Fartifact%2Fe9bfd67d95ad0ed4%2Fp%2F06744103260d33893cf18c22cf2e2c0e&size=150x150">

2024-07-22 10:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdb5bf066-b501-4ec6-84cb-aa21f38400ee%2Fartifact%2F172342de45df66b4%2Fp%2F5f134ce88efcc9a3b60a6d542bf118b1&size=150x150">

2024-07-22 10:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F929fc476-3d24-48a7-af14-f09aa6e6e40e%2Fartifact%2Fa7b3681a7910778f%2Fp%2F4f571fa7eac6fd14e5551ba6314e669d&size=150x150>

2024-07-22 11:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc38f8f5e-6874-475f-b3a7-766f9e0cd099%2Fartifact%2F3ead38c36488cd6c%2Fp%2F8218d77c434f67e1482520bef52d8dc6&size=150x150>

2024-07-22 11:34 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F1d8bb54a-ba2a-4497-8260-bde8e3016429%2Fartifact%2Fce9a683a6980af4a%2Fp%2F207f989c4423dfe4481ea0dfdf815c10&size=150x150">

2024-07-22 11:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4d009616-ce5d-48ba-a8a1-0f9585bcf278%2Fartifact%2F41126adba53a91d2%2Fp%2F80d258788ff2cbaf3eb1aaaf8170c8cd&size=150x150">

2024-07-22 13:48 UTC, kdeakinstructure approved these changes
QA 👍

2024-07-22 15:19 UTC, tamaskozmer requested changes

2024-07-23 10:45 UTC, kristofnemere requested changes

2024-07-23 10:45 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/util/Extensions.kt
> +var SemanticsPropertyReceiver.drawableId by DrawableId
This might go to pandautils

2024-07-23 10:45 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsViewModel.kt
> +            this.thresholds = thresholds.associateBy { it.id }
In the Flutter version there is a filtering logic for thresholds: AlertsHelper filterAlerts function

2024-07-23 13:17 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fac87d55e-b058-4f3f-ab31-b678c36a794f%2Fartifact%2Faef32aabda964bc3%2Fp%2Fc1b9028e0ad2def186e9486ae3fa9e21&size=150x150">

2024-07-23 13:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F19cdea3e-3599-43f8-88f4-f47721aad227%2Fartifact%2F4787206c2562ca5a%2Fp%2Fd1ec69ade8d400d2823732e34e690ceb&size=150x150>

2024-07-23 13:17 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8ee12cfb-dfc1-44c5-8489-72210654e2c2%2Fartifact%2Fe7b8b22cc7c629fa%2Fp%2F74f37f5fd8b5791152b9d69385e82410&size=150x150">

2024-07-23 13:21 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsScreen.kt
>              alertType.isAlertInfo() -> context.getColor(R.color.ash)
You missed this one.

2024-07-23 13:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F089f44cd-84b4-465f-bcc9-289112a7f592%2Fartifact%2F9343a1e54d2a24f1%2Fp%2F252d4e6ba176fbb5fe0015a5b15fee0d&size=150x150>

2024-07-23 13:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F33445043-2492-41f3-bf6a-4be87578a075%2Fartifact%2F8ded79a21f0aee95%2Fp%2F32aa00f7a86b40882670990e0d100c00&size=150x150>

2024-07-23 13:34 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F4dd83b63-1d23-4ac4-a970-1461221e857e%2Fartifact%2F3917181b90ab1585%2Fp%2F63edd1080ac4b740d9da88d63b750c08&size=150x150">

2024-07-23 13:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6d71d084-c6a7-4fbd-b34a-27be948f0c09%2Fartifact%2F3b20860277760ca2%2Fp%2F2ea2baa3fcfd96fe46ffff9858f6d296&size=150x150">

2024-07-24 12:50 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F9c741394-02e0-4530-a70f-308981d37646%2Fartifact%2Fe8dfe2d3c183d0c3%2Fp%2F72a85434ec508391b508316c16b81d81&size=150x150">

2024-07-24 12:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F54b54c01-307e-490d-9e7b-295523ee45e1%2Fartifact%2F13a041c3468129da%2Fp%2F45bc37cb36a6a0499f2012af76e63c15&size=150x150>

2024-07-24 12:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F5c80c171-af45-418a-80cb-5f7e3f91e7c5%2Fartifact%2F3c86407ce84a63bb%2Fp%2F367d418d7be0dc209531e384f38641c6&size=150x150">

2024-07-25 08:39 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff6fce9e1-458d-4856-b58d-3cd79254829c%2Fartifact%2Fdd8cc17dff41c4e6%2Fp%2Fa40024d25e00a4c87decfc1af5b5216f&size=150x150>

2024-07-25 08:40 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F97a1b985-232d-4255-874a-61287e0419b4%2Fartifact%2F774e63cedd20f229%2Fp%2F7537f7fc366cbbc066d3003d035483fa&size=150x150">

2024-07-25 08:40 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F9d01092f-a0e1-42d7-bdb0-d656f4d7fef2%2Fartifact%2F97f80b69c6d82b22%2Fp%2Fb9f2176e071016b4bede324244b2bb5a&size=150x150">

2024-07-25 09:25 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fa29f21d0-1afe-45e9-9fdd-26151fc0e0d9%2Fartifact%2F28065620a4768523%2Fp%2F74d0ded684f6e0ff8a27644af54fc9f1&size=150x150">

2024-07-25 09:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F282c246a-6a4f-4ee4-8159-4d0502624993%2Fartifact%2F14261ec50a98b8b6%2Fp%2Fa148c297a2ca0fa5c3c3b8a70e300ade&size=150x150>

2024-07-25 09:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb2f7e7bb-c67d-493e-be92-2fac3e5842fe%2Fartifact%2F189bf74d1e5a041d%2Fp%2Ff64fbe13f5f1878c76fdebd72caf1d19&size=150x150">

2024-07-25 11:28 UTC, tamaskozmer approved these changes

2024-07-25 11:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F58b8398a-8f8d-409d-8913-0137db7a748f%2Fartifact%2Fbbffb1cf65074fac%2Fp%2F39eb117affc0d3deac4697b201682e76&size=150x150>

2024-07-25 11:42 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F0ed96ee2-283b-4ffe-a080-a5d4f3830474%2Fartifact%2F50dc1fb64f8ebd63%2Fp%2F4745f91e9ff2757dbd6f016404d32177&size=150x150">

2024-07-25 11:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F41ce88c8-e5a5-491c-9c6e-35e5cb924a4f%2Fartifact%2F40f9b4523c798a73%2Fp%2F4a295aa6dbced65df249ca93690a27e3&size=150x150">

2024-07-25 11:50 UTC, kristofnemere approved these changes
QA+1

2024-07-25 11:57 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F3d2a424b-9a3b-4f22-89fc-d6659041ff88%2Fartifact%2F61a752457938b730%2Fp%2F97b21ecbef981cb8d816f6d868aa2ad5&size=150x150>

2024-07-25 11:58 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ff571d741-6924-4187-909c-c0a9e03daa58%2Fartifact%2F58fd2e299cdc9b1b%2Fp%2F3cae5e53e2e11b7a2e1c81165f6a3ef6&size=150x150">

2024-07-25 11:58 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fbe482902-2a5d-44e6-a76e-3c3bdb70cfd5%2Fartifact%2F6eec896af642315c%2Fp%2Fe220f1280e704034769b2dfaf9be4d73&size=150x150">

2024-07-25 14:09 UTC, kdeakinstructure approved these changes
QA 👍

2024-07-25 14:10 UTC, merged