Inbox compose components
instructure/canvas-android pull request #2507
Opened 2024-07-26 10:48 UTC by domonkosadam

Implemented on Compose Screen:
 - Context picker
 - Recipient picker
 - Individual send
 - Subject field
 - Body field

To be implemented:
- Attachment handling
- Reply, Forward handling

2024-07-26 10:49 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-07-26 12:33 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-07-26 13:08 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F739a8d3d-db01-48d2-a17d-4b189f983894%2Fartifact%2F31093a419a04641e%2Fp%2Fba687559fb1ea1d1180fba02d3188001&size=150x150">

2024-07-26 13:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F22e4b883-9fcf-46d9-8ef5-7eea5ae87a05%2Fartifact%2Fb24299ca55c30006%2Fp%2F550784ff3fcd2adacf76afa831b52e77&size=150x150>

2024-07-26 13:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F42dd1d30-45c6-41e2-9cd6-9d59a262b5e5%2Fartifact%2Fcf0ee43c2f622e9d%2Fp%2F2078952ffc6117ac0b099aa507818a51&size=150x150">

2024-07-29 12:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F0f68d684-5911-43d0-b132-84e4cd7113a3%2Fartifact%2F7ac1f5b45460f490%2Fp%2F404e1aa6b2fb24d72c4952153c0bd754&size=150x150">

2024-07-30 07:59 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F145a57e8-e94f-4d88-b667-fd20a8203339%2Fartifact%2F83eaf7a58253b372%2Fp%2F9d8ab987411de32648ee8da45a89683f&size=150x150">

2024-07-30 08:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F23f86a65-97d0-4952-886c-f79e1aefd02a%2Fartifact%2F34e9dabf25aa9f87%2Fp%2F5c6d39217eb592c28dbc81697499c502&size=150x150">

2024-07-30 08:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe22649f1-2e1e-47f1-8aa0-efeecb0c842b%2Fartifact%2F4475feb2600e939f%2Fp%2F7a2fd7f6666eb5c5ee8c3c954df55d08&size=150x150>

2024-07-30 13:51 UTC, kristofnemere requested changes

2024-07-30 13:51 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/list/ParentInboxRouter.kt
> +    private val fragment: Fragment,
we don't need the fragment I think

2024-07-30 13:51 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/util/navigation/Navigation.kt
> +                deepLink {
We don't need deeplink for this

2024-07-30 13:51 UTC, kristofnemere commented on buildSrc/src/main/java/GlobalDependencies.kt
> +    const val COIL_COMPOSE = "io.coil-kt:coil-compose:${Versions.COIL}"
I added compose glide in an other PR, if we can do the same thing with that we should just keep one of them

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/Avatar.kt
> +fun Avatar(user: Recipient) {
Actually I implemented this, you can find it on master

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasThemedTextField.kt
> +    cursorBrush: Brush = SolidColor(Color.Black),
Wouldn't be textDarkest better?

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelSwitchRow.kt
> +        Switch(
I think this needs some theme color

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeFragment.kt
> +                val uiState by viewModel.uiState.collectAsState()
I would just have 1 main ui state, and that could contain the other ones, also the whole AnimatedConent could be in a composable, we did similar in CreateUpdateEvent

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +    fun handleAction(action: InboxComposeActionHandler, activity: FragmentActivity?) {
Activity shouldn't be passed here, you can communicate from VM to Fragment by events

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +                updateUiState(uiState.value.copy(screenOption = InboxComposeScreenOptions.ContextPicker))
there is an extension for updating:

_uiState.update { it.copy(screenOption = InboxComposeScreenOptions.ContextPicker) }

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +private fun SectionHeaderView(subTitle: String) {
we usually pass a modifier param for all composables

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +private fun DataRow(context: CanvasContext, actionHandler: (ContextPickerActionHandler) -> Unit) {
missing modifier param, there are other places as well, please fix them

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/EnrollmentTypeExtensions.kt
> +val EnrollmentType?.displayText: String
This could be placed to ModelExtensions

2024-07-30 13:51 UTC, kristofnemere commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/compose/InboxComposeRepositoryTest.kt
> +    fun `Get courses successfully`() = runTest {
Pagination could be tested as well

2024-07-30 14:02 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +    val pullToRefreshState = rememberPullRefreshState(refreshing = false, onRefresh = {
I am not sure pull to refresh is really necessary here, but if we want to have it, please don't remove the already loaded items when refreshing. If we do a pull to refresh and it fails we will get an empty screen.

2024-07-30 14:06 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +                            color = Color(ThemePrefs.brandColor),
I think this should be buttonColor.

2024-07-30 14:12 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/recipientpicker/RecipientPickerScreen.kt
> +fun RecipientPickerScreen(
This should have a preview.

2024-07-30 14:13 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +fun ContextPickerScreen(
This should have a preview as well if we are not reusing the other similar component.

2024-07-30 14:21 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelTextFieldRow.kt
> +fun LabelTextFieldRow(
I remembered we have something similar, but that's a private Composable currently. It's in the CreateUpdateEventScreen file. Maybe we can replace that one with this or vice versa in the future.

2024-07-30 14:22 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelTextFieldRow.kt
> +        CanvasThemedTextField(
I think we need to specify the color of the text field. As I saw it has a default color that doesn't match any of our design colors. I think it's `textDark` in other places.

2024-07-30 14:23 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/TextFieldWithHeader.kt
> +fun TextFieldWithHeader(
This needs a preview as well.

2024-07-30 14:34 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasThemedTextField.kt
> +    cursorBrush: Brush = SolidColor(Color.Black),
I think we need textDark like on the create event.

2024-07-30 14:35 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +private fun SectionHeaderView(subTitle: String) {
Not just for the public ones?

2024-07-30 14:46 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +private fun SectionHeaderView(subTitle: String) {
I prefer to pass for all, except screen composales, but it's okay

2024-07-30 15:01 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F9d0ee98f-15ed-4d43-8529-0e7e48800dea%2Fartifact%2F844248eebc34d411%2Fp%2Fec66bb63d3bceaf9fbd2b23056e6aef4&size=150x150">

2024-07-30 15:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb3b2a9da-14c1-4270-b853-055566afe783%2Fartifact%2Feb574ba9a0610f5b%2Fp%2F21094cdbc2ec8b6aa2c558147ad3b3c9&size=150x150>

2024-07-30 15:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F54f90706-b244-4302-bb3a-55b451c64548%2Fartifact%2F0281428fd0cf5796%2Fp%2Fedd5e143dcdac08fdcda18b52ec385c4&size=150x150">

2024-07-31 07:48 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F653a98d7-bfc9-4419-92d4-367298c0c310%2Fartifact%2Fc9b59b8c98a0af45%2Fp%2F4c43fb78aa1854a9bdda6983da96bb9c&size=150x150">

2024-07-31 07:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fef885b9e-0761-4b52-aef7-b69d059c43e5%2Fartifact%2F736b55ac3c7b49a3%2Fp%2F678ebc22d99cdc382f89137bddd96559&size=150x150>

2024-07-31 07:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F752ae03c-b762-4ea9-b714-4f96a7b68135%2Fartifact%2F4611559cab2566ba%2Fp%2F49b56e7d00b1808643380009c383fd94&size=150x150">

2024-07-31 09:10 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F0d6bbc04-a6f8-488f-b3d7-ed1536524762%2Fartifact%2F4333caa30ff4c3ba%2Fp%2F235a4bafba0fa58f9ebeaf55041ca2c2&size=150x150">

2024-07-31 09:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F63f2d743-59ff-41ce-a15d-9b7288dcae41%2Fartifact%2F94b0e4bf80faab1e%2Fp%2F83bd6782b1eeed18a91d33cc9ddd59a8&size=150x150>

2024-07-31 09:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F017e4d45-1af0-4be9-a133-49203bc65f70%2Fartifact%2Fedc80cd085c0eaf7%2Fp%2Fb1a1bd1f12b10cc55101dff80637142f&size=150x150">

2024-07-31 14:43 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F9f538d01-bce7-4797-8512-893e64798527%2Fartifact%2F437ec127840a7564%2Fp%2Fb46eb2ab3ccd0ceb331c2cef526861e7&size=150x150">

2024-07-31 14:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd85a9b9b-7fcd-427a-893b-9d11fbdf81ef%2Fartifact%2Fe0d71fc9a3c112b9%2Fp%2F6037092d4df264dd9300120c3ad42b0e&size=150x150">

2024-07-31 14:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F4e92c369-0b2f-474a-924d-23ed527f6eba%2Fartifact%2Fac7b37e52799abfd%2Fp%2Fc340a1bdbef24da7a51cea43112e1f68&size=150x150>

2024-08-01 10:21 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F5aa97c14-d182-4ddb-82e5-901b46b515f9%2Fartifact%2F0f0f070ab5d0cf2a%2Fp%2F59d96b056589cecc03eee2552b890db2&size=150x150">

2024-08-01 13:27 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fa11462d9-8527-400d-b891-ca3a3291001f%2Fartifact%2F7cd9ccee3b099cfe%2Fp%2Fe1d3558dab9d228f1bd1d0c40893fa56&size=150x150">

2024-08-01 14:02 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F8ce9113e-10f4-4cb2-8746-97e27550fc3c%2Fartifact%2F001ac5bee1214760%2Fp%2Fbd9b247a8857cefc7bf7cf0dfbde15b4&size=150x150">

2024-08-01 15:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Faa7a7e48-25ba-44aa-b3d7-4407bed92520%2Fartifact%2F0548a33ff82b6abf%2Fp%2F5207949ae98e21ed3aff3bf8ca0b8e11&size=150x150>

2024-08-01 15:35 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fc50e6f8e-2d44-4a91-89ec-ffbcb84c3b4a%2Fartifact%2F1c46189fd6d98b1c%2Fp%2Fb1ab82f8c3963bb66dfc5f3464386e6d&size=150x150">

2024-08-01 15:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fe28877d5-219e-461d-88fb-0a01ae71c169%2Fartifact%2F43bedc0a23868af6%2Fp%2Ff5c920c538e21576f1461bd7045ac2dc&size=150x150">

2024-08-02 08:17 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F142238a5-da8a-4ca3-9373-d17c0494b9fd%2Fartifact%2F48cf83b2f0171f92%2Fp%2F82cec6176fc743f53763857491b266a8&size=150x150">

2024-08-02 08:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1ca0ca63-3327-4492-b490-c2e0c847ae56%2Fartifact%2Fa43d4b1f8074ff67%2Fp%2Fd0b0f5e3f7b34313e00e7af003b5d0e6&size=150x150>

2024-08-02 08:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F50474dc4-bea1-4a71-a59f-4313718e3537%2Fartifact%2F4efdd605536d7899%2Fp%2Fac2c2a496c66472e6d4d9cb9c351f81b&size=150x150">

2024-08-02 08:46 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F6748308a-36e3-492a-9a08-1fc48e399352%2Fartifact%2Fa214d70fdfd22ded%2Fp%2F8dbc4ad6a9d2761b1c89e1f3178d3dc0&size=150x150">

2024-08-02 08:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F1aba4084-941b-4185-8cd4-d3b18a17910a%2Fartifact%2Fc681c033943bc7ce%2Fp%2Fbb0472d724c95566322eea53ca8b4ff4&size=150x150">

2024-08-02 11:25 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F100352b5-e8cc-4dac-bbc2-51b5b1d1a63c%2Fartifact%2Fe6e52e847648051e%2Fp%2Fec9ebb3c437eab68f999419f66d54e0a&size=150x150">

2024-08-02 11:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F936235dc-136f-474c-a76f-1198f2080fe1%2Fartifact%2F63ede8a9350c5f2f%2Fp%2Fd1b3d74d0f778d61401d8dfcd36e1efb&size=150x150>

2024-08-02 11:27 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdaf67341-fe62-4c22-aefb-712fa914a5f3%2Fartifact%2Fd22e8c1442df2c9d%2Fp%2Fc2251d6f15b2c917e04de8ce3c476a2a&size=150x150">

2024-08-05 15:03 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeUiState.kt
> +    var onDismiss: () -> Unit = {},
To achieve events like this you can use one off events that are observed in the Fragment and sent by the ViewModel.

2024-08-09 07:47 UTC, kristofnemere requested changes

2024-08-09 07:47 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/InboxComposeScreen.kt
> +private fun ContentScreen(
I would name this InboxComposeScreenContent or ScreenContent

2024-08-09 07:47 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/contextpicker/ContextPickerScreen.kt
> +fun ContextPickerScreen(
Let's have a chat with Marci if we could reuse the CalendarFiltersScreen, since it has the same functionality with slightly different design

2024-08-09 07:47 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/recipientpicker/RecipientPickerScreen.kt
> +                text = roleCount.toString() + " " + if (roleCount == 1) "Person" else "People",
Use string resources here

2024-08-09 07:47 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/recipientpicker/RecipientPickerScreen.kt
> +                placeholder = "Search",
String resource

2024-08-09 07:47 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/recipientpicker/RecipientPickerScreen.kt
> +    when (uiState.screenOption) {
I would just extract the action and content description into variables

2024-08-12 07:27 UTC, domonkosadam commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeRepository.kt
> +    suspend fun getCourses(forceRefresh: Boolean = false): DataResult<List<Course>>
I think it's easier to handle errors in the ViewModel. An empty or error screen will be displayed depending on the value of the DataResult.

2024-08-12 08:00 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F5b7a0d03-d120-478b-9780-96080795591c%2Fartifact%2F43e94908b3726110%2Fp%2Fb36b0a70b6269c6c84ac158187881222&size=150x150">

2024-08-12 08:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F35ddefef-1e45-4270-b15e-48979ca3a1e0%2Fartifact%2Fc46e3de8fd5d9444%2Fp%2F69829fda504991fc6164cad3febad79b&size=150x150>

2024-08-12 08:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fcf0fa008-fedd-4063-8624-3736178ba0e0%2Fartifact%2Fa48a4311163424fe%2Fp%2Fdf19f26519371746b144abe538fa190b&size=150x150">

2024-08-12 09:34 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Ff3f89e73-922c-4c81-90eb-6cd7d891f203%2Fartifact%2Fc80990bab62bb1d4%2Fp%2Fb363814b416a95ef760f58a72c7d524c&size=150x150">

2024-08-12 09:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8d5a64c9-5cfd-4b01-a37d-689a21de1ef5%2Fartifact%2Ff1dec608834f4416%2Fp%2F406a325c1141273c8e4c6df422b1fb62&size=150x150>

2024-08-12 09:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Febc751dc-e56e-4314-84ed-f6f29c22a06d%2Fartifact%2Fcb6f74de54514d0b%2Fp%2F37bc44da99c404f40a1f123ec0c6fa70&size=150x150">

2024-08-12 10:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb214bc19-2c82-4e45-8241-f8fd6c97d5a0%2Fartifact%2F8832f71bf25ae749%2Fp%2Fb741990e7613c1164b82dabb54c960a2&size=150x150>

2024-08-12 10:25 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fee4148ed-0139-458c-b416-ac28e63da079%2Fartifact%2F3cc08250fc39ee31%2Fp%2Ff9b75596ac49389b1bcf842453ec44c2&size=150x150">

2024-08-12 10:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F813d5a48-e9b8-4769-a912-370dcea2f679%2Fartifact%2F56c342dd8c1d3e89%2Fp%2F72570ec572023e0190d7eedd76f9f724&size=150x150">

2024-08-12 11:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0bbae6be-69d8-4a46-b351-a86ef0cbdba1%2Fartifact%2F72e4d35e9d135e0a%2Fp%2F7a390ee18b019393666d9141e131d526&size=150x150>

2024-08-12 11:39 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fd2e11a4f-7924-462e-b368-1a44c3f07ae0%2Fartifact%2Fe0e268020d728a30%2Fp%2Fed570c7b393bdf6224589dc27319a2e1&size=150x150">

2024-08-12 11:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F16a37ab7-de8d-473b-9f29-f636f1849557%2Fartifact%2F99cf1afd5321b720%2Fp%2Fb6ef70944423336d121c12f543ef6962&size=150x150">

2024-08-12 12:02 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F580316d0-3460-4e31-b02f-592892542121%2Fartifact%2Fe4ba6ff45ede6e37%2Fp%2F7f278e0cd200f10015f20c4f6f7d8fe6&size=150x150">

2024-08-12 12:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F19afc975-b8fb-44dc-aa16-31654f931ac5%2Fartifact%2Fdcefd76cc3caade9%2Fp%2F2c7272989581f292093fd62994f2c974&size=150x150>

2024-08-12 12:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F89cff1cc-d88b-49d9-bb60-91828d9a9cfd%2Fartifact%2F1944d5487a0115c5%2Fp%2Fcbc2166be0a8e24ecc6dc191d833adfb&size=150x150">

2024-08-12 12:34 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F927045d9-b5d8-4fd6-8a4c-704e0a57756b%2Fartifact%2F16f31d6cd325d194%2Fp%2F45f082f2a9057190bdf1412383a83341&size=150x150">

2024-08-12 12:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2031a793-2596-44be-b179-a612d888b8bb%2Fartifact%2F8051d21834e9ebbd%2Fp%2Fee6bb131471aff6ee23c81b144de4984&size=150x150">

2024-08-12 13:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F27dec17d-35a5-487e-a49a-d74761eca46b%2Fartifact%2Fbda7dab1314cc134%2Fp%2F72bc5869b2be7cc7a61b7e0710441ce1&size=150x150>

2024-08-12 14:00 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F918d64b7-b72f-43ec-8bfe-9bce967e47ad%2Fartifact%2Fb964d378d2db5a75%2Fp%2Fbde82caa57664039d8a151c9f200fa87&size=150x150">

2024-08-12 14:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Ff864f9c2-b190-453c-a8af-b6b4d3ceae51%2Fartifact%2Fb3ec2269debdae18%2Fp%2Fb120d5202b847e23cbda059aa4b040cb&size=150x150>

2024-08-12 14:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F7a562674-7f33-429e-bf77-206717c74d4e%2Fartifact%2F80debf3a9a5e6e44%2Fp%2F23fbd37cd707d568d4bbfe40b33a41e7&size=150x150">

2024-08-12 14:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F901f399c-0422-4182-8faf-99ccd570a62c%2Fartifact%2F741d0c811d6e1b80%2Fp%2Febce5389119cbf313bd8123f1a5fe468&size=150x150>

2024-08-12 14:37 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fd5421da4-9d36-4227-8220-5b40eb1d04d3%2Fartifact%2F5ebcf7ccd0f6d7f6%2Fp%2F53085ca726398aaf08b8434487dbe81a&size=150x150">

2024-08-12 15:36 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fce6c4309-fc9c-4c65-a7b2-ef7f41f3e719%2Fartifact%2F58706d4f6f37cc77%2Fp%2F4c27350936d1429cb9691e16aed1201d&size=150x150">

2024-08-12 15:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F61349e3e-fa5a-45e9-ac0d-129a3020068c%2Fartifact%2Fa841a9c1bd9d6965%2Fp%2F25588c2e23e3818b1a97394b6e03e20c&size=150x150>

2024-08-12 15:40 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fec5fe1d5-2c76-429a-b830-674c5bb90a74%2Fartifact%2F6c2b8da0e0af74a9%2Fp%2F937fa1f45bf67ab71a6ba574b0cc42f4&size=150x150">

2024-08-13 05:32 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F2377f4f5-e60b-4df1-846d-e20d2e76024f%2Fartifact%2F4a374dfdad4b01cc%2Fp%2F026419ffcf3a88a5c3f93616670ce473&size=150x150">

2024-08-13 05:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fd0d33503-8c0e-4a48-ba3a-6f4f9c7cf4e0%2Fartifact%2F35c95ff01ff92337%2Fp%2Fc1a2ff8c966f9a4c1c6ca5ee5299f0cc&size=150x150>

2024-08-13 05:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F4a9e1c0c-b228-427c-a8be-4b115afa1304%2Fartifact%2Fb72779c97710a667%2Fp%2Fff69e23fc3405834882da5795f6885ac&size=150x150">

2024-08-13 07:30 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F05b15084-2624-4eba-9405-a49b16e6ed45%2Fartifact%2Fe1f2a46f9262a35f%2Fp%2F8a41b0b81245c3c68cc4a94d19e09087&size=150x150">

2024-08-13 07:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F416c2438-f710-4fd7-bef4-17a26e36570c%2Fartifact%2F0a407f91f929ec1f%2Fp%2F68cf1ef1b74904326df59a16c1c4d182&size=150x150">

2024-08-13 07:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F298e644e-c2cc-4e8d-a097-e309ace1027b%2Fartifact%2Fcd680a9f3a0b743c%2Fp%2F090cae3128e4597d9f3e9d1676214fdb&size=150x150>

2024-08-13 11:53 UTC, kdeakinstructure approved these changes
QA 👍

2024-08-13 12:21 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fff3eb0ce-8906-4b6b-941a-ce2faca685c6%2Fartifact%2F406ca1ced6c2bf8c%2Fp%2F46558bcdb2855d62a675cff18a53b7cd&size=150x150">

2024-08-13 12:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F0dd0c7de-ef27-4892-a308-7b85d6ebb37c%2Fartifact%2Fc203a1e1cbf9dd07%2Fp%2F899bb2c5799b2a33657af8de23d202b9&size=150x150>

2024-08-13 12:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F2d38e509-8ae0-4a7e-a7af-9d91c0300dd1%2Fartifact%2Fefa7e323575c45a9%2Fp%2Fe362194e8661eede96f18000a9c0c5cf&size=150x150">

2024-08-16 11:37 UTC, tamaskozmer requested changes

2024-08-16 11:37 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeUiState.kt
>  data class ContextPickerUiState(
This class is unused.

2024-08-16 11:37 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/RecipientPickerScreen.kt
> +                        if (roleCount == 1) stringResource(R.string.person) else stringResource(R.string.people),
This should be a parameterized plural string. Some languages might handle parameters differently, for example they will put the `roleCount` number at the end, also they might handle plurals differently.

2024-08-16 11:37 UTC, tamaskozmer commented on libs/pandautils/src/main/res/values/strings.xml
> +    <string name="people">People</string>
These should be in pandares instead.

2024-08-16 13:26 UTC, kristofnemere approved these changes
Approved it, because I'll be off next week, but please fix my comments

2024-08-16 13:26 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/compose/ParentInboxComposeRepository.kt
> +        val recipients = recipientsResult.dataOrNull ?: return recipientsResult
you could use com.instructure.canvasapi2.utils.DataResult#map instead

2024-08-16 13:26 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/compose/ParentInboxComposeRepository.kt
> +        val result = permissionResponse.dataOrNull ?: return DataResult.Fail()
Map could be used here as well

2024-08-16 13:26 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/util/navigation/Navigation.kt
> +    val help = "$baseUrl/help"
This is not necessary

2024-08-16 13:26 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeFragment.kt
> +                viewLifecycleOwner.lifecycleScope.collectOneOffEvents(viewModel.events, ::handleAction)
This should be outside of setContent, move it below applyTheme please

2024-08-16 13:26 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/InboxComposeScreenWrapper.kt
> +                    title = if (uiState.selectContextUiState.canvasContexts.filter { it.isGroup }.isEmpty())
could use none instead of filter.isEmpty

2024-08-21 07:50 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fb61212e2-cf3e-40d8-b889-0507e008ddfe%2Fartifact%2F3db4ffdb61d0f86e%2Fp%2F1684d04c3d59a868cf807da203113118&size=150x150">

2024-08-21 07:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb14c3092-d8a9-4db4-8213-de06c8e50bf9%2Fartifact%2F6b41fdc9c41d87f1%2Fp%2Fe4426ccd8b5504d128faef8431c0725f&size=150x150>

2024-08-21 07:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F8c3b6545-b86d-4d7d-8f4e-a12348575bc2%2Fartifact%2Fd57f6e8b5ad51fb1%2Fp%2F28c8935428f7c15c634adef4e985f942&size=150x150">

2024-08-21 12:17 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F3c401507-1377-4d68-9fe2-c83ce7f0e4b9%2Fartifact%2Fbd7c5691826abd52%2Fp%2Fca860e939b484f719b5d0c28744b1990&size=150x150">

2024-08-21 12:17 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Ffc061c89-ebee-42df-92dc-140bb31645fd%2Fartifact%2Fcdc859ba72016933%2Fp%2Ff10833ebc44bc95f12cd3ee5c8f99fcb&size=150x150">

2024-08-21 12:18 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fc1e4be0f-0932-4b1b-95df-d84ea089f44d%2Fartifact%2Fb08c35a27386d48a%2Fp%2Fea2caff061cc4a1cabe59ca6a9c09979&size=150x150>

2024-08-21 12:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1bf979fd-ab77-4f14-b7c9-4c097e9ef908%2Fartifact%2Ff0e5dbb1a989a0e1%2Fp%2F0207889e9618850f470406942d605db4&size=150x150>

2024-08-21 12:31 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F81e7c9a2-de8f-45b4-a7b7-fb72fae0ebca%2Fartifact%2F290b93302ef989f2%2Fp%2F4e71d2dcd7c00a59bb54b7357d89c179&size=150x150">

2024-08-21 12:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F966668cb-f276-4f22-bb5c-5bd2ff8ab391%2Fartifact%2Fe4c864ea90a05da3%2Fp%2F511f9c8a37e8c1f6faf81d29336e6639&size=150x150">

2024-08-21 13:02 UTC, tamaskozmer approved these changes

2024-08-21 13:42 UTC, merged