[MBL-17778] Student | Show 'No Internet Connection' dialog when click on Anonymous discussion details 'Open in browser' link
instructure/canvas-android pull request #2508
Opened 2024-07-27 20:51 UTC by kdeakinstructure

Show 'No Internet Connection' dialog when click on 'Open in browser' link in offline mode, on anonymous discussion details screen.

Test plan: Check that click on 'Open in browser' link in an anonymous discussion details page in offline mode will show the 'No Internet Connection' dialog.

refs: MBL-17778
affects: Student
release note: none

- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-07-27 21:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F6ba4f526-929e-4209-b2a7-24c0b1840b54%2Fartifact%2Fed104ce7839fc1e9%2Fp%2F4cf205419f841355deb74d3f0c40fde0&size=150x150">

2024-07-29 07:33 UTC, kristofnemere requested changes

2024-07-29 07:33 UTC, kristofnemere commented on apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
>          openInBrowser.onClick {
we have an extension for this: onClickWithRequireNetwork

2024-07-29 08:22 UTC, kdeakinstructure commented on apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
>          openInBrowser.onClick {
Thanks, done

2024-07-29 08:24 UTC, kristofnemere approved these changes

2024-07-29 08:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fbc45907b-c7f4-43b1-889b-1f7ed09a6106%2Fartifact%2Fc579f74a45e82efa%2Fp%2F4b7e6c6c04ca427cdc6725f7835d82f7&size=150x150">

2024-07-29 08:38 UTC, tamaskozmer approved these changes

2024-07-29 08:39 UTC, hermannakos approved these changes

2024-07-29 09:56 UTC, merged