[MBL-17620][Parent] Settings screen
instructure/canvas-android pull request #2519
Opened 2024-08-05 12:01 UTC by hermannakos

Test plan: Check the settings screen. Only added the settings items that are already in use in the native apps from the prod version. Made the screen reusable. Not every item type is implemented since we don't integrate it into the existing apps, we should revisit them once this screen is used everywhere.

refs: MBL-17620
affects: Parent
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-08-05 12:13 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fc4b8e7ce-176a-4391-8121-b953fdf1e59b%2Fartifact%2Fc6dd60452f9860b5%2Fp%2Fce353789fe9067ef3d48f3956cab1e60&size=150x150">

2024-08-05 13:55 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fb3017b83-12bc-4bb8-87da-70fd07b0ff68%2Fartifact%2Fa5d6958357715dce%2Fp%2F7111f56eb0eba58483e6754c7c857c5f&size=150x150">

2024-08-05 13:56 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fb96d95f3-1915-4449-8b40-be99c74c5fad%2Fartifact%2F5a9abecb2a6c83fa%2Fp%2Fdec79c44b1ac74c188e4cb5b0bc42637&size=150x150>

2024-08-06 15:36 UTC, tamaskozmer requested changes

2024-08-06 15:36 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/about/ParentAboutRepository.kt
> +import com.caverock.androidsvg.BuildConfig
Why are you using this strange import?

2024-08-06 15:36 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/legal/LegalDialogFragment.kt
> +class LegalDialogFragment : DialogFragment() {
Is this the exact same class as in the Teacher app? I see this was copied from there to pandautils, but the original was not deleted. Maybe we could delete that and use this so we won't have duplications. We might consider using this in the student app as well if that's the same as well.

2024-08-06 15:36 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsScreen.kt
> +    fun AppThemeItem() {
Why do you have these defined in an other Composable function? I think it would be easier to read if you just make them top level. If you want to hide them make them private in the file.

2024-08-06 15:36 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsScreen.kt
> +fun SettingsContent(uiState: SettingsUiState, modifier: Modifier = Modifier) {
This can be private as well.

2024-08-06 15:36 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsViewModel.kt
> +        val appTheme = AppTheme.fromIndex(ThemePrefs.appTheme)
ThemePrefs could be injected instead of using it as an object.

2024-08-06 15:44 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsScreen.kt
> +                        color = colorResource(id = R.color.rce_divider),
This should be `backgroundMedium` and I think the thickness should be 0.5. Ádám already created a Divider composable with these properties, but that's on the Inbox PR and not has not been merged yet.

2024-08-07 07:35 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/about/ParentAboutRepository.kt
> +import com.caverock.androidsvg.BuildConfig
oops

2024-08-07 07:36 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/legal/LegalDialogFragment.kt
> +class LegalDialogFragment : DialogFragment() {
Yes, it is the same. I didn't want to change the other apps now, but sure, I can reuse it there.

2024-08-07 08:01 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fcac8ce04-f70a-448c-90e0-abfdc5a9a4f0%2Fartifact%2Fb400dc03c9caa611%2Fp%2F4cf68c9f86381a3ad869be662180d33b&size=150x150">

2024-08-07 08:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fce19da8a-940a-4b23-bf42-55a18a60ba65%2Fartifact%2F9126e5a701099f0c%2Fp%2Fe780c7b491b59fde557b8ea69acb6571&size=150x150">

2024-08-07 08:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F8d4ea4b8-1da6-4e95-8797-4f6ad1e8fe94%2Fartifact%2F10af8cbc0771c523%2Fp%2Fdb1aacbcb8e8c5de6cf0ebeee24058c2&size=150x150>

2024-08-07 09:18 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F29484a97-76f2-4cc7-810c-02b900bd8ad6%2Fartifact%2Fa97b9678d5aba943%2Fp%2F809967d631e861f7d4e5ea0fb0a389fd&size=150x150>

2024-08-07 09:18 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F17f0dca6-a269-4a05-b5ff-e6d5aeb6b571%2Fartifact%2F0e7c354c4011369e%2Fp%2F04001907c3b015f5a705d4c765537bd4&size=150x150">

2024-08-07 09:19 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F29e104b1-30b5-4d3a-b901-c10236e8f2ca%2Fartifact%2F93bc2a3214ecd02e%2Fp%2Fb451993653025b123486c581313d6082&size=150x150">

2024-08-07 09:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fa7a9a7ee-720c-4dd8-8469-2b5ebc0dd3b5%2Fartifact%2Fe8f27f969b9aa6f7%2Fp%2Fde595abdaca6b8a5bda1295a80d844dd&size=150x150>

2024-08-08 11:33 UTC, kristofnemere approved these changes
QA+1

2024-08-08 11:40 UTC, tamaskozmer requested changes

2024-08-08 11:40 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/legal/LegalDialogFragment.kt
> +@AndroidEntryPoint
I think we need to remove the `retainInstance` in this case.

2024-08-09 11:53 UTC, kdeakinstructure approved these changes
QA 👍

2024-08-09 12:20 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fe0256a69-8ca5-445e-ab84-188afaab2d49%2Fartifact%2F23f04b8856c49262%2Fp%2F5e9201584b7b6a2b275031ea5dfc887a&size=150x150">

2024-08-09 12:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F43a9873b-f13f-4f1b-8df9-82779f1d5238%2Fartifact%2Fecf2c2f228bdd3aa%2Fp%2F525f48ae5c6885f604ffc0796117997f&size=150x150>

2024-08-09 12:49 UTC, tamaskozmer approved these changes

2024-08-12 13:37 UTC, merged