Inbox compose attachment handling
instructure/canvas-android pull request #2535
Opened 2024-08-23 13:20 UTC by domonkosadam

Implemented on Compose Screen:

Context picker
- Recipient picker
- Individual send
- Subject field
- Body field
- **Attachment handling**

To be implemented:
- Reply, Forward handling
- Update list screen if a new message composed
- Search recipient on Compose Screen

2024-08-23 13:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F218c08fb-8ee8-4893-abf1-3ff247726bba%2Fartifact%2Faa758ebc8ffc3ac1%2Fp%2Fbb3cc5b10c52f1d491995a126754ddf9&size=150x150>

2024-08-23 13:34 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F6eea47a8-b4d2-4f71-ac02-93b44a3defc3%2Fartifact%2Fe04b74c4884366a8%2Fp%2F805ec0b76d306557c5e720fb9e08fc09&size=150x150">

2024-08-23 13:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fb053cb89-e856-4224-bdc0-6eb315939ccc%2Fartifact%2Fd9cd76cc6c4215d6%2Fp%2Fe8047e6398ea745da1812b4d55f73f1c&size=150x150">

2024-08-23 13:53 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F0e4ba92a-6a20-4c31-9eee-e7a37d1463b4%2Fartifact%2Ffbf629912faaa4ea%2Fp%2F2550495fd18c5c7d9458232e2a92eb3d&size=150x150">

2024-08-23 13:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F09f86e11-4b5d-4680-be97-7b17fff06ca3%2Fartifact%2Ff4b2db07c0895a01%2Fp%2F945b78a61f2c67ade30317b3dfef3eb4&size=150x150">

2024-08-23 13:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Faccb7a76-04dc-408f-a263-a25f354c2cbf%2Fartifact%2Fa531143cff7ff795%2Fp%2Fbae44382fb5331b71138368496c10973&size=150x150>

2024-08-26 09:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F74f371ab-12f9-47ef-b2bb-e7eadafd4e5e%2Fartifact%2F02f856ba3363ef3f%2Fp%2Fd265b48a39119aac86fbf59b7d420395&size=150x150>

2024-08-26 09:17 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fd5aece1c-db9e-449b-b58e-0e531308d11d%2Fartifact%2F18c1c818e06d7ed0%2Fp%2F4a21e8926e1c7d8c0041e9e452b33ec3&size=150x150">

2024-08-26 09:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fe49f8603-6a4f-43a2-b64e-d2c750733677%2Fartifact%2F26b2f50fd9f5b85d%2Fp%2F986ebef3712ab4f0257174d3035fba7f&size=150x150>

2024-08-26 09:36 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fa743cd3b-1d35-4538-972e-b1724f81065b%2Fartifact%2F95a4616f502fc29d%2Fp%2F8131cc9ce9d375fd2ae60bf2f01c1a52&size=150x150">

2024-08-26 09:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fdcfb7d36-c4ab-42f3-800f-d63de86a55ad%2Fartifact%2Fac2ce8faa07af431%2Fp%2F4ee2572cc3a31638afc6f2557bc8fdec&size=150x150">

2024-08-28 09:12 UTC, tamaskozmer requested changes

2024-08-28 09:12 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +    private fun downloadFileToDevice(attachment: Attachment) {
I would extract this into it's own class. It might be reused in other places as well (for example downloading attachments from the inbox details) and it would also make testing easier for the ViewModel.

2024-08-28 09:12 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +    fun updateAttachments(uuid: UUID?, workInfo: WorkInfo) {
You should add tests for the new features in the ViewModel. Also for the new Actions as well in the `handleAction` function.

2024-08-28 09:12 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/AttachmentCard.kt
> +    onRemove: () -> Unit
I think this should have an optional modifier as a parameter.

2024-08-28 10:16 UTC, kristofnemere requested changes

2024-08-28 10:16 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +                    } ?: context.toast(R.string.errorUploadingFile)
this kind of toast is weird for me in the viewmodel, I would have an event for these in InboxComposeViewModelAction and handle in the fragment

2024-08-28 10:16 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/AttachmentCard.kt
> +    context: Context,
I think you don't need context as a paramter, you could get it inside like LocalContext.current

2024-08-28 10:16 UTC, kristofnemere commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModelTest.kt
> +        return InboxComposeViewModel(context, inboxComposeRepository, attachmentDao)
You should test the new logics

2024-08-28 13:48 UTC, domonkosadam commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/AttachmentCard.kt
> +    onRemove: () -> Unit
It will be fixed with implementing the Conversation Details screen.

2024-08-28 13:53 UTC, domonkosadam commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/AttachmentCard.kt
> +    context: Context,
It will be fixed with implementing the Conversation Details screen.

2024-08-28 14:42 UTC, domonkosadam commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +    private fun WorkInfo.State.toAttachmentCardStatus(): AttachmentStatus {
It will be fixed with implementing the Conversation Details screen.

2024-08-28 14:54 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F8208acee-06e5-466b-8c05-785e2ef21eb2%2Fartifact%2F87ac75dad955f4b8%2Fp%2F088194bcdd4bbf60918cb9d983213ed6&size=150x150">

2024-08-28 14:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fa7303440-325d-4715-948b-65130180fa78%2Fartifact%2F67b97c9c73616b02%2Fp%2Fbc3fe0f0b52891680a2da32ef9899d91&size=150x150">

2024-08-29 07:37 UTC, kristofnemere requested changes

2024-08-29 07:37 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt
> +class FileDownloader(private val context: Context) {
I would just provide DownloadManager instead of this class, or are we gonna use this elsewhere? If you want to keep this, please give it a more specific name that describes better what it does - like AttachmentFileDownloader or something like that

2024-08-29 07:44 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt
> +class FileDownloader(private val context: Context) {
I agree with the first part. I think it doesn't need a more specific name, I would keep this more generic like this. However in that case I would pass the `fileName`, `url` and `contentType` instead of an `Attachment` object so it can be reused easily.

2024-08-29 07:44 UTC, tamaskozmer approved these changes

2024-08-29 07:58 UTC, domonkosadam commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt
> +class FileDownloader(private val context: Context) {
We might use this class on the Conversation Details screen as well. I think it's easier to handle downloads in ViewModels by injecting the downloader class itself.

Wouldn't be a better solution to have multiple functions with different parameters?
```Kotlin
class FileDownloader(private val context: Context) {
    fun downloadFileToDevice(attachment: Attachment) {
        downloadFileToDevice(attachment.url, attachment.filename, attachment.contentType)
    }

    fun downloadFileToDevice(
        downloadURL: String?,
        filename: String?,
        contentType: String?
    ) {
        downloadFileToDevice(Uri.parse(downloadURL), filename, contentType)
    }

    fun downloadFileToDevice(
        downloadURI: Uri,
        filename: String?,
        contentType: String?
    ) {
        val downloadManager = context.getSystemService(DownloadManager::class.java)

        val request = DownloadManager.Request(downloadURI)
        request
            .setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED)
            .setTitle(filename)
            .setMimeType(contentType)
            .setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, "$filename")

        downloadManager.enqueue(request)
    }
}
```

2024-08-29 08:02 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt
> +class FileDownloader(private val context: Context) {
This can be good as well, but I would keep only the first one, and we can add the second one when we need to call it with an URI.

2024-08-29 08:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2Fed2518bd-8b37-4512-bd28-bb8f34efa3ab%2Fartifact%2F0ec80388801544e6%2Fp%2Fa9a6739f686f02d96fa3cd15a7265d13&size=150x150>

2024-08-29 08:35 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F7b57ce3c-a971-48be-8f21-53ada695f28e%2Fartifact%2F529b2faead797483%2Fp%2F13a5c06306ce658b00e74c4ae4d83d7a&size=150x150">

2024-08-29 08:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F19250d54-4004-48eb-b3c4-1c64db48026f%2Fartifact%2F2b8cf08303f8a56e%2Fp%2Fe25b7503f1d29a53857582031644b464&size=150x150">

2024-08-29 10:37 UTC, kristofnemere approved these changes
QA+1

2024-08-29 10:37 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt
> +    fun downloadFileToDevice(
I think this method is not necessary, the uri parse could be in the below method, we gonna call it with a string url typically

2024-08-29 10:52 UTC, merged