[MBL-17618][Parent] Pairing with student
instructure/canvas-android pull request #2542
Opened 2024-08-29 09:09 UTC by hermannakos

Test plan: Compare with the production version.

refs: MBL-17618
affects: Parent
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [x] Tested in dark mode
- [x] Tested in light mode

2024-08-29 09:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F6bc9b224-21a6-40e1-8e28-d947e56330b3%2Fartifact%2F70a02d38165d1d08%2Fp%2F279f8f84adeb21ef95990e8eabd2a2d8&size=150x150>

2024-08-29 09:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2Fc1ae0fb0-05e1-4285-bf2c-9bf47f97de6e%2Fartifact%2F61d4eeed4dbc5535%2Fp%2F1a8c87a238679f139e2e93f8556c8b76&size=150x150">

2024-08-29 09:22 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F933082b8-3da6-4821-92e5-125d5e44ea4a%2Fartifact%2Fa927532a618501c6%2Fp%2F18b092fc1159b7253f4d367046f6ba2f&size=150x150">

2024-08-29 12:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F1145a052-401d-4ffd-94b7-939ce3f86732%2Fartifact%2Fa520134572f68f07%2Fp%2Fdfc3abde0396f361ebc7542b02d91fee&size=150x150>

2024-08-29 12:36 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Ff859ffb0-4243-4237-97dc-82cf4f9efcd2%2Fartifact%2F9131f72a818a51fb%2Fp%2Fd1391949e58044dd1ac53e016bf2b9ef&size=150x150">

2024-08-29 12:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F52ccd239-a249-437d-8388-d84a4ecbc6d5%2Fartifact%2Ff8bd7d05dd91fb55%2Fp%2Fa8c8a7d5f8bb3fe0b3749721c0f3fe37&size=150x150">

2024-08-30 11:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Fbuild%2F9f463b82-f683-4641-85f0-6a511df700bf%2Fartifact%2F8142b1eba5951c5a%2Fp%2F299ed303a54537bd401f6dd1cbdc6daf&size=150x150>

2024-08-30 11:04 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2F05548078-5114-4ff2-b19c-aeb6c558f045%2Fartifact%2F0102daf0719ae521%2Fp%2Fef45b34da411da3a8b9d05da66b814ff&size=150x150">

2024-08-30 11:04 UTC, kdeakinstructure approved these changes
QA 👍

2024-09-02 08:46 UTC, domonkosadam requested changes
Found some unexpected behaviour:
#### Pair with Code dialog removes the entered code on orientation change

https://github.com/user-attachments/assets/16c81303-6eba-49c0-a101-ed5ec89c49f4

#### Pair with QR code screen crashes if I press back button

https://github.com/user-attachments/assets/dc1d72a9-1326-4289-ab6c-5601c232defb

2024-09-03 13:40 UTC, tamaskozmer requested changes

2024-09-03 13:40 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentViewModel.kt
> +                resetError = this::resetError
I don't really like this approach. UIState should only contains state and not callbacks to the ViewModel. These cases should be handled with the usual Actions sent to the ViewModel.

2024-09-03 13:40 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentViewModel.kt
> +    fun pairStudent(pairingCode: String) {
These can be private as well when we are using the action handler.

2024-09-03 13:40 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentViewModel.kt
> +                e.printStackTrace()
We might want to consider injecting the FirebaseCrashlytics and log a non fatal error instead.

2024-09-03 13:40 UTC, tamaskozmer commented on libs/pandares/src/main/res/values/strings.xml
> +    <string name="qrPairingDescription">You\'ll need to open your student\'s Canvas Student app to continue. Go into Main Menu > Settings > Pair with Observer and scan the QR code you see there.></st
There is a typo at the end of this string `<`.

2024-09-03 13:40 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/qr/QrPairingScreen.kt
> +                        Column(
Do we need this Column or would it be possible to only pass a modifier to the Loading composable?

2024-09-03 13:40 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/AddStudentItemViewModel.kt
> +    override val viewType: Int = 1
I would specify the viewType with an enum since we have multiple types now.

2024-09-03 13:40 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardViewModel.kt
> +        val studentItemsWithAddStudent = if (studentItems.isNotEmpty()) {
We don't want to show the add student item when we don't have any students?

2024-09-05 12:46 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-09-09 09:50 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-09-09 10:05 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fb9088ff3b56a0e1f%2Fpublic-install-page%2F1840980ffc0511966479acda8e47ee77&size=150x150">

2024-09-09 10:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F281218cfdac74559%2Fpublic-install-page%2Fcb607ccf22bba92eabe2d3cb48339aca&size=150x150">

2024-09-09 10:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F50470f1c7dedf766%2Fpublic-install-page%2F3d7be4f36774c677faf4f4ba2c6bcc37&size=150x150>

2024-09-09 13:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F19871bd8e55dc0f2%2Fpublic-install-page%2Fe2f5ec29836ce882dc9af19cfdd93baa&size=150x150>

2024-09-09 13:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ff595042b5f2b3eaa%2Fpublic-install-page%2Fa30b5911844275f083a4c009972d482f&size=150x150">

2024-09-09 13:50 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F10de0c8433f3f840%2Fpublic-install-page%2F803c1836b8aa6afbdd0186f08259a09a&size=150x150">

2024-09-09 14:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F3e9595fddbc77a3f%2Fpublic-install-page%2F5a9dd325da1e99ddaac627b8bd91c9e5&size=150x150>

2024-09-09 14:12 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ff17248932b5fe5cd%2Fpublic-install-page%2F0dfbecc8bc372a0e76484661ed9ebecd&size=150x150">

2024-09-09 14:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F6586ca9d80b95044%2Fpublic-install-page%2F3c6efb63005d7079674ce99acdf2978e&size=150x150">

2024-09-11 08:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fd37ca3de12852532%2Fpublic-install-page%2F98cdaae1d74f6b8c95331fefbc3342f6&size=150x150>

2024-09-11 08:25 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F590eb3d4613d3d9b%2Fpublic-install-page%2Fff9bd1314aaa6f8298bae800e81c28b4&size=150x150">

2024-09-11 08:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F5d67c9607c5edd93%2Fpublic-install-page%2Fa3bc2d49ae0b115f0f5961ef05855637&size=150x150">

2024-09-11 09:34 UTC, tamaskozmer approved these changes

2024-09-11 13:03 UTC, kristofnemere approved these changes
QA+1

2024-09-13 09:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Ffe00da2fe949b3b7%2Fpublic-install-page%2Fef585ad3e269ca0f6ef1596b12a28446&size=150x150>

2024-09-13 09:08 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F40f6a86b8b2234a2%2Fpublic-install-page%2Fa03205dbda9de10c439fa4875169d02b&size=150x150">

2024-09-13 09:31 UTC, merged