[MBL-17623][Parent] Implement Inbox compose screen
instructure/canvas-android pull request #2543
Opened 2024-08-29 11:03 UTC by domonkosadam

Test plan:

refs: MBL-17623
affects: Parent
release note: none

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/421cbb35-d7ec-45b6-8989-34329b576113" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-08-29 11:15 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Fbuild%2Fc0760902-4d14-47ea-be68-d4808ed354b6%2Fartifact%2F94fe4ff823efa8c6%2Fp%2F3ed9e0ebc2ef102700b42a15bff84752&size=150x150">

2024-08-29 11:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Fbuild%2F05a80fde-1116-4660-8019-0dc0880fa45a%2Fartifact%2F25f0ae7cebdb8738%2Fp%2F05de5619348426a9a2eeabd30e03c13d&size=150x150">

2024-09-05 13:38 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-09-05 13:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4f05419e7370d3ec%2Fpublic-install-page%2F6a578e5388e79b8391413f4b9cfb0612&size=150x150>

2024-09-05 13:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F8aeb518096d44f7a%2Fpublic-install-page%2F9f27725bb53851661a12c436d86b442a&size=150x150">

2024-09-05 13:53 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Feb5ff39fc3cbb8b9%2Fpublic-install-page%2F681c90cac7d7bd2078458dfd5051198d&size=150x150">

2024-09-09 08:49 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F7a43feb73f41da62%2Fpublic-install-page%2Fdc7ea4993a3138364637489e2d17d531&size=150x150">

2024-09-09 08:51 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Faa4b6e4a43f32bce%2Fpublic-install-page%2Ffa058109cced30d443497339f4bc92a4&size=150x150">

2024-09-10 09:17 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F42734707910ae554%2Fpublic-install-page%2F671b613c5973eaac7fd9ddb447bac5fe&size=150x150">

2024-09-10 09:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F10ca485954cca74b%2Fpublic-install-page%2Fed6da39b57e3a5ea804711d2452c3889&size=150x150">

2024-09-10 09:25 UTC, kdeakinstructure approved these changes
QA 👍

2024-09-10 11:11 UTC, tamaskozmer commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/InboxComposeInteractionTest.kt
> +abstract class InboxComposeInteractionTest: CanvasComposeTest() {
There should be some test cases for sending the message as well (single user, multiple users, sending attachments). The `MockCanvas` is already prepared for that since we have similar tests in the Student app. See `InboxConversationInteractionTests`.

2024-09-10 13:33 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F703c3723a14df9db%2Fpublic-install-page%2Fa26a84446173de1d34b93b5752c40ac5&size=150x150">

2024-09-10 13:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fcb0952e885ce17a5%2Fpublic-install-page%2F4289ed20617948b923e37368c5eeb50b&size=150x150>

2024-09-10 13:34 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ffb63419835287b84%2Fpublic-install-page%2Fe64869562e8038e34beb0b9ea3ea4ea6&size=150x150">

2024-09-11 07:12 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4fcaa63c233145bc%2Fpublic-install-page%2Fca50676afbcd3883574a54af9faa0491&size=150x150">

2024-09-11 07:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Ff8df10fd3b21c364%2Fpublic-install-page%2F2e5d4233866d510b0a9737929eb55868&size=150x150>

2024-09-11 07:13 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F8184d6fc3e93de70%2Fpublic-install-page%2F7ef666036debb7ba362cf8db40d1415a&size=150x150">

2024-09-11 09:06 UTC, tamaskozmer approved these changes

2024-09-11 09:21 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe8f4e128e653f5b7%2Fpublic-install-page%2F869d6630286077082f192bdb25db2db2&size=150x150>

2024-09-11 09:21 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F7564e2f3a581ced8%2Fpublic-install-page%2F3b6e4ab3fcbe8ceff75a59a9f1cf57ea&size=150x150">

2024-09-11 09:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F4952d4afa7425e18%2Fpublic-install-page%2F29069969be27ce4270681d4be07e53f3&size=150x150">

2024-09-11 10:14 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F884757f3e9482e8c%2Fpublic-install-page%2F4bdbde4ed3bf878c32acbc8c1b4f4918&size=150x150">

2024-09-11 10:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fab0f7e0bbc9213a2%2Fpublic-install-page%2Ff6c5eca11d74a3209b823840e3295859&size=150x150>

2024-09-11 10:34 UTC, kristofnemere requested changes
Checked the code, there are a few minor things I noticed, I'm testing now

2024-09-11 10:34 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +            } catch (_: Exception) { }
We might have some error handling or we could have dataOrNull.orEmpty

2024-09-11 10:34 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/ContextValueRow.kt
> +package com.instructure.pandautils.features.inbox.compose.composables
No copyright

2024-09-11 10:34 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/TextFieldWithHeader.kt
> +                .testTag("TextFieldWithHeaderTextField")
We have a convention to start test tags with lowercase

2024-09-11 10:34 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelTextFieldRow.kt
> +                .testTag("LabelTextFieldRowTextField")
We have a convention to start test tags with lowercase

2024-09-11 10:34 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/CoroutineUtils.kt
> +package com.instructure.pandautils.utils
No copyright

2024-09-11 10:34 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt
> +package com.instructure.pandautils.utils
No copyright

2024-09-11 10:34 UTC, kristofnemere commented on libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModelTest.kt
> +package com.instructure.pandautils.features.inbox.compose
No copyright

2024-09-11 10:57 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F38510cfcb30bfc27%2Fpublic-install-page%2F4553dfc554f0700240ecb1fad250c593&size=150x150>

2024-09-11 10:58 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F7aadfea472593ec6%2Fpublic-install-page%2F10fbc94926061f079922daee595a5085&size=150x150">

2024-09-11 10:58 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fbf29bff63bf42144%2Fpublic-install-page%2F6b0f3791c62d6e685a207ccc68fd005a&size=150x150">

2024-09-11 11:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9119d7d3c7d079bf%2Fpublic-install-page%2F4736244bfad7fb316d2cd5575a852b1e&size=150x150>

2024-09-11 11:13 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F211745a8cbc2d84e%2Fpublic-install-page%2F5b5d01c39325445c599df6ef126582c1&size=150x150">

2024-09-11 11:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc54e76b87af335a8%2Fpublic-install-page%2Fedbc223e663fd28dce65f9af8c415ecd&size=150x150">

2024-09-11 11:20 UTC, kristofnemere approved these changes
QA+1

2024-09-11 14:02 UTC, merged