[MBL-17938] [Student] Make HelpLinks class attributes nullable
instructure/canvas-android pull request #2574
Opened 2024-09-30 10:46 UTC by domonkosadam

Test plan: Open Help dialog on beta environment.

refs: MBL-17938
affects: Student
release note: none

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/52876f8f-0c09-46dc-9c32-717ec5685d33" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/d09bbf0d-dea7-4c63-958c-dbaa02103914" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-09-30 10:58 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F37a7469953c7f485%2Fpublic-install-page%2F5156cba07b19137a020bf997855ac62c&size=150x150">

2024-09-30 10:58 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F01f739889237f028%2Fpublic-install-page%2F894d4716c35886f1a6eb498a7859b276&size=150x150>

2024-09-30 11:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F4798643bba52b8d6%2Fpublic-install-page%2F960d05d4c911b11394ac06a680e0e2cd&size=150x150">

2024-09-30 11:05 UTC, kdeakinstructure approved these changes
QA 👍

2024-09-30 12:51 UTC, tamaskozmer requested changes

2024-09-30 12:51 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/help/HelpDialogViewModel.kt
> +            .filter { it.text != null && it.subtext != null && it.url != null }
I wouldn't filter for subtext. It might be possible to create a help link with only a text and url, and it should work fine.

2024-09-30 12:51 UTC, tamaskozmer approved these changes

2024-09-30 13:09 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F7e0a20bce527c8c2%2Fpublic-install-page%2Fcd6738dd1ac45d8e64a887622b54295c&size=150x150>

2024-09-30 13:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F1093c3dd351b3eb8%2Fpublic-install-page%2F80883e7a8dbc3cef2331ff57de443f6f&size=150x150">

2024-09-30 13:10 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fe7f739c85274634c%2Fpublic-install-page%2F1be6ee4624ded8f0e6ad1d3db7cce632&size=150x150">

2024-10-01 09:12 UTC, kristofnemere approved these changes

2024-10-01 09:52 UTC, merged