[MBL-17621][Parent] Course details - Grades
instructure/canvas-android pull request #2575
Opened 2024-10-01 00:16 UTC by kristofnemere

Test plan: compare data with the old version, the design is different, check figma in the ticket.

refs: MBL-17621
affects: Parent
release note: none.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product

2024-10-01 00:29 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F484ae88156c500e7%2Fpublic-install-page%2F89bfe11f11e90caf09f370d04807edd0&size=150x150">

2024-10-01 07:24 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9ec6fb28487b75d5%2Fpublic-install-page%2Ff90a88733ca6642008327d196a5bfb86&size=150x150>

2024-10-01 07:24 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ffa3a5dbefba6270f%2Fpublic-install-page%2F855c4527d03c399f86c753139ebf15a5&size=150x150">

2024-10-01 07:42 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fe133a55c3574bf9f%2Fpublic-install-page%2F6dca3b710108e94412aba9b053cc6d3c&size=150x150">

2024-10-01 07:42 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F755c7b765412a518%2Fpublic-install-page%2F361bda878a403530e1d493b3664e9f8d&size=150x150">

2024-10-01 07:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F815b2925db7fcf39%2Fpublic-install-page%2F22c73d76f4d202a1263ac936d26be07d&size=150x150>

2024-10-01 08:07 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-10-01 08:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F41fb494d40a5559d%2Fpublic-install-page%2F283bd20e74950bb49b523e5a01b026cf&size=150x150>

2024-10-01 08:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F4c187e637192f636%2Fpublic-install-page%2F73ddc24deeadddb70ab7742afda46427&size=150x150">

2024-10-01 08:26 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-10-01 08:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fcd02ea76389dd5c9%2Fpublic-install-page%2Fd80ff17c5ecb15c68819d5bbfc1ef8bc&size=150x150>

2024-10-01 08:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ffd3314a42adda83a%2Fpublic-install-page%2F0d4646185ea9431f71bed62897486b73&size=150x150">

2024-10-01 08:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fff840286f6a8fd53%2Fpublic-install-page%2Fb332f2d84e6640024e5c27b6ff9a8dd9&size=150x150>

2024-10-01 08:50 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fd7abd142e0dcc878%2Fpublic-install-page%2F8ae6b8c730bf1576bab6157de0c9aef7&size=150x150">

2024-10-01 08:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F72b0154003562ca7%2Fpublic-install-page%2Ffb005e03a4c9f310dc09972bee1e4b75&size=150x150">

2024-10-01 09:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F75a00cbb686abf65%2Fpublic-install-page%2Fe9b58480fdb980afabbf76ad392d5246&size=150x150>

2024-10-01 09:14 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F7ebd86d3407c52f9%2Fpublic-install-page%2F5287678040005f6414604b920bdbd4b3&size=150x150">

2024-10-01 09:15 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ffa3d52a17ba925e6%2Fpublic-install-page%2F654c1889342f9874507c9e2e35017a5b&size=150x150">

2024-10-01 13:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4bb6b9ae8b004c2b%2Fpublic-install-page%2F1a6699b04204dc9d0879a4af09a485a8&size=150x150>

2024-10-01 13:28 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc45ba1d84b1b0ac2%2Fpublic-install-page%2F4f3e56ff8b36a2df42fbf62656fa0e53&size=150x150">

2024-10-01 13:28 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fb95245de1d8b4dec%2Fpublic-install-page%2F9b7c06658606d34e1e14ab7c3b0f6834&size=150x150">

2024-10-02 06:28 UTC, tamaskozmer requested changes
QA findings:
[] Switch color is incorrect. Should be brand color or maybe student color. It would be worth discussing it with Marci.
[] Some grades are incorrect. See the Letter Grade course/Points Assignment or Onboarding/Points assignemn & Neww quiz 1 & New On Paper assignment for my test user. This might be related to the letter grade only feature.
[] I would leave some space at the bottom of the list beacause of the floating compose message button, like in the current app version.
[] I would add some minimum height to the card so it would be the same height when the text changes. By the way the animation looks really cool.
[] We might need an alternative layout for landscape, the list is barely visible. We should discuss this with Marci.
[] The card color is incorrect in dark mode. I think it should be the backgroundLightestElevated as we use that on every other card.
[] The touch target of the headers might be an accessibility issue
[] If we encounter an error on pull to refresh we show an error screen even though we already have data. We should show a Snackbar instead.

2024-10-02 06:28 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesViewModel.kt
> +            .map { assignment ->
I wouldn't use map here, since we are not mapping anything. A simple forEach would be more suitable.

2024-10-02 06:28 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesScreen.kt
> +                        text = uiState.gradeText.orEmpty(),
`.orEmpty()` is unneessary here.

2024-10-02 06:28 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesScreen.kt
> +                            interactionSource = NoRippleInteractionSource(),
Why do we need this `NoRippleInteractionSource`?

2024-10-02 06:28 UTC, tamaskozmer commented on automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/GradesInteractionTest.kt
> +abstract class GradesInteractionTest : CanvasComposeTest() {
I would add some more tests here. For example scrolling and checking that the text in the card changed, changing grading periods, cases for the letter grade only feature.

2024-10-03 11:50 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-10-03 11:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F8ce596e719c46cec%2Fpublic-install-page%2F495efd8e3bfc1bd373547c38b125a707&size=150x150>

2024-10-03 11:58 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F6f22f6e834d31286%2Fpublic-install-page%2F73892b3d0082f821d0f8962045e2cfc3&size=150x150">

2024-10-03 12:16 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F6229814c808ca71d%2Fpublic-install-page%2F9d6d8bd207e1b1766f4468a0bc77a857&size=150x150">

2024-10-03 12:16 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F570dce20787ecf81%2Fpublic-install-page%2F8cc69cd7afc31b51f2f8dcb60fb1f527&size=150x150>

2024-10-03 12:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fdfde8cc51c5def01%2Fpublic-install-page%2F421bfba1a48e7b13922a31a64bc5bb20&size=150x150">

2024-10-03 12:59 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fb7864160c2ec6b43%2Fpublic-install-page%2F2c9d2116f4191fa691ee6eab3d14420d&size=150x150">

2024-10-03 12:59 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9f755d1d32873615%2Fpublic-install-page%2F34734bfa551de616f95b97f2df613601&size=150x150>

2024-10-03 13:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fe0675e0faf9c6add%2Fpublic-install-page%2Fe4d406c407ea34a96e850267ca1af243&size=150x150">

2024-10-03 13:32 UTC, kdeakinstructure approved these changes
QA 👍

2024-10-03 13:54 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F503ffd2596bbebf0%2Fpublic-install-page%2F46b4fea79b13416bf4450c2017209ab1&size=150x150">

2024-10-04 08:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fd30aeca90942a4ac%2Fpublic-install-page%2F9c255fdfd7af9f94a255342fa0733d68&size=150x150>

2024-10-04 08:08 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F771a711cd0a8b002%2Fpublic-install-page%2F278d1a15d4f3ea7002a236d2d5d44c1e&size=150x150">

2024-10-04 08:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F225ac8aa8c963526%2Fpublic-install-page%2F2751a0cfc234ce2c39685b919c2563c6&size=150x150">

2024-10-04 09:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9919a3cec8550019%2Fpublic-install-page%2Fd3fab85a8b59a4e61863d167859274ab&size=150x150>

2024-10-04 09:28 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F442f1db3d34e1881%2Fpublic-install-page%2Fb07d3e3d885daaa5738533f63fce5a6f&size=150x150">

2024-10-04 09:28 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9290118e1b91a171%2Fpublic-install-page%2F7643802e36ccec05394f8d38b7413950&size=150x150">

2024-10-04 10:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F36a5c18aadfaf02e%2Fpublic-install-page%2F543001290d6059d18c3242cbdd5e3974&size=150x150>

2024-10-04 10:01 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc128894fdfa3776e%2Fpublic-install-page%2Fc3bc8e98a2f0fb67050fcc9084ccc15d&size=150x150">

2024-10-04 10:02 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F7c0073aeb92e56f5%2Fpublic-install-page%2F71dd2279ebf41bdaf81bb772c0f77d46&size=150x150">

2024-10-04 11:58 UTC, tamaskozmer approved these changes

2024-10-04 12:48 UTC, hermannakos approved these changes

2024-10-04 12:51 UTC, merged