[MBL-17947][Parent] Fixed student colors and theme colors
instructure/canvas-android pull request #2579
Opened 2024-10-03 14:49 UTC by tamaskozmer

Test plan: Test that the app is accessible in both dark mode and light mode. Some notes:
- I fixed the student colors so they have different shade in dark/light mode.
- Fixed canvas brand colors and theme/student color switching.
- Same things apply as for the other apps, when we have a colored background it should have dark text in dark mode, light in light mode and it should be clearly visible.
- I made some refactoring and corrected some other color issues throughout the Parent app.

refs: MBL-17947
affects: Parent
release note: none

## Screenshots

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-10-03 15:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F728e03267d2aa913%2Fpublic-install-page%2Fa46b7f27e234e3f51b43739a4f7d2db3&size=150x150>

2024-10-03 15:02 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F2d4e10841c6adf74%2Fpublic-install-page%2F7c98b90cb6d1ef6746d7a9ff9e001256&size=150x150">

2024-10-03 15:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F568ed166a65536f8%2Fpublic-install-page%2F2bfd41341cb54c8e9ec553748f5f200c&size=150x150">

2024-10-04 09:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fdf479cb528496737%2Fpublic-install-page%2F5a3bdf007a409762b75ba44f763f9afc&size=150x150>

2024-10-04 09:36 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4beb1429a6a987c9%2Fpublic-install-page%2Fcc7b6f728667a2b6acfac0399e7b3221&size=150x150">

2024-10-04 09:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fe1d1c774edf5dc96%2Fpublic-install-page%2Fde7557cac2262826a3f131f828b83e61&size=150x150">

2024-10-04 11:13 UTC, hermannakos approved these changes

2024-10-04 13:04 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-10-04 13:27 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4b195486c79ba924%2Fpublic-install-page%2F22ea3b2a9d047f0db3d2614947684cb6&size=150x150>

2024-10-04 13:27 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F7bc70beac58697d7%2Fpublic-install-page%2Fe7a8a75f066b912289ba475269ddbd09&size=150x150">

2024-10-04 13:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F562e2eacfc16eaee%2Fpublic-install-page%2F574f8d37d2858499b83ed99fdbd1dc1f&size=150x150">

2024-10-04 16:22 UTC, kristofnemere requested changes

2024-10-04 16:22 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesViewModel.kt
> +        _uiState.update {
Would look better like
```
private fun updateColor() {
     selectedStudent?.let { student ->
         _uiState.update {
             it.copy(studentColor = student.studentColor)
         }
     }
}
```

2024-10-04 16:22 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsScreen.kt
> +                                .background(color = colorResource(id = com.instructure.pandautils.R.color.backgroundLightestElevated)),
Could you remove com.instructure.pandautils. ?

2024-10-04 16:22 UTC, kristofnemere commented on apps/parent/src/test/java/com/instructure/parentapp/features/splash/SplashViewModelTest.kt
We could add a test to cover the ApplyTheme event

2024-10-04 16:22 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/utils/CanvasContextExtensions.kt
> +val User?.studentColor: Int get() {
Please use this in CourseDetailsViewModel as well

2024-10-07 06:29 UTC, tamaskozmer commented on apps/parent/src/test/java/com/instructure/parentapp/features/splash/SplashViewModelTest.kt
There is a test for it. See row 105

2024-10-07 06:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe52b848787324ac5%2Fpublic-install-page%2Fe6f389df1b5f8ab9048bfdb393e56131&size=150x150>

2024-10-07 06:54 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F479530d8b29eca40%2Fpublic-install-page%2F71e747d03376e8effae8cd6be1912f12&size=150x150">

2024-10-07 06:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fd27f185dbabd7845%2Fpublic-install-page%2Fd1bc5e4e26ec52b2ac35f45aabfd9302&size=150x150">

2024-10-07 08:52 UTC, kdeakinstructure commented on apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentViewModel.kt
> +                color = selectedStudentHolder.selectedStudentState.value.studentColor,
- [ ] Test

2024-10-07 09:48 UTC, kristofnemere approved these changes
QA+1

2024-10-07 12:11 UTC, merged