[MBL-17647][Parent] Parent Assignment details screen
instructure/canvas-android pull request #2587
Opened 2024-10-07 12:39 UTC by domonkosadam

Test plan: Test all functionality of Assignment details and submission details/upload screens. The Student application had been refactored as well, so detailed QA is needed there as well.

refs: MBL-17647
affects: Student, Parent
release note: none

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-10-07 12:40 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="">

2024-10-07 13:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc8221e11067e98bd%2Fpublic-install-page%2F078a7df91b04bf07c50691a0da564233&size=150x150">

2024-10-07 13:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fa4310f7a99d6803b%2Fpublic-install-page%2F70509df6cf94cd4596b098493b2b66c4&size=150x150>

2024-10-08 09:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F3e5875e8fa4bcd5c%2Fpublic-install-page%2F8770c9dbdb8ac85bc170212022994793&size=150x150">

2024-10-08 09:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F0682dbe2419b6775%2Fpublic-install-page%2Fcce17f3e9476813d079f020ec043315d&size=150x150>

2024-10-08 09:05 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc971f718c1dce747%2Fpublic-install-page%2F84ad302991ea8a1618fc57328ed7f96a&size=150x150">

2024-10-08 10:17 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F682bf1386270d90d%2Fpublic-install-page%2F7f2551595aff105fd4d56b4092902e2d&size=150x150">

2024-10-08 10:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fed9028491d0e6c52%2Fpublic-install-page%2Fa5816f5dbdf4d70e8d8047672f0668e0&size=150x150>

2024-10-08 10:19 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F71158ac52e92d56d%2Fpublic-install-page%2Fe7038f34dcee190431ea4c0cccaf4bb1&size=150x150">

2024-10-08 13:05 UTC, kristofnemere requested changes

2024-10-08 13:05 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRouter.kt
> +            .showThemed()
could be .showThemed(ParentPrefs.currentStudent.studentColor), but I would keep these dialogs in the common code, and the can have the default theme color, or we can pass the color by the behaviour class

2024-10-08 13:05 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRouter.kt
> +    override fun navigateToAssignmentUploadPicker(
It worth consider to just have a default implementation {} in AssignmentDetailsRouter for these methods

2024-10-08 13:08 UTC, kristofnemere requested changes

2024-10-08 13:08 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/receiver/ParentAlarmReceiverNotificationHandler.kt
> +    override fun showNotification(context: Context, assignmentId: Long, assignmentPath: String, assignmentName: String, dueIn: String) = Unit
These should be implemented I think

2024-10-09 09:46 UTC, domonkosadam commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsViewModel.kt
> +    private val _course = MutableLiveData<Course>(Course(id = courseId))
It is used to display course name with DataBinding. With this solution it will be updated automatically.

2024-10-09 15:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1705087c387fad9b%2Fpublic-install-page%2F49d41a0d465393d8096641d99bc47eb7&size=150x150>

2024-10-09 15:22 UTC, inst-danger commented
<p>Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F83db019be16ef7e2%2Fpublic-install-page%2F1bf742c46a86c94f0dce2b3a3eaf46b9&size=150x150">

2024-10-10 12:03 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4f7d005d3495cd86%2Fpublic-install-page%2F7c248796cee264d8ad84edfd9b8b461f&size=150x150">

2024-10-10 12:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F34220212a46e29cb%2Fpublic-install-page%2F60b8c04128d25c2ea33fa1ba283eddac&size=150x150>

2024-10-10 12:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F1ae643f1004f5d79%2Fpublic-install-page%2Ff89fb5c8edf794fd95d3e858d24a4bef&size=150x150">

2024-10-10 12:28 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F2cb9f915f8a6a1db%2Fpublic-install-page%2F7bf32f53494ffebdfff92bf96f4b6b45&size=150x150">

2024-10-10 12:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F554a1cf5a9f4bfb0%2Fpublic-install-page%2Fc98bb9ec619a7a09180184d709753745&size=150x150>

2024-10-10 12:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F46858cad9b508bcb%2Fpublic-install-page%2Fc02cff0e0ce5e3998830625af254354b&size=150x150">

2024-10-10 13:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F75f80eaf9db2ddab%2Fpublic-install-page%2Ff7c9af94941c9b1285c9dd8091eca616&size=150x150">

2024-10-10 13:00 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F8938d3e6dd587e1f%2Fpublic-install-page%2F8e5c406a128eb2d3ebbfd3d2625b7d6c&size=150x150">

2024-10-10 14:10 UTC, kristofnemere requested changes

2024-10-11 12:50 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-10-11 13:02 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F9e7e344bfc0437cc%2Fpublic-install-page%2Fb703b0f7ec52124038b735b13da20fe4&size=150x150">

2024-10-11 13:02 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F00cde510d7e470f0%2Fpublic-install-page%2F88c4f5370928ff445b35d0b6608962cf&size=150x150>

2024-10-11 13:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F3b4c8017f15c6b6d%2Fpublic-install-page%2Fcacbc88867d073f34c29b05ef95bc849&size=150x150">

2024-10-14 07:53 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fab42a7512b32915f%2Fpublic-install-page%2F397ec83edfcbf27602b09bd22cafa619&size=150x150">

2024-10-14 07:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F107711bcbc97f99d%2Fpublic-install-page%2F2d900a4024fcc2cc18314ade51fcf31f&size=150x150>

2024-10-14 07:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F77bb61944a13b433%2Fpublic-install-page%2F194e5340ecb03ba6917b4e80d4605336&size=150x150">

2024-10-14 08:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fd51927dd3366e842%2Fpublic-install-page%2Fa50f25e27990cc454e2ece6ccb80a67c&size=150x150>

2024-10-14 08:35 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F6e87b4cca0c89cb2%2Fpublic-install-page%2Fb6c3cdbbf97120d7da5661c2a97be18b&size=150x150">

2024-10-14 08:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F5ca8ead4b44cf427%2Fpublic-install-page%2F447f6ae409a25ba0fcc51d6024f5b8fd&size=150x150">

2024-10-14 23:02 UTC, kdeakinstructure commented
Tip: Once the E2E tests ran successfully, you can tick the 'Run E2E Tests' checkbox yourself.

2024-10-14 23:11 UTC, kdeakinstructure approved these changes
QA 👍

2024-10-15 13:31 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-10-15 13:44 UTC, tamaskozmer requested changes
QA findings:

- [x] If we have a submitted, but not graded assignment we will see a "Your submission is now waiting to be graded" message, which is pretty weird for a Parent user. You can check this with my users Math/Test Push assignment.
- [ ] We might consider using the student color for the grade chart and the "Submission & Rubric" button, just like in the current Parent app.

2024-10-15 13:44 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsBehaviour.kt
> +        ViewStyler.themeToolbarColored(activity, toolbar, ParentPrefs.currentStudent.studentColor, activity.getColor(R.color.textLightest))
`ParentPrefs` could be passed as a constructor parameter.

2024-10-15 13:44 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRouter.kt
> +class ParentAssignmentDetailsRouter: AssignmentDetailsRouter()
Do we need this empty class?

2024-10-15 13:44 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/assignments/details/StudentAssignmentDetailsRouter.kt
> +    override fun navigateToInternalWebView(
I think these WebView routing functions shouldn't be part of this interface. There is a `WebViewRouter` that can be used for routing links from WebView. That should handle the routing so if we implement the routing in Parent in that class routing will work on all screens that has WebViews.

2024-10-15 13:44 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/UploadStatusSubmissionPresenter.kt
> +    Presenter<com.instructure.student.mobius.assignmentDetails.submission.file.UploadStatusSubmissionModel, UploadStatusSubmissionViewState> {
Why do we use the full package name?

2024-10-15 13:44 UTC, tamaskozmer commented on libs/pandautils/src/main/res/layout/fragment_assignment_details.xml
> +            tools:subtitle="@{viewModel.course.name}"
What is the reason for this change? I think this field is just for the preview so it should be a hardcoded string.

2024-10-15 13:47 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F1d34756b3312456a%2Fpublic-install-page%2Fdd1a3a84e718fef8c3be7412b6186c24&size=150x150">

2024-10-15 13:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fa00988d0a7ed2d94%2Fpublic-install-page%2Fa901bc70efe62d4e7aeca778383dfd97&size=150x150>

2024-10-15 13:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F106cdb88d99a0bca%2Fpublic-install-page%2Fa99d2c6d26d8e051783500f27702d52f&size=150x150">

2024-10-16 07:03 UTC, domonkosadam commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRouter.kt
> +class ParentAssignmentDetailsRouter: AssignmentDetailsRouter()
In the near future some of the empty functions should be implemented here.

2024-10-16 07:09 UTC, domonkosadam commented on libs/pandautils/src/main/res/layout/fragment_assignment_details.xml
> +            tools:subtitle="@{viewModel.course.name}"
I replaced it with data binding. Previously the course was passed to screen from the router and we didn't have to wait for it. Now it gets the course at the screen, so we have to wait for the data.

2024-10-16 08:00 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F6fea9e4546793c99%2Fpublic-install-page%2F443bfb9e468eadc2a43a91bd8fa6ecb1&size=150x150">

2024-10-16 08:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9a40c28444bbaf1d%2Fpublic-install-page%2Fc24897adf92d5f4ce9e1c4537deda080&size=150x150>

2024-10-16 08:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F328f554280179375%2Fpublic-install-page%2F5042dbfd13bf6b4ed0118cb5203442db&size=150x150">

2024-10-16 08:30 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fad6fd4301d69724e%2Fpublic-install-page%2F65e87e0a037b620594be3460b7a251b4&size=150x150">

2024-10-16 08:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F056356015ec753f8%2Fpublic-install-page%2F1f890b40d8d0ef23ff6bc5f718aacf0c&size=150x150">

2024-10-16 08:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fb60f10cf558d24f1%2Fpublic-install-page%2F60effc41aa3cab788c9aa019966f264c&size=150x150>

2024-10-16 09:25 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc857b704cde6e7f8%2Fpublic-install-page%2Fb56c9022c782897606931215a8d9721b&size=150x150">

2024-10-16 09:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F473c745573939702%2Fpublic-install-page%2Fec6b3df80a72e6c00aa5c6567494e3ad&size=150x150">

2024-10-17 11:39 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fdc0ba0fa66a78e89%2Fpublic-install-page%2Ff2dc450da1d7673867ea60400cb9d02c&size=150x150">

2024-10-17 11:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F739f0ec6d60c618b%2Fpublic-install-page%2Ff95c48216ba07707db12934d1d5f18c0&size=150x150">

2024-10-17 11:57 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fbaa1ca0aa5bab59d%2Fpublic-install-page%2F8f4e1a952ca9b528bf585392054d1b00&size=150x150">

2024-10-17 12:30 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fcd2e7b9d5b80966e%2Fpublic-install-page%2F9a08a2fa15ee81de22681e2d2d46e6a1&size=150x150">

2024-10-17 12:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc179d0874e45bec1%2Fpublic-install-page%2F8f4ba9567ad85a849802a60c649361ef&size=150x150">

2024-10-18 07:04 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe91e53d206749517%2Fpublic-install-page%2F6aadba9ddde9f8beb7a9e9e2e916d7a0&size=150x150>

2024-10-18 07:04 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fe73fac9267ee3a2d%2Fpublic-install-page%2F22618d3bab6fb14fa20de907c823b4ab&size=150x150">

2024-10-18 07:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F639f6874ed9b9863%2Fpublic-install-page%2F18137ba89403ba4714b5a2a4cac272f6&size=150x150">

2024-10-18 07:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe6b18af8a4d5b6da%2Fpublic-install-page%2F8d328f5c80920cd560be0fe1cc5caf10&size=150x150>

2024-10-18 07:38 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F3bcfd9d9f60970e1%2Fpublic-install-page%2F44d1433a93353e9465b0963a39852a17&size=150x150">

2024-10-18 07:38 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fada7034a57b743d2%2Fpublic-install-page%2Fe8b77e26e26bb286098da7360801b063&size=150x150">

2024-10-18 08:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F0267a8af70bd7ff2%2Fpublic-install-page%2F11d38121182958c74fc0aa5db86e7441&size=150x150>

2024-10-18 08:47 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F10dd67a7dc4cbbea%2Fpublic-install-page%2Ff0abec9246775adefff28b16c340b901&size=150x150">

2024-10-18 08:47 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fe9be5e12e3881d3f%2Fpublic-install-page%2F4013bb3a580518090c99816a200d9917&size=150x150">

2024-10-18 09:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fb7a8f6bab5993d2f%2Fpublic-install-page%2F19c2cb02be73759b2f60502c7222e13b&size=150x150">

2024-10-18 09:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F537eaf5f5d596257%2Fpublic-install-page%2F4b755f580bdacb24acd254cd38b942f5&size=150x150>

2024-10-18 10:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1ca451992b03b2c6%2Fpublic-install-page%2Fa89e5fba28d11baa8654252ec976a052&size=150x150>

2024-10-18 10:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F4bc946b928877885%2Fpublic-install-page%2F6c3c3a6872cf0f5afadec15783cd829e&size=150x150">

2024-10-18 12:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe898e382e32de7ae%2Fpublic-install-page%2Fcaedcb9dd9c6933a79d8a0ed0ae36fa8&size=150x150>

2024-10-18 12:44 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fc4f0f95e2d71edca%2Fpublic-install-page%2F91a615d2a98355837bbb91379187ac53&size=150x150>

2024-10-18 12:45 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ff301d746bfe62eef%2Fpublic-install-page%2Fa389210e6604ebfe43fdf4ee63c07116&size=150x150">

2024-10-18 13:34 UTC, kristofnemere approved these changes
QA+1

2024-10-21 06:56 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-10-21 06:58 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F685d4d886b97fe1b%2Fpublic-install-page%2F7da59ae99307f23c67f15eac1247592b&size=150x150>

2024-10-21 07:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F6cdc8000b208dfa7%2Fpublic-install-page%2F33ef7b06c46188feb7f51da413fa4643&size=150x150>

2024-10-21 07:36 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F06a120ce043adb1a%2Fpublic-install-page%2F7dce56323a9180e900c74a0f45a4390e&size=150x150">

2024-10-21 07:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fe23ae6061193fb15%2Fpublic-install-page%2F2c44c864b4be8b4d445891cb170bf28b&size=150x150">

2024-10-21 09:47 UTC, merged