[MBL-17974][Student] - Handle 0 value in assignment reminder custom dialog
instructure/canvas-android pull request #2590
Opened 2024-10-08 12:53 UTC by kdeakinstructure

refs: MBL-17974
affects: Student
release note: Handle 0 value in assignment reminder custom dialog

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-10-08 13:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9dfeaa0e6c6996e7%2Fpublic-install-page%2Fbb65cb8802b0043da5743d9538dcae65&size=150x150">

2024-10-09 14:20 UTC, tamaskozmer requested changes

2024-10-09 14:20 UTC, tamaskozmer commented on apps/student/src/main/java/com/instructure/student/features/assignments/reminder/CustomReminderDialog.kt
> +        button.isEnabled = binding.choices.checkedRadioButtonId != -1 && binding.quantity.text.isNotEmpty() && binding.quantity.text.toString() != "0"
While this solves the issue in the ticket you can still type for example "0000" and it will be accepted. You should check the numerical value safely with `binding.quantity.text.toString().toIntOrNull().orDefault() > 0` I think in this case we won't even need the text.isNotEmpty condition.

2024-10-10 13:00 UTC, kdeakinstructure commented on apps/student/src/main/java/com/instructure/student/features/assignments/reminder/CustomReminderDialog.kt
> +        button.isEnabled = binding.choices.checkedRadioButtonId != -1 && binding.quantity.text.isNotEmpty() && binding.quantity.text.toString() != "0"
Good advice, thanks!

2024-10-10 14:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F82d11288d6c1a598%2Fpublic-install-page%2Fa155108756ed31958e5e0fc8faf8b430&size=150x150">

2024-10-10 15:51 UTC, tamaskozmer approved these changes

2024-10-10 15:51 UTC, tamaskozmer commented
QA + 1

2024-10-10 16:43 UTC, merged