[MBL-17617][Parent] Parent announcement details screen
instructure/canvas-android pull request #2597
Opened 2024-10-14 13:39 UTC by andrasmaczak

Test plan: Test screen with both course announcements and global announcements

refs: MBL-17617
affects: Parent
release note: none

## Screenshots

![image](https://github.com/user-attachments/assets/70d872d3-8083-4b02-8a19-a74f64c284a9)

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-10-14 13:52 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F041658ae7e204213%2Fpublic-install-page%2F7329fe9e1a64be9b1a59cfe7d757c0ad&size=150x150">

2024-10-14 13:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Ff89dd5f40e28da36%2Fpublic-install-page%2Fffba701ecf9174a4514262f5d0e0899e&size=150x150>

2024-10-14 13:53 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9717500c35b4b957%2Fpublic-install-page%2Feb568f218951688203a85fdb864ca529&size=150x150">

2024-10-14 17:55 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F03ba838b3ca34d82%2Fpublic-install-page%2Fc54ae28631644f4c473b94dcc144c58e&size=150x150">

2024-10-14 17:55 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F86b3cfa16b4c0ad3%2Fpublic-install-page%2F8cc2857180293d9a3b75a2f459912284&size=150x150">

2024-10-14 17:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F30091c52da65c5e2%2Fpublic-install-page%2F6f4974e2eee3ca9582b037b56f692dba&size=150x150>

2024-10-15 12:24 UTC, tamaskozmer requested changes
QA findings:

- [ ] I think the Toolbar title should be "Institution Announcement" like in the current app. We should also change this text on the alert list as well. Or was this intentional?
- [ ] I would remove the padding of the WebView since it already has an inside padding and it doesn't look aligned this way.
- [ ] Pull to refresh shouldn't clear the screen and show the initial screen loading. Also we shouldn't clear the already present data on pull to refresh, instead we should just show a Snackbar or Toast as an error message.
- [ ] I think the error screen and loading screen should also include the Toolbar. It looks weird without it.
- [ ] The status bar does not have the correct color after a config change.
- [ ] The back navigation is broken after a config change, it navigates back to the courses list screen.

Not in the scope of this ticket:
- [ ] When refreshing alerts with pull to refresh and we have new items they are not shown because the screen won't scroll up automatically.

2024-10-15 12:24 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt
> +                title = uiState.pageTitle
I see that the `pageTitle` logic is already implemented in the ViewModel so we don't really need to handle cases here. You can just make it an empty string by default in the UiState so you won't need to handle null cases. We usually add default values in the UiState for basic types so we don't clutter the UI layer with additional logic.

2024-10-15 12:24 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt
> +                            ) ?: "",
In cases like these where it wouldn't make sense to add an empty Date() we could just keep the nullable date in the UiState. You can use `orEmpty()` though for the string.

2024-10-15 12:24 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt
> +                        modifier = modifier.padding(16.dp)
I think this padding causes the issue with the WebView. I would move this one level deeper.

2024-10-15 12:24 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt
> +fun AnnounceDetailsScreen(
There should be a preview for every screen.

2024-10-15 12:24 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsViewModel.kt
> +                    _events.send(AlertsViewModelAction.Navigate(
I would refactor this logic and move the conditions from the Fragment into the ViewModel and would create separate actions for navigating to different alerts.

2024-10-17 12:16 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-10-17 12:25 UTC, andrasmaczak commented
> * I think the Toolbar title should be "Institution Announcement" like in the current app. We should also change this text on the alert list as well. Or was this intentional?

This was intentional.

2024-10-17 12:34 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F2dc664a2f6b1b307%2Fpublic-install-page%2Fa4a7ea1b6743ac70f80d2fe28c73a6f3&size=150x150">

2024-10-17 12:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F18b3d95a035df2fb%2Fpublic-install-page%2F5304f99a709907fd60c21d4d589699c3&size=150x150">

2024-10-18 07:16 UTC, tamaskozmer approved these changes

2024-10-18 07:42 UTC, andrasmaczak commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsViewModel.kt
> +    var first = true
Added for testing, will remove

2024-10-18 07:58 UTC, andrasmaczak commented on apps/parent/src/test/java/com/instructure/parentapp/features/alerts/list/AlertsViewModelTest.kt
> +            AlertsViewModelAction.NavigateToCourseAnnouncement(
Done

2024-10-18 08:11 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fa2b635d67419ad9d%2Fpublic-install-page%2Fb9ef7656854e4b509e4325b34343c590&size=150x150">

2024-10-18 08:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4601d06d04ece791%2Fpublic-install-page%2F803a6d26b2bd66533cd70116ccae9038&size=150x150>

2024-10-21 18:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9d71425a94af62b3%2Fpublic-install-page%2Fbd3ac5e3f78cc113e6b40cbc315b002d&size=150x150>

2024-10-21 18:06 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F965e0f84d07e6034%2Fpublic-install-page%2Fca5cd957f0a5b0fa2ce7e33bab2d449a&size=150x150">

2024-10-21 18:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fab0263062efb0e6a%2Fpublic-install-page%2F70fe9fc4a23238a0ca2e4d206b637db4&size=150x150">

2024-10-22 07:13 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fa56c0566cfe400c4%2Fpublic-install-page%2F072e0b694c9dc3a8f87640a5741493e7&size=150x150>

2024-10-22 07:13 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F7c921a8d63b8efe1%2Fpublic-install-page%2F552e737f598ba99d3bfd93d06cc25d1e&size=150x150">

2024-10-22 08:56 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F932987dbab72e03d%2Fpublic-install-page%2F1c136ff9ca96497b1cddfc8c3fbada21&size=150x150">

2024-10-22 08:57 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F53ff6719f34de72f%2Fpublic-install-page%2F08f7c2c118c1565a9c5273b71d1c10bf&size=150x150>

2024-10-22 08:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fa57c12aaa705d492%2Fpublic-install-page%2Fe9fed015a4b226367347e2e03fe4157d&size=150x150">

2024-10-22 11:33 UTC, kdeakinstructure approved these changes
QA 👍

2024-10-22 13:08 UTC, domonkosadam approved these changes
QA + 1

2024-10-22 13:08 UTC, domonkosadam commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt
> +        LaunchedEffect(uiState.showErrorSnack) {
Wouldn't be better to handle these Snackbars with Channel and Flows events like on the other new screens?

2024-10-22 13:10 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt
> +        LaunchedEffect(uiState.showErrorSnack) {
I think this is the correct way for Compose. What you mention is used on legacy screens.

2024-10-24 14:00 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F2102c502c4eb49bc%2Fpublic-install-page%2F18a3da1e18c8c214dd677123f69d815f&size=150x150">

2024-10-24 14:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fbc377dbba2227bc0%2Fpublic-install-page%2Ff7104b2ebbf4e2e7464bf1f844c4f28d&size=150x150">

2024-10-25 11:15 UTC, tamaskozmer approved these changes

2024-10-25 11:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F3fe113bb53634436%2Fpublic-install-page%2F08cda890883ccbe965fef64377802a76&size=150x150">

2024-10-25 11:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fc48fd97bff887aad%2Fpublic-install-page%2F4c8915786520782114448e6af94d3114&size=150x150>

2024-10-25 11:50 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F0aa9751003f6a6b4%2Fpublic-install-page%2Ff1d3c18f1ec185e59bce381037012f3a&size=150x150">

2024-10-25 12:23 UTC, merged