[MBL-17676][Parent] Inbox compose message FAB
instructure/canvas-android pull request #2603
Opened 2024-10-18 09:25 UTC by domonkosadam

Test plan: See in ticket

refs: MBL-17676
affects: Parent
release note: none

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-10-18 09:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe858fbdcb857de55%2Fpublic-install-page%2F9f3821f4af5e2ccb4dfd998acf3096e3&size=150x150>

2024-10-18 09:38 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F92753f98259c8817%2Fpublic-install-page%2F587ce078e7cfac88de5b395238155cb3&size=150x150">

2024-10-18 09:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9d51bd0b7ec5374e%2Fpublic-install-page%2Fddb2108118f29bbc7a2ac79b16e98bad&size=150x150">

2024-10-18 10:19 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4837b15adc73a309%2Fpublic-install-page%2Faac7ddaaae3878a0733e18834bfb322f&size=150x150">

2024-10-18 10:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fae7b07647a6d9324%2Fpublic-install-page%2F7ef4f70239e8ee23919e5195cbc243ca&size=150x150>

2024-10-18 10:21 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F2693e32cc712e157%2Fpublic-install-page%2F77ef2e0a3370e4cd008b061cc589a8f2&size=150x150">

2024-10-18 12:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F09bc812f9371ea73%2Fpublic-install-page%2Fd19661c80d527176f1fd75ad881bf7cf&size=150x150>

2024-10-18 12:29 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F9bfdad9ae39fe058%2Fpublic-install-page%2F32d03add75544fefa6e8332403aa097f&size=150x150">

2024-10-18 12:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F6cfac397ad56148c%2Fpublic-install-page%2Fa11754e2486442b8773fb527474c2b36&size=150x150">

2024-10-18 13:01 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4e4cf720c7d3fe22%2Fpublic-install-page%2Fc74b401c68930628da4ee8fcfbd0636a&size=150x150">

2024-10-21 09:45 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F9dba46d62b5f0a6a%2Fpublic-install-page%2F2b90833d92cfa351cc42b5c0ebc3043f&size=150x150">

2024-10-21 09:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F5f54d46ae5c0c84b%2Fpublic-install-page%2F9e28ce6176a696df183f0ff99ca4be03&size=150x150>

2024-10-21 09:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fce7c81e69decd382%2Fpublic-install-page%2Ff59b460f753f31ee4e27e898f9b9c9e9&size=150x150">

2024-10-21 12:27 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fcfa0a093f28d8e61%2Fpublic-install-page%2F7141bb0377f286eea340fa1600bf6c9d&size=150x150">

2024-10-21 12:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F02390a3b178c121b%2Fpublic-install-page%2F1bf9b83743c15710176305c17e59c999&size=150x150">

2024-10-21 14:25 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fa1f1f4eae0b057d5%2Fpublic-install-page%2F7d20101ecee31cc2ab4e5884d5143dcb&size=150x150">

2024-10-21 14:26 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F19dc2d2cd5b6cfb8%2Fpublic-install-page%2F00024c8e3a1eec5d81656a77361e1212&size=150x150>

2024-10-21 14:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ff55bc8c337bdfc69%2Fpublic-install-page%2Ffbaca48bb4cee1310ee9fe4928ae5c6c&size=150x150">

2024-10-22 14:28 UTC, kdeakinstructure requested changes

2024-10-22 14:28 UTC, kdeakinstructure commented on apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/ParentInboxComposeInteractionTest.kt
>  import com.google.android.apps.common.testing.accessibility.framework.checks.SpeakableTextPresentCheck
QA Findings:

- [ ] - Bottom-sheet course selector does not display all the courses (just first 5) and it's not scrollable as well. (Check screenshots)
![Screenshot_20241022_161331](https://github.com/user-attachments/assets/0ca5b5be-7dbf-4424-b223-988b6ebe3b9a)




- [ ] - Fab "message" icon is a little bit smaller than in the flutter app (I'm not sure if it was intentional, may it is, but should check and agree on it)

2024-10-22 15:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F7f15f9c37f3c5602%2Fpublic-install-page%2F9996a7ab7cdd2e5f8ba575978bd4cf79&size=150x150>

2024-10-22 15:00 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc38996002908b679%2Fpublic-install-page%2F6ff3cca17d4c7f9e705deff85823a884&size=150x150">

2024-10-22 15:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F8a0cc25b973cb4d1%2Fpublic-install-page%2Fda7323bbcdcb4e3f7621cf54f3d14d12&size=150x150">

2024-10-24 07:19 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F06c81ca38ff2c1dd%2Fpublic-install-page%2Fa0ca99a5cceb81ba9ff896db5716fee6&size=150x150">

2024-10-24 07:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fed334d42e5ccf0c1%2Fpublic-install-page%2F74ed7668f987d114c0ef7f89422bae01&size=150x150>

2024-10-24 07:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F08ed780a871193b1%2Fpublic-install-page%2F9e9908fe9b1ce7ebcc21aa2d54466ade&size=150x150">

2024-10-24 08:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F658b098d9a82e34d%2Fpublic-install-page%2F6d83da8f2f46a1ab14b03abb8cdc028e&size=150x150>

2024-10-24 08:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc642826887330f3c%2Fpublic-install-page%2F5b2992bf901add0da83ace1bff34ca83&size=150x150">

2024-10-24 08:47 UTC, tamaskozmer requested changes

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRouter.kt
> +                    context.getString(R.string.messageAssignmentPrefix) + assignment.name.orEmpty()
We shouldn't use string concatenations like this, use parameters instead.

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsFragment.kt
> +                    viewModel.uiState.value.currentTab?.labelRes?.let { getString(it) }.orEmpty()
I don't think it's a good practice to request the uiState like this from the viewModel. Maybe this logic belongs to the viewModel and the `NavigateToComposeMessageScreen` should contain the InboxComposeOptions.

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsViewModel.kt
> +    val courseId = savedStateHandle.get<Long>(Navigation.COURSE_ID).orDefault()
This can be private if we implement the changes suggested in the Fragment.

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsViewModel.kt
> +        return "${ApiPrefs.fullDomain}/courses/$courseId/${tabUrlSegment}"
Please inject `ApiPrefs` and use that one instead.

2024-10-24 08:47 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsFragment.kt
> +            is AssignmentDetailsBehaviorAction.SendMessage -> {
If we follow our architecture then I think the cleanest way to do this would be to call a `sendMessage` function on the ViewModel, do the logic there, create the `InboxComposeOptions` and the ViewModel should emit a navigation action with the correct `InboxComposeOption`.

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/coursepicker/composables/ParentInboxCoursePickerScreen.kt
> +    Column(
This should be wrapped in `CanvasTheme` and that would solve the font style issue.

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/coursepicker/ParentInboxCoursePickerViewModel.kt
> +        return "${ApiPrefs.fullDomain}/courses/${courseId}"
It would be nicer to inject `ApiPrefs` in the constructor.

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/coursepicker/ParentInboxCoursePickerBottomSheetDialog.kt
> +                ParentInboxCoursePickerScreen(uiState = uiState) { action ->
Actions from user interactions should be handled in the ViewModel. I would move the complete `InboxComposeOptions.buildNewMessage()` logic there.

2024-10-24 08:47 UTC, tamaskozmer commented on apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/ParentInboxComposeInteractionTest.kt
>  import com.instructure.canvas.espresso.common.pages.InboxPage
QA findings:

There are some design differences with the current implementation of the bottom sheet. If there is no new design for this I think we should stick to the same one we currently have or discuss the differences with Marci.
- [ ] I think the course titles are too small. Subtitle looks correct. Check the text sizes in the Flutter app.
- [ ] I would leave a bit more space between the elements.
- [ ] Do we want this to be full screen?
- [ ] We are only displaying "Student" instead of "for Student". Is this intentional change?

Other issues:
- [ ] Seems like you are not using the correct font in the bottom sheet.
- [ ] FAB is not on the same position in the Assignment Details screen than on the Course detaisl screen. This is really visible when navigating from the Course Details to the Assignment Details.
- [ ] I would populate the subject and teachers as well when selecting a course in the Inbox, just like on the current app and on the FAB action.
- [ ] We need to leave some space at the bottom on screens where we have this FAB, or make it disappear on scrolling. It can cover content in some cases (for example the html description in assignment details). See grades, it's already done there.

2024-10-24 12:40 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F805d86e11a9d1d9f%2Fpublic-install-page%2Fa5b92a574a88877ec4d46c563603a96e&size=150x150>

2024-10-24 12:40 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F385a6c36521b113f%2Fpublic-install-page%2Fbf9ee7922de26d6cdffeb2cf359df577&size=150x150">

2024-10-24 13:28 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F72d55c468f9ba583%2Fpublic-install-page%2F18b6ffa22286748c538f23a1bdf53d40&size=150x150>

2024-10-24 13:29 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F4b7f94705a4df446%2Fpublic-install-page%2F41d6a69b7a8062fec1c526e1cbdce21f&size=150x150">

2024-10-24 14:58 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F6f81bdc92af079a8%2Fpublic-install-page%2F8812eafc617753574fa293d44ebc5b63&size=150x150>

2024-10-24 14:59 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F73a64079fe11d446%2Fpublic-install-page%2F4cb1cc93687f5f540c88e61d979a79f4&size=150x150">

2024-10-25 10:45 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/coursepicker/ParentInboxCoursePickerRepository.kt
> +        val enrollments = enrollmentsResult.dataOrNull ?: return enrollmentsResult
I don't understand why we get the data and wrap it again into a success result, I would just do this:

`        return enrollmentApi.firstPageObserveeEnrollmentsParent(params)
            .depaginate { nextUrl -> enrollmentApi.getNextPage(nextUrl, params) }`

2024-10-25 10:45 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/inbox/coursepicker/ParentInboxCoursePickerViewModel.kt
> +    fun getContextURL(courseId: Long): String {
This could be private and in the test I would verify getMessageOptions function

2024-10-25 10:45 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsViewModel.kt
> +    fun handleBehaviourAction(action: AssignmentDetailsBehaviorAction) {
I would not reach the viewmodel with this, would just pass a lambda to assignmentDetailsBehaviour.applyTheme in AssignmentDetailsFragment and handle the routing there

2024-10-25 12:13 UTC, domonkosadam commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsBehaviour.kt
> +                getContextURL(course?.id.orDefault(), assignment?.id.orDefault())
It should be, but in lot of cases it has a null value

2024-10-25 13:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F792278fba238e11b%2Fpublic-install-page%2F833250fc125729b406b90e5eb835927e&size=150x150>

2024-10-25 13:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F56e89e5c418d1e75%2Fpublic-install-page%2F0ed051d52c9e4b04b02bf636bfce2303&size=150x150>

2024-10-25 13:32 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ff40b18235dbba4b7%2Fpublic-install-page%2F483e30e6113b7aee67915128eb361c74&size=150x150">

2024-10-25 13:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fcfc41490c1ed64e0%2Fpublic-install-page%2Fac2ebcb96b76461d8ae2268de760601e&size=150x150">

2024-10-25 14:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F11522ee28e8d2c0e%2Fpublic-install-page%2Ffc0bd4d2edc71e06b2199f905d0b8b6d&size=150x150>

2024-10-25 14:06 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9f76964d0b0ce24b%2Fpublic-install-page%2Fe10569ff6c5c9daffe6a70fdac334c6f&size=150x150>

2024-10-25 14:07 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ff7b45c29cf04fde5%2Fpublic-install-page%2F93246525f9588ef96f9eef6f6346570a&size=150x150">

2024-10-25 14:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F709aebd226b2652a%2Fpublic-install-page%2F22af5b3c6160df219193ee12e2293431&size=150x150">

2024-10-25 14:31 UTC, tamaskozmer approved these changes
QA + 1

2024-10-28 08:38 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F98e0153044c62c2a%2Fpublic-install-page%2F07c1bc334328fc4d107a375f4cc95259&size=150x150>

2024-10-28 08:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F2dc14747e6717bf4%2Fpublic-install-page%2F6ea468b4bb111c86a14b4243cee5f5a5&size=150x150">

2024-10-29 21:06 UTC, kdeakinstructure approved these changes
QA 👍

2024-10-30 08:59 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F33edfe6798af7f44%2Fpublic-install-page%2F798022a38e922b027bf6b1b31869b714&size=150x150">

2024-10-30 09:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fdfda961d527eab97%2Fpublic-install-page%2F8272b09b4509d7b49a61e73734509655&size=150x150">

2024-10-30 09:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1c46d884c4300e50%2Fpublic-install-page%2F81fa1ce1b1a64c7779f32f71ea4803e1&size=150x150>

2024-10-30 14:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fb54421720c57663c%2Fpublic-install-page%2F3732290067f7ed59dfe84cc1bdcea475&size=150x150>

2024-10-30 14:36 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F2fb9ed3b708e80f1%2Fpublic-install-page%2Fe955332b0dbe8ede532fc96345419414&size=150x150">

2024-10-30 14:36 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fbe181e88caa6c8ce%2Fpublic-install-page%2Fad2c6b37db1ce0f659868d1b58819ab1&size=150x150">

2024-11-04 08:11 UTC, merged