[MBL-17987][Student] Clicking alerts regarding a Discussion mention gives an error
instructure/canvas-android pull request #2608
Opened 2024-10-21 15:53 UTC by tamaskozmer

Test plan: In the ticket

refs: MBL-17987
affects: Student
release note: Fixed a bug where discussion mention alerts couldn't be opened.

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-10-21 16:06 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fe8a5c9ae0b14af55%2Fpublic-install-page%2F5956b192a333df6492f7fc2053d8cbb1&size=150x150">

2024-10-21 16:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F8415984b439b9b91%2Fpublic-install-page%2F46482886a629bc9ae7b7e0a1293bcabc&size=150x150>

2024-10-21 16:09 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Feff57b0b5f437ad7%2Fpublic-install-page%2Fead2a5e41d49ca1d87cba2052131288d&size=150x150">

2024-10-22 12:45 UTC, domonkosadam requested changes
I've tested it with the attached account and the same error occurred with some of the mention notifications.

2024-10-22 13:07 UTC, tamaskozmer commented
> I've tested it with the attached account and the same error occurred with some of the mention notifications.

Yes, those are expected, that doesn't work on iOS either because there is no way to route to the discussion. We will contact an other team with that. If the item in the video works than it's okay.

2024-10-22 13:22 UTC, merged