[MBL-17885][Student] Track Offline usage
instructure/canvas-android pull request #2612
Opened 2024-10-24 09:30 UTC by domonkosadam

Test plan: This ticket cannot be tested properly as developers has no access to analytics dashboards. You can check the sent events from Logcat.
The event names are identical to the iOS app: https://github.com/instructure/canvas-ios/pull/2912

refs: MBL-17885
affects: Student
release note: none

## Checklist

- [x] Approve from product

2024-10-24 09:42 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F358afec07dce6996%2Fpublic-install-page%2Fcbe7cbcb5f25c3dbf8a60ec8497cedf5&size=150x150>

2024-10-24 09:43 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Faf8ca4e51a9c8e6b%2Fpublic-install-page%2Fe98eddbfbcd408c93e8a1007bab21134&size=150x150">

2024-10-24 09:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F7fa91ef200d85e08%2Fpublic-install-page%2F1ff7d53744abd6a8f2dcd596b4649de2&size=150x150">

2024-10-24 11:30 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModel.kt
> +        Analytics.logEvent(eventName)
Since we are doing these in the ViewModel it would be nice to inject these in the constructor and verify the logging in the unit tests.

2024-10-28 14:11 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9d015061e9e3d19b%2Fpublic-install-page%2Fb7160ca4c3af3dbe2eaf3b462dd6d297&size=150x150">

2024-10-28 14:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fdc875bf735ec9150%2Fpublic-install-page%2F581a912cea43e9d333b1498a8b40b51f&size=150x150>

2024-10-28 14:45 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fff3e1dffc76f9aef%2Fpublic-install-page%2F72b71418dba6757a9539dcfcd9c5a942&size=150x150">

2024-10-28 14:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F7b816aba4f927efe%2Fpublic-install-page%2Fd8054fdd3d0d9526a81d4baa4a31b984&size=150x150">

2024-10-28 14:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Ffd424e6a737fb944%2Fpublic-install-page%2F2cf29c7ad264d8fb3f5e7ae56b3179bf&size=150x150>

2024-10-29 15:48 UTC, tamaskozmer requested changes

2024-10-29 15:48 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/analytics/OfflineAnalyticsManager.kt
> +object OfflineAnalyticsManager {
Why does this has to be an object? If you want this to be a singleton you can use the Hilt annotation to provide it as a singleton. In that case you can inject all the dependencies and might be testable as well. You mentioned that you couldn't unit test this, this might solve that as well.

2024-10-29 15:48 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/analytics/OfflineAnalyticsManager.kt
> +    private val SESSION_STORE_NAME = "session_store"
This can be marked as `const`.

2024-10-29 15:48 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/analytics/OfflineAnalyticsManager.kt
> +    private val Context.dataStore by preferencesDataStore(
According to the documentation of the PreferencesDataStore this should only be called once in a file (at the top level), and all usages of the DataStore should use a reference the same Instance. Like this:

```
val Context.myDataStore by preferencesDataStore("filename")  

class SomeClass(val context: Context) {    
    suspend fun update() = context. myDataStore. edit {...} 
}
```

2024-10-29 15:48 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/analytics/OfflineAnalyticsManager.kt
> +    suspend fun offlineModeEnded(context: Context) {
Shouldn't we also consider the offline feature flag for this tracking? In this case this will always be tracked even if the offline feature is not enabled for the user. This should be discussed with product.

2024-10-29 15:48 UTC, tamaskozmer commented on buildSrc/src/main/java/GlobalDependencies.kt
> +    const val DATASTORE = "androidx.datastore:datastore-preferences:${Versions.DATASTORE}"
I would move this to the AndroidX libraries section.

2024-10-30 09:29 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-11-04 08:13 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F57c5512cd24edf44%2Fpublic-install-page%2F09c3a65cec16767497e88671d942feb9&size=150x150">

2024-11-04 08:37 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-11-04 08:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fb5b80a5c4edc1fce%2Fpublic-install-page%2F6606baf0ceb139eb43b77558896d94b5&size=150x150>

2024-11-04 08:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F54748d8fe129e51e%2Fpublic-install-page%2Fe7072b7a4aec4d1da958b25b7cb88762&size=150x150">

2024-11-04 09:30 UTC, tamaskozmer approved these changes

2024-11-04 09:30 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/analytics/OfflineAnalyticsManager.kt
> +        val duration = endTimeInMillis - startTimeInMillis
We don't need to convert this to seconds anymore?

2024-11-04 09:30 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/di/ApplicationModule.kt
> +    fun provideAnalytics(): Analytics {
We already provide this in the Parent app, we might remove that provider function as well.

2024-11-04 09:36 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F6fd27ec8d7de2119%2Fpublic-install-page%2F6b6ddfc311d60ca8d40bec225fe3b780&size=150x150">

2024-11-04 09:37 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1a1241c00c922ed7%2Fpublic-install-page%2F4d25b758bbe694d20b4848a9195ff62a&size=150x150>

2024-11-04 09:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ff7c7c290aa1e5e0c%2Fpublic-install-page%2Ff39ea794af556051146005351a5b25da&size=150x150">

2024-11-04 10:19 UTC, hermannakos approved these changes

2024-11-04 11:30 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc5e8d15441389a53%2Fpublic-install-page%2F29b9c609235173dd5af46d3ae7fc5171&size=150x150">

2024-11-04 11:31 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Ff1ee1ff20f34f7a9%2Fpublic-install-page%2Fa631b857d15a72c464cb25977fd25da9&size=150x150>

2024-11-04 11:32 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F8e357a4ea92e6132%2Fpublic-install-page%2F58189a9321cb0e5a437dcfc36559fd88&size=150x150">

2024-11-04 12:51 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fdef0e58197e4c043%2Fpublic-install-page%2Fa921d3286d3ae93fc03addac91f54f7d&size=150x150">

2024-11-04 12:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Ff76283afb3b0ae36%2Fpublic-install-page%2F7aeb6d0a9490abdc398fbb78281a3ee4&size=150x150>

2024-11-04 12:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ff8aad15b8561f0bc%2Fpublic-install-page%2F02f4f725b9425e8d9cfaf311967408ba&size=150x150">

2024-11-04 13:59 UTC, merged