[MBL-18013][Student][Parent] Refactor reminder logic
instructure/canvas-android pull request #2628
Opened 2024-11-07 10:07 UTC by domonkosadam

Test plan:

- Assignment without due date:
    - Previously users couldn't set reminder for assignments without due date. Now you can set reminder for these assignments as well.
- Assignment with due date:
    - Users can set reminder from the new date time picker dialog.

refs: MBL-18013
affects: Student
release note: Reminders can be set for assignments without due date.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/00786d32-bca9-4868-9faa-55a84bef75fc" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/f2971cc0-9bf6-427e-bbb4-1728be00bc02" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-11-07 10:21 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F15fe6327f6edf580%2Fpublic-install-page%2F45ba35f1ff5ddab11a77e8828bec9316&size=150x150">

2024-11-07 10:22 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F7b6383c7e5c2bb9b%2Fpublic-install-page%2F8bb237fd96e062f159393eee3fac884e&size=150x150>

2024-11-07 10:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F7239cf9e576487df%2Fpublic-install-page%2Fbbc3d76cd6888d32e96e6bcedaf64129&size=150x150">

2024-11-07 10:52 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ff4d607da017af676%2Fpublic-install-page%2F03fe0280a8be7babc6c72c668aec79dc&size=150x150">

2024-11-07 10:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe325250084658dfa%2Fpublic-install-page%2Fbaa71cb73f9240c31c2691ee6c03c1f9&size=150x150>

2024-11-13 13:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F11bc8fe20f1f895a%2Fpublic-install-page%2Fe5c97a158d949d5a22fd1c1d7ead45f3&size=150x150">

2024-11-13 13:07 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc7d2d99b4202466d%2Fpublic-install-page%2F29cd39d593f10e801ba1160722e905e3&size=150x150">

2024-11-13 13:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fddd6239032da90cd%2Fpublic-install-page%2F6af488e04bcf2d2cff4362bbd1065116&size=150x150>

2024-11-13 13:39 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ffaa662a22674efeb%2Fpublic-install-page%2F4adbe9762c95b8924a72a0dbeaad274e&size=150x150">

2024-11-13 13:39 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F42bf0cba9d7f8768%2Fpublic-install-page%2F25f528188d359593a50770eba65d6baf&size=150x150>

2024-11-13 13:39 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F5545dc5ee6c03b75%2Fpublic-install-page%2Fb8aa86ead864e0410536e75fd933d23e&size=150x150">

2024-11-13 14:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F3d33daa049887058%2Fpublic-install-page%2Fc7cc7876beb21d75ca847d5051ba5909&size=150x150>

2024-11-13 14:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F25ec389b85b683f9%2Fpublic-install-page%2F527810f0a615cfc0367ee221be20e8c6&size=150x150">

2024-11-13 14:31 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fccd701ca0d26c7ba%2Fpublic-install-page%2F7cb585efc7382e862b2b9183bc5e75a5&size=150x150">

2024-11-13 15:11 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F89e7756361fd9f63%2Fpublic-install-page%2F143d4790c06dd5ed4216426d4d4db296&size=150x150">

2024-11-13 15:12 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fb9394d9caca3e370%2Fpublic-install-page%2F99b498c0529e0983824a95b402175f3d&size=150x150>

2024-11-13 15:12 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fd538bf9a8e69ebeb%2Fpublic-install-page%2F348616e2c9dd5f48b71460ddea97d70c&size=150x150">

2024-11-15 09:11 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F761babab56790dad%2Fpublic-install-page%2Fa3a9f81a73e8dfa3ee2b051dcd718a4c&size=150x150>

2024-11-15 09:22 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F80d1d12159c57419%2Fpublic-install-page%2Fb347cb564bb660b3193a9cb97a8ae590&size=150x150">

2024-11-15 09:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F87733955a892a465%2Fpublic-install-page%2Fa183995cae27d074be68a09fb694c8ce&size=150x150">

2024-11-15 09:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F2b790754762e7d76%2Fpublic-install-page%2F206143827908c2b5a3f7af6fc8cb33b2&size=150x150>

2024-11-15 15:28 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F2c8b76c421d93df5%2Fpublic-install-page%2F44e7ea61cbae2ca1b08f295c37bd6f6b&size=150x150">

2024-11-15 15:29 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4fb0e640c2f4c982%2Fpublic-install-page%2Fbc62472d79b72c83d91caac30e16e683&size=150x150>

2024-11-15 15:29 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-11-15 15:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F7578bb936b907ebf%2Fpublic-install-page%2F4975d6287f68607a11200aa17353daea&size=150x150>

2024-11-15 15:42 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F44df2f276aa5e954%2Fpublic-install-page%2Fa36424989338cfb58aaf073a0f1066cc&size=150x150">

2024-11-15 15:43 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F2e6f76f59c2d4480%2Fpublic-install-page%2F54ae74716991c24d7baccf1dafd68806&size=150x150">

2024-11-18 12:24 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F093f8519dc0d875b%2Fpublic-install-page%2Fa4c18be46b46ebc8850c7b06acb35ba2&size=150x150">

2024-11-18 12:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F32e5c49a4ab86e0a%2Fpublic-install-page%2Fa7fa796b6e95e456d87a1306ec4b057e&size=150x150">

2024-11-18 13:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F6763fd72268105c9%2Fpublic-install-page%2Fece586cb510d5032429c06733783bfd8&size=150x150>

2024-11-18 13:49 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F0de9d61fd4625f35%2Fpublic-install-page%2Fec5697bc1228811502fc1e0c690fd180&size=150x150">

2024-11-18 13:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fd5c7f13ec6125b65%2Fpublic-install-page%2F1f51a68d1ae0748dd901d899ce62c67f&size=150x150">

2024-11-18 15:12 UTC, tamaskozmer requested changes
QA findings:
- [ ] Date picker dialog buttons are not styled
- [ ] It would look better if the text was always alligned with the icon regardless of the line count. (screenshot attached)
<img width="615" alt="Screenshot 2024-11-18 at 14 24 45" src="https://github.com/user-attachments/assets/2fb02f0e-1c4f-48bd-9a50-bf581776d3ed">

2024-11-19 11:23 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F0837d8e2785620c4%2Fpublic-install-page%2Fc2880aecaaec4221177fda9de8dd0801&size=150x150>

2024-11-19 11:24 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F04edcbca69b8baad%2Fpublic-install-page%2F8422bcc81f6c79deca4e594aa7ea8cb5&size=150x150">

2024-11-19 11:25 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fe1b2d83b33497f58%2Fpublic-install-page%2F04912cae0c02a5b7b9dbfb818719fe08&size=150x150">

2024-11-19 12:25 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F6290bfeb634932d4%2Fpublic-install-page%2Fdbbba70588e1b9fc7dbb9517cbe2c09b&size=150x150>

2024-11-19 12:26 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F599e3e7621f57393%2Fpublic-install-page%2F6191b6c82023048b43fac2f0c83eeaa7&size=150x150">

2024-11-19 12:26 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F3e0b01f13e16b321%2Fpublic-install-page%2Fc8418410e5ac6812720a5510f5b53701&size=150x150">

2024-11-19 14:47 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Faf233fde73f9b561%2Fpublic-install-page%2F20c704825390f3585874cd08eeff6c9c&size=150x150">

2024-11-19 14:48 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fb7646b73bb340ad6%2Fpublic-install-page%2Fe903a953d1ff854e10ce7db7d1b2ceff&size=150x150">

2024-11-19 14:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F6f8e81e0dea9731f%2Fpublic-install-page%2Ff1dee81b75dde47773acde18830570ca&size=150x150>

2024-11-19 15:34 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fdfb0e82d03e24751%2Fpublic-install-page%2Fdd8ef71a59ff88707730a05e0e83e345&size=150x150">

2024-11-21 09:22 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsViewModel.kt
> +                        ApiPrefs.user?.id.orDefault(),
You should use the injected `apiPrefs` instance.

2024-11-21 09:22 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsViewModel.kt
> +    fun showCreateReminderDialog(context: Context, @ColorInt color: Int) {
It would be nice to have tests for this function.

2024-11-21 10:03 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F219f2e4e3d7451a2%2Fpublic-install-page%2F8773e2a2c62621e96e73612e70c181db&size=150x150>

2024-11-21 10:03 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F60589f68906350f2%2Fpublic-install-page%2Fccf192511c7a13d5fab44bcf7c219733&size=150x150">

2024-11-21 10:04 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F0e377c28a5f67a32%2Fpublic-install-page%2F5fb9a9c49e4dc475714701688cfcf1ea&size=150x150">

2024-11-21 12:06 UTC, tamaskozmer approved these changes

2024-11-21 15:56 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-11-22 08:14 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Faae0379489e999c8%2Fpublic-install-page%2Fc5bbee5c9e31de44901826d539ecacdc&size=150x150">

2024-11-22 08:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fa9ced70ef2295238%2Fpublic-install-page%2F49976d3d9ce313bd1088a1e5559e788f&size=150x150">

2024-11-22 08:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fd8c1c48b100cda06%2Fpublic-install-page%2F33e985afcff87c7e8473dba733bab917&size=150x150>

2024-11-22 09:46 UTC, kdeakinstructure approved these changes
QA 👍

2024-11-22 09:47 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fd7da0e51d232d9b8%2Fpublic-install-page%2F05fa6a485226a010e99f827cc43eba3f&size=150x150>

2024-11-22 09:47 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fb5b9d763ada2c68b%2Fpublic-install-page%2Fa2eb8e098d4e53c8b3d3645e746d446c&size=150x150">

2024-11-22 09:47 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F49e619428e47df14%2Fpublic-install-page%2F42f471aee3f53f78117a8dae4b202a82&size=150x150">

2024-11-22 10:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fb1906b0acd7d455a%2Fpublic-install-page%2F3a0c34688c3a592f0d838186783c94f0&size=150x150">

2024-11-22 10:57 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F0ab99442d8e6174a%2Fpublic-install-page%2Fd6d4dd341aae6128a66374f6a162a6a2&size=150x150>

2024-11-22 12:35 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fc12628ec339ad1e3%2Fpublic-install-page%2Fd0b14f8db0d0c372aba598bfca634703&size=150x150>

2024-11-22 12:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc564f60b04d5cb24%2Fpublic-install-page%2F51400081a7e7d51af1ccc60cabb38189&size=150x150">

2024-11-22 15:21 UTC, merged