[MBL-17677][Parent] Course details - Syllabus tab
instructure/canvas-android pull request #2631
Opened 2024-11-08 13:43 UTC by kristofnemere

Test plan: compare with the Flutter version, the url navigation will be implemented in another ticket.

refs: MBL-17677
affects: Parent
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-11-08 13:55 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F13837e8c4e28e945%2Fpublic-install-page%2F1f53d6475f51b580c6968485fa8eb71d&size=150x150>

2024-11-08 13:56 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F02b64708176cb0c9%2Fpublic-install-page%2Fdf3588c67ed0b650cba0e64f87ae473d&size=150x150>

2024-11-08 13:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc3f613f56c7f1e4d%2Fpublic-install-page%2F3193407e3907f02af9d6426fc1c76131&size=150x150">

2024-11-08 13:56 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F906cf67432ca43eb%2Fpublic-install-page%2Ff66653a25c76df184354d67d0f6e178f&size=150x150">

2024-11-08 14:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F9daea6c7aca2f40b%2Fpublic-install-page%2F278ab1766e9108ac8d5025d3d7d68b36&size=150x150>

2024-11-08 14:16 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4f0bf616c13109c2%2Fpublic-install-page%2F476339b00f50615dafae2c20fc925d55&size=150x150">

2024-11-08 14:38 UTC, tamaskozmer requested changes
QA findings:
- [ ] The swipe for the tabs overwrites the scroll action of the WebView too many times, so it's hard to scroll the WebView.
- [ ] It would be nice to have a refresh button.

2024-11-08 14:39 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/SyllabusScreen.kt
> +internal fun SyllabusScreen(
I think we can make this a general web content screen or something like that, because this can be exactly reused for the front page.

2024-11-11 14:41 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F2e2e230c86b234be%2Fpublic-install-page%2Ff297e401e59fae2413c4d435ab6abad1&size=150x150>

2024-11-11 14:41 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F234ca6786f6a1dea%2Fpublic-install-page%2F47d72eb03227ec1f817c97e63a55c79e&size=150x150">

2024-11-11 16:19 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4deb7ec6d669f5ee%2Fpublic-install-page%2F44f4927ffbbd650a5753bcffee34a250&size=150x150>

2024-11-11 16:23 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F800054fe9d38fa5a%2Fpublic-install-page%2F293afc77397941bb274f1e6ebd66afe2&size=150x150">

2024-11-12 09:59 UTC, tamaskozmer approved these changes

2024-11-12 09:59 UTC, tamaskozmer commented
QA + 1

2024-11-12 10:11 UTC, domonkosadam approved these changes

2024-11-12 10:13 UTC, merged