[MBL-17983][All] New Quiz - Dedicated WebView
instructure/canvas-android pull request #2632
Opened 2024-11-08 14:08 UTC by tamaskozmer

Some notes:
- There are lot of changes in this PR, I refactored the LTI launching logic, moved all the code into the common package and now all the 3 apps use the same code for LTI launching.
- This PR fixed an other issue as well which I discovered in the process. When you launch an LTI submission from the Student submission details screen it was only possible to launch it once. If the users closed the LTI tool and tried to launch it again it failed. This was due to passing an already authenticated url to the submission details screen. I had to refactor this as well.
- Currently only the new quizzes open internally but other LTI tools can be easily integrated.

Test plan:
- Verify that the new quizzes LTI opens internally and the Return button works as intended.
- Smoke test all the LTI related features (opening from nav bar, opening LTI tabs, opening and submitting LTI assignments, opening LTIs from HTML content) The new Parent app only has the first one.
- Check that the Teacher app embeds the LTI submissions.

refs: MBL-17983
affects: Student, Teacher
release note: Better new quizzes integration

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in light mode
- [ ] Approve from product

2024-11-08 14:09 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-11-08 14:31 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F5f30a877aceed937%2Fpublic-install-page%2F3bbd1db6cc8b34ed509a4c261b91b967&size=150x150">

2024-11-08 14:32 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F597ee1ab4e13e9b6%2Fpublic-install-page%2F3d79759efeeb67b8ba4d411e3a6e371c&size=150x150>

2024-11-11 14:16 UTC, hermannakos requested changes
- [x] In app navigation is not enabled from the new screen. It will navigate inside the webview. 

- [x] When navigating inside the webview pressing back pops the fragment and not the webview backstack.

2024-11-11 14:16 UTC, hermannakos commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderLtiSubmissionFragment.kt
> +            override fun canRouteInternallyDelegate(url: String): Boolean = false
We sure we don't want to route anywhere from here? Edit: see other comment

2024-11-12 07:18 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderLtiSubmissionFragment.kt
> +            override fun canRouteInternallyDelegate(url: String): Boolean = false
I don't think we need to route from LTI tools. These are completely separate tools, outside of Canvas, it was previously opened in Custom Tabs, so we didn't have any in app routing, and as far as I know this wasn't a requirement.

2024-11-12 11:11 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-11-12 11:16 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fffc9f8f958eb8666%2Fpublic-install-page%2F909c330befe9c39e0efb248427d7cf3c&size=150x150>

2024-11-12 12:14 UTC, hermannakos approved these changes
QA + 1

2024-11-12 13:17 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9b86ec82a6e3bed7%2Fpublic-install-page%2Fe4e81bd6a3ea79592b69ab7b020a44c5&size=150x150">

2024-11-12 13:17 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F9a76df685af58b22%2Fpublic-install-page%2Fabb593d7446fc5d01b0c731cca5f60ef&size=150x150">

2024-11-12 13:30 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fbb02e2f7e766f60c%2Fpublic-install-page%2F5d793f3873487503ef8caeadb4788892&size=150x150>

2024-11-12 13:31 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F5750b0a58449fe76%2Fpublic-install-page%2F1bb590090ffc2a16b70044811f347570&size=150x150">

2024-11-12 13:31 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F75d8ba4256163d67%2Fpublic-install-page%2Fb0b19174ab6304020c8a71d979584bf4&size=150x150">

2024-11-13 11:54 UTC, kristofnemere approved these changes

2024-11-13 11:57 UTC, merged