[MBL-18041][Student][Parent] Point based grading schemes
instructure/canvas-android pull request #2643
Opened 2024-11-15 12:55 UTC by hermannakos

Test plan: See ticket. Compare with web.

refs: MBL-18041
affects: Student, Parent
release note: Added support for point based grading schemes.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/2c3bb073-6640-47b4-bc72-e39e162da0e5" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/04c3496d-a10e-43e8-a47d-f93efd9caa05" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/a2719b36-df4d-4ddf-b560-537c415d3379" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/7298187e-21c5-4b1d-9909-9331777aabfa" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/c4555625-a04f-4ec8-89bd-38411a921ecd" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/f757ba17-d200-4235-aff6-f8543e5129cc" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/dc00c9e8-1969-4db0-a0c3-fe3f177a93a3" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/b7c7a8d8-0f28-4413-b092-219ccb7ca2ba" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-11-15 13:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F6b5fd92aa59599a0%2Fpublic-install-page%2Fa1da8955e3556a0478e16284888ab452&size=150x150>

2024-11-15 13:08 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ffaa6fa74bb6ca19b%2Fpublic-install-page%2Fc7db9209fb0f671dcde9b4f9a6fd7a06&size=150x150">

2024-11-15 13:10 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F429dd6500719adbc%2Fpublic-install-page%2F374d5a153f09626d18b2ea8bc71c24ab&size=150x150">

2024-11-18 09:15 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1ea0677ee191ee96%2Fpublic-install-page%2F13ff7d7a921c6b8b2bd1b312d004a1e6&size=150x150>

2024-11-18 09:16 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fbf7fa1fa6952d68c%2Fpublic-install-page%2F4615548111d80a01f7196bde93ecb03e&size=150x150">

2024-11-18 09:16 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F633427a07ce03a15%2Fpublic-install-page%2F582f456ea94d6e657f869a989da1648e&size=150x150">

2024-11-18 10:57 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fd09db6caea8a17a6%2Fpublic-install-page%2F545acc234ff4c3c428e103afe582f4cb&size=150x150">

2024-11-18 10:57 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F73a37dd6ebdc2311%2Fpublic-install-page%2Fc2cdb18b24b9f1a46756e29391765a2c&size=150x150>

2024-11-18 10:57 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fe0838524bbba80d6%2Fpublic-install-page%2Ff49482a17c381aa069742ea4bbb079ff&size=150x150">

2024-11-19 09:16 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4dfbd5c5d8db6b93%2Fpublic-install-page%2F04852c0c805e063a41484f08c756d80b&size=150x150">

2024-11-19 09:17 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F84233e2db5e10ba7%2Fpublic-install-page%2Fdcc8f9ad26ea00e723ccfc86200c11cc&size=150x150>

2024-11-19 09:17 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F6f2bd0e3b896113e%2Fpublic-install-page%2F5b176c70fb01251100c68b4cd262f652&size=150x150">

2024-11-19 13:11 UTC, kristofnemere approved these changes
QA+1

2024-11-19 15:16 UTC, tamaskozmer requested changes

2024-11-19 15:16 UTC, tamaskozmer commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/OfflineDatabaseMigrationTest.kt
> +class AppDatabaseMigrationTest {
I think this class is a victim of some copypasta 😄

2024-11-19 15:17 UTC, tamaskozmer approved these changes

2024-11-20 09:02 UTC, hermannakos commented on libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/OfflineDatabaseMigrationTest.kt
> +class AppDatabaseMigrationTest {
oops 🫣

2024-11-20 09:20 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fae2d53d8003a426f%2Fpublic-install-page%2F03d3defbb69c26f16385930b7215c889&size=150x150">

2024-11-20 09:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4805ffb73289dcba%2Fpublic-install-page%2F9d7006936c95ca5447854c74a2c4238b&size=150x150>

2024-11-20 09:20 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fcfe67d25cee11d09%2Fpublic-install-page%2F9afde487e3f48d25a84ebf78b3b0d3ed&size=150x150">

2024-11-20 11:41 UTC, tamaskozmer approved these changes

2024-11-20 11:50 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F0e5398dce4c86b54%2Fpublic-install-page%2Fa2326b850d8c60feffd037151e1cd1d0&size=150x150>

2024-11-20 11:50 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ff36c98cc94d40ef9%2Fpublic-install-page%2F5d3f98281883b154b5702d502a0658de&size=150x150">

2024-11-20 11:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fd802aadd0b979012%2Fpublic-install-page%2F17c9d1affc6f52738d9ecf9524f45858&size=150x150">

2024-11-20 13:27 UTC, merged