[MBL-17881][All] Remove Class transformers
instructure/canvas-android pull request #2646
Opened 2024-11-19 09:05 UTC by tamaskozmer

The ticket was about handling locales in the Parent app, but that was implemented by a class transformer that we didn't want to reuse in the Parent app due to deprecation in the AGP so I implemented a different solution. Since I was already doing this I replaced all the class transformers with the same approach. So we should extensively test all the features that relied on class transformers.

Test plan: 
- Verify that locale changes are reflected in the Parent app (locale needs to be changed in Canvas user/admin settings).
- Verify that Masquerading works correctly in the Student/Teacher apps.
- Verify that locales can be selected in the settings of the Student app when in debug mode.
- Verify that Heap screenviews are sent correctly as before.
- Verify that Pandata events are sent correctly as before.

refs: MBL-17881
affects: All
release note: none

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-11-19 10:11 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-11-19 10:33 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ff9a4126828e2924a%2Fpublic-install-page%2Fb1e70bbcfe950974dcb1aef15316aa67&size=150x150">

2024-11-19 10:33 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F8386ac60e6921ef7%2Fpublic-install-page%2Fb295208543d869f06cc1ca3993e443b2&size=150x150">

2024-11-19 10:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F8d590d51b21aa507%2Fpublic-install-page%2F6ad86d1ee8968b3c61452684a9c4a31d&size=150x150>

2024-11-19 13:35 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F015f5ae5b9149705%2Fpublic-install-page%2Fe42297b5cdf4c4a9168687d8b8798200&size=150x150">

2024-11-19 13:36 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F119ea5030bb60508%2Fpublic-install-page%2F5aae2927e8a8dda11191a9e896d388b1&size=150x150>

2024-11-19 13:37 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fd6ad5c8548363776%2Fpublic-install-page%2F285cd008e3f87f753b4321123c2123f3&size=150x150">

2024-11-19 14:07 UTC, domonkosadam requested changes
QA + 1

2024-11-19 14:16 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/adapters/AttendanceListRecyclerAdapter.kt
> +    presenter: com.instructure.pandautils.blueprint.SyncPresenter<Attendance, AttendanceListView>,
I moved around some classes and probably that's causing these. I removed a couple of these, but seems like I missed some so I will fix these.

2024-11-19 14:17 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/base/AppConfigProvider.kt
> +    val appName: String,
We still need the appName as a string for the ScreenViews, but I can convert this to an enum.

2024-11-19 14:18 UTC, tamaskozmer commented on libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/pageview/PageViewAnnotations.kt
> +@Retention(AnnotationRetention.RUNTIME)
We tried different solutions in the past that manipulates the code in compile time, but couldn't make it work

2024-11-19 14:52 UTC, domonkosadam approved these changes

2024-11-19 15:00 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fe06cb53ed3bb87a1%2Fpublic-install-page%2F9710ee617ec3faebb40beba7898f2bdb&size=150x150">

2024-11-19 15:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F7c622693999f316f%2Fpublic-install-page%2F89cad45cbbb334b4c3dd53f5eccd0bf1&size=150x150>

2024-11-19 15:01 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fdda44794e70efad7%2Fpublic-install-page%2Fcf950ca82e1820da5993811b182a16ac&size=150x150">

2024-11-21 10:19 UTC, hermannakos approved these changes

2024-11-21 12:44 UTC, kdeakinstructure approved these changes
QA 👍

2024-11-21 13:13 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fccb345ceefe234d0%2Fpublic-install-page%2Fec6aa3bca28c15ae474989e43ec12990&size=150x150">

2024-11-21 13:13 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe8def131ecbbd701%2Fpublic-install-page%2F3d3a7bf35aaa29635dbabf7b52626e25&size=150x150>

2024-11-21 13:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Feddd58066338a614%2Fpublic-install-page%2Ff1580f7b6215c5e69600634c2274981c&size=150x150">

2024-11-21 13:52 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fb81f93d688af278b%2Fpublic-install-page%2Feb34f8f2281a782b2d17d99baa322f27&size=150x150">

2024-11-21 13:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4ee476b1e9b4a1f7%2Fpublic-install-page%2F4ec570c661c3bbb7482c5953b688a146&size=150x150>

2024-11-21 13:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fdc16a75d18273577%2Fpublic-install-page%2F1455b20292fa3b5b186bce1de3e177c0&size=150x150">

2024-11-21 14:31 UTC, merged