[MBL-17678][Parent] Course details Summary
instructure/canvas-android pull request #2648
Opened 2024-11-21 15:43 UTC by domonkosadam

Test plan: See ticket

refs: MBL-17678
affects: Parent
release note: none

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/5a26cf21-0c9a-46e2-b1db-0a9c5d31f080" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/0672d3e6-9aa0-4b63-8d4d-24b60d95045d" maxHeight=500></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

2024-11-21 15:55 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fa398444422c75716%2Fpublic-install-page%2Fbac56d6342d43c2788731c79a27a4d50&size=150x150">

2024-11-22 08:53 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc18b1d84c37f01f8%2Fpublic-install-page%2F9ba5f906b6925f0ecfae83c32cfbb222&size=150x150">

2024-11-22 08:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fcec1fbf713b3c080%2Fpublic-install-page%2F911095fd910fcd23190d9052515bd1f4&size=150x150">

2024-11-22 08:54 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fb99304d12c1ab575%2Fpublic-install-page%2Fdf701a32615edf2f8cfdff3bd6c66657&size=150x150>

2024-11-22 12:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9da2622a34da918d%2Fpublic-install-page%2Fb380dadd59f76b4cdebab52532dd33f4&size=150x150">

2024-11-22 12:49 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F2d31472fa52da991%2Fpublic-install-page%2Fe3af98a8aad65e4599c88627ef21b36f&size=150x150>

2024-11-22 14:41 UTC, kdeakinstructure approved these changes
QA 👍

2024-11-26 15:59 UTC, tamaskozmer requested changes

2024-11-26 15:59 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/summary/SummaryUiState.kt
> +    val course: Course = Course(),
I don't think we should pass a course object to the uiState and I think we don't even need to make a course request in the ViewModel. We only need the `id` for the color and for the navigation and we already have it passed in Fragment arguments.

2024-11-26 15:59 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/summary/SummaryScreen.kt
> +                    navigateToCalendarEvent (course.type.apiString, course.id, eventId)
You can just pass here `Type.COURSE.apiString` if you implement my other suggestion.

2024-11-26 15:59 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/summary/SummaryScreen.kt
> +            tint = Color(course.color),
And this can be replaced with `CanvasContext.emptyCourseContext(id).color`

2024-11-26 15:59 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/summary/SummaryRepository.kt
> +        val params = RestParams(isForceReadFromNetwork = forceRefresh)
You should include `usePerPageQueryParam` in order to get 100 items per page instead of 20.

2024-11-26 15:59 UTC, tamaskozmer commented on apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/courses/details/summary/SummaryScreenTest.kt
> +    fun assertContentContent() {
I laughed way too hard on this name 😄

2024-11-27 14:07 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4913e587b31b30c5%2Fpublic-install-page%2F66e4a4d0cb87f34cc3d0dbc8c91affb5&size=150x150>

2024-11-27 14:07 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fd3f52bf13ddc2aa3%2Fpublic-install-page%2F71ba42829d05dc191a40972711715518&size=150x150">

2024-11-27 14:08 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F476d8f8fda3e543d%2Fpublic-install-page%2F1a1eb118c9dfd6a591eae66e71fc326b&size=150x150">

2024-11-28 09:56 UTC, tamaskozmer approved these changes

2024-11-28 10:20 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fd86cbacfe981a3d2%2Fpublic-install-page%2Fbe1e12af414c66170493abbee633e122&size=150x150">

2024-11-28 10:20 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fcb618b98386008ae%2Fpublic-install-page%2F23c739d48f34eeac8b8c5540911b45fb&size=150x150>

2024-11-28 10:22 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F125e7a244e280ca0%2Fpublic-install-page%2F1801dff81d33d9df3f5e08f1533bdf90&size=150x150">

2024-11-28 12:14 UTC, merged