[MBL-17612][Parent] Create account flow
instructure/canvas-android pull request #2652
Opened 2024-11-25 16:33 UTC by andrasmaczak

--- edit or delete this section ---

Test plan: 
- On landing page select QR code
- Select I don't have a Canvas account
- Follow create account flow
- Try logging in with the new parent user

refs: MBL-17612
affects: Parent
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

2024-11-25 16:46 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F4a50160c30318bc3%2Fpublic-install-page%2F1cac5382af150298eba97be48cb7b190&size=150x150>

2024-11-25 16:46 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fa5e3bfc1c0fcb66e%2Fpublic-install-page%2F41fa2be826ce4d04037d03e509b0ffd2&size=150x150">

2024-11-25 16:46 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F474c29fe50205970%2Fpublic-install-page%2F1d5c91d134313efbc147962c75e7d610&size=150x150">

2024-11-26 10:05 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fb3917d9965b41418%2Fpublic-install-page%2F8421f0e6d9bfcf57858eaaed716e0c18&size=150x150">

2024-11-26 10:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ff189c65bccdfbc96%2Fpublic-install-page%2F37ffd3f625b0fc8d73a5941b821af7c3&size=150x150">

2024-11-26 10:05 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1191ae900399fecb%2Fpublic-install-page%2F0d528ce9aebf7dd114ed8a3b22d76c97&size=150x150>

2024-11-26 12:01 UTC, tamaskozmer requested changes
QA findings:

- [ ] Font seems wrong on the 'Open Canvas Student' app screen, I know this is an old issue. (This might get fixed in MBL-18086)
- [x] Red color in textfield validation is too dark in dark mode. It looks the same in light mode, I guess we are using a default color and not using our own error color.
- [x] Bottom sheet text is too small and have the wrong font.
- [x] Bottom sheet items are only clickable when the actual text is clicked. The whole row should be clickable and have touch feedback. Also touch feedback is strange it can only be seen when long tapped on the text.
- [x] Soft keyboard covers the screen when a textfield is in focus instead of pushing it up.
- [x] Bottom sheet should be dismissed when navigating to the next screen.

2024-11-26 12:06 UTC, tamaskozmer commented on apps/parent/src/main/java/com/instructure/parentapp/features/login/createaccount/CreateAccountScreen.kt
> +                                color = colorResource(R.color.ash)
This should also use `textDark` and `textInfo` for the link.

2024-12-02 08:54 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F5d22785d3f468741%2Fpublic-install-page%2Ff7cc9e55b9d456d54e6e700e947da752&size=150x150">

2024-12-02 15:58 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-12-03 06:00 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fa60578497ea3610d%2Fpublic-install-page%2F97f17553131c5dacb6f0380faa11801d&size=150x150>

2024-12-03 06:00 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F58927d6b4db21f32%2Fpublic-install-page%2F67a1794ed65a4bd0a20bf83fe0f2f9ea&size=150x150">

2024-12-03 06:00 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F721d4b104fdceb43%2Fpublic-install-page%2F0adcbb495b7d6e71835af863b35da2e7&size=150x150">

2024-12-03 09:01 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F85ee7e2f8ffa959a%2Fpublic-install-page%2F30966f41e5b5e38549b8776a06ae7177&size=150x150>

2024-12-03 09:02 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F3b4f08085372c035%2Fpublic-install-page%2F3a512f634ccd20c24b0095a28169e9e4&size=150x150">

2024-12-03 09:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F7c0f7c90b5e6b73e%2Fpublic-install-page%2Ff226b235436ba40025b452ece43f0ccf&size=150x150">

2024-12-03 13:47 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F5eb5f1739cbc5101%2Fpublic-install-page%2Fbc2b28d657d9034c8a11243e53a47bb6&size=150x150">

2024-12-03 13:48 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fe6d3038edd198826%2Fpublic-install-page%2F7d1f8f0d4321bc61247e3f179a41af31&size=150x150>

2024-12-03 13:49 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fb6b6541640568c3f%2Fpublic-install-page%2Fb1f3cf95869374f4a2dc890846028e68&size=150x150">

2024-12-03 14:34 UTC, kristofnemere approved these changes
QA+1

2024-12-03 14:43 UTC, andrasmaczak commented on apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/CreateAccountPage.kt
> +    fun isRecipientsLoading(): Boolean {
Busted

2024-12-03 15:01 UTC, tamaskozmer requested changes

2024-12-04 14:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fc23cc88ee071747b%2Fpublic-install-page%2Ff07f477c39ff956afc85a6eb0f31c8c3&size=150x150>

2024-12-04 14:14 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F4715a7e3d8290d7e%2Fpublic-install-page%2F720c1290f0c6e3b791776228423c1a12&size=150x150">

2024-12-04 16:53 UTC, tamaskozmer approved these changes

2024-12-05 08:55 UTC, kristofnemere approved these changes
QA+1

2024-12-05 08:59 UTC, merged