[MBL-17672][Parent] WebView screen & navigation
instructure/canvas-android pull request #2655
Opened 2024-11-27 12:02 UTC by kristofnemere

Test plan: 
- test links in webviews
- test submission feedback
- test limit_parent_app_web_access (hidden feature flag, I was able to test it with proxy) 

refs: MBL-17672
affects: Parent
release note: none

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

2024-11-27 12:14 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F6b51f495be096958%2Fpublic-install-page%2F46dc456fd25796a35b90a63970be5365&size=150x150>

2024-11-27 12:15 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F3d99f20833b86404%2Fpublic-install-page%2F993ec5ffd6a502903555074150dc518d&size=150x150">

2024-11-28 12:57 UTC, domonkosadam requested changes
- [ ] The app crashes sometimes when we navigate back from the webview before it gets loaded. I'm not sure if it's in the scope of this ticket but I think it should be fixed.

https://github.com/user-attachments/assets/97b5d358-fc93-4d34-b92e-a4980f806bb4

2024-11-28 14:57 UTC, domonkosadam approved these changes
QA + 1

2024-11-28 16:46 UTC, hermannakos requested changes
- [ ]  After navigating from a webview the does not keep its previous state. The page scrolls up, if there was any input it's lost etc.
- [x] On API 29 the custom tab opens the app chooser and we can choose the parent app as well.
- [ ] On configuration change the webview reloads.

With the custom tabs we lose the ability for in app navigation. I think we should talk about this a bit more, if this is something we want to achive.

2024-11-28 16:46 UTC, hermannakos commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/lti/LtiLaunchFragment.kt
> +        activity?.let {
`requireActivity` should handle this.

2024-12-02 08:59 UTC, kristofnemere commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/lti/LtiLaunchFragment.kt
> +        activity?.let {
requireActivity is not safe, and there was a null check already, that's why I think it's better this way

2024-12-02 08:59 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRouter.kt
> +        val cookies = mapOf("k5_observed_user_for_$parentId" to "$currentStudentId")
yes

2024-12-02 08:59 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRepository.kt
> +    private val featuresApi: FeaturesAPI.FeaturesInterface,
It belongs to the assignment details.

2024-12-02 09:00 UTC, kristofnemere commented on apps/parent/src/main/java/com/instructure/parentapp/di/feature/DashboardModule.kt
> +    fun provideNavigation(apiPrefs: ApiPrefs): Navigation {
Good point, fixing it

2024-12-02 12:34 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fa8d13cadedf746bf%2Fpublic-install-page%2F93af54c42e4ed1f89f845a8a25ad2850&size=150x150>

2024-12-02 12:34 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ffa17744771d45056%2Fpublic-install-page%2F33075623139c4e67dca3c70ec2ba1eb2&size=150x150">

2024-12-02 12:35 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F40d731f23c04826e%2Fpublic-install-page%2Fa019fd048974201939c7f934e1237b09&size=150x150">

2024-12-02 13:16 UTC, hermannakos commented on apps/parent/src/main/java/com/instructure/parentapp/features/assignment/details/ParentAssignmentDetailsRepository.kt
> +    private val featuresApi: FeaturesAPI.FeaturesInterface,
Yes, but every time we're navigating to the Assignment details we need to check. It could be part of the navigation to the assignment details screen and handled there.

2024-12-02 15:14 UTC, merged