[MBL-17949][All] Use common inbox
instructure/canvas-android pull request #2669
Opened 2024-12-09 13:16 UTC by domonkosadam

Test plan: Test the entire inbox in all three application.

refs: MBL-17949
affects: Student, Teacher
release note: Inbox improvements

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] Approve from product

2024-12-09 13:34 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F4b4a3b4c81a656ea%2Fpublic-install-page%2F56fbf8b7a7732f9c8b43285de41e9d46&size=150x150">

2024-12-10 09:49 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-12-10 10:18 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Fab17b74c9b50e71c%2Fpublic-install-page%2F48abbc06240f90912d45418a9241d76d&size=150x150>

2024-12-10 10:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Ff1b8bfb9efc260ea%2Fpublic-install-page%2F8f90441a47ce7d2ac01d17374fc7f9d8&size=150x150">

2024-12-10 10:18 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F07324de34dfac3fd%2Fpublic-install-page%2F0bb4c0cb38a056c786f2222db0a33a1f&size=150x150">

2024-12-11 13:42 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F6455ebc2933ad9aa%2Fpublic-install-page%2F0d6a4c8d21a1ebcfec67a8f4ec021a61&size=150x150">

2024-12-11 13:43 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2Ff1a0a56009150309%2Fpublic-install-page%2Ffb1ef7e2e7be8c75b024a5e562f89f1a&size=150x150>

2024-12-11 13:44 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F9227471bc4504a8e%2Fpublic-install-page%2F6efbf3739bf7739528e770521d77efbb&size=150x150">

2024-12-12 12:38 UTC, tamaskozmer requested changes
Only tested the Teacher app on tablet. Found some important issues:

- [ ] We should handle page views and screen views on the new inbox screens
- [ ] Teacher split view cases are not handled at all

2024-12-13 08:48 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fb0ab8adc39b8bf3e%2Fpublic-install-page%2F06aefab2838a56111e56e0bb1d4a78a5&size=150x150">

2024-12-13 08:49 UTC, domonkosadam commented on apps/teacher/src/main/java/com/instructure/teacher/features/inbox/compose/TeacherInboxComposeRepository.kt
> +    override suspend fun getGroups(forceRefresh: Boolean): DataResult<List<Group>> {
I'm not sure about that either, but I checked the previous implementation and there was a network request to get the groups.

2024-12-13 08:50 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fdeb486a454936edd%2Fpublic-install-page%2Ffd726bfbc52a3d0c56aaa976a1965768&size=150x150">

2024-12-13 08:53 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F962477ea80697158%2Fpublic-install-page%2F4f9fe22af1319456be99e0eca1eee18f&size=150x150>

2024-12-13 09:17 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F844aa8c6961a5374%2Fpublic-install-page%2Fe45c5b0fbf5979dc75d989d1923a7f06&size=150x150">

2024-12-13 09:18 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2Fc61b7ea76cfe2b40%2Fpublic-install-page%2F4fd5c25a81a5700457537428a428ccef&size=150x150">

2024-12-13 12:11 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/features/inbox/compose/TeacherInboxComposeRepository.kt
> +    override suspend fun getGroups(forceRefresh: Boolean): DataResult<List<Group>> {
If think we can leave this out, we don't request the groups in the Calendar either.

2024-12-13 15:02 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fdedd14c0c95dcfe3%2Fpublic-install-page%2F925d3711dcf0c2c87be12814a266d5a5&size=150x150">

2024-12-13 15:03 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F03642789d301266c%2Fpublic-install-page%2F63ee74e8f3bfc2d421e5bdff93e1fb4d&size=150x150">

2024-12-13 15:08 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F2f55416322edfdc5%2Fpublic-install-page%2F599fbe9bc00f898317c6b11312b752b6&size=150x150>

2024-12-13 16:24 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F60795f1d7dea9f95%2Fpublic-install-page%2F983816c7e4a3f955c26c1bdf4ca49912&size=150x150">

2024-12-13 16:25 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Fc91ee701fd86032b%2Fpublic-install-page%2F6e32ee6cb8f02e4ae8aec103b5fc7fbb&size=150x150">

2024-12-13 16:28 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F29e159c98dff5f3f%2Fpublic-install-page%2Fb0064a75f9501171243d2394b058a292&size=150x150>

2024-12-16 06:05 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F04aa5b9c6fcdda13%2Fpublic-install-page%2F775c5453982da45489737e200c7db7d0&size=150x150">

2024-12-16 06:05 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F311cfaee88c46305%2Fpublic-install-page%2F89b366a9de72129e35e5442a627dbf66&size=150x150">

2024-12-16 06:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1c262b620d06a306%2Fpublic-install-page%2F8f2defcc6556d8ed65eb044c5d2f0720&size=150x150>

2024-12-16 08:06 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F8f55bd2a07078ce4%2Fpublic-install-page%2Ff2b876778a13e5e7b3b8e355653d4e78&size=150x150">

2024-12-16 08:06 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F124a8f10a5b6bf17%2Fpublic-install-page%2Fce013216dac8eecf9faf2dfa925a2c50&size=150x150">

2024-12-16 08:10 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F1db8c9ddbf81bce2%2Fpublic-install-page%2Feec6118ad3ccd124e06b26b566f2b029&size=150x150>

2024-12-16 08:30 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F53035ccee42afbd2%2Fpublic-install-page%2F8a63ea8949b8bfbb7c29bf56befc7ee8&size=150x150">

2024-12-16 08:30 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2F5ad97b0cdd56b81f%2Fpublic-install-page%2Fc7863760519f47ae35d814fae3ca709b&size=150x150">

2024-12-16 08:33 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F676b55bb2c1af07b%2Fpublic-install-page%2F3ef8a570c5bfed1dda2d65331f307474&size=150x150>

2024-12-16 09:09 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="">

2024-12-16 09:48 UTC, inst-danger commented
<p>Native Parent Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F9b3ee51c-d05d-461b-8ed0-0045237ae53e%2Finstallable-artifacts%2Ff10fb122dac48990%2Fpublic-install-page%2F2d18258d31fc9a8750b57bade44ba1bb&size=150x150">

2024-12-16 09:52 UTC, inst-danger commented
<p>Teacher Install Page</p>
<img src=https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2F18a96964420643c0%2Finstallable-artifacts%2F22f327f9295aa7b9%2Fpublic-install-page%2F237950135610adcb7a805ab84b87b802&size=150x150>

2024-12-16 12:16 UTC, tamaskozmer requested changes

2024-12-16 12:16 UTC, tamaskozmer commented on libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
> +    fun cancelDismissDialog(isShow: Boolean) {
These new functions should be unit tested as well.

2024-12-16 12:16 UTC, tamaskozmer commented on apps/teacher/src/main/java/com/instructure/teacher/activities/BottomSheetActivity.kt
> +import android.util.Log
This import is unused.

2024-12-16 14:51 UTC, kdeakinstructure commented
QA Findings:


- If there is no attachment, the expand/collapse arrow icon makes no sense and can be confusing (see 1. video)

- 'All people in course' (or All people in teachers, etc..) counts the current user but when he/She navigates back then he/she won'T be in the list (so for example all people counts 6 people but when replying to that message the recipients will be shown one by one and the current user is not among them so only 5 people will be displayed (see 1. video)

- FAB and filter colors are different in student and teacher app (maybe it's just a setting? I don't really know what is the expected color here.... brand color, or course color, etc.) (see 2. video)

- In parent the replies look very different. I thought if the inbox will be common that it mean it should be really the exact same in all apps.  (see screenshot)

https://github.com/user-attachments/assets/1f36cc8b-cc84-452a-be38-4fc8111970ee

https://github.com/user-attachments/assets/e9f725b4-600b-494e-891d-c2c904acb48b

(I couldn't upload my screenshot taken in Logcat because GitHub says it's a "big" file, and I should try again with file size less than 10MB. This is weird because the file actually 604.55 kB....)

2024-12-17 10:16 UTC, domonkosadam commented
1. I think that's the correct behaviour as only 1 line is shown in the collapsed state so longer messages can be read as well. It indeed makes no sense when the text message is only one line long but I think it's better to handle all messages universally.
2. Same as web. It's just a shortcut to handle recipients and with the current API users can't send messages to themselves.
3. I will check it, but that screen is common in the current version as well.
4. What do you mean by very different? Can you provide me some more screenshots?
5. It's just as design. I think it's ok because reply is the most common action.
6. Parent app can't handle pdf files so that's why I solved it like that. We could handle image and video attachments differently but that should be done in a different ticket.

2024-12-17 12:56 UTC, inst-danger commented
<p>Student Install Page</p>
<img src="https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Fapp.bitrise.io%2Fapp%2Fc94e0393a4d8cc19%2Finstallable-artifacts%2F529105615a784390%2Fpublic-install-page%2F10d0977c6c56ce5866178dcd572d42a8&size=150x150">

2024-12-19 12:28 UTC, kdeakinstructure approved these changes
QA 👍

2024-12-19 12:30 UTC, merged